// 一点物アイテムカタログの共通定義: ドット絵原型 + ビルダー
//
// 「上質な」「秘宝の」のような量産用の二つ名は廃止。すべてのアイテムは
// ここにあるビルダー (W/S/A/H/F/G/R/M/U) を通して固有の名と来歴を持つ一点物として定義する。
//
// 共通ルール:
//  - id は append-only (セーブ/図鑑が参照するため、改名・削除は禁止。増やすのみ)
//  - lv: 隠しレベル (1-200)。出現する迷宮帯・出現率・性能・価格の自動算出に使う
//    (lv1-20=粗末な品 / 165-200=神話級。全100迷宮の lootLv 帯に対応する)
//  - eAtk/eDef: 属性攻撃/属性防御 ["fire",1] 形式 → {el,lv} に変換される
//    Lv1=◯ (有利+50%/不利-50%), Lv2=◎ (有利+100%/不利-100%)
//  - 絵は形の原型 (ARTS) × 色 (属性色 or tint指定) で描き分ける。
//    原型は 24x24 の高解像度ドット絵。武器8種は各3型、盾・鎧・頭・足・小手・装飾は各2型を持ち、
//    同じ形キーでも item id の安定ハッシュで型を選ぶ (pickArt) ので、同系統の装備でも見た目が散らばる
import { tint } from "../dungeons/schema.js";
import { lvToRank } from "../items.js";

// 共有パレット (items.js と同等)。素材ごとに 3〜5 階調 (光源は左上)。
// base() が tint() で全キーを染め色へ寄せるので、どの色も「染めても破綻しない」明度差で並べてある
const P = {
  ".": null,
  k: "#0d0b10", // 黒縁
  // 鋼: 深影 / 影 / 中間 / 明 / 鏡面
  e: "#262433", g: "#4a4a5c", v: "#7c7d88", w: "#b5b2ad", x: "#e9e3d6",
  // 金: 深影 / 影 / 地 / 輝き
  O: "#2e2016", o: "#6b5221", y: "#a88a3e", Y: "#dcc78a",
  // 木: 深影 / 影 / 地 / 明
  S: "#1c130f", s: "#35241a", n: "#574030", N: "#7d6449",
  // 革: 深影 / 影 / 地 / 明
  D: "#241a16", d: "#4b3628", l: "#7a5f45", L: "#a88f70",
  // 赤 (紅玉・血): 影 / 地 / 明
  q: "#3a1016", r: "#7a2028", R: "#b8564a",
  // 青 (蒼玉・水): 影 / 地 / 明
  u: "#1a2234", b: "#34506e", c: "#7aa0b4",
  // 紫: 深影 / 影 / 地 / 明
  J: "#1c1426", j: "#3b2a4c", p: "#66507a", i: "#a08cb0",
  // 緑: 影 / 地 / 明
  t: "#1a2618", G: "#3e5a34", h: "#7d9a62",
  // 骨・象牙: 影 / 地 / 明
  z: "#4a4236", I: "#8f8670", B: "#c9c0a6",
  // 布 (藍鼠。染め色を素直に受ける): 深影 / 影 / 地 / 明
  F: "#17161f", f: "#2c2b3a", C: "#484a5e", A: "#6e7088",
  m: "#a0566a", // 桃 (肉・舌)
};

// 属性 → 染め色 (schema.js の ELEMENTS と同系統)
const ELEM_TINT = {
  fire: "#ff6b3a", water: "#4aa3ff", wind: "#5fd08a",
  earth: "#c89a4a", light: "#ffe27a", dark: "#9b6bd0",
};
const ELEM_KEYS = Object.keys(ELEM_TINT);

// ===== 形の原型 (24x24) =====
// 1px の黒縁 k・光源は左上・素材ごとに 4〜5 階調。キーは上の P。
// 値が「型の配列」の形キーは複数デザインを持ち、pickArt が item id のハッシュで 1 つ選ぶ。
export const ARTS = {
  // --- 武器 (サブカテゴリと同キー。各3種) ---
  ls: [ // 長剣 (3種)
    [ // 騎士の長剣: 樋のある直刃・十字鍔・紅玉
      "........................",
      ".....................e..",
      "...................eewk.",
      ".................eexwk..",
      "................ewxwgk..",
      "...............ewxwgk...",
      "..............evxvgek...",
      ".............evxggek....",
      "............ewxveek.....",
      "......O....ewxveek......",
      ".....Oyk..ewxveek.......",
      "....OYok.ewxgeek........",
      "...Oyoyokwxveek.........",
      "....kkyyyxveek..........",
      "......kyyRrek...........",
      "......DLyrqk............",
      "...OODlddyyokO..........",
      "..OYYolDkkyYYyk.........",
      ".OYYyyOk..kYok..........",
      ".OoyyoOk..Oyk...........",
      ".OoooOOk...k............",
      "..kOOOk.................",
      "...kkk..................",
      "........................",
    ],
    [ // 幅広の騎士剣: 反り鍔・ルーンの樋・長い柄
      "........................",
      ".....................e..",
      "...................eevk.",
      "..................exxk..",
      "................eexwgk..",
      "...............ewxwgek..",
      "..............ewxgvek...",
      ".............ewxcbgek...",
      "........OO..ewxgegek....",
      ".......Oyykewxgegek.....",
      "......OYokkwxcbgek......",
      "......OYokwxgegek.......",
      "......Oyyoxgegek........",
      ".......kyycbgek.........",
      "........kybuek.O........",
      ".......DLDyyykOyk.......",
      "......DldkkyyYYok.......",
      ".....DlDk..kyook........",
      "....Dldk....kkk.........",
      "..ODlDk.................",
      ".OYYyk..................",
      ".OYcok..................",
      ".Oyook..................",
      "..kkk...................",
    ],
    [ // 黒鉄の大剣: 鋸歯の峰・角鍔・紅のルーン
      "........................",
      ".....................e..",
      "...................eevk.",
      ".................eewvk..",
      "................evwvgk..",
      "...............evwvgek..",
      ".....e........evwvgek...",
      "....egk......evwRgek....",
      "...evek.....evwrgeek....",
      "...evek....evwRgekk.....",
      "...evgk...evwrgeek......",
      "....kgek.evwRgekk.......",
      "....evgkevwrgeek........",
      "....evgekkvgekk.........",
      ".....kvwRrkeek..........",
      "......kprqkkk...........",
      ".....Jpjjevke...........",
      "....JipJkegvgkeee.......",
      "...Jpjjk.keggvvggk......",
      "..evpJk...kkkeeek.......",
      ".exgvk.......kkk........",
      "ewrgk...................",
      "evgk....................",
      ".kk.....................",
    ],
  ],
  dg: [ // 短剣 (3種)
    [ // 両刃の短剣: 木葉形の刃・金鍔・蒼玉
      "........................",
      "........................",
      "....................e...",
      "..................eewk..",
      "................eexwk...",
      "...............ewxwgk...",
      "..............ewxwgk....",
      ".............ewxwgek....",
      "............ewxwgek.....",
      ".........OO.exwgek......",
      "........OYykcbgek.......",
      "........Oyyybukk........",
      ".........kooyk..........",
      "........Dldoyyk.........",
      "......ODLlDkyok.........",
      ".....OYyodk.kk..........",
      "....OYyyok..............",
      "....OoooOk..............",
      ".....kOOk...............",
      "......kk................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
    [ // 猟刀: 峰の反った幅広の刃・骨の柄
      "........................",
      "........................",
      "...................ee...",
      ".................eexgk..",
      "................exwwgk..",
      "...............exwwwgk..",
      "..............exwwwgk...",
      ".............exwwvggk...",
      "............exwwvvgk....",
      "...........exvwvvgk.....",
      "......ee..exwwvvggk.....",
      ".....egwkexwwvvggk......",
      ".....eggvxwwvvggk.......",
      "......kggwvvggkk........",
      ".......kggwggk..........",
      "......Sskgwwk...........",
      ".....SsnNkggk...........",
      "....SsYNk.kk............",
      "...SsnNk................",
      "..SsyNk.................",
      ".ewvNk..................",
      ".egek...................",
      "..kk....................",
      "........................",
    ],
    [ // 儀式の波刃短剣: 骨の柄・髑髏の柄頭・紫の宝玉
      "........................",
      "........................",
      "..................eeq...",
      ".................exxqk..",
      "................ewwqrk..",
      "...............exwqgk...",
      "..............exwggk....",
      "..............exwrk.....",
      "......O......exwvgk.....",
      ".....Oyk..eeexwwgk......",
      "....OYYYkexxwwgvgk......",
      "....OooYYxwwvvgkk.......",
      ".....koipYwvgkk.........",
      "......kpJYYgk...........",
      ".......kooYk............",
      "......zIIooYk...........",
      ".....zIIzkok............",
      "..zzzIIzk.k.............",
      ".zBBIIzk................",
      "zBBBIzk.................",
      "zIkIkzk.................",
      ".kIzzzk.................",
      "..kzkk..................",
      "...k....................",
    ],
  ],
  kt: [ // 刀 (3種)
    [ // 打刀: 黒の柄巻き・丸鍔
      "........................",
      "....................ee..",
      "...................exvk.",
      "..................evvvk.",
      ".................exvgk..",
      "................exvgk...",
      "...............exwvk....",
      "..............exwvgk....",
      ".............exwvgk.....",
      "............exwvgk......",
      "...........exwvgk.......",
      "..........exvvgk........",
      ".........exwvgk.........",
      "......eeexvvgk..........",
      ".....evvvYykk...........",
      ".....evvggek............",
      ".....zBgeek.............",
      "....FFFBek..............",
      "...FFBfkk...............",
      "..zBFfk.................",
      ".FFFBk..................",
      "OYBfk...................",
      "Oook....................",
      ".kk.....................",
    ],
    [ // 朱の太刀: 赤の柄巻き・金の花鍔
      "........................",
      "...................eee..",
      "..................exxgk.",
      ".................exvvvk.",
      "................exvvgk..",
      "...............exvvgk...",
      "..............ewvgkk....",
      ".............ewwgk......",
      "............ewvgk.......",
      "...........ewwgk........",
      "..........exvgk.........",
      ".........exwvk..........",
      ".......Oexwvgk..........",
      "......OYYYvgk...........",
      ".....OYYYyOk............",
      ".....OYYrqOk............",
      ".....DLyooOk............",
      "....qqqLOOk.............",
      "...qqLrkkk..............",
      "..DLqrk.................",
      ".qqqLk..................",
      "OYLrk...................",
      "Oyok....................",
      ".kk.....................",
    ],
    [ // 野太刀: 長大な刀身・藍の柄巻き・角鍔
      "......................e.",
      "....................eevk",
      "...................exxk.",
      "..................exvgk.",
      ".................exvvk..",
      "................exwgk...",
      "...............exwvgk...",
      "...............ewvgk....",
      "..............ewvgk.....",
      ".............ewvgk......",
      "...........eewvgk.......",
      "..........exwvgk........",
      "....Oe...exwvgk.........",
      "...Oyvk.exwvgk..........",
      "....kgvkxvvgk...........",
      ".....kgvYgkk............",
      ".....ukgek..............",
      "....uuukgek.............",
      "...uuwbkkgek............",
      "..evbbk..koek...........",
      ".uubwk....kk............",
      "uuwbk...................",
      "ubbk....................",
      ".kk.....................",
    ],
  ],
  ax: [ // 斧 (3種)
    [ // 片刃の戦斧: 三日月の刃・革巻きの柄
      ".........eeeeee.........",
      "........exxwwwwk........",
      ".......exwwvvvwk........",
      ".......exwgvvvwk..S.....",
      "......exwgggvvwk.SNk....",
      "......exwggggvvwkNnsk...",
      "......exeeggggeYOssk....",
      "......exeeeegeYYyOk.....",
      ".......kkkeeeYYyook.....",
      "..........kkOYyoovk.....",
      "...........SNOoogvk.....",
      "..........SNnsOgggvk....",
      ".........SNnskkkgggk....",
      "........SNnsk..eggk.....",
      ".......SNnsk....kk......",
      "......SNnsk.............",
      ".....DLnsk..............",
      "....DLdlk...............",
      "...Dldlk................",
      "..DLddk.................",
      "eDLdlk..................",
      "wNdlk...................",
      "wgsk....................",
      "kggk....................",
    ],
    [ // 両刃の大斧: 対の刃・頂の穂・紅玉
      "........................",
      "..........eeee.......e..",
      "........eexwxxk.....ewk.",
      ".......exxvwwwk...eewk..",
      ".......exvgvvwk..exwk...",
      "......exwgggvvkOexwgk...",
      "......exwgggvvwYwvgk....",
      "......exwegggeYYygk.....",
      "......exweeeeYRyook.....",
      ".......kkkkkYRrrovkeee..",
      "..........OYYyroeggvvwk.",
      "..........Jiyooeggggvwk.",
      ".........Jipjokeggggvwk.",
      "........Jipjkkkeggggvwk.",
      ".......Jijjk..eeeggvwk..",
      "......Oypjk...evvgvwwk..",
      ".....Jiyyk....ewwwwkk...",
      "....Jipjk......kkkk.....",
      "...Jipjk................",
      "..Jipjk.................",
      ".Oypjk..................",
      "Jiyyk...................",
      "Jpjk....................",
      ".kk.....................",
    ],
    [ // 髭斧: 手元へ垂れる長い刃・びょう打ち
      "........................",
      "..........ee............",
      "........eexwke......e...",
      ".......exxwwwxk...eewk..",
      "......exxwvvvvvkeewwk...",
      "......exwgvvvvwwwwggk...",
      ".....exwqggvvvewYvgk....",
      ".....exwqgggvewwvggk....",
      "......kkkkkkkwwvggk.....",
      "............ewYggvk.....",
      "...........ewvggggk.....",
      "..........ewvgkkkk......",
      ".........ewvgk..........",
      "........ewggk...........",
      ".......ewvgk............",
      "......ewvgk.............",
      ".....DlDgk..............",
      "....DlDdk...............",
      "...DlDdk................",
      "..DlDdk.................",
      ".DlDdk..................",
      "ewDdk...................",
      "evgk....................",
      ".kk.....................",
    ],
  ],
  mc: [ // 槌 (3種)
    [ // 出縁のメイス: 鋼の柄・六枚のフランジ
      "...............eeeeeOYYk",
      "..............exxxweYYyk",
      ".............exwwwexwyyk",
      ".............exwwexwwvk.",
      ".............exwexwwvevk",
      ".............ewexwwveggk",
      ".............eexwwveggvk",
      "............OYYwwveggvk.",
      ".............kYoveggvvk.",
      "............ewgoogvvkk..",
      "...........ewgkkkkkk....",
      "..........evgk..........",
      ".........ewgk...........",
      "........ewgk............",
      ".......ewgk.............",
      "......ewgk..............",
      ".....Dlgk...............",
      "....DLdk................",
      "...Dldk.................",
      "..DLdk..................",
      "ODLdk...................",
      "Ywdk....................",
      "Yok.....................",
      "ook.....................",
    ],
    [ // 明けの明星: 棘付きの鉄球
      "...............e........",
      "..............exk.......",
      "...........e.ekwke.e....",
      "..........exkwwwvvkxk...",
      "...........kxxwwvvgk....",
      "..........ewxwwvvvgek...",
      ".........ekwwwvvgggeke..",
      "........exwvvvvvggeevxk.",
      ".........kkveeeeeeeekk..",
      "..........egggggeeeek...",
      "...........keeeeeeek....",
      "..........exseeeeekxk...",
      ".........SNskkkgkk.k....",
      "........SNsk..exk.......",
      ".......OYok....k........",
      "......SNsk..............",
      ".....SNsk...............",
      "....SNSk................",
      "...SNsk.................",
      "..SNsk..................",
      ".OYsk...................",
      "Snok....................",
      "Ssk.....................",
      ".k......................",
    ],
    [ // 戦鎚: 四角い打面・背のくちばし・頂の穂
      "............ewk.........",
      "...........ewwwk....ee..",
      "..........ewvvwwk.eexgk.",
      ".........ewvvvgwwkxxgk..",
      "........ewvvvgggwYxgk...",
      "........eevgggggYoygk...",
      ".........keggggYyyok....",
      "..........keggYbbovk....",
      "...........keYooovvvk...",
      "...........OYyooggvvvk..",
      "...........SNyokkggvvk..",
      "..........SNskk..kkkvvk.",
      ".........SNsk.......kk..",
      "........SNsk............",
      ".......SNsk.............",
      "......SNsk..............",
      ".....DLsk...............",
      "....Dldk................",
      "...DLdk.................",
      "..Dldk..................",
      "eDLdk...................",
      "wNdk....................",
      "wgk.....................",
      "ggk.....................",
    ],
  ],
  sp: [ // 槍 (3種)
    [ // 木葉の槍: 広い穂・赤い房
      "...................eeee.",
      "..................ewwxwk",
      ".................evxxwgk",
      "................ewxxwgek",
      "................exxwggek",
      "...............ewxwggek.",
      "...............ewwggek..",
      "..............OYyeekk...",
      ".............OYyokk.....",
      "............qrRok.......",
      "...........SnqrRk.......",
      "..........SNsqrrRk......",
      ".........SNskqrrrk......",
      "........SNskkqrqrk......",
      ".......SNsk.qqkqrk......",
      "......SNsk...k.kqk......",
      ".....SNsk.......k.......",
      "....SNSk................",
      "...SNsk.................",
      "..SNsk..................",
      ".Snsk...................",
      "exvk....................",
      "Nsk.....................",
      "kk......................",
    ],
    [ // 斧槍: 斧刃・頂の穂・背のかぎ
      ".....................e..",
      "....................exk.",
      "..........eeee....eexwk.",
      "........eexxxxk..exxwk..",
      ".......exxwwvwk.exxwk...",
      ".......ewwgvvwkexxwgk...",
      ".......ewgggvvkyxwgk....",
      ".......ewggggewoygk.....",
      ".......eweegevwvyk......",
      "........keeevwvgke......",
      ".........kkvwvgvvvke....",
      "..........Oyvgkkkvgvk...",
      ".........SNnyk...kkk....",
      "........Dldkk...........",
      ".......Dldk.............",
      "......Dldk..............",
      ".....SNnk...............",
      "....SNnk................",
      "...SNnk.................",
      "..SNnk..................",
      ".SNnk...................",
      "SNnk....................",
      "Nnk.....................",
      "nk......................",
    ],
    [ // 三叉の矛: 返しのある三本の穂・金の横木
      "................e....ee.",
      "...............evkeeexxk",
      "...............evgggwwgk",
      ".............Oewgkkgwgk.",
      "............Oowgkkxgwwk.",
      "...........OYogkkxgkkwk.",
      "...........Oyyyyxgk.ewk.",
      "............kooygk.evgvk",
      ".............kyyyykwgkk.",
      "............ucbyyywgk...",
      "...........ucbkkoyok....",
      "..........ucbk..kyk.....",
      ".........ucbk....k......",
      "........ucbk............",
      ".......ucbk.............",
      "......Oyok..............",
      ".....ucbk...............",
      "....ucuk................",
      "...ucbk.................",
      "..ucbk..................",
      ".ucbk...................",
      "OYok....................",
      "cbk.....................",
      "kk......................",
    ],
  ],
  bw: [ // 弓 (3種)
    [ // 反り弓: 革巻きの握り・金の弭
      ".....................O..",
      "....................OYk.",
      ".........SSSSSSS....SNyk",
      "......DSSssssssskSSSNnk.",
      ".....DdsnnnNNNnNNnnNnk..",
      "....DdddNNkkkkkkkkBkk...",
      "...DddLdkk......zIk.....",
      "...SsLLk.......zBk......",
      "...SsNdk......zBk.......",
      "..SsnNk......zIk........",
      "..Ssnk......zBk.........",
      "..SsNk.....zBk..........",
      "..SsNk....zBk...........",
      "..SsNk...zBk............",
      "..SsNk..zBk.............",
      "..SsNk.zBk..............",
      "...kNkzBk...............",
      "...SskBk................",
      "...SnBk.................",
      "...Snk..................",
      ".OSsNk..................",
      "OYnnk...................",
      ".kyk....................",
      "..k.....................",
    ],
    [ // 長弓: 細身の弓幹・羽飾り
      "...................SSOyk",
      "...............SSSSSSsk.",
      ".............SSSSsnnBk..",
      "...........SSSsnnkkBk...",
      "..........SSsnnkkkBk....",
      ".......ODSSsnkk.zBk.....",
      "......OYddnkk..zBk......",
      ".....Oyddldk..zIk.......",
      ".....Ddddlk..zBk........",
      ".....DdddkokzIk.........",
      "....SSnlGkkkIk..........",
      "...SSskkhGkBk...........",
      "...SsnkthGtk............",
      "..SSnk..khGtk...........",
      "..Sssk.zBkhtk...........",
      ".SSnk.zBk.ktk...........",
      ".SSnkzBk...k............",
      ".SskkBk.................",
      ".SnkIk..................",
      "SSnIk...................",
      "SSBk....................",
      "Ssk.....................",
      "yk......................",
      "k.......................",
    ],
    [ // 矢をつがえた合成弓: 角の弓幹・鏃
      ".ee.....................",
      "exwk....................",
      "ewxwk.....zzzzzzz...O...",
      ".kwvgk.DzzzzzzzzzkzOyk..",
      "..kggkDDzIIIBBBBBBIIk...",
      "...kksDDIBBkkkkkkkwk....",
      "....DDDDDkk.....ewk.....",
      "...DDDddsk.....ewk......",
      "...zzIdNssk...ewk.......",
      "...zIBkkNssk.ewk........",
      "..zzIBk.kNsskwk.........",
      "..zzIk...kNssk..........",
      "..zzBk....kNssk.........",
      "..zzBk...ewknsRkq.......",
      "..zzBk..evk.kNsrRk......",
      "..zzBk.ewk...kNqrk......",
      "..zzBkewk.....kkRk......",
      "...kBkwk.......qrqk.....",
      "...zIwk.........kk......",
      "...zIk..................",
      "..Oyk...................",
      "...k....................",
      "........................",
      "........................",
    ],
  ],
  st: [ // 杖 (3種)
    [ // 宝玉の杖: 金の爪が蒼玉を掴む
      "........................",
      "................uuu.....",
      "..............Ouccbk....",
      ".............OYxxcbbk...",
      ".............uccxcbbuk..",
      ".............ubcbbbuuk..",
      "............OYbbbbuuuk..",
      "............OYYuuuuuok..",
      ".............kyyuuukok..",
      "............SNsokooook..",
      "...........Snskkookkk...",
      "..........SNsk..kk......",
      ".........OYok...........",
      "........SNsk............",
      ".......SNsk.............",
      "......Snsk..............",
      ".....SNsk...............",
      "....SNSk................",
      "...SNsk.................",
      "..SNsk..................",
      ".OYsk...................",
      "Snok....................",
      "Ssk.....................",
      ".k......................",
    ],
    [ // 捻れ木の杖: 枝が抱く紫水晶
      "...............S........",
      "..............SNkJ......",
      ".............SNnkpkJ....",
      "............SNnkpxpjk...",
      "............Snkixpjjjk..",
      "...........SNnkxijjjkS..",
      "...........SNnxxippjksk.",
      "............knkiiipknsk.",
      "............SNnkkiknsk..",
      "...........SNGhsnnssk...",
      "...........SntGssskk....",
      "..........SSnkkkkk......",
      "..........Snsk..........",
      "........SSNnk...........",
      "......SSNhGsk...........",
      ".....SNnSGtk............",
      "....SNnsskk.............",
      "....SNskk...............",
      "...SNnsk................",
      "..SkNSk.................",
      ".SNNnsk.................",
      ".Snnsk..................",
      "..kkk...................",
      "........................",
    ],
    [ // 光輪の王笏: 金の環に浮かぶ紅玉・小翼
      "...............OOOO.....",
      ".............OOYYYYk....",
      "............OYyyyyyYk...",
      "...........OyyykkkkOok..",
      "...........OYykkRrkkOok.",
      "..........OkyykRRrqkOok.",
      ".........OYByykrrqqkOok.",
      "..........kYYokqqqkkOok.",
      "..........zBYyOkkkkOOk..",
      "...........kBoOOOOOOok..",
      "...........OYoooOOook...",
      "..........OYokByBkkk....",
      ".........OYok.kByBk.....",
      "........Oyok...kkyk.....",
      ".......OYok......k......",
      "......OYok..............",
      ".....JpJk...............",
      "....Jijk................",
      "...JpJk.................",
      "..Jijk..................",
      ".OYok...................",
      "OYok....................",
      "Ook.....................",
      ".k......................",
    ],
  ],
  // --- 盾 (各2種) ---
  kite: [ // 騎士盾 (2種)
    [ // 金十字・蒼の地・鋼の縁
      "..eeeeeeeeeeeeeeeeeeee..",
      ".evvvvvvvvvvvgvvgvvvvvk.",
      "evyooooooooooooooooooovk",
      "evoccccccccYycccbbbbuovk",
      "evoYcccccccYocccbbbbYovk",
      "evoccccccccYocccbbbbuovk",
      "evoccccccccRyccbbbbbbovk",
      "evoYYYYYYYRxroYYYYYYyovk",
      "evoyoooooooqoooooooooovk",
      "evoccccccccYobucbucbuovk",
      "evoccccccccYobucbucuuovk",
      "evoYcccccccYoucbucbuYovk",
      ".kvocccccbbYobbucbucovk.",
      ".evocccbbbbYobucbucuovk.",
      "..kvobbbbbbYobucuucovk..",
      "..evobbbbbuYoucuucuovk..",
      "...kgobbbbbYobuuuuovk...",
      "....kvYbbbbYouuuuYvk....",
      ".....kvobbuYouuuovk.....",
      "......kvouuYouuogk......",
      ".......kvouYouovk.......",
      "........kvoyoovk........",
      ".........kvvvvk.........",
      "..........kkkk..........",
    ],
    [ // 背骨の稜・紅の山形・金縁
      "...OOOOOOOOOOOOOOOOOO...",
      "..Oyyyyyyyyyyyyyyyyyyk..",
      ".Oywwwvwwwwxgvvvggggeyk.",
      ".OyvYwwwwwwxgvvvggeYeyk.",
      ".Oywwwwwwwwxgvvvvggeeyk.",
      ".Oywwwvwwwwxgvvvgggeeyk.",
      ".Oyrwwwwwwwxgvvvgggeryk.",
      ".OyRrwwwwwvxgvvvgggRqyk.",
      ".OyrrrwwwvvxgvvgggRrqyk.",
      ".OywYrrwvvvxgvgggRrYeyk.",
      ".OyvvrrrvgvxggggRrqeeok.",
      ".OovvvrrrvvxgggRrqeeeyk.",
      "..kyvvvrrrvcggRrqeeeyk..",
      "..Oyvvvvrqcxbuqqeeeeyk..",
      "...kyvggggrugreeeeeyk...",
      "...Oyggggggwgeeeeeeok...",
      "....kygggggvgeeeeeyk....",
      ".....koggeewgeeeeyk.....",
      "......kyeeewgeeeyk......",
      ".......kyeewgeeyk.......",
      "........kyewgeyk........",
      ".........kyyyyk.........",
      "..........kkkk..........",
      "........................",
    ],
  ],
  round: [ // 丸盾 (2種)
    [ // 板張りの木盾・鉄の縁・びょう頭
      "...........ee...........",
      ".......eeeewvkeee.......",
      "......ewwwvvvvwwwk......",
      ".....ewvxvvNNvgxvwk.....",
      "....ewvvsSNNSnSSvvwk....",
      "...ewvNNNSNNSNSSNsgek...",
      "..ewvvvvSNvSNgSNggggek..",
      ".evvvNNSNSSNnSNnsssggek.",
      ".ewxSNSNNSnxwnSnsssSwek.",
      ".evvSsSNNxxxwvgssssSgek.",
      ".evvSNNsNxxxwvgsssSSggk.",
      "ewvsSNNnwxwwgvgessSSSgek",
      "ewvnSsnnvwwvggeesSSSSgek",
      ".kvvSnnnnvvggeesSSSSggk.",
      ".ewvSnnnseeeeeesSSSSgek.",
      ".ewxSssssSseeSSSSsSSwek.",
      ".ewvvssssSssSSSSSSSggek.",
      "..kwgvvvvvvvggggggggek..",
      "...kwgSSSSsSSSSSSSgek...",
      "....keggSSSSsSSSggek....",
      ".....kegwggSSggwgek.....",
      "......keeeggggeeek......",
      ".......kkkkeekkkk.......",
      "...........kk...........",
    ],
    [ // 日輪の円盾: 金縁・放射の浮彫
      "...........OO...........",
      ".......OOOOYYkOOO.......",
      "......OYYYoyyyYyYk......",
      ".....OYyyyggggyyoYk.....",
      "....OYoggwwwwvvggoYk....",
      "...OYygwwwwwwvvvggOok...",
      "..OYygywwwwwwvvvgyeOok..",
      ".OYygvwYwvvwvvgvoggeOok.",
      ".OYygwwwYwwwgvgygggeOok.",
      ".OYowwwvwwYYoyvgggeeOok.",
      ".OygwwwwwYYYyyogggeeeOk.",
      "OYygvwwgvYYxYoOggeeeeOok",
      "OyygvvvvgoyYoOOgeeeeeOok",
      ".kygvvvvvoooOOOgeeeeeOk.",
      ".OYygvvvvgOOOOeeeeeeOok.",
      ".OYyggggoggggeeyeeeeOok.",
      ".OYygggygggeeeeeyeeeOok.",
      "..kYygygeeeeeeeeeoeOok..",
      "...kYOeeeeeeeeeeeeOok...",
      "....koOeeeeeeeeeeOok....",
      ".....koOOOeeeeOOOok.....",
      "......koooOOOOoook......",
      ".......kkkkookkkk.......",
      "...........kk...........",
    ],
  ],
  // --- 鎧 (各2種) ---
  plate: [ // 胸甲・重鎧 (2種)
    [ // 騎士の胸甲: 丸い肩当て・金の襟・草摺
      "...eeee..........eeee...",
      "..ewvxxk........evggek..",
      ".ewwvwwwkkkkkkOeggggeek.",
      "egvvvvgvykkkkkkoeeeeeeek",
      "eeeeeeeeyykkkkyoeeeeeeek",
      "ewwYvgewvwyyyyvvgwwgYgek",
      ".kvgggekwwwxgvvgvvggekk.",
      ".ewwvgewwwvxgvgggwwvgek.",
      "..kvgkgvvvvxgggggevgkk..",
      "...kvvvvvvvxgggeeeeek...",
      "...egggggggwggeeeeeek...",
      "...eeggggggvgeeeeeeek...",
      "....keeeegewgeeeeeek....",
      "....eeeeeeewgeeeeeek....",
      ".....klllldyylllldk.....",
      ".....DdDDDDoodDDDDk.....",
      "....evwwwwwvvvggeeek....",
      "....egvvvvvgggeekkke....",
      "...evwYwwwwgvvgggYeek...",
      "...egvgvvvvgggeeekkke...",
      "..evvwwwwwvvvvgggeeeek..",
      "..egvvvvvgggggeeekkkk...",
      "...kkkkkkkkkkkkkk.......",
      "........................",
    ],
    [ // 黒鋼の重鎧: 首鎧・重ね札・鎖の裾
      "..ee.....OOOOOO.....ee..",
      ".exxk...OYyyYYyk...egvk.",
      "ewxxxkeOyyooooookeeggevk",
      "ewwwwwwkyokkkkYokgeeeeek",
      "ggggggggvyyyyyoveeeeeeee",
      "eeeeeeeevwwwwwvgeeeeeeee",
      "kgvvvvvwvwwvvvggveekkkkk",
      "evwwwwwvwwwvvvgggggeeeek",
      ".kvggwwvwwRrRvgggegkkkk.",
      "..kwwwwwwwrrqvgggeegek..",
      "...kvvvvvvvqggeeekkkk...",
      "...evwwwwwwvvvgggeeek...",
      "....kwvvwwvvvggggeek....",
      "....evvvvgvgggeeekk.....",
      "....evvvvvvgggeeeeek....",
      ".....kdddddYydddddk.....",
      "....ewgwgvevevegeek.....",
      "....egwgwgvevegegkek....",
      "...egwgwgwegevegeekek...",
      "...ewgwgwgvevegegkek....",
      "..evgwgvgwevevegeekek...",
      "..eewgwgwgvevegegkekek..",
      "...kkkkkkkkkkkkkk.k.k...",
      "........................",
    ],
  ],
  robe: [ // 法衣 (2種)
    [ // 魔導師のローブ: 広い袖・金の前立て・帯の宝玉
      "........JJJJJJJJ........",
      ".......Jiipiiiipk.......",
      "......JpjJJJJJJppk......",
      ".....JiipJJJJJJjjJk.....",
      "....JiiiiyFFFFyjjJJk....",
      "...JppiiiiyFFyjjjJJJk...",
      "..JipiiiiiiYypjjjJJjjk..",
      ".JipppipYiiYopjjjJpjjjk.",
      ".JippjpiiiiYopjYjJpjjJk.",
      "JippjpJpiiiYopjjjJjjjjJk",
      "JipyjjJiiiiyopjjjJjjJJJk",
      "JpjjjjJCCCCcbCCCCJJJYJJk",
      "JpjjjJkiiiiYypjjjkjJJJJk",
      "OyyjjJkiiiiYopjjjkjJJYyk",
      ".kooyykiiiiYopjjjkyoook.",
      "..kkkkiiiipYopjjjJkkkk..",
      ".....JiijiiYopjJjJk.....",
      "....JiiYjiiYojjJjJJk....",
      "....JpiijiiYopjJjJJk....",
      "...JpiiijiiYopjJYJJJk...",
      "...JpiiijiiYopjJjJJJk...",
      "..Ooooyyoyoooyyyyyoyyk..",
      "...kkkkkkkkkkkkkkkkkk...",
      "........................",
    ],
    [ // 頭巾つきの外套: 尖った頭巾・頸垂帯
      "..........FAAk..........",
      ".........FACCCk.........",
      "........FAAAACCk........",
      ".......FAAAACCCfk.......",
      ".......FAAAkkCffk.......",
      "......FAACkkkkffFk......",
      "......FCCkkkkkkFFk......",
      ".....FfCCkkkkkkFFFk.....",
      "....FAffffkkkkFFFFFk....",
      "...FAAAFFFFFFFFFFfFFk...",
      "..FAACAAAFFYrFFfffFFFk..",
      ".FCCACAAYyppjJYyffFFFFk.",
      ".FCAfAAAYoppjJYoffFkFFk.",
      "FfCAfAAAYoppjJYoffFkFFFk",
      "FffAfAAAYoppjJYyffFkFFFk",
      "FfCfAAAAxoppjJYyffFFkFFk",
      ".kffAACAyoppjJYoffFFkFk.",
      ".FCfAACAYoppjJYoffFFkFk.",
      ".FCAfAACyoppjJyoffFkFFk.",
      ".FCAfACCyoppjJyoffFkFFk.",
      ".FCCAfAAoOppjJoOffkFFFk.",
      ".FfCfCCCCCfffffFFFFFFFk.",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
    ],
  ],
  // --- 頭 ---
  helm: [ // 兜 (2種)
    [ // 騎士の大兜: 羽飾り・十字の覗き穴
      "..............qqq.......",
      "...........qqqRRrk......",
      "..........qrRRRrrqk.....",
      "........eqrRrrrqqk......",
      "......eewwgxgvvvke......",
      ".....ewwvwgxgvvvggk.....",
      "....ewwwwwvxgvvvggek....",
      "...evwwwvwvxgvvvggeek...",
      "...ewwwwwwvxgvvvggeek...",
      "..Oyyyoyyyyyyyyyyyyyyk..",
      "..evwYwwwwvwgvvvggYeek..",
      "..evwkkkkkkwgkkkkkkeek..",
      "..evwwwwwwvwgvvvggeeek..",
      "..evwvwwwwvwkkvvggeeek..",
      "..evwwwwwwvwkkgvgkekek..",
      "..evwwwwwwgwkkvvggeeek..",
      "...kwvwwwwvwkkvvgkekk...",
      "...ewywwwwvvgvvvggYek...",
      "....kwwvwwgwggvvggek....",
      "....OyYYYYYYYYYYYYyk....",
      ".....kyoooooooooook.....",
      "......kkkkkkkkkkkk......",
      "........................",
      "........................",
    ],
    [ // 角兜: 骨の双角・鼻当て
      "........................",
      "........................",
      ".z....................z.",
      "zBk..................zIk",
      "zBk..................zIk",
      "zBk..................zBk",
      "zIzk......eeee......zzBk",
      ".kIzkz..eewwwvke..zzzIk.",
      ".zBIzzkexxxwwvvvkzzzzBk.",
      "..kBIIzYxxxwwvvvyzIIBk..",
      "...kBByIxxwwwvvvIoBBk...",
      "....kBBBxwwwvvvgBBBk....",
      "....OYYYYYYYYYYYYYyk....",
      "....OyoYooooooooYook....",
      "....evvvkkkwgkkkeeek....",
      "....evvvkkkwgkkkeeek....",
      "....egvvvkkwgkkeeeek....",
      "....eggggkkwgkkeeeek....",
      "....eeeggkkkkkkeeeek....",
      ".....keeekkkkkkeeek.....",
      "......keekkkkkeeek......",
      ".......kk......kk.......",
      "........................",
      "........................",
    ],
  ],
  hat: [ // 帽子・頭巾 (2種)
    [ // とんがり帽子: 折れた先端・留め金・広いつば
      "........................",
      "........................",
      "........................",
      ".................FF.....",
      "................FAfk....",
      "...............FACFk....",
      "..............FACFk.....",
      ".............FAAyFk.....",
      "............FACCfFk.....",
      "...........FAACCfFk.....",
      "..........FAYACffFk.....",
      ".........FAAAACCfFFk....",
      "........FCAACCCffFFk....",
      ".......FCAAACCyCffFFk...",
      ".......FCACAACCCffFFk...",
      "......JjiiiiipppjjJJJk..",
      "..FFFFkiijjJkyyipppjJk..",
      ".FAAAAAAAAAAACAAAAAAAfk.",
      "FCAAAAAACCCfCCCCCCCCCCfk",
      ".kFFFFFFFFFFFFFFFFFFFFk.",
      "..kkFFFFFFFFFFFFFFFFkk..",
      "....kkkkkkkkkkkkkkkk....",
      "........................",
      "........................",
    ],
    [ // 革の頭巾: 深い影・肩掛け
      "........................",
      "........................",
      "..........DDDD..........",
      "........DDLLDlkD........",
      ".......DLLLlDLdlk.......",
      "......DLLLLLDLlldk......",
      ".....DLLLLLLDlllddk.....",
      ".....DLLlLLlDlddddk.....",
      "....DLLLLddddddddDDk....",
      "....DlLLdkkkkkkddDDk....",
      "....DlldkSSSSSSkdDDk....",
      "....DlldkkkkkkkkdDDk....",
      "....DdddkkkkkkkkdDDk....",
      "....DdDddkkkkkkdDDDk....",
      "...DlDDDDdkkkkdDDDDlk...",
      "..DLLlDDDDDDDDDDDLLlDk..",
      ".DLLLLlldDDyyLLlllldDDk.",
      ".DlLLDLLLLllllldddDDDDk.",
      ".DlLLLLDLLllllldDdDDDDk.",
      ".DDdddddddDDDDDDDDSSSSk.",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
    ],
  ],
  circlet: [ // 宝冠: 金の環・正面の紅玉・小さな尖塔
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    ".......OOOOOOOOOO.......",
    "....OOOoooooyOOOOkOO....",
    "...OookkkkkkykkkkOOOk...",
    "..Ookk..O.OYook.O.kkOk..",
    ".OookO.OykkoRokOyk.OOOk.",
    ".OokkykkykoRxrokykOykOk.",
    ".OyykykYooorrqoYyokoook.",
    ".OyoYyoYyokoqokYooYyook.",
    "..kyyoYYYkkkokkyyooook..",
    "...kybYYYYYYYYyyyyobk...",
    "....kkkYGYyYYYooGkkk....",
    ".......kkkkkkkkkk.......",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
  ],
  // --- 足 ---
  boots: [ // 長靴 (2種)
    [ // 革の長靴 (一足): 折り返しの履き口・留め革
      "........................",
      "........................",
      "........................",
      ".............DDDDDDDD...",
      "............DdddddddDk..",
      "............SSSSSSSSSk..",
      ".............kddDDSSk...",
      "......DDDDDDDkddDkSSk...",
      ".....DLlLLLLLlkOkykOk...",
      ".....DDDDDDDDDkdDkSSk...",
      "......kLLlddDkddDDSSk...",
      "......DLLlldDkddDSSSk...",
      "......OoooYookdDDSSSk...",
      "......DLLlldDkDDSSSSk...",
      "......DLLlldDkDDDSSSSk..",
      ".....DLLLlddDkDDDSSSSk..",
      "...DDLLLlldDDkSSSSSSSSk.",
      "..DllLLllddDDkkkkkSSSk..",
      ".DlLLLLlllddDDk...kkk...",
      ".DlLLLllllddDDk.........",
      ".Ssssssssssssssk........",
      "..kssskkkkksssk.........",
      "...kkk.....kkk..........",
      "........................",
    ],
    [ // 毛皮縁の旅靴: 交差した革紐
      "........................",
      "...........zzzzzzzzz....",
      "..........zBBBIBBBBIk...",
      ".........zIIIIIIzIIIIk..",
      "..........kzzzzzzzzzk...",
      "...........kLLLlddDk....",
      "...........DLLLlddDk....",
      "...........DdYoDDSSk....",
      "...........DLLLlddDk....",
      "...........DLLLlddDk....",
      "...........DLLLlddDk....",
      "...........DdYoDDSSk....",
      "...........DLlLlddDk....",
      "..........DLLLlldDDk....",
      ".........DLlLLdddDDk....",
      ".......DDlLLLllddDDk....",
      ".....DDlLLLLddlddDDk....",
      "...DDlLLLLLdllddDDDk....",
      "..DllLLLLLllllddDDDk....",
      "..DlLlLLLLllldddDDDk....",
      "...ksssssssssssssssk....",
      "....kkkkkkkkksssskk.....",
      ".............kkkk.......",
      "........................",
    ],
  ],
  greaves: [ // 脚甲 (2種)
    [ // 鋼のすね当て (一対): 膝当て・札板の鉄靴
      "........................",
      ".............eeeee......",
      "............exxwvgk.....",
      "...........evvvYggek....",
      "...........eeeeeeeek....",
      "............kwevvgek....",
      "...........egggeekk.....",
      "...........ewewvggek....",
      "...........ewewvggek....",
      "...........egggeekk.....",
      "...........ewewvggek....",
      "...........ewewvggek....",
      "...........OYYYyooOk....",
      "..........ewwwvvgeek....",
      ".........eggggeeekk.....",
      ".......eevwwwvvggeek....",
      ".....eeggggggeeekkk.....",
      "....evwwwwvvvvggeeek....",
      "...egggggggeeeekkkk.....",
      "..ewwwwwwwvvvgggeeek....",
      "...keeeeeeeeeeeeeeek....",
      "....kkkkkkkkkeeeekk.....",
      ".............kkkk.......",
      "........................",
    ],
    [ // 金縁の騎士脚甲: 棘の膝当て・翼の飾り
      "........................",
      "........................",
      "...............eeeee....",
      "..............evvggxk...",
      ".............egggeek....",
      "..............kkkkkO....",
      "...........kkOovvgkok...",
      "........eeekkkvvggek....",
      ".......exwvvxkvvggek....",
      "......evRrggekvvggek....",
      "......eeeeeeekvvggek....",
      "....zOkoewveykyyoooOk...",
      "...zBYkwevvgekeekkkk....",
      "..OYYYYwevvgekvggekk....",
      "...kYoowevvgekekkkkk....",
      "....kkkwevvgekvggeekO...",
      "......OYYyyoOkOOOOOOOk..",
      ".....egggeekkkkkkkkkk...",
      "....ewwwvvgeek..........",
      "...eggggeeekke..........",
      "..evwwwwgvggeek.........",
      "..Ooooooooooook.........",
      "...kkkkkkkkkkk..........",
      "........................",
    ],
  ],
  // --- 小手 ---
  gloves: [ // 手袋 (2種)
    [ // 革の手袋: 開いた手・縫い目の袖口
      "........................",
      "........................",
      "..........DD............",
      ".......DDDLdkDD.........",
      "......DLdkLdkLdkDD......",
      "......DLdkLdkLdkLdk.....",
      "......DLdkLdkLdkLdk.....",
      "......DLdkLdkLdkLdk.....",
      "......DLdkLdkLdkLdk.....",
      "...DD.DdLLdllddddDk.....",
      "..DLlkklLLLLdlddDDk.....",
      "..DlllklLlLLllddDDk.....",
      "...kldlddddddDDDDDk.....",
      "....kldddddDDDDDDDk.....",
      ".....kDDDDDDDDDDDDk.....",
      "......kDDDDDDDDDDk......",
      "......DdlllddDDSSk......",
      ".....DdlllldddDDSSk.....",
      ".....DdllllldlDlSlk.....",
      ".....DdlllldddDDSSk.....",
      ".....SSSSSSSSSSSSSk.....",
      "......kkkkkkkkkkkk......",
      "........................",
      "........................",
    ],
    [ // 拳闘の籠手袋: 握り拳・びょう・編み上げの腕当て
      "........................",
      "...............DD.......",
      "............DDDlDkDD....",
      "...........DlDklDklDkDD.",
      "...........DlDkdDklDklDk",
      "...........DdDklDklDklDk",
      "...........DdllllddDDSSk",
      ".........DDkdllllddDDSSk",
      "......DDDLdkkklllddDDSSk",
      ".....DLdkLdkLdkkklddDSk.",
      ".....DLdkLdkLdkLdkdDDSk.",
      ".....DLdkLdkldkLdkDSSk..",
      ".....DdLLLLllddDDkSSSk..",
      "...DDklLLLlllddDDkSSSk..",
      "..DLlklxLLxllxdDDkSSSSk.",
      "..DlllLLLLLLlldDkSSSSSk.",
      "...kldLLLLLllddDkkkkkk..",
      "....kllllldddDDk........",
      ".....kDDDDDDDDDk........",
      ".....DllllddDSSk........",
      "....DdllllldlDlSk.......",
      "....SSSSSSSSSSSSk.......",
      ".....kkkkkkkkkkk........",
      "........................",
    ],
  ],
  gauntlet: [ // 籠手 (2種)
    [ // 鋼の籠手: 札板の指・金縁の袖口
      ".........eee............",
      ".....eeeewvekeee........",
      "....ewvekwgekwvek.......",
      "....ewvekvvekwvekeee....",
      "....egekkgekkgekkvvek...",
      "....ewgekwvekwgekwvek...",
      "....ewvekwvekwvekgek....",
      "....egekkgekkgekkvvek...",
      "..eekwvekwvekwvekwvek...",
      ".ewvkwxwvwxwwwxwwwxvk...",
      "ewvvvvggggggggggggggk...",
      "eevvgwweeewwxwwvggggk...",
      ".kevgvveeevvwvvggeeek...",
      "..kegvweeewvwvvggeeek...",
      "...kwweeewwvwvgggeeek...",
      "...egveeevvgggeeeeeek...",
      "...OyYYYYYYyyyoooOOOk...",
      "..evwwvwwvvvvvgggeeeek..",
      "..evwwwwwvvvvvgggeeeek..",
      "..eegggggggeeeeeeeeeek..",
      "..evwvwwwwvvvvgggeeeek..",
      "..OyYYYYYYyyyyoooOOOOk..",
      "...kkkkkkkkkkkkkkkkkk...",
      "........................",
    ],
    [ // かぎ爪の籠手: 鋭い爪・紅玉の甲
      "......e..exk..e.........",
      ".....exkevwk.exk........",
      "....evvkkggkevwk..e.....",
      "....evgkkggkkvgk.exk....",
      "....eekkkekkkekkevwk....",
      "....evgkkvgkkvgkkvgk....",
      "....evgkkvgkkvgkkekk....",
      "..e.eekkkekkkekkkvgk....",
      ".ewkkvgkkvgkkvgkkvgk....",
      "exvgkvwvvvwvgvwvvvwgk...",
      "evggggeeeeeeeeeeeeeek...",
      ".kggevvgvvvgRvgggeeek...",
      "..kgeggvvgvRrrgeekkk....",
      "...kegvvvvvrrqgeekkk....",
      "...evvgvvvvgqgeeekkk....",
      "...eeggggggeeekkkkkO....",
      "..ekyYYYYYYyyyoooOOOke..",
      ".ewgvvvvvvggggeeekkkkgk.",
      "..kgvvvvvvggggeeekkkkk..",
      "..ekeeeeeeekkkkkkkkkke..",
      ".evgvvvvvvggggeeekkkkek.",
      "..kyYYYYYYyyyooooOOOOk..",
      "...kkkkkkkkkkkkkkkkkk...",
      "........................",
    ],
  ],
  // --- 装飾品 ---
  ring: [ // 指輪 (2種)
    [ // 紅玉の指輪: 金の環・爪留めの大粒
      "........................",
      "..........qqqq..........",
      ".........qRRRRk.........",
      "........qRxRRrrkO.......",
      ".......OoRRrrrrqok......",
      ".......qRrrrrrqqOk......",
      "........kqrrrqqkk.......",
      ".........kqqqqk.........",
      ".........Ooyoook........",
      ".......OOoyYYyyok.......",
      "......OooooOOOoOOk......",
      "....OOokkkkkkkkkkOkO....",
      "...Oook..........kOOk...",
      "...Oook..........OOOk...",
      "..Oook............kOOk..",
      "..Ooook..........OOOOk..",
      "..Oyyyk..........Ooook..",
      "..OyyyykO......OOooook..",
      "...kyyyYYkOOOOOyyoook...",
      "...OyyyYYYYYYyyyyoook...",
      "....kkyYYYYYYyyyyokk....",
      "......kYYYYYYyyyyk......",
      ".......kkkkkkkkkk.......",
      "........................",
    ],
    [ // 刻印の指輪: 銀の太環・印章面・蒼玉の粒
      "........................",
      "........................",
      "........................",
      ".........eeeeee.........",
      "........exxwwggk........",
      ".......exxwwevvgk.......",
      "......ewwwweeeggek......",
      "......evvvevegeeek......",
      "......evvvggegeeek......",
      ".....egggggeeeeeeek.....",
      "....ucbkkeeeeeekkcbk....",
      "...eguk..kkkkkk..kuek...",
      "..egggk..........eeeek..",
      "..egggk..........eeeek..",
      "..egggk..........eeeek..",
      "..evvvk..........egggk..",
      "..evvvwkee....eeevgggk..",
      "..evvgwwwwkeeevvvvgggk..",
      "...kgvwwwwvwvvvvvvggk...",
      "....kvvwwwwwwvvvgvgk....",
      ".....kvwwwwwwvvvvvk.....",
      "......kkwewwevvekk......",
      "........kkkkkkkk........",
      "........................",
    ],
  ],
  amulet: [ // 護符 (2種)
    [ // 雫の護符: 金鎖・蒼玉の雫
      "...O................OO..",
      "..Ook..............Oyok.",
      "..Ooyk............Oook..",
      "...kyok..........Oook...",
      "....kyok........Oook....",
      ".....kokO......Okok.....",
      "......koyk....Oyok......",
      ".......kyk....Ook.......",
      "........kok..Ook........",
      ".........kokOok.........",
      "..........kyYk..........",
      ".........OyoOyk.........",
      "........OYYYYYYk........",
      "........OYxccbYk........",
      "........OYccbbYk........",
      ".......OYcxccbuok.......",
      ".......Oyxxccbbok.......",
      "......OYYcccbbuook......",
      ".......kYcbbbbuok.......",
      ".......OYbbbbuuok.......",
      "........kobuuuok........",
      ".........kooook.........",
      "..........kkkk..........",
      "........................",
    ],
    [ // 日輪の護符: 革紐・金の円盤・紅の宝玉
      "....D..............DD...",
      "...Ddk............DDDk..",
      "...Dddk..........DDDk...",
      "....kddk........DDDk....",
      ".....kddk......DDDk.....",
      "......kddk....DDDk......",
      ".......kddk..DDDk.......",
      "......O.kddkDDDk.O......",
      ".....OYkkYYkkYYkOYk.....",
      ".....OYYkYYYYYYkYYk.....",
      "......kYYooYyooYYk......",
      "...OOOkYoYYYYyoOokOOO...",
      "..OYYYYyYYYRryoOoooook..",
      "...kkyYoYYxRrroOOookk...",
      ".....kYoyyRrrqoOOok.....",
      "...OOYYoyyrrqqOOOookO...",
      "..OYYyYooooqqOOOOooook..",
      "...kkkkYoOOOOOOOokkkk...",
      "......OooOOOOOOook......",
      ".....Oooooooooooook.....",
      ".....Ookkooooookkok.....",
      "......k.Oookkook.k......",
      "........OookOook........",
      ".........kk..kk.........",
    ],
  ],
  // --- 収集品 (戦利品) ---
  fang: [ // 魔獣の牙
    "........................",
    "........................",
    ".................qq.....",
    "...............zqqrkz...",
    "..............zzrzzqIk..",
    "..............zzzzzIIIk.",
    "..............zzzzzIqk..",
    ".............zzzzzzIzk..",
    ".............zzIIBzIzk..",
    ".............zzrBBBBBk..",
    "............zzzIBBBBk...",
    "............zzqBBBBBk...",
    "...........zzIBBBBBk....",
    "..........zzIIBBBBk.....",
    "..........zzIBBBBk......",
    "........zzIIBBBkk.......",
    ".......zzIBBIBk.........",
    "......zzIBBBkk..........",
    "....zzzBxxkk............",
    "...zzBxkkk..............",
    "....kkk.................",
    "........................",
    "........................",
    "........................",
  ],
  gem: [ // 宝石
    "........................",
    "..................e.....",
    ".................exk....",
    "................exxxk...",
    "........uueuuuuu.kxk....",
    ".......uccxccccuk.k.....",
    "......ucccxwcccuuk......",
    ".....ucccbbbbbbuuuk.....",
    "....uccccbbbbbbuuuuk....",
    "....exxxxccccccbbbbk....",
    ".....kbwuccbbbuuuuk.....",
    ".....ubbuccbbbuuuuk.....",
    "......kbbxcbbbuuuk......",
    "....u..kbuccbbuuk.......",
    "...uck.ubbucbuuuk.......",
    "....k...kbucbuuk........",
    "........ubucbuuk........",
    ".........kbubuk.........",
    "..........kubuk.........",
    "..........ucuk..........",
    "...........kuk..........",
    "............k...........",
    "........................",
    "........................",
  ],
  ore: [ // 鉱石
    "........................",
    "...........e............",
    "..........exk..e........",
    ".........exwvkexk.......",
    ".........ewvgkxwvk......",
    "........exwvgkvvgk......",
    "........ewggekggek......",
    ".......SkNgeNNgek.......",
    "......SNNNsnNNNssk......",
    ".....SsNNNNsNnNsssk.....",
    "....SNNsnNnyNnsssssk....",
    "....SNNNssYsNsssssssk...",
    "...SNNNNNNysNssssssssk..",
    "...SNNNnooNnNsssssyySk..",
    "..SsssoossssssSSyYSSSk..",
    "..SnnonsnnsssSyySSSSSk..",
    "...ksnnnSsSSsSSosssSSk..",
    "...SnnnSsSSSsSSSoSSssk..",
    "....knssSSSSsSSSSoSkk...",
    "....SsSSSSSSsSSSkkk.....",
    ".....kkkkkkkkkkk........",
    "........................",
    "........................",
    "........................",
  ],
  bone: [ // 骨
    "........................",
    "...............eez......",
    "..............exxIk.....",
    ".............exxIIzk....",
    ".............zBIBIzkz...",
    ".............zBIIzwxBk..",
    ".............zzzzxxxBzk.",
    "..............kBIxBBIzk.",
    ".............zBIzBBIzzk.",
    "............zBIzkzzzzk..",
    "...........zBzzk.kkkk...",
    "..........zBzzk.........",
    ".........zBIzk..........",
    "...eezz.zBIzk...........",
    "..exxIIkBzzk............",
    ".exxBBzBIzk.............",
    ".zBBBIzIzk..............",
    ".zIIIzxxBIk.............",
    "..kzzxxxBIk.............",
    "...kkBBBIzk.............",
    "....zIIzzzk.............",
    ".....kzzzk..............",
    "......kkk...............",
    "........................",
  ],
  coin: [ // 古代の金貨
    "........................",
    ".............OOOOO......",
    "...........OOoyyyykO....",
    "..........OyyyOOOyyyk...",
    ".........OyyOyyyyyOOOk..",
    "......OOOkyOyyyyoooOOk..",
    ".....OYyYYYYYOyyooooOOk.",
    "....exYooooooYYoooooOOk.",
    "...exYxYYYYyyoYOooooOOk.",
    "..OYYxYyYYyyoyyOOoooOOk.",
    ".OYYoYYYooooyyoyOOooOOk.",
    ".OYoYYYoyYyyOyyoyOoOOk..",
    ".OyoYYYoOyOyOyooyOOOOk..",
    ".OYoYYooooyyOoooyOOOk...",
    ".OYoYyyyoYOOoooooOkk....",
    ".OYoyyyyOyOoooooyOk.....",
    ".OYoyyyyooooooooyOk.....",
    ".OYooyyyooooooooOOk.....",
    "..kYYyyyooooooyOok......",
    "...kOOyooooooyOOk.......",
    "....kOOoyyyyyOOk........",
    ".....kOOOOOOOOk.........",
    "......kkkkkkkk..........",
    "........................",
  ],
  vial: [ // 霊薬の小瓶
    "........................",
    "..........DDDD..........",
    ".........DLLLlk.........",
    ".........Dldddk.........",
    ".........OYYyOk.........",
    ".........exAAAk.........",
    ".........exxAAk.........",
    "........exxAAAAk........",
    "......eexxxAAAACkF......",
    ".....exxxxAAAAACCCk.....",
    "....ewxxxAAAAACCCffk....",
    "...FAcccccbbbbbbbbffk...",
    "...FAccxccbbbbbbbuufk...",
    "..FCccwcbbbbbbbbuuuufk..",
    "..FAbbxbbbbbbcbuuuuufk..",
    "..FCbbcbbbbbbbuuuuuufk..",
    "..FCbbbbbbbbbuuuuuuufk..",
    "..Ffbbbbbbbuuuucuuuufk..",
    "...kfuuuuucuuuuuuuufk...",
    "...Fffuuuuuuuuuuuuffk...",
    "....kffuuuuuuuuuuffk....",
    ".....kkffffffffffkk.....",
    ".......kkkkkkkkkk.......",
    "........................",
  ],
  cloth: [ // 布 (反物)
    "........................",
    "........................",
    "........................",
    "........................",
    "...JJJJJJJJJJJJJJJJ.....",
    "..Jiiiipiiiiiiiiiijk....",
    ".Jipiiiiiiiiippjppppk...",
    ".JiiiiiiiiiippppppjjkJ..",
    ".Jiiipiiiipppppppppjppk.",
    ".OyYYYYyYyyyyoooOOOOppjk",
    ".JiiiyippyjppypppyjjpJjk",
    ".JiiyiopypopypopyjojJpJk",
    ".JipiopppopppopjjojjjjJk",
    ".OyYYYYYYyyyyoooOOOOjjJk",
    ".JippjppppjjjjjjjjjjJJJk",
    ".JipppjpppjjjjjjjjjjJJk.",
    ".Jpppppppjjjjjjjjjjjkk..",
    "..kpjjjjjjjjjjjjjjjk....",
    "...kooooooooooooook.....",
    "...Ookokokokokokok......",
    "....k.k.k.k.k.k.k.......",
    "........................",
    "........................",
    "........................",
  ],
  eye: [ // 魔眼
    "........................",
    "........................",
    "........eeeeezzz........",
    "......eexxxxwBBBkz......",
    ".....exxwxxxxBrBBIk.....",
    "....exxxxxxxxrBBBIIk....",
    "...exxxxxxxxxrBBBIIzk...",
    "...exxxxxxxxuuBBIIIzk...",
    "..exxxxxxuucccuuIIIzzk..",
    "..exxxxxxucckccuuIIzzk..",
    "..exxrqxucxbkbbbuIzzzk..",
    "..qrrxwqucxbkkbbbuzzzk..",
    "..zBBBIqucbbkkbbbuzzzk..",
    "..zBBBBBucbbkkbbbzzzzk..",
    "..zBBBBBucbbkkbbuzzrrk..",
    "..zIIIIIIubbkbbuuqrzzk..",
    "...kIIIIzzuukuuzzzzzk...",
    "...zzIIIzIzzzzzzzzzzk...",
    "....kzzzzzrzzzzzzzzk....",
    ".....kzzzzrzzzzzzzk.....",
    "......kkzrzzzzzzkk......",
    "........kkkkkkkk........",
    "........................",
    "........................",
  ],
  bell: [ // 鈴
    "..........OOOO..........",
    ".........OYyyyk.........",
    "........OYokkYyk........",
    "........OyokkYok........",
    ".........kyyook.........",
    ".........OkYokO.........",
    "........OYYyyoOk........",
    ".......OYxyyyoOOk.......",
    "......OyYYYyyooOOk......",
    "......OyYYYyyooOOk......",
    "......OyYyYyyooOOk......",
    "......OyyyooooOOOk......",
    ".....OyYYYYyyyooOOk.....",
    ".....OyYYYYyyyooOOk.....",
    "....OoYYYYYyyyooOOOk....",
    "...OyYYYYYyyyyoooOOOk...",
    "..OoYYYYYYyyyyoooOOOOk..",
    "..OyYYYYYYyyyyoooOOOOk..",
    "...kOOOOOOOOOOOOOOOOk...",
    "....kkkkkkkYykkkkkkk....",
    ".........OyyoOk.........",
    "..........kOOk..........",
    "...........kk...........",
    "........................",
  ],
  skull: [ // 髑髏
    "........................",
    "........................",
    ".........eeeezz.........",
    ".......eexxxxBBkz.......",
    "......exxxxxxxzBIk......",
    ".....exwxxxxxxzBIIk.....",
    "....exxxxxxxxBBzIIzk....",
    "....exxwxxxxBBBzzIzk....",
    "...exxxwxxxBBBBIIIzzk...",
    "...exxxxxBBBBBIIIzzzk...",
    "...zBBIkkkkBBkkkkzzzk...",
    "...zBBkkrkkkIkkqkkkzk...",
    "...zIBkkkkkkIkkkkkkzk...",
    "....kIIkkkkIIzkkkkzzk...",
    "....zzIIIIzzkzzzzzzk....",
    ".....kzzzzzkkkzzzzzk....",
    "......kzzzzzzzzzzzk.....",
    "......zBBBBBBBBBBBk.....",
    "......zBkBkBkBkBkBk.....",
    ".......kBBBBIIIzzk......",
    "........kBBBIIzzk.......",
    ".........kkkkkkk........",
    "........................",
    "........................",
  ],
  horn: [ // 魔獣の角
    "........................",
    "........................",
    "........................",
    "........................",
    "..........zzzzzzzzz.....",
    "........zzIBIIIBBIzk....",
    ".......zIIBBIIIIBxxBk...",
    "......zBIIIIzzIzIBxxBk..",
    ".....zBBIzIIzzkkkkBBxBk.",
    "....zIBBzzzzzk....kkBIBk",
    "...zIIBIzzzzk.......kIBk",
    "..zBzIBIzzzk.........kBk",
    "..zBIzzIzzzk..........k.",
    ".zIBIzzzzzk.............",
    ".zIIIzzzzk..............",
    "zIIIIzzzzk..............",
    "zBIIzzzzzk..............",
    "zBzzzzzzk...............",
    "IBzzzzzzk...............",
    "IYYYyyyok...............",
    "IYYYyyyok...............",
    "IYYyyyook...............",
    "Izzzzzzzzk..............",
    "Bzzzzzzzk...............",
  ],
  book: [ // 魔導書
    "........................",
    "....JJJJJJJJJJJJJOOO....",
    "...JiiiipiiiipppjYYYk...",
    "..JJjppppjpppjjjjjYyIk..",
    "..JJjpppppppjjjjjjjyIzk.",
    "..JJyppppppjjjjjjjjJIIk.",
    "..JJjpppppjjjjjjjjjJIzk.",
    "..JJjppppjoyyojjjjjJIIk.",
    "..JJjpppjyjjjjojjjjJIzk.",
    "..JJyppjyjjRRjjojjjoyIk.",
    "..JJjpjjyjRxrRjojjJyYzk.",
    "..JJjjjjyjRrrqjOjjJyoIk.",
    "..JJjjjjojjqqjjOjJJoOzk.",
    "..JJyjjjjojjjjOjJJJJIIk.",
    "..JJjjjjjjoOOOjJJJJJIzk.",
    "..JJjjjjjjjjjjJJJJJJIIk.",
    "..JJjjjjjjjjjJJJJJJJIzk.",
    "..JJyjjjjjjjJJJJJJJyIIk.",
    "..JJjjjjjjjJJJJJJJYyIzk.",
    "..JJjjjjjjJJJJJJJyyyIk..",
    "...kjJJJJJJJJJJJJJJJk...",
    "....kkkkkkkkkkkkkkkk....",
    "........................",
    "........................",
  ],
  orb: [ // 水晶球
    "........................",
    "..........uuuu..........",
    "........uubbbbku........",
    "......eubbbbbbbbku......",
    ".....exxbbbbbbbbbbk.....",
    "....ubxcbbbbbbbbuuuk....",
    "....ubcbbbbbbbbuuuuk....",
    "...ubbbbbbbbbbuuuuuuk...",
    "...ubbbbbbbbbxuuuuuuk...",
    "...ubbbbbbbbuucccccuk...",
    "...ubbbbbbbuuccccccuk...",
    "...ubbbbbbuucccccccuk...",
    "...ubbbbuucuucccccuuk...",
    "...ubuuuuuuuuccccuuuk...",
    "....kbuuuuuuuuuubuuk....",
    "....ubuuuuuuuuucuuuk....",
    "....OkuuuuuuuuuuuukO....",
    "...Oykkkuuuuuuuukkkok...",
    "....kok.kkuuyukk.OOk....",
    ".....k..OoyYYyok..k.....",
    ".......Ooyyyyyyok.......",
    "......OOoooooooOk.......",
    ".....OOOOOOOOOOOOk......",
    "......kkkkkkkkkkk.......",
  ],
  pouch: [ // 革袋
    "........................",
    "........DD..DD..........",
    ".......DllkDdlk.........",
    "........kllllk..........",
    ".........kyyk...........",
    "........DLLLlk..........",
    ".......Dlddddlk.........",
    "........kDDDDk..........",
    "......DDLLLLllkD........",
    ".....DLLLLLlLlldk.......",
    "....DLLlLLLLlllddk......",
    "...DLLLLLLLLlllddDk.....",
    "..DLLLLLlLlllldddDDk....",
    "..DLLLLDlldlldddDDDk....",
    "..DlllllDdllddddDDDk....",
    "..DllllDlldddddDDDDkOO..",
    "..DdddddddddddDDDDooYok.",
    "...kDdddddDDDDDDDoyYYyok",
    "....kDDDDDDDDDDoyyoyyook",
    ".....kkDDDDDDDDyYYyOook.",
    ".......kkkkkkkkoyyokkk..",
    "...............kkkk.....",
    "........................",
    "........................",
  ],
  herb: [ // 薬草 (束ねた葉)
    "........................",
    "..........tt............",
    ".........tGhk...........",
    "........tGGhtk..........",
    "........tGGhttk.........",
    ".......tGGGhtttk........",
    "..tt...tGGGhtttk..tttt..",
    ".thtkttkGGGhtttkttGGhhk.",
    ".tGttttkGGGttttkGGGGhhk.",
    ".tGhhtttGGGhtttGGGGhttk.",
    ".tGGhtttkGGtttkGGGhtttk.",
    ".tGGGhtttGGhtkkGGhhtttk.",
    ".tGGGhhttkGhk.tGGhtttk..",
    "..kGGGhttkkhGkkGhtttk...",
    "...khttttkktGkkhtttk....",
    "...thhttttktGkthGkk.....",
    "...tGGhhttktGk.kGk......",
    "....kGGGhhktGktGk.......",
    "....tGGGGGllllkGk.......",
    ".....kkkktdLldGk........",
    "........ttkdGdGk........",
    ".........kttGlk.........",
    ".........tttGGdk........",
    "..........kkkkk.........",
  ],
};

// id の安定ハッシュ (FNV-1a 32bit)。同じ id は常に同じ絵の型になる (セーブ/図鑑で見た目が変わらない)
function hashId(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193); }
  return h >>> 0;
}
// 形キー → 絵 (行配列)。ARTS[key] が「型の配列」なら id のハッシュで 1 つ選ぶ。単一形はそのまま返す
export function pickArt(artKey, id) {
  const a = ARTS[artKey];
  return Array.isArray(a[0]) ? a[hashId(String(id)) % a.length] : a;
}

// 秘宝の燐光: 輪郭に接する透明画素を半透明の光暈 "*" にする (絵ごとに一度だけ作る)
const GLOW_DEFAULT = "#a8c4ff";
const GLOW_ALPHA = 0.24;
const _glowArt = new WeakMap();
function withGlow(art) {
  let g = _glowArt.get(art);
  if (g) return g;
  const at = (x, y) => (art[y] && art[y][x]) || ".";
  g = art.map((row, y) => [...row].map((c, x) => (
    c === "." && (at(x + 1, y) !== "." || at(x - 1, y) !== "." || at(x, y + 1) !== "." || at(x, y - 1) !== ".") ? "*" : c
  )).join(""));
  _glowArt.set(art, g);
  return g;
}
function rgba(hex, a) {
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a})`;
}

// 武器サブカテゴリごとの威力倍率 (職業制限は souls.js の JOB_GEAR テーブルで一元管理)
const W_MUL = { ls: 1.0, dg: 0.78, kt: 1.06, ax: 1.16, mc: 1.1, sp: 1.04, bw: 0.92, st: 0.66 };

// 形状 → 装備重量 (canEquip の鎧重量チェックに使う)
const SHAPE_WEIGHT = {
  plate: "heavy", helm: "heavy", greaves: "heavy", gauntlet: "heavy", kite: "heavy",
  round: "light", boots: "light", gloves: "light", hat: "light",
  robe: "cloth", circlet: "cloth",
};

// 性能はすべてフラット値 (ATK+10 など)。自動算出値は lv の二次関数で単調増加し、
// opt.pow (自動主ステの倍率) と各種ボーナス/ペナルティで装備ごとの個性を出す。
const round = Math.round;
const priceOf = (lv) => round(10 + lv * lv * 0.30 + lv * 5);

function chk(cond, msg) { if (!cond) throw new Error("catalog: " + msg); }

// 共通フィールドを組み立てる
// 性能キーは六大ステ (atk/vit/agi/int/pie/luk) + hp/mp。ビルダーの opt は
// 直感的な別名 (def=VIT, spd=AGI, atkB=ATK) を受け、ここで変換する。
function base(id, name, slot, lv, artKey, opt) {
  chk(id && name, "id/name required");
  chk(lv >= 1 && lv <= 200, "lv out of range (1-200): " + id);
  chk(ARTS[artKey], "unknown art: " + artKey + " (" + id + ")");
  chk(typeof opt.desc === "string" && opt.desc.length >= 24, "desc too short: " + id);
  const it = {
    id, name, slot, lv,
    rank: lvToRank(lv),
    classes: opt.cls !== undefined ? opt.cls : null,
    desc: opt.desc,
  };
  if (opt.eAtk) { chk(ELEM_KEYS.includes(opt.eAtk[0]), "bad eAtk element: " + id); it.eAtk = { el: opt.eAtk[0], lv: opt.eAtk[1] || 1 }; }
  if (opt.eDef) { chk(ELEM_KEYS.includes(opt.eDef[0]), "bad eDef element: " + id); it.eDef = { el: opt.eDef[0], lv: opt.eDef[1] || 1 }; }
  if (opt.spd) it.agi = opt.spd;       // 旧称 spd → AGI
  if (opt.agi) it.agi = (it.agi || 0) + opt.agi;
  if (opt.hp) it.hp = opt.hp;
  if (opt.mp != null) it.mp = opt.mp;
  if (opt.int) it.int = opt.int;
  if (opt.pie) it.pie = opt.pie;
  if (opt.luk) it.luk = opt.luk;
  if (opt.crit) it.crit = opt.crit;
  if (opt.atkB) it.atk = opt.atkB;     // 防具などの攻撃ボーナス
  if (opt.vitB) it.vit = opt.vitB;     // 武器・装飾の VIT 補正 (負値=重武器のペナルティ等)
  if (opt.cursed) it.cursed = true;
  if (opt.align) it.align = opt.align;
  // %補正 (装飾品など): { atk:0.2, hp:0.2 } で +20%。recalc が乗算レイヤーで適用する
  if (opt.mult) it.mult = opt.mult;
  // 戦闘効果 (LR装飾品など): { actFirst, multistrike, lifesteal, autoRevive, guard, spellCostMul }。
  // recalc が member.eff へ集約し、combat.js が actor に展開して使う。
  if (opt.eff) it.eff = opt.eff;
  // LR (レジェンドレア・専用装備) のティア。lr が立つと専用ドロップ層・LR表示になる
  if (opt.lr) it.lr = opt.lr;
  if (opt.forJob) it.forJob = opt.forJob;
  if (opt.exclusive) it.exclusive = true;
  // 絵: 原型 × 染め色 (属性があれば属性色が既定)
  const el = (opt.eAtk && opt.eAtk[0]) || (opt.eDef && opt.eDef[0]) || null;
  const tc = opt.tint || (el ? ELEM_TINT[el] : null);
  // 秘宝 (LR・職業専用・神話級 lv165+) は輪郭の外に淡い燐光をまとう。色は属性色、無属性は青白い燐光
  const relic = !!(opt.lr || opt.exclusive || lv >= 165);
  it.art = relic ? withGlow(pickArt(artKey, id)) : pickArt(artKey, id);
  it.palette = tc ? tint(P, tc, opt.tintAmt != null ? opt.tintAmt : (el ? 0.3 : 0.22)) : P;
  if (relic) it.palette = { ...it.palette, "*": rgba(el ? ELEM_TINT[el] : GLOW_DEFAULT, GLOW_ALPHA) };
  it.price = opt.price != null ? opt.price : priceOf(lv);
  return it;
}

// 武器: W(id, 名, サブカテゴリ, lv, opt)
// opt: { desc(必須), eAtk, two, cls, pow(自動ATKの倍率), vitB, spd, mp, hp, atk(絶対値上書き), tint, tintAmt, cursed, align, price }
export function W(id, name, cat, lv, opt = {}) {
  chk(W_MUL[cat], "unknown weapon cat: " + cat + " (" + id + ")");
  const it = base(id, name, "weapon", lv, cat, { cls: opt.cls !== undefined ? opt.cls : null, ...opt });
  it.cat = cat;
  const two = !!opt.two || cat === "bw"; // 弓は常に両手
  if (two) it.twoHanded = true;
  it.atk = opt.atk != null ? opt.atk : Math.max(1, round((2 + lv * 0.82 + lv * lv * 0.0026) * W_MUL[cat] * (two && cat !== "bw" ? 1.25 : 1) * (opt.pow || 1)));
  it.hit = opt.hit != null ? opt.hit : 1 + Math.floor(lv / 25);
  it.dice = opt.dice || ("1d" + (4 + Math.min(20, Math.floor(lv / 9))) + (lv >= 30 ? "+" + Math.min(15, Math.floor(lv / 13)) : ""));
  it.swings = opt.swings || 1;
  if (cat === "st") {                                                // 杖は魔力の触媒
    // INT は呪文威力に ×0.5 で直結する術者の「攻撃力」— 武器ATKと同格のカーブにする
    if (it.mp == null) it.mp = round(3 + lv * 0.3 + lv * lv * 0.0008);
    if (it.int == null) it.int = Math.max(1, round(2 + lv * 0.5 + lv * lv * 0.0015));
  }
  if (cat === "dg" && it.agi == null) it.agi = Math.max(1, round(1 + lv * 0.06)); // 短剣は取り回しが軽い (lvに比例)
  return it;
}

// 盾: S(id, 名, lv, opt) — opt.shape: "kite"(既定) | "round" | "orb" | "book"。opt.def は VIT の上書き
export function S(id, name, lv, opt = {}) {
  const shape = opt.shape || "kite";
  const it = base(id, name, "shield", lv, shape, { cls: null, ...opt });
  it.vit = opt.def != null ? opt.def : Math.max(1, round((2 + lv * 0.16 + lv * lv * 0.0014) * (opt.pow || 1)));
  it.weight = SHAPE_WEIGHT[shape] || "cloth";  // orb/book 等は cloth 扱い
  return it;
}

// 鎧: A(id, 名, lv, opt) — opt.shape: "plate"(既定) | "robe"。opt.def は VIT の上書き
// opt.weight: "heavy"(既定) | "light" | "cloth" — 省略時は shape から自動決定
export function A(id, name, lv, opt = {}) {
  const robe = opt.shape === "robe";
  const it = base(id, name, "body", lv, robe ? "robe" : "plate", opt);
  const autoWeight = robe ? "cloth" : "heavy";
  const weight = opt.weight || autoWeight;
  const lightMul = weight === "cloth" ? 0.5 : weight === "light" ? 0.75 : 1;
  it.vit = opt.def != null ? opt.def : Math.max(1, round((3 + lv * 0.22 + lv * lv * 0.0014) * lightMul * (opt.pow || 1)));
  if (robe || weight === "cloth") {
    // PIE は回復量に ×0.5 で直結する — 法衣は癒し手の主装備としてしっかり伸ばす
    if (it.mp == null) it.mp = round(2 + lv * 0.25 + lv * lv * 0.0007);
    if (it.pie == null) it.pie = Math.max(1, round(1 + lv * 0.28 + lv * lv * 0.0008));
  }
  it.weight = weight;
  return it;
}

// 段階装備の役割ステ量 (lv に応じて単調増加)。頭/小手の主ステ算出に使う。
const roleStatAmt = (lv) => Math.max(1, round(0.8 + lv * 0.16 + lv * lv * 0.0006));
const tokenVit = (lv) => Math.max(1, round(lv * 0.05));

// 頭: H(id, 名, lv, opt) — opt.shape: "helm"(既定) | "hat" | "circlet"。opt.def は VIT の上書き
// opt.weight: shape から自動決定 (helm=heavy, hat=light, circlet=cloth)。上書き可
// 段階装備の方針: 物理職向け(軽/重)は VIT 主体、術者向け(布)は opt.magStat ("int"|"pie") 主体。
// magStat 指定時のみ VIT をトークンに落として INT/PIE を主ステにする (既存の一点物には無影響)。
export function H(id, name, lv, opt = {}) {
  const shape = opt.shape || "helm";
  const it = base(id, name, "head", lv, shape, opt);
  it.vit = opt.def != null ? opt.def : Math.max(1, round((1 + lv * 0.10 + lv * lv * 0.0012) * (opt.pow || 1)));
  it.weight = opt.weight || SHAPE_WEIGHT[shape];
  if (opt.magStat === "int" || opt.magStat === "pie") {
    it[opt.magStat] = (it[opt.magStat] || 0) + roleStatAmt(lv);
    if (opt.def == null) it.vit = tokenVit(lv);
  }
  return it;
}

// 足: F(id, 名, lv, opt) — opt.shape: "boots"(既定) | "greaves"。opt.def は VIT の上書き
// opt.weight: shape から自動決定 (boots=light, greaves=heavy)。上書き可 (例: weight:"cloth" で布靴)
// 足は「AGI(すばやさ)の部位」: 重量に応じて AGI を自動付与する (布>軽>重)。
// opt.agi/opt.spd を渡すと、その分が自動AGIに上乗せされる (韋駄天の靴など俊足の品)。
const FEET_AGI_COEF = { cloth: 0.11, light: 0.085, heavy: 0.04 };
export function F(id, name, lv, opt = {}) {
  const shape = opt.shape || "boots";
  const it = base(id, name, "feet", lv, shape, opt);
  it.vit = opt.def != null ? opt.def : Math.max(1, round((1 + lv * 0.09 + lv * lv * 0.0010) * (opt.pow || 1)));
  it.weight = opt.weight || SHAPE_WEIGHT[shape];
  // AGI 自動付与 (base() が opt.agi/spd で設定済みの分には上乗せ)
  const coef = FEET_AGI_COEF[it.weight] != null ? FEET_AGI_COEF[it.weight] : 0.085;
  it.agi = (it.agi || 0) + Math.max(1, round(0.6 + lv * coef));
  return it;
}

// 小手: G(id, 名, lv, opt) — opt.shape: "gloves"(既定) | "gauntlet"。opt.def は VIT の上書き
// opt.weight: shape から自動決定 (gloves=light, gauntlet=heavy)。上書き可 (例: weight:"cloth" で布手袋)
// 段階装備の方針: 小手は「攻めの部位」。物理職向け(軽/重)は opt.role:"atk" で ATK 主体、
// 術者向け(布)は opt.magStat ("int"|"pie") 主体。指定時は VIT をトークンに落とす (既存品は無影響)。
export function G(id, name, lv, opt = {}) {
  const shape = opt.shape || "gloves";
  const it = base(id, name, "hands", lv, shape, opt);
  it.vit = opt.def != null ? opt.def : Math.max(1, round((1 + lv * 0.09 + lv * lv * 0.0010) * (opt.pow || 1)));
  it.weight = opt.weight || SHAPE_WEIGHT[shape];
  if (opt.role === "atk") {
    it.atk = (it.atk || 0) + roleStatAmt(lv);
    if (opt.def == null) it.vit = tokenVit(lv);
  } else if (opt.magStat === "int" || opt.magStat === "pie") {
    it[opt.magStat] = (it[opt.magStat] || 0) + roleStatAmt(lv);
    if (opt.def == null) it.vit = tokenVit(lv);
  }
  return it;
}

// 装飾品: R(id, 名, 形, lv, opt) — 防御の自動値は持たず、性能 (hp/mp/luk/crit/eAtk/eDef…) は opt で明示する
export function R(id, name, shape, lv, opt = {}) {
  const it = base(id, name, "acc", lv, shape, opt);
  if (opt.def != null) it.vit = opt.def;
  return it;
}

// 収集品 (戦利品): M(id, 名, 形, lv, opt) — 装備も使用もできず、商店で売るか宝物庫に奉納する
export function M(id, name, shape, lv, opt = {}) {
  const it = base(id, name, "misc", lv, shape, opt);
  it.price = opt.price != null ? opt.price : round(8 + lv * lv * 0.25 + lv * 4);
  return it;
}

// 道具 (消耗品): U(id, 名, lv, use, opt) — use: { heal?, mp?, cure? }
export function U(id, name, lv, use, opt = {}) {
  const it = base(id, name, "use", lv, opt.shape || "vial", opt);
  it.use = use;
  if (opt.price == null) it.price = round(14 + lv * lv * 0.30 + lv * 6);
  return it;
}
