// 頭・足・小手・装飾品カタログ (頭50種 + 足50種 + 小手18種 + 装飾品8種)。id は append-only (改名・削除禁止)。
// lv は隠しレベル (1-200)。lv帯ごとに満遍なく配置し、防御・価格・ランクは自動算出に任せる。
// eDef は六属性をほぼ均等に散らし、◎(Lv2) は深層帯のみ。
import { H, F, G, R } from "./defs.js";

export const HEADS = [
  // ---- lv1-5 ----
  H("h_gravedigger_hood", "墓掘りの頭巾", 1, { shape: "hat",
    desc: "夜露と墓土に湿った仕事着の頭巾。かぶると土の匂いが鼻をつくが、不思議と死者への恐れが薄らぐと墓掘り人たちは言う。" }),
  H("h_ratfang_cap", "鼠牙の革帽", 5, { shape: "hat", tint: "#8a6438", tintAmt: 0.25,
    desc: "下水に巣食う大鼠どもの革を張り合わせた帽子。縁に縫い止めた牙は仕留めた獲物の証で、鼠捕りたちのささやかな誇りだ。" }),
  H("h_watch_kettle_helm", "夜番の鉄笠", 9, { cls: ["fighter", "knight", "priest"], tint: "#8a92a2", tintAmt: 0.2,
    desc: "城壁の夜番が雨と流れ矢をしのいだつば広の鉄笠。叩けば鈍い鐘の音がして、居眠りの番兵を幾度も死の淵から呼び戻したという。" }),
  H("h_confessor_hood", "懺悔聴きの頭巾", 13, { shape: "hat", mp: 2, cls: ["priest", "bishop"],
    desc: "罪人の最期の告白を聴く僧が顔を隠した深い頭巾。降り積もった懺悔を吸った布は重く、かぶる者の心をほのかな魔力で満たす。" }),
  H("h_boartusk_helm", "猪頭の骨兜", 13, { eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "大猪の頭骨をくり抜いた蛮族の兜。眼窩越しの視界は狭いが、土を駆ける獣の加護が宿り、押し寄せる大水すらせくという。" }),
  H("h_martyr_thorn_crown", "殉教者の茨冠", 17, { shape: "circlet", eDef: ["light", 1], mp: 2, cls: ["priest", "bishop"],
    desc: "火刑に処された聖者へ嘲りとしてかぶせられた茨の冠。とげはいつしか金色に乾き、闇の爪をやわらかく払う加護に変わった。" }),
  H("h_mourner_veil", "会葬者の面紗", 17, { shape: "hat", eDef: ["dark", 1], mp: 2,
    desc: "喪に服す貴婦人が顔を覆った黒の面紗。葬列を幾度も見送った布は宵闇に溶けて、まばゆい光の矢からそっと目を守る。" }),

  // ---- lv6-10 ----
  H("h_gaoler_visor", "牢番の面頬", 21, { cls: ["fighter", "knight"],
    desc: "地下牢の看守が囚人の爪から顔を守った鉄の面頬。覗き窓の奥の目が情を映さぬよう、内側には目隠しの布まで当ててある。" }),
  H("h_bog_leech_helm", "沼ヒルの革兜", 24, { eDef: ["water", 1], cls: ["fighter", "knight", "thief"],
    desc: "底なし沼の主と呼ばれた大ヒルの革を縫い合わせた兜。常にじっとりと湿り、燃え盛る炎の息すら触れる端から鎮めてしまう。" }),
  H("h_falconer_hood", "鷹匠の目隠し帽", 28, { shape: "hat", tint: "#8a6438", tintAmt: 0.22,
    desc: "猟鷹を鎮める目隠しを模した革の帽子。深くかぶれば雑念がそぎ落とされ、獲物の立てる微かな羽音だけが妙に近く聞こえる。" }),
  H("h_cantor_circlet", "詠唱者の銀環", 32, { shape: "circlet", mp: 3, cls: ["mage", "priest", "bishop"], tint: "#e8e8f4", tintAmt: 0.3,
    desc: "聖歌隊の先導者が額にはめた銀の輪。詠唱の波長に共鳴して細かく震え、声に乗せる魔力をわずかに研ぎ澄ましてくれる。" }),
  H("h_ossuary_sallet", "納骨堂のサレット", 32, { cls: ["fighter", "knight"], tint: "#d9d4bf", tintAmt: 0.3,
    desc: "納骨堂の番人が骨片を漆で固めて作った兜。死者の欠片に守られていると思えば迷宮の闇も存外に心強い、と番人は笑った。" }),
  H("h_stormcrier_hat", "嵐呼びのつば広帽", 36, { shape: "hat", eDef: ["wind", 1], mp: 2, cls: ["mage", "bishop"],
    desc: "雨乞いならぬ嵐乞いを生業とした呪い師の帽子。つばがひとりでに風をはらんで揺れ、飛来する土塊や石礫を逸らしてくれる。" }),
  H("h_ember_guard_helm", "おき火の戦兜", 36, { eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "火竜の巣を暴いて全滅した傭兵団の形見。鉄の奥でおき火が今も眠り、斬りつける風の刃を熱で焼き鈍らせる。冬でも妙に温かい。" }),

  // ---- lv11-15 ----
  H("h_tollgate_helm", "関守の半兜", 40, { cls: ["fighter", "knight", "priest"],
    desc: "国境の関で旅人を検め続けた老兵の半兜。嘘を見抜く力が宿るというのは噂だが、額に走る傷はどれも本物の矢を受けた痕だ。" }),
  H("h_plague_beak_mask", "検疫医のくちばし面", 44, { shape: "hat", tint: "#3a3a46", tintAmt: 0.25,
    desc: "疫病に呑まれた街を巡り歩いた医師のくちばし形の面。詰められた香草はとうに朽ちたが、死の瘴気を潜り抜けた験は布に残っている。" }),
  H("h_sunken_river_crown", "沈み川の宝冠", 48, { shape: "circlet", eDef: ["water", 1], mp: 3, cls: ["mage", "priest", "bishop"],
    desc: "氾濫に沈んだ王都から、漁師の網にかかって還ってきた宝冠。藻に覆われた宝石は水底の冷たさを保ち、額に迫る炎の熱を奪う。" }),
  H("h_headsman_cowl", "斬首吏の黒覆面", 52, { shape: "hat", tint: "#3a3a46", tintAmt: 0.3,
    desc: "首打ち役人が素顔を隠した黒覆面。恨まれる顔を持たない者は呪いも受けない——その理屈を信じ、迷宮へ潜る者にも重宝される。" }),
  H("h_crag_sentry_helm", "岩番の重兜", 52, { eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "山岳砦の見張りが落石から頭を守った無骨な兜。岩肌と同じ冷たさと頑なさを宿し、叩きつける鉄砲水さえ岩のように受け流す。" }),
  H("h_crematory_grate_helm", "火葬炉の面格子", 56, { eDef: ["fire", 1], cls: ["fighter", "knight", "priest"],
    desc: "火葬炉の焚き口から外した鉄格子を打ち直した面頬。あまたの亡骸を見送った鉄は熱に疲れ、風の刃程度ではもう火照りもしない。" }),

  // ---- lv16-20 ----
  H("h_wolfwind_helm", "狼おろしの羽兜", 60, { eDef: ["wind", 1], cls: ["fighter", "knight", "thief"],
    desc: "冬山から吹き下ろす「狼おろし」を独りで渡り切った狩人の兜。両脇の羽根飾りが風向きを読み、礫混じりの突風から目を守ってくれる。" }),
  H("h_forbidden_archive_cap", "禁書庫司書の角帽", 63, { shape: "hat", mp: 4, cls: ["mage", "bishop"], tint: "#6b3fa0", tintAmt: 0.25,
    desc: "読む者を狂わせる書物を管理し続けた司書の角帽。ページをめくる音が今も縫い目から漏れ、かぶる者へ禁じられた知識の欠片を囁く。" }),
  H("h_saltgrave_helm", "塩墓の潜兜", 67, { cls: ["fighter", "knight"], tint: "#e8e8f4", tintAmt: 0.25,
    desc: "崩落した岩塩坑、坑夫たちが塩漬けのまま眠る「白い墓」から掘り出された兜。塩の殻は今も清らかに輝き、穢れを寄せ付けない。" }),
  H("h_blackpike_burgonet", "黒槍隊のひさし兜", 71, { cls: ["fighter", "knight"],
    desc: "敗北を知らぬまま全滅した傭兵隊「黒槍」のひさし付き兜。生き残りがいない以上、彼らの強さを語れるのはもはやこの兜だけだ。" }),
  H("h_blind_seer_band", "千里眼の盲布", 71, { shape: "hat", mp: 4, cls: ["mage", "priest", "bishop"],
    desc: "自ら両の目を潰した予言者が巻いていた布。視界を閉ざしたその瞬間から、見えるはずのないものの輪郭がまぶたの裏に滲みはじめる。" }),
  H("h_fallen_king_circlet", "廃王の額環", 75, { shape: "circlet", eDef: ["dark", 1], mp: 3,
    desc: "玉座を追われ、廃坑の闇で果てた王の額環。宝石は疾うに抜き取られたが、空の台座が玉座の間の暗がりを覚えており、強い光を嫌って呑む。" }),

  // ---- lv21-25 ----
  H("h_ash_knight_armet", "灰の騎士の兜", 79, { eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "居城もろとも焼け落ちた騎士の鎧から、唯一原形を留めて拾われた兜。内に残る焔の熱が、斬りかかる風の刃をあぶって鈍らせる。" }),
  H("h_dusk_hunter_tricorn", "宵闇狩りの三角帽", 83, { shape: "hat", tint: "#6b3fa0", tintAmt: 0.2,
    desc: "夜にしか現れぬ獣だけを狙う狩人たちの三角帽。つばを深く傾ければ顔は闇に沈み、こちらの殺気だけが綺麗に消え失せるという。" }),
  H("h_stone_warden_greathelm", "石衛士の大兜", 87, { eDef: ["earth", 1], hp: 5, cls: ["fighter", "knight"],
    desc: "石像の衛兵を模し、のみで彫り出したように仕上げられた兜。かぶれば体が大地に根を張った心地がして、濁流のただ中でも揺らがない。" }),
  H("h_holy_candle_diadem", "聖蝋の宝冠", 91, { shape: "circlet", eDef: ["light", 1], mp: 4, cls: ["priest", "bishop"],
    desc: "絶えず灯り続けてきた大聖堂の蝋燭、その滴りを集めて固めた冠。ほのかな灯が常に額に在り、忍び寄る闇の手を焼いて退ける。" }),
  H("h_gale_runner_helm", "風走りの軽兜", 95, { eDef: ["wind", 1], cls: ["fighter", "knight", "thief"],
    desc: "矢の雨を駆け抜ける伝令兵のため、限界まで削ぎ落とされた軽兜。風がそのまま兜になったと評され、礫の豪雨さえ滑らせて逸らす。" }),

  // ---- lv26-30 ----
  H("h_carrion_feast_helm", "屍宴の角兜", 98, { hp: 6, cls: ["fighter", "knight"], tint: "#d9d4bf", tintAmt: 0.28,
    desc: "戦場の骸を漁る食屍鬼の王、その角を戴いた兜。死肉の宴を統べた角には生への妄執が滲み、かぶる者の命を粘り強くする。" }),
  H("h_silent_vow_cowl", "黙誓僧の深頭巾", 102, { shape: "hat", mp: 5, cls: ["mage", "priest", "bishop"],
    desc: "生涯の沈黙を誓った修道僧の頭巾。声にされなかった祈りが布の奥に積もり続け、かぶる者の内側で静かな魔力として満ちていく。" }),
  H("h_iron_queen_crown", "鉄妃の宝冠", 106, { shape: "circlet", mp: 4, tint: "#8a92a2", tintAmt: 0.3,
    desc: "黄金を嫌い、鉄の冠を望んだ女王の遺品。飾り気のない輪は今も冷たく額を締めつけ、挫けかけた心をまっすぐに立たせてくれる。" }),
  H("h_inquisitor_peak", "異端審問官の尖帽", 110, { shape: "hat", mp: 5, cls: ["priest", "bishop"],
    desc: "魔女裁判を取り仕切った審問官の尖り帽。火刑の煙を吸い続けた布は信仰とも狂気ともつかぬ熱を帯び、祈りを過剰なまでに研ぐ。" }),
  H("h_lion_maw_helm", "獅噛の面兜", 114, { hp: 8, cls: ["fighter", "knight"], tint: "#c9a227", tintAmt: 0.25,
    desc: "獅子の顎が頭ごと喰らいつく意匠の面兜。戦場でこれと相対した敵は、中の人間ではなく獅子と戦っている錯覚に呑まれたという。" }),

  // ---- lv31-35 ----
  H("h_gallows_hood", "縛り首の覆面", 118, { shape: "hat", cursed: true, align: "悪", def: 16, hp: -12, tint: "#6b3fa0", tintAmt: 0.3,
    desc: "絞首台で死刑囚にかぶせられる目隠しの袋。死の間際の奇妙な安らぎが染みつき、あらゆる刃から頭を守る——だが見えない縄が首を絞め続け、ひとたびかぶれば外せない。" }),
  H("h_abyss_bishop_crown", "深淵司教の宝冠", 126, { shape: "circlet", eDef: ["water", 2], mp: 6, cls: ["mage", "priest", "bishop"],
    desc: "光の届かぬ海淵で異形の神を奉じた司教の冠。深海の冷たさと重さを宿し、どれほど猛る劫火も額の前で泡となって掻き消える。" }),
  H("h_dragon_jaw_sallet", "竜顎の兜", 130, { hp: 8, cls: ["fighter", "knight"], tint: "#d9d4bf", tintAmt: 0.3,
    desc: "朽ちた竜の顎骨をそのまま兜に仕立てた蛮王の戦利品。牙の隙間から戦場をにらめば、竜ににらまれる側の恐怖が敵の足を縛りつける。" }),
  H("h_asura_visor", "修羅の面頬", 134, { hp: 10, cls: ["fighter", "knight"],
    desc: "幾多の戦場を生き抜いた剣鬼が、最期まで外さなかった面頬。鉄越しにも伝わる闘気が染みつき、かぶる者の血を内側からたぎらせる。" }),

  // ---- lv36-40 ----
  H("h_throne_guard_helm", "玉座番の黄金兜", 138, { hp: 10, cls: ["fighter", "knight"], tint: "#c9a227", tintAmt: 0.3,
    desc: "主が空けたままの玉座を守り続けた近衛の黄金兜。主なき忠義は重いが、その重さがかぶる者の腹を据えさせる。めっきの下は質実な鋼だ。" }),
  H("h_stargazer_nightcap", "星読みの夜帽", 141, { shape: "hat", mp: 6, cls: ["mage", "bishop"], tint: "#6b3fa0", tintAmt: 0.3,
    desc: "凶星の巡りを言い当てすぎて処刑された占星術師の帽子。裏地に刺繍された星図は夜ごと配置を変え、明日の凶兆を耳元に囁いてくる。" }),
  H("h_ogre_eater_helm", "鬼喰いの兜", 145, { hp: 12, cls: ["fighter", "knight"], tint: "#3a3a46", tintAmt: 0.3,
    desc: "鬼を喰らいその力を得るという山の民に伝わる黒鉄の兜。まびさしの裏には鬼の臼歯がはめ込まれ、かぶる者へ荒々しい生気を分け与える。" }),
  H("h_serpent_empress_circlet", "蛇女帝の額環", 153, { shape: "circlet", mp: 6, cls: ["mage", "priest", "bishop"],
    desc: "蛇の化身と恐れられた女帝の額環。絡み合う双つの蛇の意匠は見つめた者の思考をからめ捕り、額にはいつまでも冷たい鱗の感触が残る。" }),

  // ---- lv41-45 ----
  H("h_headless_duke_helm", "首無し公の白兜", 161, { hp: 12, cls: ["fighter", "knight"], tint: "#e8e8f4", tintAmt: 0.25,
    desc: "首をはねられてなお馬を駆り続けたと伝わる公爵の白兜。失われた首の代わりに兜が主の意地を覚えていて、かぶる者の急所を頑なに守る。" }),
  H("h_dawn_herald_diadem", "暁告げの宝冠", 165, { shape: "circlet", eDef: ["light", 2], mp: 6, cls: ["mage", "priest", "bishop"],
    desc: "夜明けを告げる役目の大司祭だけが戴いた宝冠。常に東雲の色へ淡く輝き、夜を統べる者の呪詛も闇の爪も、光輪の前で薄れて消える。" }),
  H("h_lost_capital_warcrown", "亡都の戦王兜", 173, { hp: 15, cls: ["fighter", "knight"],
    desc: "滅びの晩、都もろとも炎に呑まれた王の戦兜。王冠を兼ねた鉢金には民の名がびっしりと刻まれ、その重みが背骨を支える芯になる。" }),

  // ---- lv46-50 ----
  H("h_total_eclipse_cowl", "皆既蝕の頭巾", 180, { shape: "hat", eDef: ["dark", 2], mp: 7, cls: ["mage", "bishop"],
    desc: "太陽が喰われた日に織り上げられたという頭巾。布の内側はいかなる正午であろうと完全な夜で、目を灼く聖光さえ蝕の闇が呑み干す。" }),
  H("h_dragonfall_armet", "竜ほふりの大兜", 184, { hp: 16, cls: ["fighter", "knight"],
    desc: "単身で古竜の顎へ潜り込み、内から喉を裂いた英雄の兜。浴びた竜血で鋼は半ば竜鱗と化し、生半可な牙にも爪にももう貫けない。" }),
  H("h_star_sovereign_crown", "星々の王の宝冠", 192, { shape: "circlet", mp: 8, hp: 10,
    desc: "天の星々を臣下に数えたという伝説の王の宝冠。夜空を縮めて鋳たとされる輪の内では今も小さな星が生まれては流れ、祈りを集める。" }),

  // ===== 魔法系・低ランク補完 (circlet=cloth重量。序盤から魔法職が頭を守れるように) =====
  H("h_scholar_band", "学徒の知恵帯", 4, { shape: "circlet", mp: 1,
    desc: "迷宮学院の入学と同時に配られる布製の額帯。地味だが呪文の暗記を助けると先輩たちは言い、殆どの卒業生が迷宮へも持ち込んでいる。" }),
  H("h_apprentice_arcana_circlet", "魔法習得の額輪", 18, { shape: "circlet", mp: 2, int: 1,
    desc: "呪文の型を覚えた者に授けられる銀環。新しい術式が額から流れ込むような感覚があり、詠唱を繰り返すたびに輪の光が僅かに深まる。" }),
  H("h_mage_apprentice_hat", "術師見習いの帽子", 8, { shape: "hat", mp: 1, cls: ["mage", "bishop", "hexer", "hermit", "arcthief", "warden", "arcanist", "necromancer", "sage", "cardinal", "archmage"],
    desc: "大きすぎて目が隠れる、術師見習いの支給品の帽子。先輩たちが呪文の公式を書き込み続けた裏地には、今も微かな魔力が滲んでいる。" }),

  // ===== 侍・魔剣士系専用頭装備 (cls:samurai系。hat=light重量なので侍が装備可) =====
  H("h_jingasa", "陣笠", 15, { shape: "hat", luk: 1, cls: ["samurai", "spellblade", "brigand", "shadow"],
    desc: "戦陣で風雨と矢を防いだ竹張りの笠。野戦の侍には鎧より先に手に入る馴染みの形で、笠の傾け方で流派が分かるという。" }),
  H("h_tatami_kabuto", "畳み兜", 45, { shape: "hat", agi: 2, cls: ["samurai", "spellblade", "shadow", "brigand"],
    desc: "折り畳んで腰に差して運べる軽量の兜。兜の折り目は剣の引き方に沿って計算されており、被った瞬間に抜刀の速度が上がる気がする。" }),
  H("h_war_blade_mempo", "戦刃の面頬", 88, { shape: "hat", agi: 3, crit: 0.02, cls: ["samurai", "spellblade"],
    desc: "鬼の表情を刻んだ面頬。覗き穴の角度は急所を自然に狙うよう調整されており、百戦を経た目が面の奥で煌く。侍と魔剣士の証。" }),
  H("h_demon_blade_visor", "魔剣士の鬼面", 138, { shape: "hat", agi: 4, crit: 0.03, cls: ["samurai", "spellblade"],
    desc: "魔力を鬼の面に封じた半面。被れば身の丈が一段大きく見え、周囲の魔が一瞬だけ怯む。その一瞬に全てを賭けるのが魔剣士の道だ。" }),
];

export const FEET = [
  // ---- lv1-5 ----
  F("f_corpse_bearer_sandals", "屍運びのわらじ", 1, { spd: 1,
    desc: "死者を墓地へ運ぶ人夫が履き潰したわらじ。軽さだけが取り柄だが、死出の道を往復し続けた足は迷宮でも不思議と疲れを知らない。" }),
  F("f_sewer_waders", "下水番の胴長靴", 5, {
    desc: "都の下水路を見回る番人の胴長靴。汚水もヒルも通さない厚革は、迷宮の床にわだかまる得体の知れない水溜りから足を守ってくれる。" }),
  F("f_rampart_gaiters", "土塁兵の脚絆", 9, { eDef: ["earth", 1],
    desc: "土塁を築いては崩される工兵たちの脚絆。踏み固めた大地の頑なさが革に宿り、足元をすくおうとする奔流をせき止めてくれる。" }),
  F("f_deserter_boots", "敗走兵の泥靴", 13, { spd: 1,
    desc: "戦場から逃げ延びた兵の泥まみれの靴。恥も外聞も捨てて駆けたからこそ持ち主は生き残った。逃げ足の速さも立派な才覚である。" }),
  F("f_palisade_greaves", "柵門兵の脚甲", 13, { shape: "greaves", cls: ["fighter", "knight"], tint: "#8a92a2", tintAmt: 0.2,
    desc: "砦の柵門を死守する兵へ支給された脚甲。敵の槍は何よりもまずすねを狙ってくる——それを骨身で知った古参隊長の発案だという。" }),
  F("f_drowned_fisher_boots", "水死人の漁長靴", 17, { eDef: ["water", 1],
    desc: "嵐の夜に海へ消えた漁師の、長靴だけが浜に流れ着いた。革に染みた海水は決して乾かず、足元をなめる炎を冷たく鎮めてしまう。" }),
  F("f_rustbite_greaves", "錆噛みの脚甲", 17, { shape: "greaves", cls: ["fighter", "knight", "priest"], tint: "#8a5a2a", tintAmt: 0.3,
    desc: "赤錆に深く噛まれながら、芯の鋼だけは頑なに残った脚甲。錆を落とせば往時の輝きが覗き、鍛えた職人の意地をまだ覚えている。" }),

  // ---- lv6-10 ----
  F("f_night_thief_shoes", "夜盗の忍びぐつ", 21, { eDef: ["dark", 1], spd: 2,
    desc: "名の知れた夜盗が処刑の朝まで隠し通した柔らかなくつ。足音を闇に溶かし、月明かりからも松明の光からも主の足元を覆い隠す。" }),
  F("f_post_rider_boots", "早馬役のあぶみ靴", 24, { spd: 2,
    desc: "凶報ばかり運ばされた早馬乗りのあぶみ靴。かかとが擦り減るほど駆けた革は履く者の足を急かすように軽い。次こそ良い報せを運んでやれ。" }),
  F("f_windkick_boots", "風蹴りの軽靴", 28, { eDef: ["wind", 1], spd: 2,
    desc: "峠越えの飛脚たちが愛用した革の軽靴。爪先が風をはらむたびに体がふわりと浮き、飛んでくる石礫さえ追い風に乗って逸れていく。" }),
  F("f_firewalk_sabatons", "火渡りの鉄ぐつ", 32, { shape: "greaves", eDef: ["fire", 1], cls: ["fighter", "knight", "priest"],
    desc: "おき火の上を素足同然で渡る苦行のために鍛えられた鉄ぐつ。底に溜まった熱は今も冷めることなく、斬りつける風の刃をあぶって鈍らせる。" }),
  F("f_pit_slave_greaves", "闘奴の脚甲", 32, { shape: "greaves", cls: ["fighter", "knight"], tint: "#3a3a46", tintAmt: 0.25,
    desc: "闘技場の奴隷剣士に投げ与えられた粗末な脚甲。砂と血を吸った鉄には歓声の記憶がこびりつき、履く者の覚悟を試すように冷たい。" }),
  F("f_forester_deerhide_boots", "森番の鹿革靴", 36, { spd: 2, tint: "#8a6438", tintAmt: 0.25,
    desc: "密猟者を追い立てる側だった森番の鹿革靴。柔らかな底は枯枝の上でも音を立てず、追われる身となった今も足取りを軽くしている。" }),
  F("f_prisoner_chain_greaves", "囚人鎖の脚甲", 36, { shape: "greaves", spd: -2, cls: ["fighter", "knight"],
    desc: "足枷ごと鎧へ打ち直された囚人の鎖。歩くたびに重く鳴るが、絡んだ鉄輪は刃をよく弾く。自由の代わりに守りを得たとは皮肉な話だ。" }),

  // ---- lv11-15 ----
  F("f_idaten_tabi", "韋駄天の足袋", 40, { spd: 2,
    desc: "東方の俊足の神の名を冠した足袋。届かぬはずの間合いが届き、かわせぬはずの刃がかわせる——脱いだ後も、足の裏はまだ走りたがる。" }),
  F("f_lantern_pilgrim_boots", "灯持ちの巡礼靴", 44, { eDef: ["light", 1], mp: 2,
    desc: "聖地への夜道を灯火で先導する巡礼の靴。革に染み込んだ灯の温もりは消えることがなく、足元へ忍び寄る闇の手をやんわりと退ける。" }),
  F("f_bog_strider_boots", "沼渡りの高靴", 48, {
    desc: "泥に呑まれた者は還らないと言われる湿原の民の、膝まで覆う高靴。沈んだ仲間を引き上げるかぎまで備えた造りが、かえって頼もしい。" }),
  F("f_quarry_slave_greaves", "採石奴の重脚甲", 52, { shape: "greaves", eDef: ["earth", 1], spd: -4, cls: ["fighter", "knight"],
    desc: "石切場の奴隷が落石からすねを守った脚甲。岩盤の冷たさと重さをそのまま宿し、押し流そうとする洪水にもびくともしない。" }),
  F("f_duelist_heel", "果し合いのかかと鉄", 56, { spd: 4, cls: ["fighter", "knight", "thief"], tint: "#8a92a2", tintAmt: 0.2,
    desc: "決闘者が踏み込みのひと足に懸けてあつらえたかかと鉄付きの靴。石畳を噛むかかとが火花を散らすたび、間合いはこちらのものになるという。" }),
  F("f_mausoleum_greaves", "霊廟番の銀脚甲", 56, { shape: "greaves", mp: 2, cls: ["fighter", "knight", "priest"], tint: "#e8e8f4", tintAmt: 0.3,
    desc: "王家の霊廟を守る衛士の銀の脚甲。死者の眠りを乱す者を蹴り出すための銀は、穢れたものに触れると鈍く曇って主へ報せる。" }),

  // ---- lv16-20 ----
  F("f_breaker_greaves", "破城兵の重脚甲", 60, { shape: "greaves", spd: -4, hp: 5, cls: ["fighter", "knight"],
    desc: "城門へ破城槌を運ぶ決死隊の脚甲。矢の雨の下を歩み続けるために鉄板を幾重にも張り、軽さという美徳を端から捨て去っている。" }),
  F("f_drownvale_webbed_boots", "溺れ谷の水掻靴", 63, { eDef: ["water", 1], spd: 4,
    desc: "鉄砲水に沈んだ谷の漁民が、水中を駆けるために編んだ水掻き付きの靴。濡れるほどに足は軽く、燃え盛る火の海さえ鎮めて渡る。" }),
  F("f_spurred_hunt_greaves", "狩猟頭の拍車脚甲", 67, { shape: "greaves", cls: ["fighter", "knight"],
    desc: "王の猟犬団を率いた狩猟頭の、拍車付きの脚甲。犬どもは今もこの拍車の音を覚えていて、迷宮の獣すら血筋の記憶でわずかにたじろぐ。" }),
  F("f_shadow_silk_shoes", "影踏みの絹ぐつ", 71, { eDef: ["dark", 1], spd: 4, cls: ["thief", "mage", "bishop"],
    desc: "人の影だけを踏んで歩いたと噂された暗殺者の絹ぐつ。爪先は常に薄闇に浸り、聖堂の燭光の真下でさえ足元の影は濃いまま残る。" }),
  F("f_funeral_road_boots", "野辺送りの黒ぐつ", 75, { mp: 3, tint: "#3a3a46", tintAmt: 0.3,
    desc: "野辺送りの列の先頭、棺の前を歩く者だけに許される黒ぐつ。彼岸へ続く道を知る革は、迷宮の闇路でも決して道を踏み外させない。" }),
  F("f_oathbreaker_greaves", "背信騎士の脚甲", 75, { shape: "greaves", hp: 6, cls: ["fighter", "knight"],
    desc: "主君を裏切り、裏切った先でもまた裏切った騎士の脚甲。鉄はどの主の紋章も拒んで無地のまま、生き延びる才覚だけが染みている。" }),

  // ---- lv21-25 ----
  F("f_gale_chaser_boots", "暴風追いの長靴", 79, { eDef: ["wind", 1], spd: 4,
    desc: "嵐の目を追って大陸を渡り歩いた風狂いの観測者の長靴。履けばふくらはぎを追い風が押し、礫の豪雨も体をかすめて後ろへ逸れていく。" }),
  F("f_carrion_crow_boots", "鴉葬場のくつ", 83, { tint: "#3a3a46", tintAmt: 0.28,
    desc: "死者を鳥へ還す葬場の番人が履いたくつ。鴉どもはこの靴の主を仲間と見なすらしく、迷宮の中でも頭上のどこかから翼の音が付いてくる。" }),
  F("f_wyvern_hide_boots", "飛竜革のかぎ爪靴", 87, { spd: 10, cls: ["fighter", "knight", "thief"],
    desc: "墜とされた飛竜の翼膜とかぎ爪から仕立てた靴。岩壁に爪が掛かれば飛竜の脚力が革の内に蘇り、崖路も瓦礫の山もただの足場に変わる。" }),
  F("f_scorched_march_greaves", "焦土行軍の脚甲", 91, { shape: "greaves", eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "燃え落ちる王都を踏み抜いて退いた、撤退戦の生き残りの脚甲。焼けた街路の熱を吸った鉄は、吹き付ける風の刃を陽炎のように溶かす。" }),
  F("f_vesper_keeper_greaves", "晩鐘守の脚甲", 95, { shape: "greaves", mp: 3, cls: ["fighter", "knight", "priest"], tint: "#c9a227", tintAmt: 0.2,
    desc: "日没の鐘を生涯つき続けた老僧の脚甲。鐘楼の長い螺旋階段を昇り降りした鉄には残響が宿り、歩くたびに微かな祈りの音が鳴る。" }),

  // ---- lv26-30 ----
  F("f_beast_tamer_boots", "猛獣使いの革長靴", 98, { hp: 5, tint: "#8a6438", tintAmt: 0.25,
    desc: "鞭ひとつで魔獣を従えた猛獣使いの長靴。幾度も噛み砕かれては縫い直された革は、牙の通らない急所の在処を誰よりよく知っている。" }),
  F("f_owl_feather_shoes", "梟羽の夜靴", 102, { spd: 20, cls: ["thief", "mage", "bishop"],
    desc: "梟の風切羽を縫い込んだ夜歩き用の靴。梟が羽音を立てぬのと同じ理で、履く者の足音と気配を夜気へ溶かす。狩られる側は気づけない。" }),
  F("f_relic_route_boots", "聖跡巡りの白ぐつ", 106, { eDef: ["light", 1], mp: 4,
    desc: "聖者の足跡を辿る大巡礼を満願した白ぐつ。踏んだ聖跡の分だけ革は白く晒され、夜道に忍ぶ闇の指先を静かに払いのける。" }),
  F("f_war_prelate_greaves", "戦僧正の鋼脚甲", 110, { shape: "greaves", hp: 8, cls: ["fighter", "knight", "priest"],
    desc: "自ら戦場に立つことを選んだ僧正の鋼脚甲。祈りだけでは民を守れぬと悟った日の決意が宿り、踏み留まる足から折れない力が湧く。" }),
  F("f_deep_well_greaves", "深井の潜り脚甲", 114, { shape: "greaves", eDef: ["water", 1], spd: -10, cls: ["fighter", "knight"],
    desc: "かれずの大井戸の底をさらう潜り人足の脚甲。おもりを兼ねた鉄は水底の冷気を含んだままで、噴き上がる劫火さえ湯気に変えて防ぐ。" }),

  // ---- lv31-35 ----
  F("f_border_runner_boots", "国境破りの密行靴", 118, { spd: 20,
    desc: "関所を避けて夜の国境を抜ける案内人の靴。誰よりも速く、誰にも見られずに歩くことで生きてきた男の足癖が革に染みついている。" }),
  F("f_mountain_breaker_greaves", "山砕きの岩脚甲", 126, { shape: "greaves", eDef: ["earth", 2], spd: -30, cls: ["fighter", "knight"],
    desc: "山をひとつ崩したと伝わる巨人のかかとの骨を、岩盤ごと削り出した脚甲。大地そのものの足である以上、どんな濁流もこれを押し流せない。" }),
  F("f_basilica_guard_greaves", "大伽藍衛士の脚甲", 130, { shape: "greaves", hp: 10, cls: ["fighter", "knight", "priest"], tint: "#e8e8f4", tintAmt: 0.28,
    desc: "大伽藍の聖域を守った衛士の白銀の脚甲。何人たりとも通さぬという誓いの重さが鉄に移り、履く者は退くという選択を忘れてしまう。" }),
  F("f_otherfield_boots", "彼岸野の野ぐつ", 134, { mp: 5, tint: "#6b3fa0", tintAmt: 0.28,
    desc: "彼岸に咲く花の野を歩いてきたとしか思えないくつ。土の代わりに見知らぬ花の香が染みつき、この世ならざる場所への足掛かりになる。" }),

  // ---- lv36-40 ----
  F("f_giant_feller_greaves", "巨人殺しの脚甲", 138, { shape: "greaves", hp: 12, cls: ["fighter", "knight"], tint: "#d9d4bf", tintAmt: 0.3,
    desc: "巨人の向こうずねを断って勝った小兵の英雄譚にあやかった脚甲。巨人の骨を芯に仕込み、何よりも頑丈に、何よりも低く構えられる。" }),
  F("f_phantom_coach_boots", "亡霊馬車の御者靴", 141, { spd: 60, tint: "#e8e8f4", tintAmt: 0.2,
    desc: "真夜中に死者を乗せて走る馬車——その御者が履いていたとされる靴。地を踏んでいるのに車輪のように滑らかで、足音だけが遅れて届く。" }),
  F("f_deadmarch_greaves", "死出の行軍脚甲", 145, { shape: "greaves", cursed: true, align: "悪", def: 18, spd: -30, cls: ["fighter", "knight"], tint: "#3a3a46", tintAmt: 0.3,
    desc: "全滅した軍団が死後も続けているという行軍から、隊列を乱して脱げ落ちた脚甲。鉄壁の堅さと引き換えに、履けば亡者の歩調が足を縛り、もう自分の意志では脱げない。" }),
  F("f_sabbath_dance_shoes", "魔女夜会の踊り靴", 153, { mp: 6, spd: 30, cls: ["mage", "bishop"],
    desc: "魔女どもが夜会で夜通し踊り明かすための靴。踊り手の正気を少しずつ月へ捧げる代わりに足は軽く、魔力は満ちる。いわく付きの逸品だ。" }),

  // ---- lv41-45 ----
  F("f_purgatory_furnace_greaves", "煉獄炉の脚甲", 157, { shape: "greaves", eDef: ["fire", 2], cls: ["fighter", "knight"],
    desc: "罪を焼き浄める煉獄の炉、その焚き口の鉄扉から鍛え直された脚甲。内に封じた獄炎は嵐すら薪として喰らい、風の刃を残らず灰にする。" }),
  F("f_worldsend_boots", "果ての荒野の旅靴", 165, { spd: 60, hp: 10,
    desc: "地図が白紙に変わる場所まで歩き通した放浪者の旅靴。世界の果てを見てきた革にとって、迷宮の深さなど旅路の続きでしかない。" }),
  F("f_nightmare_hoof_boots", "夢魔の蹄ぐつ", 169, { eDef: ["dark", 1], spd: 30, mp: 4,
    desc: "悪夢を運ぶ夢魔の蹄を象ったくつ。履く者の足音は他人の夢の中でだけ響くといわれ、現の闇夜はおろか聖光のただ中さえ素通りしていく。" }),

  // ---- lv46-50 ----
  F("f_storm_sovereign_boots", "嵐王の渡靴", 177, { eDef: ["wind", 2], spd: 60,
    desc: "雲の上から地上の戦を見下ろしたという嵐の王の靴。歩むたび足元で旋風が渦を巻き、降り注ぐ岩塊も土砂も届く前に残らず吹き散らす。" }),
  F("f_elder_dragon_greaves", "老竜鱗の重脚甲", 184, { shape: "greaves", hp: 15, spd: -30, cls: ["fighter", "knight"], tint: "#c9a227", tintAmt: 0.3,
    desc: "天寿を全うした老竜が、形見にと鱗を許した——そんな伝説を持つ脚甲。黄金の鱗は山の重みで足を縛るが、竜の永い命を分け与えてくれる。" }),
  F("f_eternal_pilgrim_boots", "永劫巡礼のくつ", 192, { spd: 60, hp: 12, tint: "#e8e8f4", tintAmt: 0.3,
    desc: "世界をひと巡りしてなお歩みを止めない、終わりなき巡礼者のくつ。歩いた道のりの分だけ命を蓄えるといわれ、革はもう擦り切れ方を忘れた。" }),

  // ===== 布足装備 (weight:"cloth" — 魔法系・祈祷系が序盤から足を更新できるように) =====
  F("f_robe_sandals", "術師の草履", 4, { weight: "cloth", tint: "#8a6438", tintAmt: 0.2,
    desc: "魔法使いの見習いが初めて迷宮へ向かう朝に履かされる、麻紐の草履。軽さが取り柄で、呪文詠唱の姿勢を乱さない程度には役に立つ。" }),
  F("f_incense_treads", "香炉台の布靴", 14, { weight: "cloth", mp: 1, tint: "#9b59b6", tintAmt: 0.2,
    desc: "香炉の台座から採れた樹脂を靴底に染み込ませた布靴。香りが薄れることなく足元を包み、詠唱の集中力を微かに高めてくれる。" }),
  F("f_mist_step_slippers", "霧踏みの布靴", 26, { weight: "cloth", spd: 2, tint: "#7fd0e6", tintAmt: 0.22,
    desc: "濃霧の中を歩く霊媒師の布靴。靴底に縫い込んだ霧水晶が足運びを霧の揺らめきに変え、踏んだ床の軋みをすべて呑み込む。" }),
  F("f_wind_chant_sandals", "風詠みの草履", 40, { weight: "cloth", eAtk: ["wind", 1], spd: 2, tint: "#5fd08a", tintAmt: 0.2,
    desc: "嵐の呪師が竜巻の中心で脱ぎ捨てた草履。風の流れを読む術が皮に宿り、履く者の踏み込みに風の刃が乗り移る。" }),
  F("f_deep_script_shoes", "深偈踏みの布靴", 54, { weight: "cloth", mp: 3, tint: "#6b3fa0", tintAmt: 0.25,
    desc: "迷宮の深層から写し取った深偈を靴底に刷った布靴。一歩ごとに偈の一節が消えていくが、読み終えた頃には魔力が満ちている。" }),
  F("f_star_weave_slippers", "星織りの踏鞋", 73, { weight: "cloth", eAtk: ["light", 1], mp: 4, tint: "#ffe27a", tintAmt: 0.22,
    desc: "夜空の星を機に通して織り込んだ踏鞋。踏むたびにかすかな星明かりが漏れ、暗闇でも足元だけは小さな宇宙が広がっている。" }),
  F("f_void_silk_treads", "虚空絹の踏鞋", 93, { weight: "cloth", spd: 4, mp: 5, tint: "#3a3a46", tintAmt: 0.25,
    desc: "在らざる糸で織った踏鞋。確かな手触りがあるのに足元の影だけが濃く、踏んだ石畳はこれがいつ通ったのか記憶を持てない。" }),
  F("f_dark_mantle_treads", "暗幕の呪靴", 118, { weight: "cloth", eAtk: ["dark", 1], mp: 6, tint: "#9b6bd0", tintAmt: 0.25,
    desc: "夜会の舞台幕を縫い直した呪靴。幕は昼でも舞台の夜を覚えており、踏み出した一歩の足音を暗幕の向こうへ隠してしまう。" }),
  F("f_aeon_cloth_sandals", "永劫の術師草鞋", 150, { weight: "cloth", mp: 8, int: 2, tint: "#6b3fa0", tintAmt: 0.28,
    desc: "時間の流れが別の場所で編まれたという草鞋。秒が時間に感じられる詠唱の瞬間に、この草鞋だけは正しい速度で時を刻む。" }),
  F("f_cosmos_soul_slippers", "星宙魂の踏鞋", 180, { weight: "cloth", eAtk: ["dark", 2], mp: 10, int: 3, tint: "#9b6bd0", tintAmt: 0.3,
    desc: "星々が生まれる前の宇宙の静寂を踏み固めた踏鞋。履く者の足元では時間の概念が薄れ、迷宮の闇さえ宇宙の一点に過ぎなくなる。" }),
];

// ===== 小手 (18種) =====
// items.js の基本3点 (lv1-7) の先、lv9-192 を約20lvごとに埋める。
export const HANDS = [
  G("g_ratskin_wraps", "鼠革の手覆い", 9, { tint: "#7a6a5a", tintAmt: 0.25,
    desc: "下水の大鼠の革を巻いただけの簡素な手覆い。安物だが噛み傷にも毒針にも一度は耐えてくれる。その一度が生死を分ける。" }),
  G("g_gravedigger_mitts", "墓掘りの厚手袋", 13, {
    desc: "墓掘り人が棺の釘と土の冷たさから手を守った厚革の手袋。掌に染みた土の匂いは、死者の世界への挨拶代わりになるという。" }),
  G("g_watchman_gauntlets", "夜警の鉄籠手", 21, { shape: "gauntlet", cls: ["fighter", "knight"], tint: "#8a92a2", tintAmt: 0.2,
    desc: "迷宮口の夜警が酔漢と魔物を等しく殴り分けた鉄籠手。拳の部分だけ妙に磨り減っていて、持ち主の夜勤の長さを物語る。" }),
  G("g_poacher_gloves", "密猟者の革手袋", 28, { agi: 2, tint: "#6a8f5a", tintAmt: 0.22,
    desc: "領主の森で罠を仕掛け続けた密猟者の手袋。指先だけ革が薄く滑らかで、音を立てずに獲物へ触れる細工がしてある。" }),
  G("g_legion_gauntlets", "戦列の鉄籠手", 36, { shape: "gauntlet", cls: ["fighter", "knight"],
    desc: "肩を並べて壁を成した軍団の支給品。隣の兵の盾を掴んで支え合うため、掌には滑り止めの溝が彫られている。" }),
  G("g_ember_grips", "燠火の手甲", 44, { eDef: ["fire", 1],
    desc: "竈の神に捧げられた火伏せの手甲。常にほの温かく、燃え盛る得物すら素手のように握れる。風の刃は炎の幕が焼き払う。" }),
  G("g_tidecaller_gloves", "潮詠みの手袋", 52, { eDef: ["water", 1], mp: 3,
    desc: "潮を読む巫の家系に伝わる手袋。指を水に浸せば遠い海流の機嫌が分かるといい、火の災いを潮の加護が鎮める。" }),
  G("g_duelist_gauntlets", "決闘士の篭手", 63, { shape: "gauntlet", crit: 0.03, cls: ["fighter", "knight", "thief"], tint: "#a83232", tintAmt: 0.22,
    desc: "夜明けの決闘場で勝ち続けた剣士の篭手。相手の刃を受け流した傷が無数に走り、急所へ滑り込む手筋を覚えている。" }),
  G("g_stonewall_gauntlets", "石壁の重籠手", 75, { shape: "gauntlet", eDef: ["earth", 1], spd: -4, cls: ["fighter", "knight"],
    desc: "城壁の石を素手で積んだ石工聖人の籠手。岩の重みに慣れた指は何が降ってきても離さず、大水の流れすら堰き止める。" }),
  G("g_galewing_gloves", "風翼の指貫", 87, { eDef: ["wind", 1], agi: 20,
    desc: "風の精の羽根を編み込んだ指貫。指先が風を先読みして勝手に動き、土塊の弾礫は指の間をすり抜けて落ちる。" }),
  G("g_executioner_gauntlets", "処刑人の黒籠手", 99, { shape: "gauntlet", atkB: 4, cls: ["fighter", "knight"], tint: "#3a3a46", tintAmt: 0.3,
    desc: "処刑斧を握り続けた者の黒革籠手。柄を握る形に固まったまま戻らず、嵌めた者の握力ごと断頭の重さを思い出させる。" }),
  G("g_saintly_mitts", "聖手の祈り手袋", 110, { eDef: ["light", 1], pie: 3, cls: ["priest", "bishop"],
    desc: "千人の傷に触れた癒し手の白手袋。布は祈りを吸って淡く光り、闇の爪はこの手に触れる寸前で躊躇するという。" }),
  G("g_dragonscale_grips", "竜鱗の手甲", 122, { eDef: ["fire", 1], hp: 8, tint: "#3a7a6a", tintAmt: 0.25,
    desc: "脱皮した竜の鱗を継いだ手甲。鱗は今も己を竜と思っており、炎は同族の手を焼くことを避けて通る。" }),
  G("g_nightprowler_gloves", "夜歩きの絹手袋", 137, { eAtk: ["dark", 1], agi: 60,
    desc: "月のない夜にだけ仕事をした怪盗の絹手袋。触れたものの輪郭を闇に溶かし、その手刀は影そのものの冷たさで斬りつける。" }),
  G("g_titan_gauntlets", "巨人骨の大籠手", 149, { shape: "gauntlet", atkB: 8, spd: -30, cls: ["fighter", "knight"], tint: "#d9d4bf", tintAmt: 0.25,
    desc: "墓所の巨人の指骨を削り出した大籠手。嵌めると自分のものではない膂力が腕に流れ込み、岩も扉も同じ脆さに思えてくる。" }),
  G("g_frostbite_gauntlets", "霜噛みの籠手", 161, { shape: "gauntlet", eDef: ["water", 2], cls: ["fighter", "knight"],
    desc: "氷河に千年埋もれていた籠手。中の手はとうに無く、霜だけが形を保つ。纏う冷気は劫火すら噛み消す——◎の水護り。" }),
  G("g_archmage_gloves", "大魔導の指貫", 177, { mp: 10, int: 3, cls: ["mage", "priest", "bishop"], tint: "#6a4a8a", tintAmt: 0.28,
    desc: "指先で星座を書き換えたと謳われる大魔導の指貫。十指それぞれに別の呪文の癖が染みつき、詠唱の途中を勝手に補ってくれる。" }),
  G("g_godhand_gauntlets", "神手の黄金籠手", 192, { shape: "gauntlet", eDef: ["light", 2], hp: 15,
    desc: "神像の両手を鋳潰して打たれた黄金の籠手。祝福と瀆神をひとしく握り潰してきた手であり、闇はこの掌の上では形を保てない。" }),

  // ===== 布小手 (weight:"cloth" — 魔法系・祈祷系が序盤から小手を更新できるように) =====
  G("g_spell_wraps", "魔術の指包み", 5, { weight: "cloth", mp: 1, tint: "#9b59b6", tintAmt: 0.2,
    desc: "術師見習いが指先の感覚を掴むために巻く薄布の指包み。詠唱のたびに指先から魔力が染み出るのが分かり、少しだけ呪文が届く気がする。" }),
  G("g_rune_cloth_gloves", "符文の手袋", 20, { weight: "cloth", mp: 2, tint: "#6b3fa0", tintAmt: 0.22,
    desc: "掌に呪符を書き込んだ薄手の手袋。符の文字は手を動かすたびに形を変え、握った得物の扱いを秘かに呪文の延長へと変えていく。" }),
  G("g_hex_finger_guards", "呪法の指貫", 38, { weight: "cloth", int: 1, mp: 3, tint: "#9b6bd0", tintAmt: 0.22,
    desc: "呪法師が術式を指で描くために仕立てた指貫。五指それぞれに異なる呪の型が覚えられており、握るだけで詠唱の下準備が整う。" }),
  G("g_tide_weave_gloves", "潮詠みの手袋", 58, { weight: "cloth", eDef: ["water", 1], mp: 4, tint: "#4aa3ff", tintAmt: 0.22,
    desc: "潮の満ち引きに呼応して魔力を満たすことを覚えた手袋。炎の奔流が来るたびに、手袋はその熱を潮に変えて消し去る。" }),
  G("g_ley_reader_gloves", "地脈詠みの指貫", 78, { weight: "cloth", int: 1, pie: 1, mp: 5, tint: "#c89a4a", tintAmt: 0.22,
    desc: "地脈の流れを手で読んだ占師の指貫。地の底の魔力が指先まで昇ってきて、詠唱と癒しの両方へ均等に分配されていく。" }),
  G("g_star_cloth_gauntlets", "星布の手甲", 108, { weight: "cloth", eAtk: ["light", 1], mp: 6, int: 2, tint: "#ffe27a", tintAmt: 0.22,
    desc: "夜空を圧縮した糸で織った手甲。握った呪文の器に星明かりが満ちて溢れ、光に属するものへの呪文が一段冴えるという。" }),
  G("g_soul_weave_wraps", "魂糸の指貫", 140, { weight: "cloth", mp: 8, int: 2, pie: 2, tint: "#9b6bd0", tintAmt: 0.28,
    desc: "迷宮で散った術師の魂を糸に紡いで編んだ指貫。先人の術式の記憶が指先まで流れ込み、詠唱の途中から手が勝手に動き始める。" }),
  G("g_arcane_void_gloves", "秘術虚無の手袋", 172, { weight: "cloth", eAtk: ["dark", 2], mp: 10, int: 3, tint: "#9b6bd0", tintAmt: 0.3,
    desc: "在らざる空間から引き抜いた糸で縫い上げた手袋。嵌めれば指の輪郭が曖昧になり、虚空へ放った呪文は次の虚空を渡って届く。" }),
];

// ===== 装飾品 (8種) =====
// items.js の既存12点の隙間 (序盤帯と最深部帯) を埋める。
export const ACCS = [
  R("r_rabbitfoot", "兎足の御守り", "pouch", 5, { luk: 2,
    desc: "三度罠を逃れた野兎の後ろ足を干した御守り。迷信だと笑う者ほど、迷宮の入口でこっそり撫でていくという。" }),
  R("r_copper_signet", "銅の印章指輪", "ring", 13, { luk: 1, hp: 4, tint: "#a9672a", tintAmt: 0.3,
    desc: "潰れた商会の印章指輪。商運は尽きたが、幾度もの倒産を生き延びた店主のしぶとさだけは銅の中に残っている。" }),
  R("r_warpriest_beads", "戦僧の数珠", "amulet", 56, { pie: 3, mp: 4, tint: "#8a6438", tintAmt: 0.25,
    desc: "戦場で祈りながら戦った破戒僧の数珠。珠のひとつひとつが弔った敵の数で、握って祈れば法力が指先まで満ちてくる。" }),
  R("r_hawkeye_pendant", "鷹の目の首飾り", "eye", 72, { crit: 0.04,
    desc: "百発百中と謳われた狩人が相棒の鷹の目を封じた首飾り。獲物の急所が淡く光って視えるといい、外した時の言い訳を奪う。" }),
  R("r_bulwark_brooch", "城壁の襟章", "amulet", 120, { def: 6, hp: 20, tint: "#8a92a2", tintAmt: 0.25,
    desc: "落ちなかった城の最後の城壁守備隊章。胸に留めると壁の一部になったような重い安心が宿り、刃が肌に届く前に鈍る。" }),
  R("r_stormcoil", "嵐環の指輪", "ring", 150, { eAtk: ["wind", 1], agi: 90,
    desc: "小さな竜巻を環の形に封じた指輪。指の周りで風が絶えず渦を巻き、振るう得物に嵐の刃を上乗せする。" }),
  R("r_phoenix_plume", "不死鳥の尾羽", "horn", 185, { eDef: ["fire", 2], hp: 30,
    desc: "灰から蘇る霊鳥が灰に残した一枚の尾羽。身につける者の命を熾火のように保ち、いかなる業火も同じ炎として素通りする。" }),
  R("r_soulking_signet", "魂王の印璽", "ring", 196, { luk: 5, mp: 15, eAtk: ["dark", 1],
    desc: "百の迷宮の主たちが恐れる印が刻まれた黒い印璽。嵌めた者の影が一回り濃くなり、迷宮の闇が道を譲るとも、招くともいう。" }),
];
