// 頭・足カタログ増補 (頭47種 + 足49種)。id は append-only (改名・削除禁止)。
// gear.js と合わせ頭100種・足100種。lv1〜200 を満遍なく散らし、属性◎(Lv2) は深層帯のみ。
import { H, F } from "./defs.js";

export const HEADS2 = [
  H("h_straw_sunhat", "麦わらの日よけ帽", 1, { shape: "hat",
    desc: "畑仕事の日差しをしのいだ麦わら帽。迷宮に日差しはないが、上から降ってくるものは案外多い。" }),
  H("h_potlid_helm", "鍋蓋の兜", 3, {
    desc: "鍋の蓋に顎紐をつけた急造の兜。笑われがちだが、鍋として煮炊きに耐えた鉄は石礫程度なら平気で弾く。" }),
  H("h_ferryman_rainhat", "渡し守の雨笠", 5, { shape: "hat", eDef: ["water", 1],
    desc: "雨の川面を百年見てきた渡し守の笠。雨垂れを流す編み目は、降りかかる火の粉も同じ要領で流す。" }),
  H("h_miner_candle_helm", "坑夫の燭台帽", 9, { tint: "#8a6438", tintAmt: 0.25,
    desc: "額に蝋燭を据えた坑夫の革帽。蝋の滴りの痕は地下で過ごした歳月の数で、革は落盤の予兆に強張る。" }),
  H("h_acolyte_cowl", "侍祭の頭巾", 13, { shape: "hat", mp: 2,
    desc: "聖堂の侍祭が朝課で被った頭巾。聞き覚えた祈祷の節が布に残り、被る者の詠唱に小声で和す。" }),
  H("h_foxfur_cap", "狐毛皮の冬帽", 17, { shape: "hat", luk: 1,
    desc: "猟師を七年欺いた古狐の毛皮帽。狐の悪知恵が毛先に残っていて、被る者の勘を妙に冴えさせる。" }),
  H("h_quarry_hardhat", "石切場の保護兜", 21, { eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "落石から坑夫の頭を守り抜いた木芯の兜。岩盤に鍛えられた兜は、上から来るものすべてに頑固だ。" }),
  H("h_streetbrawler_band", "喧嘩屋の鉢巻", 24, { shape: "hat", hp: 3,
    desc: "裏町の喧嘩屋が締め続けた鉢巻。血と汗の染みた布は、殴られても折れない意地の締め方を知っている。" }),
  H("h_furnace_visor", "炉前の遮熱面", 28, { eDef: ["fire", 1], cls: ["fighter", "knight", "priest"],
    desc: "鋳造所の炉前作業で使われた遮熱の面。千度の熱と向き合った鉄面に、風の刃の冷たさはむしろ快い。" }),
  H("h_herbalist_wreath", "薬草師の花冠", 32, { shape: "circlet", pie: 2,
    desc: "薬草師が干し薬草で編んだ実用の冠。香りは気つけ薬を兼ね、被る者の祈りに薬効を混ぜる。" }),
  H("h_windvane_helm", "風見鶏の兜", 36, { eDef: ["wind", 1],
    desc: "尖塔の風見鶏を頂に据えた酔狂な兜。鶏は今も風向きに敏く、礫まじりの突風が来る前に首を回す。" }),
  H("h_gravecandle_circlet", "墓蝋燭の環", 40, { shape: "circlet", eDef: ["dark", 1], mp: 3,
    desc: "墓前の蝋燭立てを額環に打ち直した冠。死者の傍らで灯り続けた金属は、闇との間合いを心得ている。" }),
  H("h_riverpearl_diadem", "川真珠の額飾り", 44, { shape: "circlet", eDef: ["water", 1], mp: 3,
    desc: "川底の真珠貝から採れた歪な真珠の額飾り。淡水の冷たさを宿す珠は、額に迫る熱を露に変える。" }),
  H("h_siegeworks_helm", "攻城兵器班の兜", 48, { cls: ["fighter", "knight"],
    desc: "投石機の傍らで働いた兵器班の鉄兜。味方の石が頭上を飛び交う持ち場は、兜の目利きを厳しくする。" }),
  H("h_owlfeather_hood", "梟羽の頭巾", 52, { shape: "hat", spd: 1,
    desc: "梟の羽根を縫い込んだ夜行の頭巾。被れば首の動きが音を失い、視界の端の気配に敏くなる。" }),
  H("h_saltminer_helm", "岩塩坑の白兜", 56, { eDef: ["earth", 1], cls: ["fighter", "knight", "priest"],
    desc: "岩塩坑で塩の結晶に覆われた兜。清めの塩をまとった鉄は、穢れたものの爪を一歩手前で止める。" }),
  H("h_lamplighter_hat", "点灯夫のシルクハット", 60, { shape: "hat", eDef: ["light", 1],
    desc: "街灯を灯して回った点灯夫の山高帽。千の灯りを見届けた帽子は、闇の濃い場所で微かに発光する。" }),
  H("h_warhorn_helm", "角笛の兜", 63, { hp: 5, cls: ["fighter", "knight"],
    desc: "突撃の角笛を兜に組み込んだ蛮族の戦兜。被る者の雄叫びは角を通って戦場の端まで届く。" }),
  H("h_smokeveil_cowl", "煙幕の頭巾", 67, { shape: "hat", eDef: ["wind", 1],
    desc: "煙とともに消える怪盗の頭巾。布は常に薄くかすんでいて、矢も礫も輪郭を捉えそこねて逸れる。" }),
  H("h_coralcrown", "珊瑚の王冠", 71, { shape: "circlet", eDef: ["water", 1], mp: 4,
    desc: "海底神殿の主が戴いた珊瑚の冠。海の冷たさを忘れない珊瑚は、炎の熱を潮騒の彼方へ流す。" }),
  H("h_pyrewatch_helm", "火葬見守りの兜", 75, { eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "火葬の火を夜通し見守る役目の兜。炎を見つめ続けた鉄面は、もはや火の色に動じることがない。" }),
  H("h_centurion_galea", "百卒長の羽兜", 79, { hp: 6, cls: ["fighter", "knight"],
    desc: "百人の兵を預かった百卒長の羽飾り兜。羽根は部下の数だけあり、折れた羽根は一本もないのが自慢だった。" }),
  H("h_stargazer_circlet", "天測の銀環", 83, { shape: "circlet", mp: 5, cls: ["mage", "priest", "bishop"],
    desc: "星の運行を測った天文学者の銀環。星図の刻まれた輪は、被る者の思考を夜空のように澄ませる。" }),
  H("h_executioner_hood", "処刑人の革頭巾", 87, { shape: "hat", eDef: ["dark", 1],
    desc: "処刑人が素顔を隠した革頭巾。顔のない者に呪いは届かない——その理屈を、頭巾は今日も証明する。" }),
  H("h_galecrest_helm", "風冠の兜", 91, { eDef: ["wind", 1], spd: 1, cls: ["fighter", "knight", "thief"],
    desc: "山嶺の風の神に捧げられた飾り兜。頂の風切り板が常に鳴り、被る者は風の来る方を先に知る。" }),
  H("h_torchbearer_helm", "松明持ちの兜", 95, { eDef: ["fire", 1],
    desc: "夜襲の先頭で松明を掲げた決死隊の兜。火の粉を浴び続けた鉄は、炎の機嫌の読み方を覚えた。" }),
  H("h_seer_blindcrown", "予見者の目隠し冠", 98, { shape: "circlet", mp: 5, cls: ["mage", "priest", "bishop"],
    desc: "視ることをやめて視えるようになった予見者の冠。目元を覆う銀板の裏で、別の目が静かに開く。" }),
  H("h_kraken_beak_helm", "大烏賊嘴の兜", 102, { eDef: ["water", 1], cls: ["fighter", "knight"],
    desc: "船を沈めた大烏賊の嘴を兜に据えた船乗りの戦利品。深海の闇を泳いだ嘴は、火脈の熱を冷たく嗤う。" }),
  H("h_mourning_empress_veil", "喪服の女帝の面紗", 106, { shape: "hat", eDef: ["dark", 1], mp: 5,
    desc: "夫帝を弔い続けた女帝の黒い面紗。十年の喪が染みた布は夜より濃く、聖光すら遠慮がちに避ける。" }),
  H("h_avalanche_helm", "雪崩生きの兜", 110, { eDef: ["earth", 1], hp: 6, cls: ["fighter", "knight"],
    desc: "雪崩に三日埋まって生還した猟師の兜。山の重さを一度受け止めた鉄は、大抵の衝撃を軽いと感じる。" }),
  H("h_warlock_hornband", "魔角の額環", 114, { shape: "circlet", mp: 6, cls: ["mage", "bishop"],
    desc: "悪魔と契った術師の額に生えた角を、死後に環へ打ち直したもの。角は今も契約の続きを囁いてくる。" }),
  H("h_sunsteel_barbute", "陽鋼の兜", 118, { eDef: ["light", 1], cls: ["fighter", "knight"],
    desc: "真夏の太陽に七年さらして焼き入れた陽鋼の兜。正午の輝きを宿す鉄は、夜のものの爪を焼いて返す。" }),
  H("h_deepvault_helm", "大金庫の兜", 122, { tint: "#c9a227", tintAmt: 0.25, cls: ["fighter", "knight"],
    desc: "破られなかった大金庫の扉から打ち出された兜。中身より硬いと評された鉄が、今は頭蓋を守っている。" }),
  H("h_tempest_circlet", "暴風の環", 126, { shape: "circlet", eDef: ["wind", 2], mp: 5,
    desc: "嵐の目の静けさを輪の形に封じた額環。被る者の周りだけ風が凪ぎ、礫の豪雨は輪の外で散る。" }),
  H("h_magmaforge_helm", "溶岩炉の兜", 134, { eDef: ["fire", 2], cls: ["fighter", "knight"],
    desc: "溶岩を直接くべる魔窯で鍛えられた兜。鋼の芯はまだ赤熱の記憶に火照り、いかなる劫火も古巣の火だ。" }),
  H("h_lichking_diadem", "死霊王の額冠", 138, { shape: "circlet", eDef: ["dark", 1], mp: 7, cls: ["mage", "bishop"],
    desc: "玉座で朽ちた死霊王の額から外された冠。死後も衰えなかった魔力の残滓が、輪の内側に渦巻いている。" }),
  H("h_judgment_halo_helm", "裁きの光輪兜", 141, { eDef: ["light", 1], mp: 5, cls: ["fighter", "knight", "priest"],
    desc: "頭上に細い光輪を戴く審判者の兜。輪の光は被る者の迷いを焼き、闇の囁きを耳に入る前に裁く。" }),
  H("h_behemoth_skull_helm", "巨獣頭骨の兜", 149, { hp: 12, cls: ["fighter", "knight"],
    desc: "大地を揺らした巨獣の頭骨を削った兜。獣の頭蓋に守られる安心感は、人の兜では決して得られない。" }),
  H("h_maelstrom_crown", "大渦の宝冠", 153, { shape: "circlet", eDef: ["water", 2], mp: 6,
    desc: "船呑みの大渦の中心で見つかった冠。渦の静かな目を戴く者の額に、火も熱も辿り着けない。" }),
  H("h_gravelord_greathelm", "墓王の大兜", 161, { eDef: ["dark", 2], cls: ["fighter", "knight"],
    desc: "千の墓を統べた墓王の大兜。死者の国の冠を兼ねた鉄は、聖光の裁きを古い知人のようにあしらう。" }),
  H("h_skyfortress_helm", "天空砦の兜", 165, { eDef: ["wind", 1], hp: 10, cls: ["fighter", "knight"],
    desc: "雲の上に浮かんだという砦の衛兵の兜。天の風に磨かれた鉄は、地上の嵐を子供の息と笑う。" }),
  H("h_worldtree_wreath", "世界樹の葉冠", 173, { shape: "circlet", mp: 8, hp: 8,
    desc: "世界樹の落ち葉を編んだ冠。枯れてなお葉脈には樹液が巡り、被る者の命と魔力を根のように支える。" }),
  H("h_dawnempire_crown", "暁帝国の宝冠", 180, { shape: "circlet", eDef: ["light", 2], mp: 7,
    desc: "夜明けとともに興り、日没とともに滅びたという帝国の冠。輪には永遠の朝焼けが封じられている。" }),
  H("h_volcanolord_helm", "火山王の兜", 184, { eDef: ["fire", 2], hp: 10, cls: ["fighter", "knight"],
    desc: "火口の玉座に座した王の兜。鋼は溶岩の流れる紋様に波打ち、劫火はこの兜の前で頭を垂れる。" }),
  H("h_starfall_diadem", "星降りの宝冠", 192, { shape: "circlet", mp: 9, luk: 3,
    desc: "星が降った夜に隕鉄から打たれた宝冠。輪の内側では今も小さな流星が巡り、願いを聞き飽きている。" }),
  H("h_abyssgod_visage", "深淵神の面", 196, { eDef: ["dark", 2], mp: 8,
    desc: "深淵で祀られた名もなき神の顔を写した面。被れば深淵がこちらを覗き返すが、敵はもっと覗かれる。" }),
];

export const FEET2 = [
  F("f_barefoot_wraps", "素足の布巻き", 1, {
    desc: "靴も買えない駆け出しが足に巻いた布。それでも素足よりはましで、迷宮の床の冷たさを少しだけ忘れられる。" }),
  F("f_fieldhand_clogs", "農夫の木靴", 3, {
    desc: "泥田を歩き抜いた農夫の木靴。ぬかるみに沈まない厚底は、迷宮の得体の知れない床でも頼りになる。" }),
  F("f_chimneysweep_boots", "煙突掃除のすす靴", 9, { eDef: ["fire", 1],
    desc: "煙突の中を上り下りした掃除夫の革靴。すすに燻され続けた革は、火の粉の上を平気で歩く。" }),
  F("f_eelskin_boots", "ウナギ革の滑り靴", 13, { eDef: ["water", 1], spd: 1,
    desc: "大ウナギの革を張った漁師の靴。濡れた岩場で滑らない皮肉な造りで、濡れるほど足は軽くなる。" }),
  F("f_towncrier_boots", "触れ役の早足靴", 17, { spd: 1,
    desc: "布告を町中へ触れて回った役人の靴。一日中歩いても疲れない造りは、職人の腕より本人の切実さの賜物だ。" }),
  F("f_vineyard_treaders", "葡萄踏みの素足靴", 21, {
    desc: "葡萄を踏んで搾った娘たちの薄革靴。果皮を潰して種を潰さない繊細な足裏が、罠の感触も拾い上げる。" }),
  F("f_gravepath_sandals", "墓道のわらじ", 24, { eDef: ["dark", 1],
    desc: "墓地への道を毎日往復した僧のわらじ。彼岸への道順を覚えた足元は、亡者の手にも怯まない。" }),
  F("f_stonemason_greaves", "石積み工の脚甲", 28, { shape: "greaves", eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "城壁を積んだ石工のすね当て。落ちてくる石材から脛を守った当て板は、岩の落ち方を先読みする。" }),
  F("f_dancer_slippers", "旅芸人の踊り靴", 32, { spd: 1,
    desc: "広場で日銭を稼いだ踊り子の靴。観衆の輪の中で磨かれた足さばきは、敵の輪の中でも変わらない。" }),
  F("f_emberwalk_boots", "おき火渡りの靴", 36, { eDef: ["fire", 1],
    desc: "祭りの火渡り神事で使われた厚底靴。おき火の上を百度渡った底革は、炎を床の延長としか思わない。" }),
  F("f_messenger_windboots", "風脚の伝令靴", 40, { eDef: ["wind", 1], spd: 1,
    desc: "敗報を誰より速く届け続けた伝令の靴。向かい風の中を駆けた革は、いつしか風と歩調を合わせ始めた。" }),
  F("f_marshwader_boots", "湿原渡りの長靴", 44, { eDef: ["water", 1],
    desc: "底なし湿原の道なき道を知る案内人の長靴。水と泥の機嫌を読む革は、火の沼でも同じように歩ける。" }),
  F("f_bellringer_boots", "鐘つき守の靴", 48, { mp: 2,
    desc: "鐘楼の螺旋階段を一日五往復した鐘つきの靴。昇り降りに鍛えられた革は、祈りの時刻を足裏で覚えている。" }),
  F("f_huntpack_boots", "猟犬番の革靴", 52, { spd: 1,
    desc: "猟犬の群れと駆けた犬番の革靴。犬たちと同じ歩法を刻んだ底は、獲物を追う足を疲れさせない。" }),
  F("f_catacomb_greaves", "地下墓地の脚甲", 56, { shape: "greaves", eDef: ["dark", 1], cls: ["fighter", "knight"],
    desc: "地下墓地の巡回兵の脚甲。骨の転がる床を踏み続けた鉄は、死者の不機嫌を踏んでも祟られない。" }),
  F("f_orchardthief_shoes", "果樹園泥棒の軽靴", 60, { luk: 2,
    desc: "領主の果樹園に十年通った泥棒の靴。一度も捕まらなかった幸運の半分は、この音のしない靴底にある。" }),
  F("f_lavafield_greaves", "溶岩原の脚甲", 63, { shape: "greaves", eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "冷えきらない溶岩原を測量した学者の脚甲。足元の熱に慣れた鉄は、吹き付ける熱風を涼しげに受ける。" }),
  F("f_courier_cliffboots", "崖道飛脚の靴", 67, { eDef: ["earth", 1], spd: 1,
    desc: "崖っぷちの郵便路を駆けた飛脚の靴。崩れる足場を読む底革は、落石の気配に足の方が先に応える。" }),
  F("f_tidewatcher_boots", "潮見櫓の長靴", 71, { eDef: ["water", 1],
    desc: "高潮を見張る櫓の番人の長靴。波しぶきを浴び続けた革は潮の重さを知り、火の波も同じ要領で受け流す。" }),
  F("f_gallowswalk_boots", "刑場歩きの黒靴", 75, { eDef: ["dark", 1],
    desc: "死刑囚を刑場まで先導した役人の黒靴。最期の道を千度歩いた革は、死の影と並んで歩く作法を知る。" }),
  F("f_skirmish_greaves", "遊撃兵の軽脚甲", 79, { shape: "greaves", spd: 1, cls: ["fighter", "knight", "thief"],
    desc: "重装の戦列を駆け回った遊撃兵の脚甲。守りを削って速さを取った設計は、止まらない者をよく守る。" }),
  F("f_stormchaser_boots", "嵐追いの長靴", 83, { eDef: ["wind", 1], spd: 1,
    desc: "竜巻を追いかけて記録した変人学者の長靴。嵐に近づきすぎた革は風に好かれ、礫が当たらなくなった。" }),
  F("f_reliquary_greaves", "聖骨匣の脚甲", 87, { shape: "greaves", eDef: ["light", 1], mp: 3, cls: ["fighter", "knight", "priest"],
    desc: "聖者の脛骨を納めた匣の銀板から打たれた脚甲。聖骨を守った銀は、纏う者の脛も同じ熱心さで守る。" }),
  F("f_ratking_sewerboots", "鼠王の下水靴", 91, { tint: "#5a6a4a", tintAmt: 0.25,
    desc: "下水道を統べた盗賊王の長靴。都の地下をすべて歩いた底革には、抜け道を嗅ぎ分ける癖が染みている。" }),
  F("f_glacier_greaves", "氷河の青脚甲", 95, { shape: "greaves", eDef: ["water", 1], cls: ["fighter", "knight"],
    desc: "氷河の青氷を芯に封じた脚甲。千年の冷気が脛を包み、迫る業火は届く前に湯気へ変わる。" }),
  F("f_pilgrimage_end_boots", "結願の巡礼靴", 98, { mp: 4,
    desc: "八十八の霊場を巡り終えた満願の靴。歩いた祈りの道のりが革に蓄えられ、持ち主の魔力を支える。" }),
  F("f_warbeast_hide_boots", "軍獣革の重靴", 102, { hp: 6,
    desc: "戦象の革から仕立てた重騎兵の靴。踏まれる側から踏む側に回った革は、踏み込みの一歩が崩れない。" }),
  F("f_emberdancer_shoes", "火踊りの靴", 106, { eDef: ["fire", 1], spd: 1,
    desc: "祭りの火の輪をくぐり続けた踊り手の靴。炎との間合いを体で覚えた革は、火を踏む寸前で必ずかわす。" }),
  F("f_nightcourier_boots", "夜便りの靴", 110, { eDef: ["dark", 1], spd: 1,
    desc: "夜にしか動かない密使の靴。月明かりすら避けて歩いた革は闇に溶け、足音は持ち主にすら聞こえない。" }),
  F("f_rockslide_greaves", "山津波の脚甲", 114, { shape: "greaves", eDef: ["earth", 1], hp: 6, cls: ["fighter", "knight"],
    desc: "山津波に呑まれて生還した男の脚甲。土砂の本気を受け止めた鉄は、地のものの怒りを受け流せる。" }),
  F("f_zealot_march_greaves", "狂信行軍の脚甲", 118, { shape: "greaves", mp: 4, cls: ["fighter", "knight", "priest"],
    desc: "不眠不休で聖地へ行軍した狂信兵の脚甲。限界を知らない歩みが鉄に染みつき、疲れという言葉を拒む。" }),
  F("f_seafoam_boots", "海泡の靴", 122, { eDef: ["water", 1], spd: 1,
    desc: "波頭の泡だけを踏んで渡ったという聖者の靴。海面の記憶を持つ革は、足場の悪さを意に介さない。" }),
  F("f_cinderlord_greaves", "燼の領主の脚甲", 126, { shape: "greaves", eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "灰になった領地を歩き続けた領主の脚甲。灰の中の熾火を踏み抜いた鉄は、劫火の床も領地と見なす。" }),
  F("f_galeprince_boots", "風公子の靴", 134, { eDef: ["wind", 2], spd: 1,
    desc: "風の精の血を引くと噂された公子の靴。歩くたび足首で小さな旋風が生まれ、礫も土塊も巻いて散らす。" }),
  F("f_boneking_greaves", "骨王の脚甲", 138, { shape: "greaves", eDef: ["dark", 1], hp: 8, cls: ["fighter", "knight"],
    desc: "骨の玉座から立ち上がった王の脚甲。死者の国を踏破した鉄は、生者の国の刃を遠い昔話のように防ぐ。" }),
  F("f_lightbringer_sabatons", "光運びの鉄靴", 141, { shape: "greaves", eDef: ["light", 1], mp: 5, cls: ["fighter", "knight", "priest"],
    desc: "闇に沈んだ村々へ聖火を届けた使者の鉄靴。光を運んだ足元は自ら淡く灯り、闇の手は触れる先から薄れる。" }),
  F("f_chasmleaper_boots", "裂け谷跳びの靴", 149, { spd: 2,
    desc: "幅七間の裂け谷を助走なしで跳んだという軽業師の靴。革は跳ぶ感覚を覚えていて、持ち主の踏切を急かす。" }),
  F("f_tsunami_greaves", "大津波の脚甲", 153, { shape: "greaves", eDef: ["water", 2], cls: ["fighter", "knight"],
    desc: "大津波に正面から耐えた防波堂の扉から打たれた脚甲。海の全力を知る鉄の前では、業火はせせらぎだ。" }),
  F("f_shadowmonarch_boots", "影帝の靴", 161, { eDef: ["dark", 2], spd: 1,
    desc: "影だけで国を統べたという帝の靴。履く者の足元から影が先に歩き出し、聖光は影を踏めずに立ち尽くす。" }),
  F("f_skystrider_boots", "天駆けの靴", 165, { eDef: ["wind", 1], spd: 2,
    desc: "雲を足場に天を駆けたという伝説の靴。地を踏む足音が半分空に逃げ、駆ける姿は風の残像に紛れる。" }),
  F("f_magmacore_greaves", "溶岩心核の脚甲", 173, { shape: "greaves", eDef: ["fire", 2], cls: ["fighter", "knight"],
    desc: "火山の心核から削り出された脚甲。大地の血潮の温度を知る鉄は、地上のいかなる炎にも沸点を許さない。" }),
  F("f_worldroot_boots", "世界根の靴", 180, { eDef: ["earth", 2], hp: 10,
    desc: "世界樹の根の皮で仕立てた靴。大地そのものと繋がる革は、立つ者を世界の重さで支えて揺るがせない。" }),
  F("f_dawnchaser_boots", "暁追いの靴", 188, { eDef: ["light", 1], spd: 2,
    desc: "沈まぬ朝日を追って世界を一周したという靴。夜明けの速さで駆けた革は、闇が追いつく隙を残さない。" }),
  F("f_voidstep_boots", "虚空歩みの靴", 196, { spd: 2, mp: 8,
    desc: "存在しない床を三歩まで踏めるという靴。三歩の根拠は誰も知らないが、四歩目で皆いなくなった。" }),
  F("f_harvestmoon_sandals", "豊穣月のわらじ", 45, { luk: 2,
    desc: "豊穣の満月の夜にだけ編まれるわらじ。月光を編み込んだ藁は、履く者の足元に小さな実りを呼ぶ。" }),
  F("f_coalraker_boots", "炭かき夫の靴", 57, { eDef: ["fire", 1],
    desc: "炉の炭をかき続けた炭かき夫の厚底靴。落ちた熾火を踏み消すのが癖の底革は、火の床を恐れない。" }),
  F("f_plague_pit_boots", "疫病溝の防護靴", 81, { hp: 5,
    desc: "疫病の死者を葬る溝で働いた人夫の靴。最悪の場所を歩き抜いた革は、持ち主の命に妙にしぶとい。" }),
  F("f_summit_shrine_boots", "山頂社の参道靴", 129, { eDef: ["earth", 1], mp: 4,
    desc: "雲より高い山頂の社へ千段の石段を登り続けた神主の靴。霊峰の気を吸った革が、足と祈りを支える。" }),
  F("f_riverstyx_sandals", "三途渡しのわらじ", 157, { eDef: ["dark", 1], mp: 6,
    desc: "彼岸の川の渡し守が編んだというわらじ。岸と岸の間を歩いた藁は、生と死の境目で滑らない。" }),
];
