// 小手・装飾品カタログ増補 (小手80種 + 装飾品62種)。id は append-only (改名・削除禁止)。
// gear.js と合わせ小手100種・装飾品70種。lv1〜200 を満遍なく散らし、属性◎(Lv2) は深層帯のみ。
import { G, R } from "./defs.js";

export const HANDS2 = [
  G("g_fieldwork_mitts", "野良仕事の手袋", 1, {
    desc: "鍬の柄で硬くなった農夫の手袋。豆だらけの掌を守った布は、剣の柄でも同じ仕事をする。" }),
  G("g_fishnet_gloves", "網引きの手覆い", 3, {
    desc: "漁網を引き続けた漁師の手覆い。縄擦れに耐えた革は、武器を握る掌をまめひとつなく守る。" }),
  G("g_stablehand_gloves", "馬丁の革手袋", 5, {
    desc: "気性の荒い軍馬を宥めた馬丁の手袋。噛まれ蹴られて鞣された革は、暴れるものの扱いを知っている。" }),
  G("g_woodcutter_grips", "木こりの厚手袋", 9, {
    desc: "斧の柄を握り続けた木こりの厚革手袋。掌の革だけ飴色に光り、振り下ろす得物を逃さない。" }),
  G("g_scullery_mitts", "厨房の鍋つかみ", 13, { eDef: ["fire", 1],
    desc: "城の厨房で熱鍋を掴み続けた厚手袋。煮えた鉄を素手同然に扱った布は、火の熱を軽くいなす。" }),
  G("g_gravedigger_gauntlets", "墓掘りの鉄手袋", 17, { shape: "gauntlet", cls: ["fighter", "knight"],
    desc: "凍った墓土を掘った冬場用の鉄手袋。土の冷たさと死者の冷たさ、その両方に慣れている。" }),
  G("g_falconer_glove", "鷹匠の止まり手袋", 21, { luk: 1,
    desc: "猟鷹を腕に止めた鷹匠の長手袋。爪痕だらけの革には、空の狩人に信頼された証が刻まれている。" }),
  G("g_ratter_gloves", "鼠捕りの噛まれ手袋", 24, {
    desc: "千匹の鼠に噛まれた鼠捕りの革手袋。牙の通らなくなった革は、小さな顎の急所も覚えてしまった。" }),
  G("g_bellfounder_gauntlets", "鋳鐘師の籠手", 28, { shape: "gauntlet", eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "溶けた青銅を鋳型へ注いだ鋳鐘師の籠手。湯の温度と付き合った鉄は、炎を道具としか見ていない。" }),
  G("g_netmender_gloves", "網繕いの指貫", 32, { agi: 1,
    desc: "破れた漁網を繕い続けた指貫。細かい結び目を辿った指先は、敵の守りのほつれも見つけ出す。" }),
  G("g_quarry_gauntlets", "石切りの岩籠手", 36, { shape: "gauntlet", eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "岩を素手で扱った石切り人足の籠手。石の粉に磨かれた鉄は、岩のものの一撃を岩として受ける。" }),
  G("g_winecellar_gloves", "酒蔵番の手袋", 40, { luk: 1,
    desc: "百年物の酒樽を扱った蔵番の手袋。決して落とさないと誓われた掌は、勝機もまた取り落とさない。" }),
  G("g_rainmaker_mitts", "雨乞い師の手袋", 44, { eDef: ["water", 1], mp: 2,
    desc: "雨乞いの舞で天へ掲げ続けられた手袋。雨雲に愛された布は、火の粉を雨粒のように払い落とす。" }),
  G("g_armorer_gauntlets", "武具師の試し籠手", 48, { shape: "gauntlet", cls: ["fighter", "knight"],
    desc: "鍛えた剣の刃を素手で確かめた武具師の籠手。千本の刃を撫でた鉄は、刃の通る筋を先に知る。" }),
  G("g_galeweaver_gloves", "風織りの指貫", 52, { eDef: ["wind", 1], agi: 1,
    desc: "風で糸を紡ぐという機織りの指貫。風と指の呼吸を覚えた布は、礫を指の間に通さない。" }),
  G("g_lampkeeper_gloves", "灯火番の手袋", 56, { eDef: ["light", 1],
    desc: "聖堂の千の蝋燭を灯し続けた番人の手袋。灯心の温もりが染みた布は、闇の爪を火皿で受け止める。" }),
  G("g_tombrobber_gloves", "盗掘者の薄手袋", 60, { agi: 1, luk: 1,
    desc: "棺の留め金を音もなく外した盗掘者の薄手袋。罰当たりな器用さと、まだ捕まらない悪運の残りつき。" }),
  G("g_pikeman_gauntlets", "槍兵の柄革籠手", 63, { shape: "gauntlet", cls: ["fighter", "knight"],
    desc: "長槍の柄を握り込む形に固まった槍兵の籠手。突きの衝撃を受け続けた鉄は、握撃の重さが違う。" }),
  G("g_duskmoth_gloves", "宵蛾の鱗粉手袋", 67, { eDef: ["dark", 1],
    desc: "宵蛾の翅の鱗粉をまぶした手袋。指先は薄闇をまとい、聖光の下でも手の内が読まれない。" }),
  G("g_glasswright_gloves", "硝子師の精密手袋", 71, { agi: 2,
    desc: "吹き硝子を仕上げた職人の薄手袋。割れ物の限界を知る指先は、敵の守りの限界も同じ精度で測る。" }),
  G("g_tidesinger_gloves", "潮歌いの手袋", 75, { eDef: ["water", 1], mp: 3,
    desc: "潮の満ち引きを歌で操ったという巫女の手袋。指先が潮を覚えていて、火の波を引き潮に変える。" }),
  G("g_siegebreaker_gauntlets", "破城の大籠手", 79, { shape: "gauntlet", atkB: 3, cls: ["fighter", "knight"],
    desc: "城門を素手で叩いたという豪傑の大籠手。鉄拳の凹みは門の数だけあり、まだ増やしたがっている。" }),
  G("g_herbwitch_gloves", "薬草魔女の手袋", 83, { pie: 2, mp: 3,
    desc: "毒草と薬草を素手で摘み分けた魔女の手袋。生死の境を撫でてきた指先は、癒しの加減を心得る。" }),
  G("g_avalanche_gauntlets", "雪崩止めの籠手", 87, { shape: "gauntlet", eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "雪崩から小屋の柱を支え続けた男の籠手。山の重みを受けた鉄は、降りかかる土砂を支えて余る。" }),
  G("g_stormrigger_gloves", "嵐帆の手袋", 91, { eDef: ["wind", 1], agi: 1,
    desc: "嵐の中で帆綱を握った水夫の手袋。風の力と引き合った革は、突風の癖を掌で読んでしまう。" }),
  G("g_relicbearer_mitts", "聖遺物運びの白手袋", 95, { eDef: ["light", 1], mp: 4,
    desc: "聖遺物に素手で触れることを許された運び手の白手袋。祝福の移り香が、闇の爪を遠ざける。" }),
  G("g_boneknapper_gauntlets", "骨細工師の籠手", 98, { shape: "gauntlet", tint: "#d9d4bf", tintAmt: 0.25,
    desc: "巨獣の骨を削り続けた細工師の骨装籠手。骨の硬さを知り尽くした拳は、骨のある場所を正確に打つ。" }),
  G("g_emberjuggler_gloves", "火玉芸人の手袋", 102, { eDef: ["fire", 1], agi: 1,
    desc: "燃える玉を投げて稼いだ芸人の手袋。炎を玩具にした指先は、火のものの攻撃も曲芸のように受ける。" }),
  G("g_gravewright_gloves", "墓彫りの指貫", 106, { eDef: ["dark", 1], mp: 4,
    desc: "墓碑銘を彫り続けた石工の指貫。千の名を刻んだ指は死者に顔が利き、呪いの彫り直し方も知っている。" }),
  G("g_warsurgeon_gloves", "軍医の縫合手袋", 110, { pie: 3, hp: 5,
    desc: "戦場で千の傷を縫った軍医の手袋。命の閉じ方と開き方を知る指先は、祈りに確かな手応えを与える。" }),
  G("g_glacier_climber_gauntlets", "氷壁登りの籠手", 114, { shape: "gauntlet", eDef: ["water", 1], cls: ["fighter", "knight"],
    desc: "垂直の氷壁を素手同然で登った男の籠手。氷の冷たさに焼かれた鉄は、業火の熱を凍えさせる。" }),
  G("g_runescribe_gloves", "ルーン書きの指貫", 118, { int: 3, mp: 4, cls: ["mage", "bishop"],
    desc: "古代文字を羊皮紙に写し続けた写字生の指貫。指先に文字の力が残り、詠唱の綴りを勝手に正す。" }),
  G("g_stonewright_gauntlets", "石神像の手", 122, { shape: "gauntlet", eDef: ["earth", 1], spd: -1, hp: 8, cls: ["fighter", "knight"],
    desc: "崩れた石神像の両手をくり抜いた籠手。神の手だった石は、受け止めるという行為に誇りを持っている。" }),
  G("g_nightharvest_gloves", "夜摘みの手袋", 126, { eDef: ["dark", 1], agi: 2,
    desc: "月夜にだけ咲く毒花を摘んだ庭師の手袋。夜の花に好かれた指先は、闇の中で誰より正確に動く。" }),
  G("g_pyrekeeper_gauntlets", "火葬守の籠手", 130, { shape: "gauntlet", eDef: ["fire", 2], cls: ["fighter", "knight"],
    desc: "火葬の炎へ亡骸を送り込む役目の籠手。千の弔い火に手を入れた鉄に、焼け残る熱はもうない。" }),
  G("g_tempest_falconer_gloves", "嵐鷹匠の長手袋", 134, { eDef: ["wind", 1], agi: 2,
    desc: "嵐の中でしか飛ばない魔鷹を操った鷹匠の手袋。暴風と猛禽に鍛えられた腕は、嵐の中ほど冴える。" }),
  G("g_deepsea_diver_gauntlets", "深海潜りの籠手", 141, { shape: "gauntlet", eDef: ["water", 2], cls: ["fighter", "knight"],
    desc: "海溝の底の沈没船を漁った潜り屋の籠手。深海の水圧に握り潰されなかった鉄は、劫火を水泡と扱う。" }),
  G("g_lightweaver_gloves", "光織りの指貫", 149, { eDef: ["light", 1], mp: 6, cls: ["mage", "priest", "bishop"],
    desc: "朝の光を糸に紡いだという機織りの指貫。指先に夜明けの残りが絡みつき、闇は織り目に入れない。" }),
  G("g_dragonknuckle_gauntlets", "竜指骨の籠手", 153, { shape: "gauntlet", atkB: 6, cls: ["fighter", "knight"],
    desc: "古竜の指の骨をそのまま指甲にした籠手。岩を砂に変えた竜の握力が、拳の一打ごとに目を覚ます。" }),
  G("g_voidtouched_gloves", "虚空触れの手袋", 161, { eDef: ["dark", 2], mp: 6,
    desc: "虚空に触れて戻ってきた探求者の手袋。指先は半分この世にないため、聖光はそこを照らせない。" }),
  G("g_seraphfeather_mitts", "熾天羽の手袋", 173, { eDef: ["light", 2], pie: 4,
    desc: "天の戦士が落とした羽根を編んだ手袋。羽根は今も天上の白さを保ち、闇の爪は触れる前に燃え尽きる。" }),
  G("g_worldsmith_gauntlets", "世界鍛冶の作業籠手", 184, { shape: "gauntlet", atkB: 7, hp: 10,
    desc: "世界を鍛えた神の鍛冶場に残されていた作業籠手。万物を打った掌は、打てないものを知らない。" }),
  G("g_fateweaver_gloves", "運命織りの指貫", 196, { luk: 5, mp: 8,
    desc: "運命の糸を織る三女神の機から盗まれた指貫。指先が他人の糸の解れに触れ、勝敗の綾が見えてしまう。" }),
  G("g_carter_reins_gloves", "荷馬車引きの手袋", 7, {
    desc: "悪路の荷馬車を御し続けた馭者の手袋。手綱の食い込んだ掌は、御しがたいものの御し方を知る。" }),
  G("g_chandler_wax_gloves", "蝋燭職人の手袋", 11, { eDef: ["fire", 1],
    desc: "熱した蝋を素手で整形した職人の手袋。蝋の温度に慣れた指先は、多少の火傷を仕事と呼ぶ。" }),
  G("g_locksmith_gloves", "錠前師の指貫", 15, { agi: 1,
    desc: "精密な錠前を組み上げた職人の指貫。鍵穴の中を視るような指先は、敵の構えの隙間も探り当てる。" }),
  G("g_brewmaster_mitts", "醸造長の厚手袋", 19, {
    desc: "煮え立つ麦汁の大釜を扱った醸造長の手袋。湯気に蒸された革は厚く、刃も熱もよく受け止める。" }),
  G("g_courier_gloves", "急使の拍車手袋", 26, { agi: 1,
    desc: "昼夜駆け通した急使の手袋。手綱を握り続けた革は、速さのためなら何でも握る覚悟ができている。" }),
  G("g_torchrunner_gloves", "聖火走者の手袋", 34, { eDef: ["fire", 1],
    desc: "祭典の聖火を継いで走った走者の手袋。聖火を落とさなかった誇りが、炎の扱いを丁寧にさせる。" }),
  G("g_welldigger_gauntlets", "井戸掘りの籠手", 38, { shape: "gauntlet", eDef: ["earth", 1], cls: ["fighter", "knight"],
    desc: "固い地層を掘り抜いた井戸掘りの籠手。土の頑固さと付き合った鉄は、土塊の打撃に驚かない。" }),
  G("g_ferryrope_gloves", "渡し綱の手袋", 42, { eDef: ["water", 1],
    desc: "急流の渡し綱を手繰り続けた船頭の手袋。水の力と引き合った革は、流れに呑まれない握りを知る。" }),
  G("g_birdcatcher_gloves", "鳥刺しの軽手袋", 46, { agi: 1,
    desc: "飛び立つ小鳥を素手で捕えた鳥刺しの手袋。羽音より速く動く指先は、敵の手元の小細工も掴み取る。" }),
  G("g_sapper_gauntlets", "工兵の爆破籠手", 50, { shape: "gauntlet", eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "城壁の下に火薬を仕掛けた工兵の籠手。爆風に煽られ慣れた鉄は、炎の咆哮を作業の音と聞く。" }),
  G("g_silkmerchant_gloves", "絹商人の検分手袋", 54, { luk: 2,
    desc: "絹の真贋を指先ひとつで見抜いた商人の手袋。価値を見極める指は、戦機の真贋も同じように測る。" }),
  G("g_monk_prayer_wraps", "修道士の祈り布", 58, { pie: 2, mp: 2,
    desc: "数珠を繰り続けた修道士の手布。祈りの回数だけ柔らかくなった布は、掌の祈りを温かく保つ。" }),
  G("g_windmill_keeper_gloves", "風車守の手袋", 62, { eDef: ["wind", 1],
    desc: "嵐の夜に風車の羽根を縛った番人の手袋。暴れる風と格闘した革は、風の刃の掴み方を覚えた。" }),
  G("g_ossuary_keeper_gloves", "納骨堂番の手袋", 66, { eDef: ["dark", 1],
    desc: "幾千の骨を棚へ納め続けた番人の手袋。死者に触れ続けた革は、死者の側から信用されている。" }),
  G("g_vintner_press_gauntlets", "圧搾機の籠手", 70, { shape: "gauntlet", atkB: 2, cls: ["fighter", "knight"],
    desc: "葡萄圧搾機の重い梃子を回し続けた籠手。締め上げる力に特化した鉄は、握撃で骨を軋ませる。" }),
  G("g_icefisher_mitts", "氷上漁の手袋", 74, { eDef: ["water", 1],
    desc: "凍った湖に穴を開けて釣った漁師の厚手袋。指先の凍えと付き合った革は、炎の熱を冷やして通す。" }),
  G("g_belltower_gloves", "鐘楼守の革手袋", 78, { mp: 3,
    desc: "大鐘の綱を引き続けた鐘楼守の手袋。祈りの刻を告げた掌には、鐘の残響と敬虔さが染みている。" }),
  G("g_dunewalker_wraps", "砂漠民の手巻き", 82, { eDef: ["earth", 1],
    desc: "砂嵐の中を隊商と歩いた砂漠民の手巻き布。砂粒ひとつ通さない巻き方は、土塊の礫も同様に拒む。" }),
  G("g_lanternfish_gloves", "提灯魚革の手袋", 86, { eDef: ["light", 1], mp: 3,
    desc: "深海の提灯魚の発光革を張った手袋。指先がほの白く灯り、闇の中の手元仕事と魔除けを兼ねる。" }),
  G("g_warbanner_gauntlets", "軍旗持ちの籠手", 90, { shape: "gauntlet", hp: 6, cls: ["fighter", "knight"],
    desc: "倒れても旗を離さなかった旗手の籠手。軍旗を支えた握りは、何があろうと得物を取り落とさない。" }),
  G("g_asylum_keeper_gauntlets", "癲狂院の拘束籠手", 94, { shape: "gauntlet", cls: ["fighter", "knight"],
    desc: "暴れる患者を傷つけず押さえた看守の籠手。力の加減を知り尽くした鉄は、殺さない打撃も打てる。" }),
  G("g_sandglass_turner_gloves", "刻守りの手袋", 105, { agi: 2, luk: 1,
    desc: "都の大砂時計を反転させ続けた刻守りの手袋。時の重さを扱った指先は、一瞬の好機を取り逃さない。" }),
  G("g_thundersmith_gauntlets", "雷鍛冶の籠手", 138, { shape: "gauntlet", eAtk: ["wind", 1], cls: ["fighter", "knight"],
    desc: "落雷を素材に鍛冶をした変人の籠手。雷気の残る鉄拳は、打った敵の体に行き場のない痺れを残す。" }),
  G("g_moonpriestess_gloves", "月巫女の絹手袋", 145, { eDef: ["dark", 1], mp: 6, pie: 3, cls: ["priest", "bishop"],
    desc: "月の満ち欠けに祈りを捧げた巫女の絹手袋。夜の祝福を受けた指先は、闇を恐れず闇に守られる。" }),
  G("g_hellforge_gauntlets", "獄炉の黒籠手", 157, { shape: "gauntlet", eAtk: ["fire", 1], atkB: 5, cls: ["fighter", "knight"],
    desc: "地獄の炉で鍛えられたと噂される黒籠手。拳の芯に獄炎の熾火が眠り、打たれた鎧は内から焼ける。" }),
  G("g_archangel_vambraces", "大天使の腕甲", 165, { eDef: ["light", 2], hp: 10, cls: ["fighter", "knight", "priest"],
    desc: "翼を失った大天使が地上に残した腕甲。天上の白金は穢れを知らず、闇の刃は触れた先から薄れる。" }),
  G("g_chronomancer_gloves", "刻術師の指貫", 177, { agi: 3, mp: 8, cls: ["mage", "bishop"],
    desc: "時を半瞬だけ巻き戻せたという術師の指貫。指先が常に半瞬未来に動き、詠唱も回避も先回りする。" }),
  G("g_oathkeeper_gauntlets", "誓約者の白銀籠手", 188, { shape: "gauntlet", hp: 12, eDef: ["light", 1], cls: ["fighter", "knight"],
    desc: "決して破られなかった騎士の誓いを鋼に写した籠手。誓いを守り抜く力が、握る拳と仲間を守る。" }),
  G("g_plaguewarden_gloves", "検疫官の蝋引き手袋", 30, {
    desc: "疫病街区を検分した検疫官の蝋引き手袋。死の瘴気を遮った蝋膜は、迷宮の毒気にも申し分ない。" }),
  G("g_mirrorpolisher_gloves", "鏡磨きの手袋", 64, { eDef: ["light", 1],
    desc: "大聖堂の聖鏡を磨き続けた職人の手袋。光を曇りなく保った布は、自らも光の側に数えられている。" }),
  G("g_serpenthandler_gloves", "蛇使いの革手袋", 68, { agi: 1, luk: 1,
    desc: "毒蛇を素手で操った蛇使いの手袋。牙の届く間合いを知り尽くした革は、致命の一寸を外させる。" }),
  G("g_cannonmate_gauntlets", "砲手の装填籠手", 100, { shape: "gauntlet", eDef: ["fire", 1], cls: ["fighter", "knight"],
    desc: "熱した砲身に弾を込め続けた砲手の籠手。火薬と熱に焼かれた鉄は、爆ぜる炎を恐れず掴む。" }),
  G("g_shadowpuppeteer_gloves", "影絵師の黒指貫", 169, { eAtk: ["dark", 1], agi: 2,
    desc: "影絵で王を泣かせたという芸人の指貫。指先の影が勝手に演じ、敵は本体でない方を斬ってしまう。" }),
  G("g_giantslayer_grips", "巨人殺しの握り革", 192, { atkB: 8, hp: 10,
    desc: "巨人の指を登って首元へ達した英雄の握り革。掴んだものを離さない執念が、革の芯に縫い込まれている。" }),
];

export const ACCS2 = [
  R("r_luckpenny", "幸運の穴あき銅貨", "coin", 1, { luk: 1,
    desc: "処刑を免れた男が記念に穴を開けた銅貨。安酒場で千回語られた強運の、これが現物である。" }),
  R("r_milktooth_charm", "乳歯の御守り", "fang", 3, { hp: 3,
    desc: "初めての乳歯を銀線で巻いた母の御守り。子はもう大きいが、守ろうとする力は今も健在だ。" }),
  R("r_fisherman_floatring", "浮き玉の指輪", "ring", 5, { hp: 4,
    desc: "沈まない漁の浮き玉を削った指輪。沈まないという性根が宿り、嵌めた者を土壇場で浮かせる。" }),
  R("r_sparrow_skull_charm", "雀骨の御守り", "skull", 9, { agi: 1,
    desc: "雀の頭骨を蝋で固めた旅人の御守り。小さく素早いものの加護で、足取りがわずかに軽くなる。" }),
  R("r_tavern_dice", "酒場のいかさま賽", "orb", 13, { luk: 2,
    desc: "六しか出ないよう細工された賽。いかさま師は身を滅ぼしたが、賽の方は今日も六を出す。" }),
  R("r_candlestub_locket", "蝋燭残りのロケット", "amulet", 17, { mp: 3,
    desc: "聖堂の蝋燭の燃え残りを納めたロケット。祈りの火の残り香が、胸元で小さな魔力を灯す。" }),
  R("r_wolfear_charm", "狼耳の御守り", "fang", 21, { agi: 1, luk: 1,
    desc: "群れを率いた狼の耳を干した猟師の御守り。風上の気配に、持ち主の耳が狼のように動く。" }),
  R("r_ploughshare_ring", "鋤先の鉄輪", "ring", 24, { hp: 6,
    desc: "三代使われた鋤の先を打ち直した指輪。土と共に生きた鉄には、枯れないしぶとさが宿る。" }),
  R("r_chimes_of_warning", "風知らせの鈴", "bell", 28, { agi: 1,
    desc: "盗賊が忍び込む風の変化で鳴ったという軒先の鈴。腰に提げれば、背後の殺気で小さく鳴る。" }),
  R("r_inkwell_pendant", "書記の壺飾り", "vial", 32, { int: 2, mp: 3,
    desc: "宮廷書記が生涯使った小さなインク壺の首飾り。千の文書を記した墨の残りが、思考を黒々と冴えさせる。" }),
  R("r_ferry_toll_string", "渡し賃の銭緡", "coin", 36, { luk: 2,
    desc: "渡し守が客から受けた銭を編んだ緡。川を渡った人数分の道中安全が、銭の穴に通してある。" }),
  R("r_bearclaw_necklace", "熊爪の首飾り", "fang", 40, { hp: 8,
    desc: "冬眠前の大熊と素手で渡り合った猟師の戦利品。爪には熊の体力が残り、持ち主の命を太くする。" }),
  R("r_choirboy_bell", "聖歌隊の小鈴", "bell", 44, { pie: 2, mp: 3,
    desc: "声変わりで隊を去った少年が残した小鈴。最も澄んだ声の記憶が、祈りの音程を支えてくれる。" }),
  R("r_compass_locket", "狂わない羅針盤", "orb", 48, { luk: 2,
    desc: "迷宮の中でも狂わないという小さな羅針盤。針が指すのは北ではなく、持ち主の生き残る方角だ。" }),
  R("r_mole_paw_charm", "土竜手の御守り", "pouch", 52, { def: 3,
    desc: "地中を泳ぐ土竜の前足を干した御守り。土の加護で、地面から来る災いが半歩それる。" }),
  R("r_glassblower_orb", "硝子師の検査玉", "orb", 56, { int: 2,
    desc: "硝子の歪みを見抜くための完全な球。完璧をひとつ持ち歩く者は、不完全の見つけ方が早くなる。" }),
  R("r_almsgiver_ring", "施し手の指輪", "ring", 60, { pie: 3,
    desc: "貧者に施し続けた聖女の指輪。与える手に嵌められ続けた銀は、癒しの祈りに利息をつけて返す。" }),
  R("r_stormglass_vial", "嵐硝子の小瓶", "vial", 63, { agi: 2,
    desc: "天候を結晶で告げる嵐硝子の首飾り。荒れる前に必ず曇る瓶は、敵の殺気にも同じ反応をする。" }),
  R("r_huntinghorn_charm", "狩り角笛の飾り", "horn", 67, { atkB: 2,
    desc: "獲物を追い詰めた合図の角笛を小さく削った飾り。吹かずとも、狩りの昂ぶりが血に伝わる。" }),
  R("r_widow_ring", "後家の黒指輪", "ring", 71, { mp: 5,
    desc: "三人の夫を見送った後家の黒曜の指輪。死別の悲しみを三度吸った石は、魔の理に半分通じた。" }),
  R("r_pilgrimshell_amulet", "巡礼貝の首飾り", "amulet", 75, { hp: 8, pie: 2,
    desc: "聖地の浜で拾われる白い貝の首飾り。道中の加護のしるしで、貝の数だけ祈りが重なっている。" }),
  R("r_foxfire_lantern", "狐火の小提灯", "orb", 79, { eAtk: ["fire", 1],
    desc: "狐火を一匹だけ閉じ込めた豆提灯。火は逃げたがって暴れ、振るう得物にまで燃え移る。" }),
  R("r_tidebead_rosary", "潮珠の数珠", "amulet", 83, { eDef: ["water", 1], mp: 4,
    desc: "引き潮の夜にだけ採れる珠を連ねた数珠。珠の中で小さな潮が満ち引きし、火の災いを引かせる。" }),
  R("r_gallows_splinter", "絞首台のささくれ", "fang", 87, { eAtk: ["dark", 1],
    desc: "百人を吊った絞首台の木片。死の重みを支えた木は、振るう刃に処刑の冷たさを上乗せする。" }),
  R("r_sunchime", "陽光の風鈴", "bell", 91, { eDef: ["light", 1], mp: 4,
    desc: "正午の光を音に変えるという風鈴。澄んだ音が鳴るたび、足元の影から伸びる手が怯んで引っ込む。" }),
  R("r_minstrel_pick", "吟遊詩人の撥", "fang", 95, { luk: 3,
    desc: "王侯の宴で弾き続けた詩人の象牙の撥。場を読む才が染みていて、持ち主に最良の間を教える。" }),
  R("r_quicksilver_ring", "水銀の指輪", "ring", 98, { agi: 3,
    desc: "封じた水銀が絶えず巡る指輪。流れ続ける重さが腕の振りを先導し、手数がひとつ分速くなる。" }),
  R("r_owl_eye_pendant", "梟眼の首飾り", "eye", 102, { crit: 0.03, agi: 1,
    desc: "夜目の王と呼ばれた大梟の眼の首飾り。闇の中の急所が淡く浮かび、見えたものは外さない。" }),
  R("r_battlechaplain_book", "従軍司祭の小聖典", "book", 106, { pie: 4, mp: 5,
    desc: "戦場で千回開かれた手のひら大の聖典。ページは血と祈りで重く、開けば癒しの章が先に開く。" }),
  R("r_magnetite_charm", "磁鉄鉱の御守り", "ore", 110, { def: 5,
    desc: "天然の磁鉄鉱を磨いた御守り。鉄の刃は不思議とこれに吸い寄せられ、急所への一撃が逸れる。" }),
  R("r_embercoal_pendant", "残り火炭の首飾り", "gem", 114, { eAtk: ["fire", 1], hp: 6,
    desc: "決して消えない炭の欠片を銀枠に収めた首飾り。胸元の熱が血を温め、振るう得物に火を分ける。" }),
  R("r_grimoire_page_locket", "魔導書一頁のロケット", "book", 118, { int: 4, mp: 6,
    desc: "焼かれた魔導書から逃げ延びた一頁を納めたロケット。頁は読まれたがっていて、詠唱に割り込む。" }),
  R("r_galefeather_brooch", "風切羽の襟章", "horn", 122, { eDef: ["wind", 1], agi: 2,
    desc: "嵐を渡る大鳥の風切羽の襟章。羽根は今も飛ぶ気でいて、持ち主の体を風に乗せたがる。" }),
  R("r_kingsransom_coin", "身代金の金貨", "coin", 126, { luk: 3, hp: 8,
    desc: "捕虜の王の身代金に使われた刻印金貨。王ひとりの命と釣り合った金は、持ち主の命も重く扱う。" }),
  R("r_frostheart_gem", "霜心臓の宝石", "gem", 130, { eDef: ["fire", 2],
    desc: "凍死した氷の精の心臓が結晶した宝石。胸元の永久の冷気が、劫火を触れる先から鎮火させる。" }),
  R("r_warlock_pact_ring", "魔契の指輪", "ring", 134, { eAtk: ["dark", 1], mp: 6, cursed: true, align: "悪",
    desc: "悪魔との契約の証印たる黒い指輪。底知れぬ魔力が指から流れ込む——契約の解除条項は、ない。" }),
  R("r_seawitch_conch", "海魔女の法螺貝", "horn", 138, { eAtk: ["water", 1], mp: 5,
    desc: "嵐を呼んだ海魔女の小さな法螺貝。耳に当てれば海溝の声がして、唱える呪文に潮の重さが乗る。" }),
  R("r_saintsfinger_reliquary", "聖指の聖遺物匣", "amulet", 141, { pie: 5, hp: 8,
    desc: "奇跡を行った聖者の指骨を納めた小匣。指は今も祝福の形に曲がっていて、癒し手の指に力を貸す。" }),
  R("r_thundershard_pendant", "雷片の首飾り", "gem", 145, { eAtk: ["wind", 1], agi: 2,
    desc: "落雷が砂を硝子に変えた、その芯の結晶。胸元で微かに帯電し、得物の一閃に雷気を走らせる。" }),
  R("r_gravekeeper_lantern", "墓守の角灯", "orb", 149, { eDef: ["dark", 1], mp: 6,
    desc: "墓守が亡者を照らして鎮めた角灯。灯りは死者にだけ眩しく、彼らはこの光の輪を越えてこない。" }),
  R("r_basilisk_eye_amulet", "石化蜥蜴の眼", "eye", 153, { def: 8,
    desc: "視線で石を生んだ蜥蜴の眼の護符。残った睨みが敵の得物を一瞬石に変え、打撃の芯を鈍らせる。" }),
  R("r_phoenix_ashes_vial", "霊鳥の灰の小瓶", "vial", 157, { hp: 15,
    desc: "不死鳥が蘇った後の灰を詰めた小瓶。灰にはまだ蘇生の余熱が残り、持ち主の命を執念深くする。" }),
  R("r_moondrop_earring", "月雫の耳飾り", "gem", 161, { mp: 10,
    desc: "満月の夜にだけ滴るという月の雫の結晶。耳元で夜の魔力が満ち続け、詠唱の泉を涸らさない。" }),
  R("r_dragonheart_ember", "竜心臓の熾火", "gem", 165, { eAtk: ["fire", 1], hp: 10,
    desc: "討たれた竜の心臓に残った最後の熾火。胸元の鼓動が持ち主の心臓と重なり、血が竜の温度になる。" }),
  R("r_voidshard_ring", "虚空片の指輪", "ring", 169, { eAtk: ["dark", 2], mp: 8,
    desc: "世界の綻びから零れた「無」の欠片の指輪。嵌めた指の周りだけ世界が薄く、刃はそこを通って届く。" }),
  R("r_seraph_tear_pendant", "熾天の涙の首飾り", "gem", 173, { eDef: ["dark", 2], pie: 4,
    desc: "地上を憐れんだ天使の涙の結晶。胸元の白い光は決して翳らず、闇の手はこの涙の前で動けない。" }),
  R("r_leviathan_whisker", "海獣の髭の腕輪", "horn", 177, { eDef: ["water", 1], hp: 12,
    desc: "大海獣の髭を曲げた腕輪。深海の脈動を覚えた髭は、持ち主の脈を深く太く整え直す。" }),
  R("r_worldserpent_scale", "世界蛇の鱗", "gem", 184, { def: 10, hp: 10,
    desc: "世界を呑むという大蛇の剥がれ鱗。世界ひとつ分の執念で鍛えられた鱗は、滅多なことでは砕けない。" }),
  R("r_godslayer_shackle", "神殺しの枷輪", "ring", 188, { atkB: 6, cursed: true, align: "悪",
    desc: "神を殺した罪人を縛った枷の片輪。罪の重さがそのまま腕力に変わる——外し方は神しか知らない。" }),
  R("r_genesis_bell", "創世の鈴", "bell", 192, { mp: 12, pie: 5,
    desc: "世界が始まる合図に鳴らされたという鈴。音はもう誰にも聞こえないが、万物が今も従おうとする。" }),
  R("r_eternity_hourglass", "永遠の砂時計", "orb", 196, { luk: 4, agi: 3,
    desc: "砂が決して落ちきらない小さな砂時計。持ち主の最期の一瞬を量り続け、その到来を先送りにする。" }),
  R("r_beggar_bowl_charm", "托鉢椀の飾り", "pouch", 7, { luk: 1, pie: 1,
    desc: "生涯施しで生きた行者の小さな椀。空のまま満ちているという椀は、持ち主の運を静かに満たす。" }),
  R("r_sundial_brooch", "日時計の襟章", "coin", 11, { agi: 1,
    desc: "懐中日時計を兼ねた襟章。時を読み続けた盤面は、踏み込むべき一瞬を影の傾きで教える。" }),
  R("r_canary_cage_charm", "炭鉱カナリアの籠", "bell", 15, { luk: 1, hp: 3,
    desc: "坑夫の命を百度救ったカナリアの小さな籠。鳥はいないが、危険を先に鳴く性分は籠に残った。" }),
  R("r_ropewalker_sash", "綱渡りの帯紐", "cloth", 38, { agi: 2,
    desc: "大聖堂の塔の間を渡った綱渡り師の腰紐。落ちなかった千歩の平衡感覚が、結び目に宿っている。" }),
  R("r_executioner_hourring", "刑吏の刻印輪", "ring", 85, { atkB: 3,
    desc: "処刑の刻限を告げた刑吏の鉄輪。振り下ろす合図を出し続けた指は、一撃の重みを知っている。" }),
  R("r_alchemist_prism", "錬金術師の分光石", "gem", 93, { int: 3, mp: 4,
    desc: "光を七色に裁いた錬金術師の角柱石。世界を分解して視る癖が移り、術式の組み立てが速くなる。" }),
  R("r_shipinabottle", "瓶中の帆船", "vial", 108, { luk: 3,
    desc: "瓶の中で帆を張る精巧な小船。嵐の夜には瓶の中も時化るといい、本物の災難を小さく肩代わりする。" }),
  R("r_warhorn_mouthpiece", "突撃角笛の吹き口", "horn", 116, { atkB: 4, hp: 5,
    desc: "百の突撃を告げた角笛の吹き口。咥えずとも進軍の血の昂ぶりが伝い、退く足を前に向ける。" }),
  R("r_oracle_smoke_vial", "神託の煙の小瓶", "vial", 132, { int: 4, luk: 2,
    desc: "神殿の巫女が吸った神託の煙を封じた瓶。栓越しに漏れる一筋が、半瞬先の景色を見せてくれる。" }),
  R("r_crownjewel_shard", "砕けた王冠の宝玉", "gem", 181, { mp: 10, luk: 3,
    desc: "簒奪の夜に砕かれた王冠の中央宝玉。王権の残滓が宿り、持つ者の号令に玉座の重みが乗る。" }),
];
