// LR (レジェンドレア・専用装備) カタログ — id prefix: lr_
//
// 各職に1つだけ許された「専用武器」。指定職しか装備できないが、ドロップ帯より約5ランク
// 上 (LR5 ≒ 表示ランクR10相当) の破格の性能を持つ。宝箱を開けた瞬間に flat 2% で出現する
// 専用ドロップ層 (game.js pickLR) でのみ手に入る。
//
// 強さの基準: 戦士LR5「フランベルジュ」= 長剣 ATK+90。各カテゴリは W_MUL で按分する
//   ls90 / dg70 / kt95 / ax104 / mc99 / sp94 / bw83 / st(自動 INT≒59・ATK≒64)
// LR装飾品 (鬼神/魔神の腕輪) は %補正 (recalc の乗算レイヤー) を持つ全職共通の品。
//
// id は append-only。lr ティア (5/10/15/20) は将来 LR10〜LR20 を順次追加する。
import { W, R } from "./defs.js";

// LR フラグ付与: tier=5/10/15/20, forJob=指定職 (装飾品は省略=全職共通)
function lr(item, tier, forJob) {
  item.lr = tier;
  item.exclusive = true; // 通常 lootLv 抽選から除外
  if (forJob) item.forJob = forJob;
  return item;
}

export const LR_ITEMS = [
  // ===== LR5 専用武器 (全36職 各1) =====
  lr(W("lr_fighter5", "フランベルジュ", "ls", 90, { cls: ["fighter"], atk: 90, eAtk: ["fire", 1],
    desc: "炎をまとう波打つ刃の大剣。揺らめく刀身が斬撃に灼熱を重ね、戦士の握りにだけ完璧な均衡で応える伝説の業物。" }), 5, "fighter"),
  lr(W("lr_knight5", "騎士王の聖剣", "ls", 90, { cls: ["knight"], atk: 90, eAtk: ["light", 1],
    desc: "亡き騎士王が誓いとともに振るった聖剣。刃に宿る光が不浄を退け、盾を取る者の手にこそ真価を発揮する。" }), 5, "knight"),
  lr(W("lr_priest5", "聖光の戦鎚", "mc", 90, { cls: ["priest"], atk: 99, eAtk: ["light", 1],
    desc: "打ち下ろすたびに聖なる光が爆ぜる祝福の戦鎚。僧侶の祈りに呼応して輝きを増し、闇に巣食う者を浄化で砕く。" }), 5, "priest"),
  lr(W("lr_mage5", "灼熱の魔杖", "st", 90, { cls: ["mage"], eAtk: ["fire", 1],
    desc: "杖頭の宝珠に永遠の業火を封じた魔導士の杖。触れた術式が炎を帯び、唱える攻撃呪文を圧倒的な威力で解き放つ。" }), 5, "mage"),
  lr(W("lr_thief5", "影牙の短剣", "dg", 90, { cls: ["thief"], atk: 70, eAtk: ["dark", 1],
    desc: "光を返さぬ闇鉄の短剣。盗賊の手首に沿って消え、気配を殺したまま影から急所だけを正確に喰い破る。" }), 5, "thief"),
  lr(W("lr_bishop5", "二理の聖杖", "st", 90, { cls: ["bishop"], eAtk: ["light", 1],
    desc: "攻と癒、二つの理を一本に束ねた法杖。司教だけが相反する流れを同時に御し、光の力で術のすべてを底上げする。" }), 5, "bishop"),
  lr(W("lr_samurai5", "妖桜丸", "kt", 90, { cls: ["samurai"], atk: 95, eAtk: ["wind", 1],
    desc: "抜けば刃に桜吹雪のごとき疾風をまとう妖刀。侍の踏み込みに乗って風を裂き、一閃のうちに幾人もを斬り伏せる。" }), 5, "samurai"),
  lr(W("lr_berserker5", "血染めの巨斧", "ax", 90, { cls: ["berserker"], atk: 104, eAtk: ["fire", 1],
    desc: "無数の返り血を吸って黒ずんだ巨斧。狂戦士の怒りに共鳴して刃が熱を帯び、振るうたびに破壊の衝動を煽り立てる。" }), 5, "berserker"),
  lr(W("lr_hunter5", "風裂きの猟弓", "bw", 90, { cls: ["hunter"], atk: 83, eAtk: ["wind", 1],
    desc: "霊樹から削り出した長弓。狩人が弦を引くと風が自ら矢を捕らえ、失速も逸れもなく千里の獲物を射抜く。" }), 5, "hunter"),
  lr(W("lr_shadow5", "宵闇の暗刃", "dg", 90, { cls: ["shadow"], atk: 70, eAtk: ["dark", 1],
    desc: "黄昏時にしか鍛えられぬ闇鉄の刃。暗殺者の手に渡ると周囲の影を喰らい、持ち主の輪郭ごと闇に溶かしてしまう。" }), 5, "shadow"),
  lr(W("lr_paladin5", "聖盟の剣", "ls", 90, { cls: ["paladin"], atk: 90, eAtk: ["light", 1],
    desc: "聖典の頁に記された武装をそのまま鍛えた剣。聖騎士が掲げると刃から経文が溢れ、不浄をことごとく焼き払う。" }), 5, "paladin"),
  lr(W("lr_guardian5", "不動の鉄槌", "mc", 90, { cls: ["guardian"], atk: 99, eAtk: ["earth", 1],
    desc: "大地の重みを宿した守護騎士の戦鎚。一打ごとに足元から岩の加護が立ち上り、味方を守る壁となって敵を圧し潰す。" }), 5, "guardian"),
  lr(W("lr_spellblade5", "魔刃・烈火", "kt", 90, { cls: ["spellblade"], atk: 95, eAtk: ["fire", 1],
    desc: "魔力を炎へ変えて刃に纏わせる魔法剣士の刀。斬撃と呪文が一体となり、振り抜いた軌跡に紅蓮の尾を曳く。" }), 5, "spellblade"),
  lr(W("lr_monk5", "羅漢の金剛杵", "mc", 90, { cls: ["monk"], atk: 99, eAtk: ["wind", 1],
    desc: "悟りに至った武僧が握ったと伝わる金剛杵。打ち込むたびに疾風が渦巻き、気の力を乗せた一撃が鎧ごと相手を貫く。" }), 5, "monk"),
  lr(W("lr_hexer5", "呪詛の黒杖", "st", 90, { cls: ["hexer"], eAtk: ["dark", 1],
    desc: "おびただしい怨念を吸い込んだ漆黒の杖。呪術師の手に握られると蓄えた呪詛が牙を剥き、敵を内側から蝕んでいく。" }), 5, "hexer"),
  lr(W("lr_hermit5", "仙木の杖", "st", 90, { cls: ["hermit"], eAtk: ["earth", 1],
    desc: "千年を生きた霊木から削り出した隠修士の杖。大地の気脈と通じ、唱える術に山のごとき静かな力を与える。" }), 5, "hermit"),
  lr(W("lr_brigand5", "義賊の隠し刃", "dg", 90, { cls: ["brigand"], atk: 70, eAtk: ["wind", 1],
    desc: "袖に仕込んで風のように抜き放つ義賊の刃。軽やかな身のこなしと一体になり、狙った相手だけを音もなく仕留める。" }), 5, "brigand"),
  lr(W("lr_arcthief5", "魔導の盗刃", "dg", 90, { cls: ["arcthief"], atk: 70, eAtk: ["dark", 1],
    desc: "魔力を帯びた刃に呪印を刻んだ魔盗賊の短刀。刺すと同時に相手の魔力を掠め取り、闇へ溶けて逃げ去る。" }), 5, "arcthief"),
  lr(W("lr_crusader5", "聖戦の大剣", "ls", 90, { cls: ["crusader"], atk: 90, eAtk: ["light", 1],
    desc: "聖戦の旗のもとで振るわれた巨大な聖剣。聖戦士が掲げると刃が白く燃え上がり、邪悪を薙ぎ倒す光の刃となる。" }), 5, "crusader"),
  lr(W("lr_battlemage5", "爆炎の魔剣", "ls", 90, { cls: ["battlemage"], atk: 90, eAtk: ["fire", 1],
    desc: "刀身に炎の呪文式を編み込んだ魔闘士の剣。斬りつけた瞬間に式が暴発し、斬撃と爆炎を同時に叩き込む。" }), 5, "battlemage"),
  lr(W("lr_darkknight5", "冥黒の魔剣", "ls", 90, { cls: ["darkknight"], atk: 90, eAtk: ["dark", 1],
    desc: "持ち主の生気を糧に力を増す呪われた魔剣。魔騎士の闇に染まった魂と契りを交わし、斬った相手の命を喰らう。" }), 5, "darkknight"),
  lr(W("lr_templar5", "神殿の聖鎚", "mc", 90, { cls: ["templar"], atk: 99, eAtk: ["light", 1],
    desc: "神殿の祭壇を守るために鋳られた聖なる戦鎚。神殿騎士の信仰に応えて輝き、振り下ろす一撃で結界ごと敵を打ち砕く。" }), 5, "templar"),
  lr(W("lr_exorcist5", "祓いの銀刃", "dg", 90, { cls: ["exorcist"], atk: 70, eAtk: ["light", 1],
    desc: "祓魔の真言を刻んだ銀の短刀。祓魔師が構えると刃が清浄な光を放ち、憑いた悪霊を肉ごと斬り離して浄める。" }), 5, "exorcist"),
  lr(W("lr_warden5", "護法の杖", "st", 90, { cls: ["warden"], eAtk: ["earth", 1],
    desc: "結界の理を封じた護法師の杖。大地の守りの呪を編み、味方を覆う障壁を張りながら攻めの術をも研ぎ澄ます。" }), 5, "warden"),
  lr(W("lr_arcanist5", "秘奥の宝杖", "st", 90, { cls: ["arcanist"], eAtk: ["water", 1],
    desc: "秘術の奥義を結晶化した宝珠を頂く杖。秘術師の指先に応えて澄んだ水の魔力を巡らせ、呪文の精度を極限まで高める。" }), 5, "arcanist"),
  lr(W("lr_inquisitor5", "断罪の鉄槌", "mc", 90, { cls: ["inquisitor"], atk: 99, eAtk: ["fire", 1],
    desc: "異端を裁くために鋳られた審問官の鉄槌。罪を焼く炎が頭に宿り、振り下ろすたびに咎人を業火で断罪する。" }), 5, "inquisitor"),
  lr(W("lr_archbishop5", "大聖堂の錫杖", "st", 90, { cls: ["archbishop"], eAtk: ["light", 1],
    desc: "大聖堂の祭壇に安置されてきた荘厳な錫杖。大司教が振るうと環が天上の音色で鳴り、聖なる光で奇跡を増幅する。" }), 5, "archbishop"),
  lr(W("lr_ascetic5", "修験の金剛杵", "mc", 90, { cls: ["ascetic"], atk: 99, eAtk: ["earth", 1],
    desc: "幾度もの荒行に耐えた修験者の金剛杵。大地に根ざした不屈の気を宿し、打ち込むたびに山が崩れるような重みを伝える。" }), 5, "ascetic"),
  lr(W("lr_hero5", "勇者の聖剣", "ls", 90, { cls: ["hero"], atk: 90, eAtk: ["light", 1],
    desc: "選ばれし者だけが抜けるという伝説の聖剣。勇者の手に握られた刹那、刃は黄金に燃え立ち、いかなる闇をも斬り裂く。" }), 5, "hero"),
  lr(W("lr_asura5", "修羅の妖剣", "ls", 90, { cls: ["asura"], atk: 90, eAtk: ["fire", 1],
    desc: "戦いの果てに鬼と化した者が遺した妖剣。修羅の闘気に呼応して刃が紅蓮に染まり、振るうほどに殺意を研ぎ澄ます。" }), 5, "asura"),
  lr(W("lr_dragonknight5", "竜殺しの剣", "ls", 90, { cls: ["dragonknight"], atk: 90, eAtk: ["wind", 1],
    desc: "古竜の鱗をも断つために鍛えられた竜騎士の剣。刃に竜を狩る風の加護が宿り、空を駆ける巨竜の急所を確実に貫く。" }), 5, "dragonknight"),
  lr(W("lr_necromancer5", "死霊の骨杖", "st", 90, { cls: ["necromancer"], eAtk: ["dark", 1],
    desc: "無数の死者の骨を束ねて作った死霊術師の杖。冥府と通じて尽きせぬ闇の魔力を引き出し、攻撃呪文を死の力で満たす。" }), 5, "necromancer"),
  lr(W("lr_sage5", "賢者の天杖", "st", 90, { cls: ["sage"], eAtk: ["water", 1],
    desc: "天と地の理を究めた賢者の杖。澄んだ水の魔力を湛え、攻めの術にも癒しの術にも淀みなく力を通す万能の法具。" }), 5, "sage"),
  lr(W("lr_cardinal5", "枢機卿の聖杖", "st", 90, { cls: ["cardinal"], eAtk: ["light", 1],
    desc: "教権の頂に立つ枢機卿の聖杖。掲げれば聖堂の鐘が遠く鳴り響くといい、注がれた祈りを天上の光へと変えて放つ。" }), 5, "cardinal"),
  lr(W("lr_archmage5", "大魔導の星杖", "st", 90, { cls: ["archmage"], eAtk: ["dark", 1],
    desc: "天の星々と契約した大魔導の杖。杖頭に小さな暗黒星を宿し、世界の理を歪めるほどの魔力を攻撃呪文へ注ぎ込む。" }), 5, "archmage"),
  lr(W("lr_chaplain5", "護教の聖鎚", "mc", 90, { cls: ["chaplain"], atk: 99, eAtk: ["light", 1],
    desc: "信徒を守る盾として鋳られた護教官の戦鎚。掲げると淡い光の膜が味方を包み、振るえば不浄を打ち払う聖光が爆ぜる。" }), 5, "chaplain"),

  // ===== LR 装飾品 (全職共通・%補正) =====
  lr(R("lr_oni", "鬼神の腕輪", "ring", 90, { mult: { hp: 0.2, atk: 0.2 }, tint: "#cf3b34",
    desc: "鬼神の魂を封じた猛々しい腕輪。嵌めた者の肉体に鬼の膂力が漲り、生命力と一撃の重みを二割も底上げする。" }), 5),
  lr(R("lr_majin", "魔神の腕輪", "amulet", 90, { mult: { mp: 0.2, int: 0.2, pie: 0.2 }, tint: "#7a4ac0",
    desc: "魔神の知を封じた妖しい腕輪。嵌めた者の魂に魔の叡智が流れ込み、魔力と攻・癒の術の冴えを二割も引き上げる。" }), 5),

  // ===== LR10 専用武器 (全36職 各1) =====
  // LR5 の覚醒・真打。隠しlv145 (≒R15帯の派生ステ)、ATK = 180×W_MUL、属性は Lv2(◎)。
  lr(W("lr_fighter10", "真・フランベルジュ", "ls", 145, { cls: ["fighter"], atk: 180, eAtk: ["fire", 2],
    desc: "フランベルジュが秘めた炎を解き放った真の姿。波打つ刀身が業火をまとい、戦士の一閃が触れたものを残らず焼き斬る。" }), 10, "fighter"),
  lr(W("lr_knight10", "騎士王の覇聖剣", "ls", 145, { cls: ["knight"], atk: 180, eAtk: ["light", 2],
    desc: "亡き騎士王の聖剣が覇道に覚めた姿。刃に宿る光が天を衝き、盾を取る者の守りの誓いを無敵の刃へと変える。" }), 10, "knight"),
  lr(W("lr_priest10", "大聖光の破魔鎚", "mc", 145, { cls: ["priest"], atk: 198, eAtk: ["light", 2],
    desc: "聖光の戦鎚が極まった破魔の鎚。打ち下ろすたびに大聖光が炸裂し、僧侶の祈りに応えて不浄を根こそぎ浄め払う。" }), 10, "priest"),
  lr(W("lr_mage10", "業炎の大魔杖", "st", 145, { cls: ["mage"], eAtk: ["fire", 2],
    desc: "灼熱の魔杖が宿す業火を極めた大杖。杖頭の永炎が世界を焼く理を映し、魔導士の唱える炎の呪文を極限まで燃え上げる。" }), 10, "mage"),
  lr(W("lr_thief10", "影牙王の双刃", "dg", 145, { cls: ["thief"], atk: 140, eAtk: ["dark", 2],
    desc: "影牙の短剣が対の刃へと覚めた双刃。盗賊の手首に沿って二度消え、気配の途切れた闇から急所だけを二重に抉る。" }), 10, "thief"),
  lr(W("lr_bishop10", "三理の大聖杖", "st", 145, { cls: ["bishop"], eAtk: ["light", 2],
    desc: "二理の聖杖に守の理を加えた大法杖。攻・癒・守の三つを一身に御し、司教の手の中で術のすべてを高みへ導く。" }), 10, "bishop"),
  lr(W("lr_samurai10", "真・妖桜丸", "kt", 145, { cls: ["samurai"], atk: 191, eAtk: ["wind", 2],
    desc: "妖桜丸が真の刃へと冴え渡った姿。抜けば桜吹雪が暴風と化し、侍の踏み込みに乗って一閃のうちに敵陣を薙ぎ払う。" }), 10, "samurai"),
  lr(W("lr_berserker10", "血咆の大巨斧", "ax", 145, { cls: ["berserker"], atk: 209, eAtk: ["fire", 2],
    desc: "血染めの巨斧が咆哮を上げる究極の姿。狂戦士の怒りに呼応して刃が紅蓮に燃え、振るうたびに破壊の渦を巻き起こす。" }), 10, "berserker"),
  lr(W("lr_hunter10", "烈風裂きの神猟弓", "bw", 145, { cls: ["hunter"], atk: 166, eAtk: ["wind", 2],
    desc: "風裂きの猟弓が神域に至った姿。狩人が弦を引けば烈風が矢を捕らえて加速し、地平の彼方の獲物すら過たず射抜く。" }), 10, "hunter"),
  lr(W("lr_shadow10", "深宵の暗刃", "dg", 145, { cls: ["shadow"], atk: 140, eAtk: ["dark", 2],
    desc: "宵闇の暗刃が深淵の宵へと沈んだ姿。暗殺者の手に渡ると周囲の闇を喰らい尽くし、刃も持ち主も完全に消し去る。" }), 10, "shadow"),
  lr(W("lr_paladin10", "聖盟王の剣", "ls", 145, { cls: ["paladin"], atk: 180, eAtk: ["light", 2],
    desc: "聖盟の剣が盟主の証へと昇華した姿。聖騎士が掲げると経文が奔流となって溢れ、視界のすべての不浄を焼き払う。" }), 10, "paladin"),
  lr(W("lr_guardian10", "不動明王の鉄槌", "mc", 145, { cls: ["guardian"], atk: 198, eAtk: ["earth", 2],
    desc: "不動の鉄槌が明王の威を帯びた姿。一打ごとに大地が割れて岩の加護が噴き上がり、守護騎士は揺るがぬ壁となる。" }), 10, "guardian"),
  lr(W("lr_spellblade10", "魔刃・劫火", "kt", 145, { cls: ["spellblade"], atk: 191, eAtk: ["fire", 2],
    desc: "魔刃・烈火が劫火へと極まった姿。斬撃と呪文が完全に溶け合い、振り抜いた軌跡に世界を焼く紅蓮の尾を曳く。" }), 10, "spellblade"),
  lr(W("lr_monk10", "阿羅漢の大金剛杵", "mc", 145, { cls: ["monk"], atk: 198, eAtk: ["wind", 2],
    desc: "羅漢の金剛杵が阿羅漢の境地に達した姿。打ち込むたびに疾風が渦巻き、武僧の気の一撃が鎧ごと相手を打ち砕く。" }), 10, "monk"),
  lr(W("lr_hexer10", "大呪詛の黒杖", "st", 145, { cls: ["hexer"], eAtk: ["dark", 2],
    desc: "呪詛の黒杖が万の怨念を束ねた大杖。呪術師の手に握られると蓄えた呪詛が奔流となり、敵を内側から確実に蝕み崩す。" }), 10, "hexer"),
  lr(W("lr_hermit10", "大仙木の杖", "st", 145, { cls: ["hermit"], eAtk: ["earth", 2],
    desc: "仙木の杖が万年を経た霊木へと育った大杖。大地の気脈と深く通じ、隠修士の術に山岳のごとき揺るがぬ力を与える。" }), 10, "hermit"),
  lr(W("lr_brigand10", "義賊王の隠し刃", "dg", 145, { cls: ["brigand"], atk: 140, eAtk: ["wind", 2],
    desc: "義賊の隠し刃が義賊王の証となった姿。風のように抜き放たれ、軽やかな身のこなしと一体で狙った相手だけを仕留める。" }), 10, "brigand"),
  lr(W("lr_arcthief10", "大魔導の盗刃", "dg", 145, { cls: ["arcthief"], atk: 140, eAtk: ["dark", 2],
    desc: "魔導の盗刃が大魔導の呪印を帯びた姿。刺すと同時に相手の魔力を根こそぎ掠め取り、闇へ溶けて音もなく逃げ去る。" }), 10, "arcthief"),
  lr(W("lr_crusader10", "聖戦王の大剣", "ls", 145, { cls: ["crusader"], atk: 180, eAtk: ["light", 2],
    desc: "聖戦の大剣が聖戦王の旗剣へと昇華した姿。掲げれば刃が白く燃え立ち、聖戦士の進む道の邪悪をことごとく薙ぎ倒す。" }), 10, "crusader"),
  lr(W("lr_battlemage10", "劫炎の魔剣", "ls", 145, { cls: ["battlemage"], atk: 180, eAtk: ["fire", 2],
    desc: "爆炎の魔剣が劫炎を宿した姿。刀身の呪文式が暴走し、魔闘士の斬撃のたびに世界を焼く爆炎が炸裂して敵を呑む。" }), 10, "battlemage"),
  lr(W("lr_darkknight10", "冥王の魔剣", "ls", 145, { cls: ["darkknight"], atk: 180, eAtk: ["dark", 2],
    desc: "冥黒の魔剣が冥王の力に覚めた姿。魔騎士の闇と完全に契り、斬った相手の命を喰らって振るう者をさらに強くする。" }), 10, "darkknight"),
  lr(W("lr_templar10", "大神殿の聖鎚", "mc", 145, { cls: ["templar"], atk: 198, eAtk: ["light", 2],
    desc: "神殿の聖鎚が大神殿の祭具へと極まった姿。神殿騎士の信仰に応えて眩く輝き、結界ごと敵を打ち砕く聖光を放つ。" }), 10, "templar"),
  lr(W("lr_exorcist10", "大祓いの銀刃", "dg", 145, { cls: ["exorcist"], atk: 140, eAtk: ["light", 2],
    desc: "祓いの銀刃が大祓の真言を帯びた姿。祓魔師が構えると刃が清浄な光の奔流を放ち、憑いた悪霊を肉ごと斬り浄める。" }), 10, "exorcist"),
  lr(W("lr_warden10", "大護法の杖", "st", 145, { cls: ["warden"], eAtk: ["earth", 2],
    desc: "護法の杖が大結界の理を宿した姿。護法師の唱える障壁を岩盤のごとく堅くし、なお攻めの術をも極限まで研ぎ澄ます。" }), 10, "warden"),
  lr(W("lr_arcanist10", "真・秘奥の宝杖", "st", 145, { cls: ["arcanist"], eAtk: ["water", 2],
    desc: "秘奥の宝杖が真の奥義を解き放った姿。宝珠が澄んだ水の理を巡らせ、秘術師の呪文の精度と威力を極限まで高める。" }), 10, "arcanist"),
  lr(W("lr_inquisitor10", "大断罪の業鎚", "mc", 145, { cls: ["inquisitor"], atk: 198, eAtk: ["fire", 2],
    desc: "断罪の鉄槌が業火を宿した審判の鎚。罪を焼く炎が燃え盛り、審問官が振り下ろすたびに咎人を業火で完全に断罪する。" }), 10, "inquisitor"),
  lr(W("lr_archbishop10", "大聖堂の大錫杖", "st", 145, { cls: ["archbishop"], eAtk: ["light", 2],
    desc: "大聖堂の錫杖が荘厳を極めた大錫杖。大司教が振るうと環が天上の和音で鳴り響き、聖なる光で奇跡を圧倒的に増幅する。" }), 10, "archbishop"),
  lr(W("lr_ascetic10", "大修験の金剛杵", "mc", 145, { cls: ["ascetic"], atk: 198, eAtk: ["earth", 2],
    desc: "修験の金剛杵が大荒行を経て極まった姿。大地に根ざした不屈の気を宿し、修験者の一打が山をも崩す重みを伝える。" }), 10, "ascetic"),
  lr(W("lr_hero10", "真・勇者の聖剣", "ls", 145, { cls: ["hero"], atk: 180, eAtk: ["light", 2],
    desc: "勇者の聖剣が真の力を解き放った姿。勇者の手の中で黄金の光が天を貫き、いかなる深淵の闇をも一刀のもとに斬り裂く。" }), 10, "hero"),
  lr(W("lr_asura10", "阿修羅の妖剣", "ls", 145, { cls: ["asura"], atk: 180, eAtk: ["fire", 2],
    desc: "修羅の妖剣が阿修羅の闘気に覚めた姿。握る者の殺意に応えて刃が紅蓮に燃え盛り、振るうほどに止まらぬ修羅と化す。" }), 10, "asura"),
  lr(W("lr_dragonknight10", "竜帝殺しの剣", "ls", 145, { cls: ["dragonknight"], atk: 180, eAtk: ["wind", 2],
    desc: "竜殺しの剣が竜帝すら屠る神剣へと至った姿。竜を狩る風の加護が極まり、空を統べる竜帝の急所すら過たず貫く。" }), 10, "dragonknight"),
  lr(W("lr_necromancer10", "大死霊の骨杖", "st", 145, { cls: ["necromancer"], eAtk: ["dark", 2],
    desc: "死霊の骨杖が万骨を束ねた大杖。冥府の門と深く通じて尽きせぬ闇の魔力を引き出し、死霊術師の呪文を死の力で満たす。" }), 10, "necromancer"),
  lr(W("lr_sage10", "大賢者の天杖", "st", 145, { cls: ["sage"], eAtk: ["water", 2],
    desc: "賢者の天杖が天地の理を極めた大杖。澄んだ水の魔力を満々と湛え、賢者の攻めにも癒しにも淀みなく無限の力を通す。" }), 10, "sage"),
  lr(W("lr_cardinal10", "教皇の聖杖", "st", 145, { cls: ["cardinal"], eAtk: ["light", 2],
    desc: "枢機卿の聖杖が教皇の権を帯びた聖杖。掲げれば天上の鐘が鳴り渡り、注がれた祈りを世界を照らす聖光へと変える。" }), 10, "cardinal"),
  lr(W("lr_archmage10", "大魔導の極星杖", "st", 145, { cls: ["archmage"], eAtk: ["dark", 2],
    desc: "大魔導の星杖が極星の力に覚めた杖。杖頭の暗黒星が世界の理を歪め、大魔導の攻撃呪文を破滅的な威力で解き放つ。" }), 10, "archmage"),
  lr(W("lr_chaplain10", "大護教の聖鎚", "mc", 145, { cls: ["chaplain"], atk: 198, eAtk: ["light", 2],
    desc: "護教の聖鎚が大いなる守りを宿した姿。掲げると味方を眩い光の膜が包み、振るえば不浄を一掃する聖光が爆ぜる。" }), 10, "chaplain"),

  // ===== LR15 専用武器 (全36職 各1) =====
  // LR10 を極めた神威の形。隠しlv195 (≒R20帯の派生ステ)、ATK = 270×W_MUL、属性は Lv2(◎)。
  lr(W("lr_fighter15", "極・フランベルジュ", "ls", 195, { cls: ["fighter"], atk: 270, eAtk: ["fire", 2],
    desc: "フランベルジュが極限まで研ぎ澄まされた究極の姿。波打つ刀身が太陽のごとき業火を噴き、戦士の一閃が万物を斬り焼く。" }), 15, "fighter"),
  lr(W("lr_knight15", "騎士神王の聖剣", "ls", 195, { cls: ["knight"], atk: 270, eAtk: ["light", 2],
    desc: "騎士王の覇聖剣が神域に至った姿。刃の光が天地を照らし、盾を取る者の守りの誓いを神威の刃へと昇華させる。" }), 15, "knight"),
  lr(W("lr_priest15", "極光の破魔鎚", "mc", 195, { cls: ["priest"], atk: 297, eAtk: ["light", 2],
    desc: "大聖光の破魔鎚が極光を宿した究極の鎚。打ち下ろすたびに極まった聖光が世界を白く染め、不浄を残らず浄め払う。" }), 15, "priest"),
  lr(W("lr_mage15", "獄炎の神魔杖", "st", 195, { cls: ["mage"], eAtk: ["fire", 2],
    desc: "業炎の大魔杖が獄炎を宿した神域の杖。杖頭の永炎が地獄の業火と化し、魔導士の唱える炎の呪文を破滅的に燃え上げる。" }), 15, "mage"),
  lr(W("lr_thief15", "影牙神の双刃", "dg", 195, { cls: ["thief"], atk: 211, eAtk: ["dark", 2],
    desc: "影牙王の双刃が神域の冴えに達した姿。盗賊の手の中で幾度も消え、闇に紛れて急所だけを神速で抉り尽くす。" }), 15, "thief"),
  lr(W("lr_bishop15", "万理の神聖杖", "st", 195, { cls: ["bishop"], eAtk: ["light", 2],
    desc: "三理の大聖杖が万理を束ねた神聖杖。攻・癒・守をはじめ理のすべてを御し、司教の手で術を極限の高みへ導く。" }), 15, "bishop"),
  lr(W("lr_samurai15", "極・妖桜丸", "kt", 195, { cls: ["samurai"], atk: 286, eAtk: ["wind", 2],
    desc: "妖桜丸が極まった神刀。抜けば桜吹雪が神域の暴風と化し、侍の踏み込みに乗って一閃のうちに千の敵を薙ぎ払う。" }), 15, "samurai"),
  lr(W("lr_berserker15", "血咆神の大巨斧", "ax", 195, { cls: ["berserker"], atk: 313, eAtk: ["fire", 2],
    desc: "血咆の大巨斧が神威に覚めた究極の斧。狂戦士の怒りが極まると刃が太陽のごとく燃え、振るうたびに破滅の渦を生む。" }), 15, "berserker"),
  lr(W("lr_hunter15", "神烈風の猟弓", "bw", 195, { cls: ["hunter"], atk: 248, eAtk: ["wind", 2],
    desc: "烈風裂きの神猟弓が神域に至った姿。狩人が弦を引けば神威の烈風が矢を捕らえ、地平の彼方の獲物すら一矢で貫く。" }), 15, "hunter"),
  lr(W("lr_shadow15", "極宵の暗刃", "dg", 195, { cls: ["shadow"], atk: 211, eAtk: ["dark", 2],
    desc: "深宵の暗刃が極夜の闇へ沈んだ姿。暗殺者の手に渡ると一帯の光を喰らい尽くし、刃も気配も存在ごと闇へ消し去る。" }), 15, "shadow"),
  lr(W("lr_paladin15", "聖盟神王の剣", "ls", 195, { cls: ["paladin"], atk: 270, eAtk: ["light", 2],
    desc: "聖盟王の剣が神王の証へと昇華した姿。聖騎士が掲げると経文が光の津波となって溢れ、視界の不浄を一掃する。" }), 15, "paladin"),
  lr(W("lr_guardian15", "不動神王の鉄槌", "mc", 195, { cls: ["guardian"], atk: 297, eAtk: ["earth", 2],
    desc: "不動明王の鉄槌が神王の威を極めた姿。一打ごとに大地が裂けて神威の岩壁が立ち、守護騎士は不滅の砦と化す。" }), 15, "guardian"),
  lr(W("lr_spellblade15", "魔刃・神炎", "kt", 195, { cls: ["spellblade"], atk: 286, eAtk: ["fire", 2],
    desc: "魔刃・劫火が神炎へと極まった姿。斬撃と呪文が神域で一体となり、振り抜いた軌跡に世界を焼く神の炎を曳く。" }), 15, "spellblade"),
  lr(W("lr_monk15", "釈尊の大金剛杵", "mc", 195, { cls: ["monk"], atk: 297, eAtk: ["wind", 2],
    desc: "阿羅漢の大金剛杵が悟りの極致に達した杵。打ち込むたびに神域の疾風が渦巻き、武僧の気の一撃が万物を打ち砕く。" }), 15, "monk"),
  lr(W("lr_hexer15", "神呪の黒杖", "st", 195, { cls: ["hexer"], eAtk: ["dark", 2],
    desc: "大呪詛の黒杖が神域の呪を宿した黒杖。呪術師の手で万の怨念が神威の呪詛と化し、敵を内側から確実に滅ぼし尽くす。" }), 15, "hexer"),
  lr(W("lr_hermit15", "神仙木の杖", "st", 195, { cls: ["hermit"], eAtk: ["earth", 2],
    desc: "大仙木の杖が神木へと至った杖。大地の気脈の源と通じ、隠修士の術に大地そのもののごとき不動の力を与える。" }), 15, "hermit"),
  lr(W("lr_brigand15", "義賊神王の隠し刃", "dg", 195, { cls: ["brigand"], atk: 211, eAtk: ["wind", 2],
    desc: "義賊王の隠し刃が神域の冴えに達した姿。神威の風のごとく抜き放たれ、軽やかな身のこなしで狙いを過たず仕留める。" }), 15, "brigand"),
  lr(W("lr_arcthief15", "神魔導の盗刃", "dg", 195, { cls: ["arcthief"], atk: 211, eAtk: ["dark", 2],
    desc: "大魔導の盗刃が神域の呪印を帯びた姿。刺すと同時に相手の魔力を残らず奪い尽くし、神威の闇へ溶けて消え去る。" }), 15, "arcthief"),
  lr(W("lr_crusader15", "聖戦神王の大剣", "ls", 195, { cls: ["crusader"], atk: 270, eAtk: ["light", 2],
    desc: "聖戦王の大剣が神王の旗剣へと昇華した姿。掲げれば刃が神の光に燃え立ち、聖戦士の道の邪悪を残らず薙ぎ倒す。" }), 15, "crusader"),
  lr(W("lr_battlemage15", "神劫炎の魔剣", "ls", 195, { cls: ["battlemage"], atk: 270, eAtk: ["fire", 2],
    desc: "劫炎の魔剣が神域の炎を宿した姿。刀身の呪文式が神威で暴走し、魔闘士の斬撃のたびに世界を焼く神炎が炸裂する。" }), 15, "battlemage"),
  lr(W("lr_darkknight15", "冥神王の魔剣", "ls", 195, { cls: ["darkknight"], atk: 270, eAtk: ["dark", 2],
    desc: "冥王の魔剣が冥神王の力に覚めた姿。魔騎士の闇と神域で契り、斬った相手の命と魂を喰らって振るう者を高みへ導く。" }), 15, "darkknight"),
  lr(W("lr_templar15", "神殿神王の聖鎚", "mc", 195, { cls: ["templar"], atk: 297, eAtk: ["light", 2],
    desc: "大神殿の聖鎚が神王の祭具へと極まった姿。神殿騎士の信仰に応えて神光を放ち、いかなる結界も敵もろとも打ち砕く。" }), 15, "templar"),
  lr(W("lr_exorcist15", "神祓いの銀刃", "dg", 195, { cls: ["exorcist"], atk: 211, eAtk: ["light", 2],
    desc: "大祓いの銀刃が神域の真言を帯びた姿。祓魔師が構えると刃が神の光の奔流を放ち、いかなる悪霊も肉ごと斬り浄める。" }), 15, "exorcist"),
  lr(W("lr_warden15", "神護法の杖", "st", 195, { cls: ["warden"], eAtk: ["earth", 2],
    desc: "大護法の杖が神域の結界を宿した姿。護法師の障壁を神威の岩盤と化し、なお攻めの術をも極限まで研ぎ澄ます。" }), 15, "warden"),
  lr(W("lr_arcanist15", "極・秘奥の宝杖", "st", 195, { cls: ["arcanist"], eAtk: ["water", 2],
    desc: "真・秘奥の宝杖が奥義の極致に達した杖。宝珠が神域の水の理を巡らせ、秘術師の呪文の精度と威力を極限まで高める。" }), 15, "arcanist"),
  lr(W("lr_inquisitor15", "神断罪の業鎚", "mc", 195, { cls: ["inquisitor"], atk: 297, eAtk: ["fire", 2],
    desc: "大断罪の業鎚が神域の審判を宿した鎚。罪を焼く神火が燃え盛り、審問官が振り下ろすたびに咎人を神の業火で断罪する。" }), 15, "inquisitor"),
  lr(W("lr_archbishop15", "大聖堂の神錫杖", "st", 195, { cls: ["archbishop"], eAtk: ["light", 2],
    desc: "大聖堂の大錫杖が神域に至った錫杖。大司教が振るうと環が神の和音で鳴り渡り、聖なる光で奇跡を神威の域まで増幅する。" }), 15, "archbishop"),
  lr(W("lr_ascetic15", "大修験王の金剛杵", "mc", 195, { cls: ["ascetic"], atk: 297, eAtk: ["earth", 2],
    desc: "大修験の金剛杵が荒行の極致を経た杵。大地に根ざした不屈の神気を宿し、修験者の一打が山脈をも崩す重みを伝える。" }), 15, "ascetic"),
  lr(W("lr_hero15", "極・勇者の聖剣", "ls", 195, { cls: ["hero"], atk: 270, eAtk: ["light", 2],
    desc: "勇者の聖剣が究極の力を解き放った姿。勇者の手で神々しい黄金光が天を貫き、世界を覆う深淵の闇すら一刀で斬り裂く。" }), 15, "hero"),
  lr(W("lr_asura15", "阿修羅王の妖剣", "ls", 195, { cls: ["asura"], atk: 270, eAtk: ["fire", 2],
    desc: "阿修羅の妖剣が修羅道の王の刃へと覚めた姿。握る者の殺意が極まると刃が業火を噴き、振るうほどに無敵の修羅と化す。" }), 15, "asura"),
  lr(W("lr_dragonknight15", "竜神殺しの剣", "ls", 195, { cls: ["dragonknight"], atk: 270, eAtk: ["wind", 2],
    desc: "竜帝殺しの剣が竜神すら屠る神剣へと至った姿。竜を狩る風の加護が神域に達し、神話の竜神の急所すら過たず貫く。" }), 15, "dragonknight"),
  lr(W("lr_necromancer15", "神死霊の骨杖", "st", 195, { cls: ["necromancer"], eAtk: ["dark", 2],
    desc: "大死霊の骨杖が冥府の神域に通じた杖。尽きせぬ闇の魔力を冥界の源から引き出し、死霊術師の呪文を死の神威で満たす。" }), 15, "necromancer"),
  lr(W("lr_sage15", "大賢者神の天杖", "st", 195, { cls: ["sage"], eAtk: ["water", 2],
    desc: "大賢者の天杖が天地の理を極めた神杖。澄んだ水の魔力を無限に湛え、賢者の攻めにも癒しにも神域の力を通す。" }), 15, "sage"),
  lr(W("lr_cardinal15", "教皇神の聖杖", "st", 195, { cls: ["cardinal"], eAtk: ["light", 2],
    desc: "教皇の聖杖が神権を帯びた神聖杖。掲げれば天上の鐘が世界に鳴り渡り、注がれた祈りを万物を照らす神光へと変える。" }), 15, "cardinal"),
  lr(W("lr_archmage15", "大魔導神の極星杖", "st", 195, { cls: ["archmage"], eAtk: ["dark", 2],
    desc: "大魔導の極星杖が神域の星に覚めた杖。杖頭の暗黒星が世界の理を捻じ曲げ、大魔導の攻撃呪文を破滅的な威力で放つ。" }), 15, "archmage"),
  lr(W("lr_chaplain15", "大護教王の聖鎚", "mc", 195, { cls: ["chaplain"], atk: 297, eAtk: ["light", 2],
    desc: "大護教の聖鎚が護教王の祭具へと極まった姿。掲げると味方を神光の膜が包み、振るえば不浄を一掃する神の聖光が爆ぜる。" }), 15, "chaplain"),
];
