// 収集品の固有の絵 (100種、1品に1枚)。id → { pal, art }
//  - art: 24 行 × 24 文字のドット絵。"." = 透明。光源は左上、黒縁 k は 1px。
//  - pal: defs.js の共有パレット P (ITEM_PALETTE) に足す/上書きする色 { 文字: "#rrggbb" }。染め (tint) はしない。
//  - lv165 以上の品は defs.js が輪郭の外に燐光を足す。
//  - 見本と検査: node tools/miscart.mjs  (下書きは node tools/miscart.mjs <file.mjs>)
//  - 収集品を足すときは、ここに固有の絵を足す (無いと defs.js の M() が投げる)。
export const MISC_ART = {
  // 鉄格子に歯形を残す鼠王の橙色の前歯
  m_rat_king_tooth: {
    pal: { "a": "#3d200c", "H": "#6e3c14", "M": "#a8621e", "P": "#d6923a" },
    art: [
      "........................",
      ".........kk.............",
      "....kkkkkPPkk...........",
      "...kPPPPPPPMMk..........",
      "...kPPPPPPPPMMkk........",
      "..kMPMMMMMPPPPMMk.......",
      "...kHHHIIIBMPPPMHk......",
      "....kkkzzIIBBPPMHk......",
      ".......kkkzIBBBMMak.....",
      "..........kkBBxMMHk.....",
      "...........kIBxBMHk.....",
      "............kBBxBMak....",
      ".............kBxBHak....",
      ".............kxxBHk.....",
      ".............kxxBHk.....",
      ".............kBxBHkkk...",
      "........kkkkkkkxBakwwk..",
      "..kkkkkkwwwwwwkIHkwwwvk.",
      ".kwwwwwwwwwkewwkkvkevgk.",
      ".kwwwkevkevvvggggggdeek.",
      ".kvggggggeeeeddekkkkkk..",
      "..kedekkkkkkkkkk........",
      "...kkk..................",
      "........................",
    ],
  },
  // 鎖の輪を鉤のように抱え込んだ指の骨
  m_chained_finger: {
    pal: {  },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      ".............kkk........",
      ".........kkkkxxkk.......",
      "........kxxxxxkxBk......",
      "........kBBIzzkxIk......",
      "....kk..kkkkkkkxIkkk....",
      "..kkwvk.kxIkwkkxIkwwkk..",
      ".kwvgvvkkxzkvvkxBkvgvgk.",
      ".kwekkkkxxzkkkkkkkkdvvk.",
      ".kvk.kvkxBzkkwkxzkkkkvk.",
      ".kwdkwkkxBzkkkkkkvkkwgk.",
      ".kgvwvekIzzkdgk.kvwwvk..",
      "..kkkkkxkkkkkk...kkkk...",
      "......kxBzk.............",
      "......kxIk..............",
      ".....kxxIk..............",
      ".....kxBIk..............",
      ".....kzzzk..............",
      "......kkk...............",
      "........................",
    ],
  },
  // 木の柄の真鍮の手鈴、柄に牢の鍵が結んである
  m_gaoler_bell: {
    pal: {  },
    art: [
      "........................",
      "..........kkk...........",
      ".........kNNnk..........",
      ".........kNNSk..........",
      ".........kNnSk..........",
      ".........kNnSk..........",
      ".........kNnSk..........",
      ".........kNnSk..........",
      "........kYYYyLk.........",
      ".......kxxxxxyLk........",
      ".......kxxxxxyoLkkk.....",
      ".......kxxxxxyokwvvk....",
      ".......kxxxxxyowekwk....",
      "......kxxxxxxyoOvwvk....",
      "......kxxxxxYyyokwk.....",
      ".....kYxxxxxYyyoOvgk....",
      ".....kxxxxxxYYyoOkvk....",
      "....kYxxxxxxYYyooOwkk...",
      "...kkkkkkkkkkkkkkkwggk..",
      "..kkoOOOOOOOOOkkkkvggk..",
      "...kkooooowwgOOOOOkkk...",
      ".....kkkkkvvekkkkk......",
      "..........kkk...........",
      "........................",
    ],
  },
  // 藍の袖口からこぼれる、顔の擦り減った銅貨
  m_bribe_copper: {
    pal: { "a": "#2e160c", "H": "#5e3018", "M": "#8e522a", "P": "#bc7c44", "Q": "#dcaa70", "Z": "#8c8ea6" },
    art: [
      "........................",
      "...kkkk.................",
      "..kZZZCk................",
      "..kAZACk................",
      "..kZAACCk...............",
      ".kAZACCCkk...k..........",
      ".kZZZAAAACkkkZk.........",
      ".kAZZZAAAAZAZZZk........",
      ".kCAAAZAAZZZkkZk........",
      "..kCAAAAAZZZkkZk........",
      "...kCAAAAZZkkkZk........",
      "...kCAAAACZkkkZk........",
      "....kCACCCZkkkZk........",
      ".....kCCCCZkkZkkkkk.....",
      "......kkCCZkkkQPPPMk....",
      "........kkZkkQPPMMMMk...",
      "..........kkQHPMHHMHk...",
      "...........kPPMMHHHMk...",
      "......kkkkkkPMMHHHMHk...",
      ".....kQQQMakPMMMHMPak...",
      ".....kHHaaakkMHMMaak....",
      "......kkkkk..kkkkkk.....",
      "........................",
      "........................",
    ],
  },
  // 飯粒しっくいの塊に塗り込められた銀貨
  m_unlisted_cell_key: {
    pal: { "a": "#47433a", "H": "#726b5c", "M": "#a29a86", "P": "#ccc4ac", "Q": "#e6dfca" },
    art: [
      "........................",
      "........................",
      "........................",
      "..........kkkk..........",
      ".........kxxwvk.........",
      "........kvvvvgekkkk.....",
      ".....kkkxvxvvveekPPk....",
      "....kPPkvxxxwgeekQQPk...",
      "...kPPPkgwxxveeekPMPPk..",
      "...kPQQPkkkkkkkkHHHkk...",
      "..kPPPPPPPPPMHHHHHHHk...",
      "..kMMMMHMMMHHHHHHQQHHk..",
      "..kMMMMHMMHQHHHHHHHHHk..",
      "..kMQMMMMMHHHHHHHaaHHk..",
      "..kMMMaaaaMHHMHavvHHHk..",
      "..kMMMMwwwaaaaavHHHHHk..",
      "..kMMMHMxxxxxwHHHHHHHk..",
      "..kMMQMMMHMHHHHHHQHHHk..",
      "...kMMMMHMQHHMHHHHHHHk..",
      "....kMMMHHMMHHHHHHHkk...",
      ".....kkkkkkkkkkkkkk.....",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 袖口を掻きむしった血の筋の残る白い死装束
  m_execution_shroud: {
    pal: { "a": "#38363e", "H": "#62606a", "M": "#94929a", "P": "#c4c2c0", "Q": "#e4e2da" },
    art: [
      "........................",
      "........................",
      "........................",
      "...........kkk..........",
      "........kkkkkkkk........",
      "..kkkkkkPaHPPMMHkkkkkk..",
      ".kPPPPPPkPaHPMHMMMMMMMk.",
      ".kPPPPPPkPaHMHkMMMMMMMk.",
      ".kPPPPPPkPMaHHkMMMMMMMk.",
      ".kPPPPPPkMMMHHkMMMMMMMk.",
      ".kPPPPPPkMMMaHkMMMMMMMk.",
      ".kPPPPPPkMMMMaHMMMMMMrk.",
      ".kPqPrPPkMMMMakMMMMqMrk.",
      ".kPPqrPPkMMMMMHHHHHHqrk.",
      ".kMMqkkkPMMMMMHkkkkkqHk.",
      "..kkk.kPMMMMMMMMMk..kk..",
      "......kPPMMMMHHMHk......",
      "......kMPMMMMHHHHk......",
      "......kMMMMMMHHHHk......",
      "......kMMMMMMHHHHk......",
      "......kMMMMMMHHHHk......",
      ".......kkkkkkkHkk.......",
      "..............k.........",
      "........................",
    ],
  },
  // 口紐の麻袋、指輪・乳歯・赤い結い紐がこぼれる
  m_kobold_keepsake: {
    pal: { "a": "#2a1e14", "H": "#4e3a26", "M": "#7a6040", "P": "#a48a62" },
    art: [
      "........................",
      "........................",
      "........................",
      ".......k.k.k............",
      "......kMkMkHk...........",
      ".....kMMMMMHk...........",
      "......kkkkkk............",
      ".....kLLLLLLk...........",
      "......kkkkkllk..........",
      ".....kMMHHHHLk..........",
      "....kPPPPPPMHLk.........",
      "...kPPPPPPPMMHk...kk....",
      "..kPPPPPPPMMMHakkkRrk...",
      "..kPPaPPPPMMHHkRRqrRk...",
      ".kMPPPPPPMMMHHkrqkkqrk..",
      ".kMPPaPPMMMHHaakk.kRrk..",
      "..kMMMMMMMHHHaak.kkRqk..",
      "..kMMMaHHHHHaaakkYYkk...",
      "...kHHHHHHaaakkkykkYk...",
      "....kaHaaaaakxBkykkYk...",
      ".....kkaaaakkBIkkOOk....",
      ".......kkkk..kzk.kk.....",
      "..............k.........",
      "........................",
    ],
  },
  // 翼膜を背にした大蝙蝠の眼球、瞳は細くすぼまる
  m_bat_night_eye: {
    pal: { "a": "#1a1420", "H": "#2e2236", "M": "#4a3a54", "P": "#6e5a7a", "Q": "#c8b0e0" },
    art: [
      "........................",
      "........................",
      "........................",
      "..kk................kk..",
      ".kHPkkk..........kkkMHk.",
      ".kPHHPPkk......kkMMHHMk.",
      ".kMPPHHPPkkkkkkMMHHMMMk.",
      ".kMMMMPHkkPPPMkkHMMMMHk.",
      ".kMMMMMkiiiiiPPMkMHHHHk.",
      ".kMMMMkiiQQQjipMHkHHHHk.",
      ".kMMakiiQQjQQipjHakaHHk.",
      ".kaaMkiQQQQQiijjJakHaak.",
      "..kMMkiQjiQkiipjJakHHk..",
      "..kHMkiiQQikkppjJakHHk..",
      "...kakPijiikkpjJJakak...",
      "....kkMppppkpjjJJakk....",
      ".....kHMjpjjjJJkaak.....",
      "......kHHJJJjJkRkk......",
      ".......kaaaaakRRrk......",
      "........kkaaaakrRrk.....",
      "..........kkkk.krRk.....",
      "................kk......",
      "........................",
      "........................",
    ],
  },
  // 錆くずの山に残った混じりけの無い鉄塊と錆虫
  m_rust_worm_iron: {
    pal: { "a": "#331810", "H": "#5e2c16", "M": "#8e4822", "P": "#ba7038", "Q": "#d89a5a" },
    art: [
      "........................",
      "........................",
      "........................",
      "............k...........",
      "...........kwkkk........",
      "..........kxwwwwk.......",
      ".........kxxwwwwwk......",
      "........kxxxxwwwgk......",
      ".......kkxxxxwwwgk......",
      ".....kkqkkxxvvwggk......",
      "....krkkkkxvvvvgggk.....",
      "...kmmqkkvvvvvvgggk.....",
      "..kmrqqkvvvvvvvgggk.....",
      "..krRqk.kvvvvvvgggk.....",
      ".kmmqqk.kvvvvvgggk......",
      ".krrrk..kvvvvvggk.......",
      ".kmmqkkkkkvvvvgkkkk.....",
      ".krrrkPPPPkkkvkPMHHkk...",
      ".kmmqkPPPPPPPkPMMMHHak..",
      ".krrrkPPPMPPMPMMMaaaHk..",
      ".kqrqkMHHHHMMHHaaaaaak..",
      "..kkkkkaaaaHaHaaaakkk...",
      ".......kkkkkkkkkkk......",
      "........................",
    ],
  },
  // 赤紐を結んだ御守りの小さな捻れ角
  m_imp_milk_horn: {
    pal: { "a": "#1c1226", "H": "#36244a", "M": "#5a4072", "P": "#8a6aa4", "Q": "#b89ccc" },
    art: [
      "........................",
      "........................",
      "..................k.....",
      ".................kMk....",
      "............kkkkkQHk....",
      "..........kkMQQQMPak....",
      ".........kQQQMPMHak.....",
      "........kQMQPMaakk......",
      ".......kQQQHaakk........",
      "......kQMMPHak..........",
      ".....kMQQPaak...........",
      ".....kQMQMHak...........",
      "....kQQQHMak............",
      "....kMQQMaak............",
      "...kPQQHMHak............",
      "...kMQQPaHk.............",
      "...kkMQPkkk.............",
      "..kYykkkRRRkkk..........",
      "..kYokRRRrrRrRk.........",
      ".kkOOkqqkkRqkrqk........",
      "..kkkkkkaaRrkRqk........",
      ".kRqkHHaakkrRrk.........",
      "..kk.kkkk..kkk..........",
      "........................",
    ],
  },
  // 細首の涙壺に澄んだ涙、上に落ちる一粒
  m_tear_bottle: {
    pal: { "a": "#26303a", "H": "#48586a", "M": "#7a8c9c", "P": "#aebccc", "Q": "#dae4ea" },
    art: [
      "........................",
      "........................",
      "..........kkk...........",
      ".........kRRrk..........",
      ".........kRrqk..........",
      "........kQQqPHk.........",
      ".........kQQHk..........",
      ".........kQQHk..kk......",
      ".........kQQHk.kQQk.....",
      ".........kQQHk.kQck.....",
      ".........kQQHk.kcbk.....",
      ".........kQQHk..kk......",
      ".........kQQMk..........",
      "........kQQQPHk.........",
      ".......kQQQQPMak........",
      ".......kQQQQQMHk........",
      "......kQQQQQQMHak.......",
      "......kQccccccbak.......",
      "......kQccccccbak.......",
      "......kQccccccbak.......",
      ".......kQQQQQMHk........",
      "........kkkkkkk.........",
      "........................",
      "........................",
    ],
  },
  // 天秤の皿に載せられ傾かぬままのどくろ
  m_unjudged_skull: {
    pal: {  },
    art: [
      "........................",
      "...........kk...........",
      "..........kYyk..........",
      "...kkkkkkkkYokkkkkkkk...",
      "..kYYYYYYYYOOYYYYYYYok..",
      "..koOOOOOOOOOOOOOOOOOk..",
      "...kkkkkkkkyOkkkkkkkvk..",
      "...kxxBIk.kyOk.....kvk..",
      "..kxxxxBzkkyOk....kvvk..",
      ".kxxxxBBzkkyOk....kvvk..",
      ".kxxxBBIzkkyOk...kvkkvk.",
      ".kBkkBkkzkkyOk...kvkkvk.",
      "..kIIIIIzkkyOk...kvkkvk.",
      "..kIIkIIkkkyOk..kvkkkvk.",
      ".kYYzkzkokkyOk..kYYYyvk.",
      ".kyyyooOOkkyOk..kyooOk..",
      "..kkkkkkk.kyOk...kkkk...",
      "..........kyOk..........",
      "..........kyOk..........",
      "........kkkyOkkk........",
      ".......kyyyoooook.......",
      "......kyyyyooooook......",
      ".......kkkkkkkkkk.......",
      "........................",
    ],
  },
  // すすと血でつづった頁と黒く塗り潰した終いの頁
  m_gaol_confession: {
    pal: { "a": "#4a3c2c", "H": "#7a684e", "M": "#a8946e", "P": "#c8b48c" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "...kkkkkk......kkkkkk...",
      "..kPMMMMMkk.kkkMMMMMMk..",
      ".kkPMMMMMMMkMMMMFFFFMdk.",
      ".kkgggMMMMMkRFFFFFFFMdk.",
      ".kkMMMMgggMkMFFFFFFFMdk.",
      ".kkgMgMMMMMkMFFFFFFFMdk.",
      ".kkMMMggMMMkRFFFFFFFMdk.",
      ".kkrrrMMMMMkMFFFFFFFMdk.",
      ".kkMMMMrrrMkMFFFFFFFMdk.",
      ".kkgMgMMMMMkRFFFFFFFMdk.",
      ".kkMMMggMMMkMFFFFFFfMdk.",
      ".kkMMMMMMMMkMFfFfMMMMdk.",
      ".kdkkkMMMMMkRMMMMMddddk.",
      ".kddddkkkkkdddddddddddk.",
      "..kkkkkkdddddddkkkkkkk..",
      "........kkkkkkk.........",
      "........................",
      "........................",
    ],
  },
  // 蝋の涙の形に垂れた琥珀、芯に眠る羽虫
  m_candle_amber: {
    pal: { "a": "#3a1a06", "H": "#743a0e", "M": "#b06618", "P": "#dc9a36", "Q": "#f2cc80" },
    art: [
      "........................",
      "........................",
      "...........kkk..........",
      "..........kQQHk.........",
      "..........kQQHk.........",
      "..........kQQHk.........",
      ".........kQQQMk.........",
      ".........kQQQMk.........",
      "........kQQQQMHk........",
      "........kQQQQMHkk.......",
      ".......kQQQQQPMHQk......",
      "......kQQQQQQPMPPMk.....",
      ".....kQQQQQQQPMMPPk.....",
      ".....kQQQQQQQQMMPPHk....",
      "....kQQQQQQQHQaMHPMk....",
      "....kQQQQQHHQaPHHQMk....",
      "....kPPQQMQQaPMMaQMk....",
      ".....kPPPQPaMMHaaMHk....",
      ".....kMMMMaMHHaakkk.....",
      "......kHMMHHaaak........",
      ".......kHHHaaak.........",
      "........kkkkkk..........",
      "........................",
      "........................",
    ],
  },
  // 縞の入った青灰の大きな風切羽
  m_harpy_pinion: {
    pal: { "a": "#1e2634", "H": "#3a4a60", "M": "#5e7690", "P": "#8aa4bc", "Q": "#bccfdc" },
    art: [
      "........................",
      "........................",
      ".................kk.....",
      "................kHHk....",
      "...............kHHzk....",
      ".............kkHMzMk....",
      "............kHHHzzPk....",
      "...........kaHHHzPk.....",
      "..........kHHHHzzMk.....",
      "..........kHHHMzMMk.....",
      ".........kHHHMzPMk......",
      ".........kHHHzzPk.......",
      "........kHHHzzMPk.......",
      "........kHMzzMMk........",
      ".......kHMMzPMk.........",
      ".......kHzzPkk..........",
      ".......kzzMk............",
      ".....kkzzkk.............",
      "....kBBkk...............",
      "...kBBk.................",
      "...kxk..................",
      "....k...................",
      "........................",
      "........................",
    ],
  },
  // 国璽の盾紋を鑿で×に潰された古銀貨
  m_lost_realm_silver: {
    pal: { "a": "#2a2c36" },
    art: [
      "........................",
      "........................",
      "........kkkkkkk.........",
      "......kkxxxxwwwkk.......",
      ".....kxxxvggggwvvk......",
      "....kxxvvxxwwweevgk.....",
      "...kxxvxxxxxwwvveggk....",
      "..kxxvxxxxwxwwvggaggk...",
      "..kxvvxaxwxwwwwwawagk...",
      "..kxvxxxaxvvgggaweagk...",
      ".kwxgxxxvaxvggaweeaggk..",
      ".kwxgwxxvvaxgaweeeaggk..",
      ".kwwgwwwvvvawwgeeeaggk..",
      ".kwwgwwwvvawgaxeeeaggk..",
      "..kwevvvvawvggaxeeagk...",
      "..kveeggawvvgeeaxaagk...",
      "..kvvggaweeveeeeaxggk...",
      "...kgggeeeeeeeeeaggk....",
      "....kggaaeeeeeaaggk.....",
      ".....kgggaaaaagggk......",
      "......kkgggggggkk.......",
      "........kkkkkkk.........",
      "........................",
      "........................",
    ],
  },
  // 翼のように張った太い首の椎骨、たてがみの房を結ぶ
  m_warhorse_neckbone: {
    pal: { "a": "#4a3e2c", "H": "#7e6e50", "M": "#b0a07c", "P": "#d8cca8", "Q": "#1e140e", "U": "#3a2a1e" },
    art: [
      "........................",
      "...........kk...........",
      "..........kPMk..........",
      ".........kMkkak.........",
      "......kkkkkPMkkkkk......",
      ".....kPPkPPPPMHkPMk.....",
      "....kPPkPPPPPMHakMMk....",
      "...kPPPkPPPQQMHakMMMk...",
      "..kPPMakMPQQQQHakMaMMk..",
      ".kPPMaakMMMQQHaakHMaMak.",
      "..kHakk.kHHdLaak.kkHHk..",
      "...kk....kkaLkk....kk...",
      "........kk.kLkkk........",
      ".......kwwkklkvgk.......",
      ".......kwvk.kkvvk.......",
      "......kwwek..kvvek......",
      "......kwvek...kegk......",
      "......kwvk....kwek......",
      "......kvegk..kwvek......",
      ".......kvvvkkwwgk.......",
      ".......kevvwwwgek.......",
      "........kkgggekk........",
      "..........kkkk..........",
      "........................",
    ],
  },
  // 緑青の吹いた警鐘、垂れた綱と射込まれた矢
  m_silent_alarm: {
    pal: { "a": "#1c2420", "H": "#36463a", "M": "#566c58", "P": "#86967a", "Q": "#a8b49a" },
    art: [
      "........................",
      "..kkkkkkkkkkkkkkkkkkk...",
      ".kNNNNNNNNNNNNNNNNNNnk..",
      ".kNnnnnnnnnnnnnnnnnnsk..",
      ".kSSSSSSSSSSSSSSkkSSSk..",
      "..kkkkkkkQQQQMkkLlkkk...",
      ".......kQQQQQPMkllk.....",
      "......kQQQQQPSHakLk.....",
      "......kQQQQSSnMakLlk....",
      "......koQQSnnMMHkkLk....",
      "......kQQSnQPMMHkkLlk...",
      "......kSSnQQPMoHkkllk...",
      ".....kSnnQQQPMMHk.kLk...",
      "...kkSnQQQQQPMMHk.kLk...",
      "..kBIkMMMMMMHHaoakkLk...",
      "..kBBkPQQQPPMMHHakkLDk..",
      ".kBIkPPQQQPPMMHHaakLDk..",
      "..kkkPQQQQPPMMMHHakLDk..",
      "...kaaaaaaaaakkkkkkLDk..",
      "....kkkkkkkkkkkkkkklDk..",
      ".......kkkkkkkkk..klklk.",
      "...................k.k..",
      "........................",
      "........................",
    ],
  },
  // 緑の毒袋を根に付けた反り牙と毒のしずく
  m_wall_lizard_fang: {
    pal: { "a": "#a6c872", "H": "#2a3a22" },
    art: [
      "........................",
      "........kkkk............",
      ".......kxxxBk...........",
      "......kxxxxBzk..........",
      "......kxxGBIIk..........",
      "....kkkhhhtBIk..........",
      "...kaaGhGtBBIzk.........",
      "...kaaatGkxIIzk.........",
      "..kaaaaaGtkIBIk.........",
      "..kaaaahGtkIBIk.........",
      "..khaahGttkxIIk.........",
      "..kGhhtttkBxIIzk........",
      "...ktttttkBxIBzk........",
      "....kkkkk.kBxIIk........",
      "..........kBxIIk........",
      "...........kBBIzk.......",
      "...........kzBIBk.......",
      "............kkBBk.......",
      "..............kBBk......",
      "...............kIkk.....",
      "................katk....",
      "................khtk....",
      ".................kk.....",
      "........................",
    ],
  },
  // 革手袋の掌で燃え続ける、亀裂の光る炭の石
  m_undying_ember: {
    pal: { "a": "#d47630", "H": "#f2b856", "M": "#211c22", "P": "#3a3238", "Q": "#564a50" },
    art: [
      "........................",
      "............k...........",
      "...........kak.k........",
      ".........k..k.kak.......",
      "........kak....k........",
      ".........kkkkk..........",
      ".......kkggggPkk........",
      "......kggggggQQPk.......",
      ".....kggggggggrrMk......",
      ".....kggrggggrQPPk......",
      "....kggggrrggaQPPMk.....",
      "....kggrggggraQPMMk.....",
      "....kgggrrgHaQPkkkkk....",
      "....kkkQQQaaHrrLLLLLk...",
      "....kLdkQQrPPPMrkkkllk..",
      "...kLlDkPPPrMMMkLLLkkk..",
      "..kLLdkMMMMrMMMkkkkLLk..",
      "..kLlDkLLMMMMMkLLLlkkk..",
      ".kllDkLLLLLLLlklllLLLk..",
      "..kDkllllllldddkkkDddk..",
      "...kddddddDDDDDDDDkkk...",
      "....kkkDDDDDDDDDkkk.....",
      ".......kkkkkkkkk........",
      "........................",
    ],
  },
  // 天守の封蝋 — 二つに割れて片方がずれた厚い封蝋の円盤。盛り上がった縁、押された天守の紋、後ろから紐の端
  m_keep_seal_key: {
    pal: { "a": "#4a1218", "H": "#8c2a2c", "K": "#b04a40", "W": "#d27a62", "q": "#36090f", "r": "#6a1c22" },
    art: [
      "........................",
      ".........kkkkk..........",
      ".......kkWWWWWk.........",
      ".....kkWWWaaark.kk......",
      "....kWWWaaHHHakkWKkk....",
      "....kWaaHHHHHk.kaWKKk...",
      "...kWWaqHqHqHk.kHaaKk...",
      "...kWaHqqqqqqk.kHHaKKk..",
      "..kWWaHHqqqqqHkkHHHaKk..",
      "..kWaHHHqqqqqHkkrHHaKrk.",
      "..kWaHHHqqHqqrkkaHHHark.",
      "..kWaHHHqqqqqakkHHHHark.",
      "..kWWaHHqqqqrk.kHHHHark.",
      "..krWaHqqqHqakkHHHHaHrk.",
      "..kaKWaHKKHKk.kqHHHarrk.",
      "...krKaaHHHHk.kHHHaHrak.",
      "...kaKKKaaHHk.kHHaarrk..",
      "....krrKKKaak.kaaHrrak..",
      "...kLaarrrrrk.kHrrrrk...",
      "..kLlkkaarrakkrrrraak...",
      ".kNlk..kLaak.krraakk....",
      "..kk..kNlkk..kaakk......",
      ".......kk.....kk........",
      "........................",
    ],
  },
  // 白粉が口に盛り上がる白磁の瓶 (椿の絵・真珠の照り)、抜けた栓と根元の白粉の山
  m_deathpaint_bottle: {
    pal: { "a": "#4e4a5a", "H": "#8a8498", "K": "#c4bfcc", "M": "#ece8ee", "P": "#e2c6d0", "Q": "#bccbe0", "T": "#f8f6f8" },
    art: [
      "........................",
      "........................",
      ".........kkkk...........",
      "........kTTTMk..........",
      ".......kMMMMMHk.........",
      ".......kHKMKaak.........",
      "........kyyook..........",
      "........kMTaaTk.........",
      "........kMQaaMk.........",
      ".......kkMKHakk.........",
      "......kMMMKHHKHk........",
      ".....kMMMMKKKKHHk.......",
      "....kMMPKKKKKKHHHk......",
      "....kMTKKKKKKKHHak......",
      "...kMMPKKKKrKKHHHHk.....",
      "...kHQKKKKrYrKHaaak.....",
      "....kKKKrKKrGHHaak.M....",
      "....kHHrRKHHHGaaakkk....",
      "...kNnaHKHHHHaaakTTMkK..",
      "..kNnskKKHHHHHaaaMMMTMk.",
      "..knsskHaaaaaaaMMMMMMKk.",
      "...kkk.kkkkkkkkKKKKKKKk.",
      "...............kkkkkkk..",
      "........................",
    ],
  },
  // 右上が焼け落ちてくすぶる革表紙の戦記 (交差した剣の紋・厚い紙束)
  m_halfburnt_chronicle: {
    pal: { "a": "#2a1410", "H": "#5a2a1c", "K": "#8a4a2c", "M": "#b07048", "Z": "#c8582a", "W": "#f0a040", "V": "#4a464e", "U": "#6e6a72" },
    art: [
      "........................",
      "........................",
      "...................V....",
      "...kkkkk.kk.....U...U...",
      "..kMaMMMkZWk....V...V...",
      "..kMaHKKSkkWkk.....U....",
      "..kMaHKKKKSZZZkk...V....",
      "..kMaHKKYoKZZZZZk.V.....",
      "..kMaMKKKYoKSkkkk.......",
      "..kMaHKKKKyoSZkZZk......",
      "..kMaHKKKKKYYKkSkZkk....",
      "..kHaHKKKKOyyoKSSZZZk...",
      "...kaMKKKOyKKyoKHSZkZk..",
      "...kaHKKOYKKKKYoHaZZZk..",
      "...kaHKyYKKKKKKyYakSZk..",
      "...kaHoKKKKKKKKKHokBIk..",
      "...kaMKKKKKKKKKKHakIIk..",
      "...kaHHHHHHHHHHHHakBIk..",
      "...kvHaaaaaaaaaaaakIIk..",
      "...kwvkkkkkkkkkkkkkBIk..",
      "...kxwvBBBBBBBBBBBIIIk..",
      "....kkIIIIIIIIIIIIIIIk..",
      "......kkkkkkkkkkkkkkk...",
      "........................",
    ],
  },
  // 硝子の義眼 (青白く光る瞳) と、そこから尾を引いて立ちのぼる亡霊の顔
  m_haunted_glass_eye: {
    pal: { "0": "#6a8a88", "M": "#f4f0ea", "T": "#2c5a5a", "U": "#4f9a92", "V": "#9ad8c8", "W": "#a8c8c4", "X": "#dcece8" },
    art: [
      "........................",
      "........................",
      "................XXW.....",
      "...............XXXWW.0..",
      "..............XXJWJW0...",
      "..............XXWWW00...",
      "......kkkkkkk.XXWJ000...",
      ".....kMMMMxxBkXWWJ00....",
      "....kMMMMMMxxBWW000..0..",
      "...kMMMMMMMxxBI00.......",
      "..kMMMMMMMxxxBBIk.......",
      "..kMMMMVVxxxBBIIk.......",
      ".kxMMVVVVUxxBBIzzk......",
      ".kxMMVXkVUTBBIIzzk......",
      ".kxxVVkkTUTBBIIzzk......",
      ".kBxUVkkkTTBIIzzzk......",
      "..kBxUUUTTTIIzzzk.......",
      "..kBBBTTTTIIzzzzk.......",
      "...kIIIIIIzzzzzk........",
      "....kIIIzzzzzzk.........",
      ".....kzzzzzzzk..........",
      "......kkkkkkk...........",
      "........................",
      "........................",
    ],
  },
  // 苦悶の顔が浮いた黒い鉄塊 (眼と口の奥に炉の火)
  m_groaning_iron: {
    pal: { "a": "#1a1922", "Z": "#b04a22", "W": "#f09838" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "...........k............",
      ".........kkwkkkkk.......",
      "........kwwvvwwwek......",
      ".....kkkwwwvvveveak.....",
      "...kkwwwwwvvvvvgaak.....",
      "..kwwwwvwvvggggeavkk....",
      "..kvwwvgvvggggeevgeek...",
      "..kvgvgkkkgggggkkkaeak..",
      "..keegggkZkgggkZkggaak..",
      "...kgvvggggggggggeaaak..",
      "...kvggggggkkgggeaaaak..",
      "...keeeeegkZZkeeeaaak...",
      "....kgeaegkWZZaaaaaak...",
      "....kaaeeekZZkZaaaak....",
      ".....kkaeeakkaWaeak.....",
      ".......kaeaaaakZkk......",
      "........kaaakk.k........",
      ".........kkk............",
      "........................",
      "........................",
    ],
  },
  // 霧の渦を抱えた水晶球と、球にまとわり台座に溜まる霧
  m_mist_crystal: {
    pal: { "a": "#2a3444", "H": "#4c5e74", "K": "#7e94aa", "M": "#b4c6d4", "P": "#e6eef2", "Q": "#8a96a6", "U": "#c0c8d2" },
    art: [
      "........................",
      "........................",
      "........................",
      "........kkkkkkkk........",
      ".......kMMMMMMKKk.......",
      "......kMMMMKKKKKHk......",
      ".....kMMPPKMMMKKHHk.....",
      ".....kMMPMMMMKKKHHk.....",
      "....kMMKMMMMMMKKHHak....",
      "....kMMKMMMMKKMHHHak..Q.",
      "....kMMKMMMMKKMMHaakQUU.",
      "....kKKKKKKKKHMHaaaQU...",
      "..QQkKKKKKKKHHMHaaaQ....",
      ".QUUQkKKKKKKMMaaaak.Q...",
      ".U..UQHHHHHHHaaaaakQU...",
      ".....UQQHHHaaaaaakQU....",
      ".......UUQaaaaaQQUU.....",
      ".......kwwUUUUUUk.......",
      ".......kwvvvvvvek.......",
      "......kwvggggggggk......",
      "...Q..kgeeeeeeeeeQ......",
      "....QQUUkkkkUUQQk.......",
      "......QQ.....QQ.........",
      "........................",
    ],
  },
  // 大きく口を開けた暗い二枚貝の真珠層に載る、紫と緑の照りを帯びた黒真珠
  m_abyss_black_pearl: {
    pal: { "a": "#0e0a14", "H": "#241c34", "K": "#46385e", "Q": "#a89cbc", "U": "#ece6f2", "V": "#4a8a84", "T": "#cabedc" },
    art: [
      "........................",
      "........................",
      ".......k.kk..kk.k.......",
      ".....kkikijkkijkikk.....",
      "....kiipiippJipippjk....",
      "...kiiippJppJpppJpjjk...",
      "...kiJJjpjJpJjjJjjJJk...",
      "..kipjjJJkkkkkkjJJJjjk..",
      "..kjkkkkkQQQQQQkkkkkJk..",
      "...kkQpppkpipKkppppkk...",
      ".....kkkkUTppKHkkkk.....",
      "....kUUUpTppKKHaTTTk....",
      "...kUUUkpppKKHHakTTTk...",
      "..kUUUTkKKKKHHaakTTTQk..",
      "..kTTQTTHKHHHaaVTQQQQk..",
      "...kQQkQkHHaajVkQQkQk...",
      "..kjkJpkJkaaaakpkJpkJk..",
      "...kjpJppJpJppJpJpJJk...",
      "....kjjJJpJpJpJjJJJk....",
      ".....kJJjJJJJJJJJJk.....",
      "......kkJJJJJJJJkk......",
      "........kkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  // 銛のように返しが三つ後ろ向きに張り出した青ざめた牙と、根元に巻いた海藻
  m_sahagin_barb: {
    pal: { "a": "#2e3c48", "H": "#6a7c86", "K": "#a8b8b8", "M": "#dfe6e0" },
    art: [
      "........................",
      "...................k....",
      ".................kkKk...",
      "...............kkMak....",
      "..............kMMak.....",
      "..............kMak......",
      "............kkMKKKk.....",
      "...........kMMKaHKk.....",
      "..........kMMKakaHk.....",
      ".........kMKKak.kak.....",
      "........kMKKKKk..kk.....",
      ".......kMMKaHKKk........",
      "......kMKKHaaHKk........",
      "......kMKHaakaHk........",
      ".....kMKKKak.kak........",
      "....kMKKHKKk..kk........",
      "...kMKGGaHKk............",
      "..kMGhHaaaHk............",
      ".kGhKKHaGkak............",
      "..kKKHhGk.kk............",
      "..kGhGak................",
      "..GGHak.................",
      ".G..kk..................",
      "........................",
    ],
  },
  // 枝に吊るした根の織布 (叫ぶ顔の織り模様) と、垂れ下がる根の房
  m_shriek_root_cloth: {
    pal: { "a": "#22220f", "H": "#3e3c20", "K": "#5e5a32", "M": "#847c4c" },
    art: [
      "........................",
      "........................",
      "...kkkkkkkkkkkkkkkkkkk..",
      "..kNNNNNNNNNNNNNNNNNNnk.",
      ".kNssssSsssssssSssssssk.",
      "..kkkMMMMMMMMMMMMMHkkk..",
      "....kMaHaKaKaHaKaHak....",
      "....kMKHKKHKKHKKHaak....",
      "....kMKHGKHGKGKKHaak....",
      "....kMaHkGaKGkGKaaak....",
      "....kMKHkkHKKkkKHaak....",
      "....kMKHKKHttHKKHaak....",
      "....kMaHaKtqktaKaaak....",
      "....kMKHHHtkktHHHaak....",
      "....kMHaaaattaaaaaak....",
      "...kKaaaaaaaaaaaaaaak...",
      "....kkkkkkkkkkkkkkkk....",
      "....klklklklklklklklk...",
      "....klklklklklklklklk...",
      "....kLkkLkklkkllLk.klk..",
      ".....k.kdkklkkLlk..kLk..",
      ".......kLkkLdkkLk...k...",
      "........k..kk..k........",
      "........................",
    ],
  },
  // 額に聖印の焼き痕がある煤けた頭蓋と、その下に積もった灰の小山
  m_martyr_skull: {
    pal: { "a": "#3e3830", "H": "#6e665a", "K": "#a49a86", "M": "#d0c8b4", "Z": "#c8582a", "U": "#5a5660", "V": "#8a8690" },
    art: [
      "........................",
      "............k...........",
      "........kkkkZkkk........",
      ".......kMMMMSMMHk.......",
      "......kMMMMrSrKHHk......",
      ".....kMMMZSSSSSZHHk.....",
      "....kMMMKKKrSrKKHHak....",
      "....kMMKKKKKSKKKHaak....",
      "....kMKKKKKKSKKHHaak....",
      "....kMKKKKKKKKKHHaak....",
      "....kMKKKKKKKKKHHaak....",
      "....kMKKkFkKKkkFaaak....",
      "....kHHkkkkKKkkkkaak....",
      ".....kakkkkKKkkkkak.....",
      "......kKKKKKKHHaak......",
      "...V..kMKKKHaHaaak......",
      "......kMKHHkkaaaak......",
      "....kkkkHaaaaaaak...V...",
      "..kkVVVVkMaMaMaMUkkkk...",
      ".kVVUUUUUUUUUUUUUVVVUk..",
      "..kUeeeUUUUUUUUUUUUUeek.",
      "...kkkkeeeeeeeeeeeeekk..",
      ".......kkkkkkkkkkkkk....",
      "........................",
    ],
  },
  // 緑青に半ば覆われた金貨 (舟の浮き彫り) にからむ水草と泡
  m_watergrave_coin: {
    pal: { "a": "#1e3a32", "H": "#3a6a58", "K": "#6a9a80", "M": "#9ac4a8" },
    art: [
      "........................",
      ".....kk.................",
      "....khtk...........c....",
      "....kGk..kkkkk....c.c...",
      "....kGkkkYYYYokk...c....",
      "...khtkYYYooooyokk......",
      "...kGtYYooyyyooooOk.c...",
      "....khGoyyyyyyyoooOk....",
      "....kGtyyyyoyyyoYOOk....",
      "....kYhGGyyoYyyoYooak...",
      "...kYYhtyyyoyYyooYaak...",
      "...kYhtyyyyoyyyyoYaak...",
      "...kthtyyoooooyyoYaak...",
      "..kGhtoyyyoyyyyHoMaak...",
      "...khtoyyyyyKKyHMaaak...",
      "...khtoooyyyKHHHMaaak...",
      "...kGkOYYoHHoHMMaaak....",
      "..khtkkOoYMMMMMaaak.....",
      "..kGtk.kaaHaaaaaaak.....",
      "...kGGk.kaaaaaaakk......",
      "....kGk..kkkkkkk........",
      "....ktk.................",
      ".....k..................",
      "........................",
    ],
  },
  // 畝の刻まれた反りの強い幼竜の角 (根元の割れ口でくすぶる残り火と煙)
  m_whelp_shed_horn: {
    pal: { "a": "#3a1a12", "H": "#6e2c18", "K": "#a84a26", "M": "#d4824a", "P": "#ecc08a", "Z": "#c8582a", "W": "#f0b048", "V": "#4e4a52", "U": "#7a7680" },
    art: [
      "........................",
      "........................",
      "................kkkkk...",
      ".............kkkMMMMHk..",
      "............kMMMKakkk...",
      "...........kMMHKak......",
      ".........kkMMKHHk.......",
      "...V....kMMMKaak........",
      "...U....kMMKaak.........",
      ".......kMMHHak..........",
      "....V.kMMKKHak..........",
      ".....kMMKKHaHk..........",
      ".....kKKKKHak...........",
      "....VkMKKKHak...........",
      "....kMMHHHHak...........",
      "....kKKKKHHHk...........",
      "....kKKKHHak............",
      "....kKKKHHak............",
      "....kBBBBBIk............",
      "....kIzZzWzk............",
      "....kHHHZaZk............",
      ".....kaaaak.............",
      "......kkkk..............",
      "........................",
    ],
  },
  // 下半分が水に沈んだ銀の鈴 (鈴口・水面の波紋) と、吊り輪から垂れる組紐
  m_water_sprite_bell: {
    pal: { "a": "#28384a", "H": "#4e6a82", "K": "#8eb0c4", "M": "#d4e8f0", "T": "#1c3a4a", "U": "#2e5a6c", "V": "#4e8494", "W": "#9ad0dc" },
    art: [
      "........................",
      "..........kkkk..........",
      ".........kwvvvk.........",
      ".........kvkkvbkkk......",
      ".........kvkkvubcbk.....",
      "........kkMMMKkkbuk.....",
      ".......kMMMMMMKKkbbk....",
      "......kMMMMMMMKKHkcbk...",
      ".....kMMMMMMMMKKHHcuk...",
      "....kMMMMMMMMKKKHHbuk...",
      "....kMMMMMMMKKKKHHabk...",
      "....kMMMMMKKKKKKKKKbk...",
      "....kKKKKHHHHHHHHHHck...",
      "....kKKKKKKKKHHHaaabk...",
      ".....kKKkKKKHHHkaakuk...",
      ".WWW.WMWWMWWMWWMWWMkWWW.",
      "....VVkTkTTTTTTkTkVV....",
      ".......kTTTTTTTTk.......",
      "........kkTTTTkk........",
      "...VV.....kkkk......VV..",
      ".....UUU..........UUU...",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 溶けて流れ固まった銀の溜まり (雫が散る) と、そこに角ばったまま残った竜銀の塊 (焼けの斑)
  m_dragon_silver: {
    pal: { "a": "#2c3440", "H": "#5a6878", "K": "#9aaabb", "M": "#d2dce6", "P": "#f4f8fa", "Q": "#6e5434", "U": "#b08a58" },
    art: [
      "........................",
      "........................",
      "........................",
      "..........kkk...........",
      ".........kPPPkk.........",
      ".......kkPPPPPMk........",
      "......kPPPPPPMMMk.......",
      "......kKMPPPMMMMMk......",
      ".....kKKKMMMMMMMMMk.....",
      ".....kKKKKMMMMMMMHk.....",
      "....kKKKKKHHHHHHHHk.....",
      "....kKKKKKHHHHHHHHk.....",
      "....kKMKKKHHHHHHHak.....",
      "....kKKKKKHHHHHHHHk.....",
      "..k.kKUKKKHHHHHHHk......",
      ".kPkkKUQaaHHHHHHakk.....",
      ".kakkKaUaaHHHUHHkPMkk...",
      "..kPPkkaaHHHUQUkMMKPMk..",
      ".kPMMKKkkkkkkkkKKKKMKKk.",
      ".kHKHHHHHKHHHHHHHHHHKak.",
      "..kaaaaaaHaaaaaaaaaaHHk.",
      "...kkkkkkakkkkkkkkkkaak.",
      ".........k..........kk..",
      "........................",
    ],
  },
  // 口紐のゆるんだ革袋と、こぼれ出た赤石の指輪・札の付いた紙包み
  m_robber_left_pouch: {
    pal: { "a": "#1e2416", "H": "#3c4628", "K": "#5e6a3e", "M": "#869060" },
    art: [
      "........................",
      "........................",
      "........................",
      "......kkkkkk............",
      ".....kKKKKKHk...........",
      ".....kHHaaaHk...........",
      "......kMMMHk............",
      "......kMMHakkk..........",
      ".....klLlLlLlLk.........",
      "....kkMMKHHHklk.........",
      "...kMMMMKKHHKLk.........",
      "...kMMMKKKKKHak.........",
      "..kMMMKKKKKKHHHkkkkk....",
      "..kMMKKKKKKHHHakLDLlk...",
      "..kMKKKKKKKKHakLLDlnk...",
      "..kMKKKKKKKHHakLlsDDDk..",
      "..kHHKHHHHHHaaDDDDlnk...",
      "...kKHHHHHHaaakllDnnk...",
      "...kHaHaaaaRRaknnDnDk...",
      "....kkaaaaaoyk.kkDkxBk..",
      "......kkkkokkYk..kkBIk..",
      "..........kyYk.....kk...",
      "...........kk...........",
      "........................",
    ],
  },
  // 鋲打ちの胸当ての欠片にはまり、金色に輝く心珠
  m_hollow_armor_core: {
    pal: { "a": "#8a6a1a", "H": "#ffe8a0", "K": "#fff8dc" },
    art: [
      "........................",
      "............Y...........",
      "........................",
      ".....Ykkk......kk..Y....",
      "....kkxwgkk..kkxgkk.....",
      "...kxxxwgwgkkxxxvwgk....",
      "...kwxxwvvkookxwwvgek...",
      "...kwwxvkoKKKHokvxeek...",
      "...kwwweoKKKKHYoveeek...",
      "...kwwwkKKKKHHYykeeek...",
      "...kwwwoKKKHHYYyoeeek...",
      "..YkwwwoHHHHYYyaoeeekYY.",
      "...kwwwkYHHYYyaakeeek...",
      "...kwvvgoYYyyaaoeeeek...",
      "...kegggkoaaaaokeeeek...",
      "....kegxvvkookgexeek....",
      ".....kvvevggvgeeeek.....",
      ".....kegvgggveeeeek.....",
      "......kveeeggeeeek......",
      "......keeeeegeeek.......",
      ".......kkkeegekk........",
      "..........kkkk..........",
      "........................",
      "........................",
    ],
  },
  // 二股の太い根を張った巨大な臼歯 (すり減った噛み面・ひび・根元の血染み)
  m_ogre_molar: {
    pal: { "a": "#3e3624", "H": "#7a6c48", "K": "#b4a47a", "M": "#dcd0a8" },
    art: [
      "........................",
      "........................",
      "...........kk...........",
      "......kkk.kMMkkkkk......",
      ".....kMMMkMKKMMMMMk.....",
      "....kMKKKMKMKHaKKHMk....",
      "...kMHMKKHMKKKaKKHKMk...",
      "...kMMKKKKKKKKKaKHHKk...",
      "...kMKKKKKKKKKKaKHaak...",
      "...kMKKKKKKKKKKaHHaak...",
      "...kHHHHKKKKKKaHHaaak...",
      "....kaHKKKKKKKaHaaak....",
      ".....kKKKKHHHHHHaak.....",
      ".....knnKnnHnnHnnak.....",
      "....kssKssassassrssk....",
      "....kMMHaqaaaaaqKHak....",
      "....kMKaakkkkkkKKaak....",
      "....kMKaak....kHHHak....",
      "....kMHak......kKHak....",
      "....kMaak......kHaak....",
      "....kHak........kaak....",
      ".....kak.........kk.....",
      "......k.................",
      "........................",
    ],
  },
  // 十字を彫った星鉄の墓標が斜めに折れた上半分 (地肌に星の瞬き)
  m_grave_star_iron: {
    pal: { "a": "#14142a", "H": "#2a2a4c", "K": "#46467a", "M": "#6e6ea8", "P": "#b4b4e0" },
    art: [
      "........................",
      "....................P...",
      ".........kkkkk.....PxP..",
      ".......kkMMMMHk.k...P...",
      "......kMMMMMKPKkak......",
      ".....kMMxMMKKKKHkak..M..",
      "....kMMMMKKaaKKHHkak....",
      "....kMMKKKKaMKKHakak....",
      "....kMKPKKaaaaaHakHak...",
      "....kMKKKKaMMMMHPkaak...",
      "....kMKKKKKaMKHHakaak...",
      "....kMKKKKKaMKHHakaak...",
      "....kMKKKKKaMKHHaKaak...",
      "....kMKKKKKaMHHPKkaak...",
      "....kMKKKHHHHHaaKkaak...",
      "....kMKKHHHHaaaKkkaak...",
      "....kMKKaaaaaakkaakak...",
      "....kMKaPakakkaakakk....",
      "....kMHakkakaakk.k......",
      "....kMakHkaakk..........",
      "....kakkaakk............",
      ".....kkakk..............",
      ".......k................",
      "........................",
    ],
  },
  // 四隅を鋲で留めた石の銘板 (淡く光る刻線・欠けた角)
  m_guardian_tablet: {
    pal: { "a": "#2e2c2a", "H": "#545250", "K": "#807c78", "M": "#aaa6a0", "U": "#e0c068", "V": "#8a6a2a" },
    art: [
      "........................",
      "........................",
      "........................",
      "................kkkk....",
      "..........kkkkkkMMMHk...",
      "...kkkkkkkMMMMMMMMwgk...",
      "..kKMMMMMMMMKKKKaagak...",
      "...kMwgKKKaaaaaaKHMak...",
      "...kMgaaaaKKKKKKKUMak...",
      "...kMKaKKKKUKUUUKVMak...",
      "...kMKaKUUKVKVVVKHMak...",
      "...kMKaKVVKKKKKKKUMak...",
      "...kMKaKKKKUUKUUKVMak...",
      "...kMKaKUKUVVKVVKHMak...",
      "...kMKaKVKVKKKKKKHaak...",
      "...kMKaKKKKKUKUUKaMak...",
      "...kMKaKUUUKVKVVHaMak...",
      "...kMKaKVVVKKKKHaaawgk..",
      "...kMKaHHHHMMMMaaakgk...",
      "...kMwgMMMMHHaaakkkk....",
      "...kHgaaaaaaaaak.kKHk...",
      "....kkkkkkkkkkk..kHak...",
      "..................kk....",
      "........................",
    ],
  },
  // 大腿骨の柄に黒いリボンを結んだ紫がかった青銅の弔い鈴 (骨の舌)
  m_ossuary_key: {
    pal: { "a": "#20162a", "H": "#3e2c48", "K": "#664a6c", "M": "#94788e", "P": "#c0a8b4" },
    art: [
      "........................",
      "..........kkkk..........",
      ".........kxBBIk.........",
      ".........kIBIzk.........",
      ".......kk.kBzkk.........",
      "......kCCkkBzCCk........",
      "......kfACkBCAfk........",
      ".......kfCkkCfk.........",
      "........kfPPfMHk........",
      ".......kCMPMMCak........",
      "......kCkPMMKaCk........",
      ".......kPPPMKHKHk.......",
      ".......kMPMKKKHak.......",
      ".......kPMMKKHaak.......",
      "......kPPPMKKKHKHk......",
      "......kPPMKKKKKHak......",
      ".....kHHHaaaaaaaaak.....",
      "....kMMMMMKKKKKKKKKk....",
      "...kMaaaaaaaaaaaaaaak...",
      "....kkaaaaaIBaaaaakk....",
      "......kkkkkzBkkkkk......",
      "..........kBIk..........",
      "...........kk...........",
      "........................",
    ],
  },
  // 三対の肋骨と胸骨。胸骨に青い誓いの紐が掛かり、頭に銀の印が残る
  m_oath_rib: {
    pal: { "a": "#2c2a26", "H": "#e2dccb", "K": "#1e2a3c", "M": "#3c5674", "Q": "#6f90b0", "T": "#a7c2da" },
    art: [
      "........................",
      "...........kk...........",
      "..........kHzk..........",
      ".......kkkzxxzkkk.......",
      "......kHHHxxwvHHzk......",
      ".....kHHzzzwvzzzBzk.....",
      "....kHHzkkkHzkkkzBzk....",
      "...kHHzkkkHHzKkkkzBzk...",
      "...kHzkHHHBTTKHHzkHzk...",
      "...kHHHBzTTKKzzzBHBzk...",
      "...kHBzzkKKHzMkkzzBzk...",
      "...kHzkkkkHHMzMkkkHzk...",
      "..kHBzkHHHBHMBMHzkHBzk..",
      "..kHBBHBzzzBMzzMBHBBzk..",
      "..kHBBBzkkkBzkkMzBBIzk..",
      "..kHBBzk..kBzkkKkzIIzk..",
      "..kHBzk...kzzk.k.kBIzk..",
      "..kzBzk....kk....kzIzk..",
      "...kzk............kzk...",
      "...kzk............kzk...",
      "...kHzk..........kBzk...",
      "...kzzk..........kzzk...",
      "....kk............kk....",
      "........................",
    ],
  },
  // 灰色の祭服 (紫鼠のストラを垂らす)。裾が崩れて灰の粒となって零れる
  m_ash_woven_vestment: {
    pal: { "a": "#1f1f23", "H": "#3d3d43", "K": "#5f5e63", "M": "#86847f", "Q": "#b2aea4", "T": "#d6d1c4", "U": "#4a3f52", "V": "#6e6078" },
    art: [
      "........................",
      "..........kkkk..........",
      "........kkaaaakk........",
      "......kkQQaaaaQHk.......",
      ".....kQQQVVQQMVVHkk.....",
      "....kQQQQVVQMMVVMQHk....",
      "...kQQQQQVVMMMVVMMMHk...",
      "...kQQQQQVVMMMVVMMMHk...",
      "..kQQQQQKVVMQKVVQKMMHk..",
      "..kQQQQMMVVMMMVVMMMKHk..",
      "..kHQQHMMVVMMMVUMMHKHk..",
      "...kHHHMMVUMMMVUMKHHk...",
      "....kkHMMVVMMMUUKHHk....",
      ".....kQMMVVMMMUUKHk.....",
      ".....kQQKVVMQKUUQKk.....",
      ".....kQMMVVMKKUUKHk.....",
      ".....kQMMVVKKKUUKHk.....",
      ".....kHHHVVkHHUUkHk.....",
      "......kkkVk.kkUUkk......",
      ".........k....kk........",
      ".......M.....Q...M......",
      "..........Q....M...M....",
      "......M.................",
      "........................",
    ],
  },
  // 舟に立って竿をさす頭巾の渡し守を浮き彫りにした冥府の銀貨 (縁に墓土のしみ)
  m_ferrymans_fee: {
    pal: { "a": "#20242f", "H": "#3b4253", "K": "#5d677e", "M": "#8a95ac", "Q": "#bdc6d6", "T": "#e6ecf4", "U": "#2a3a3c" },
    art: [
      "........................",
      "........................",
      "........kkkkkkkk........",
      ".......kQQQQQQQQk.......",
      ".....kkQTQHHHHQQMkk.....",
      "....kQQTHHKKKTHHMMMk....",
      "....kQTHKKKKKTHKHMMk....",
      "...kQTHKKMKKKKTKKHMKk...",
      "..kQQHKKKQQKKKTKKKHKKk..",
      "..kQQHKKQQHKKKTHKKHKKk..",
      "..kQHKKKQQMMMKTKKKKHKk..",
      "..kQHKKKQQQHKKKTKKKHKk..",
      "..kQHKKQQQQQHKKTHKKHHk..",
      "..kQHKQQQQQQHKKTKQHHHk..",
      "..kQQHKQKMMMMMMTQHHHHk..",
      "..kMMHKHQQQQQQQQTKHHHk..",
      "...kMMHKHHHHHHHHTHHHk...",
      "....kMMHKKKKKKKKTHUk....",
      "....kKKKHHKKKKHHHUak....",
      ".....kkKKKHHHHHHUkk.....",
      ".......kKHHHHHHak.......",
      "........kkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  // 瞳に黄金の山が映り込んで固まった金色の虹彩の眼球 (視神経を垂らす)
  m_gold_seared_eye: {
    pal: { "a": "#3e3028", "H": "#7e6c5e", "K": "#b9aa98", "M": "#e6dccb", "Q": "#fff6e2", "T": "#5a1c22", "U": "#2a0c10", "V": "#f6e2a0" },
    art: [
      "........................",
      "........................",
      "..........kkkkk.........",
      "........kkQQQMMkk.......",
      ".......kQQQQQOOMKk......",
      "......kQQQQOOYYOOKk.....",
      ".....kQQQQOYYYYYYOHk....",
      "....kQQQQOYYYYYYyyOak...",
      "....kQQQQOYYVVkkyyOak...",
      "....kQrQOYYYkkkkyooOk...",
      "....kQQrOYYYkkYkkoOOk...",
      "....kMQQQOYYoyyyooOak...",
      "....kMMMMOyyyykooOOak...",
      "....kKrMMMOyooooOOaak...",
      "....kKKKKKKOOoOOOaaak...",
      ".....kHKKKKHHOOaaaak....",
      "....kkmHHrHHHaaaaark....",
      "...kmmrraaaaaaaaakk.....",
      "...kmrrUUkaaaaakk.......",
      "..kmrUUkk.kkkkk.........",
      ".kUrUkk.................",
      "..kUk...................",
      "...k....................",
      "........................",
    ],
  },
  // 首長の丸底フラスコに汲まれた暗紅の血 (口から外へ一筋垂れている)
  m_challenger_blood: {
    pal: { "a": "#1c080c", "H": "#2a3038", "K": "#4c5866", "M": "#8a9aa8", "Q": "#d6e0e6", "T": "#d88070" },
    art: [
      "........................",
      "..........kkkk..........",
      ".........kLLLDk.........",
      ".........kDDDDk.........",
      "........kQQQQQHk........",
      "........kHHHHHRk........",
      ".........kQMKHrk........",
      ".........kQKKHkrk.......",
      ".........kMKKHkrk.......",
      ".........kMrrHkrk.......",
      ".......kkMKrrKHqk.......",
      "......kMMRrRRraMHk......",
      ".....kMKQTrrrrraKHk.....",
      ".....kMQTrrrrrrraHk.....",
      "....kMKQrrrrrrrraHHk....",
      "....kMaQrrrrrrqqqaHk....",
      "....kHKRrrrrrqqqaHHk....",
      ".....kMarrrrqqqqaHk.....",
      ".....kHKarqqqqqaHHk.....",
      "......kHHaaaaaaHHk......",
      ".......kkHHHHHHkk.......",
      ".........kkkkkk.........",
      "........................",
      "........................",
    ],
  },
  // 内に灯りを宿す琥珀金色の涙の形の結晶 (切子面と輝き)
  m_dragon_tear_stone: {
    pal: { "a": "#3a2208", "H": "#7a4a10", "K": "#bc8420", "M": "#e8bc4c", "Q": "#fff0b4", "T": "#5a3410" },
    art: [
      "........................",
      "........................",
      "...........kk...........",
      "..........kMMk..........",
      "..........kQMk..........",
      ".........kQQMQk.........",
      ".........kQQMQk.........",
      "........kQQQMQMk........",
      "........kQQQMQMk........",
      ".......kQQQQMQMMk.......",
      "......kQQQQQQMMMKk......",
      "......kQQTQQMMMTKk......",
      ".....kQQQQTMMMTKKHk.....",
      ".....kQQQQMTHTKKHHk.....",
      ".....kQQMMMMHKKKHHk.....",
      ".....kMMMMKKKHHHHak.....",
      ".....kMMKKKMQKHHHak.....",
      "......kKKKKMMHHaak......",
      "......kKKKHHHHaaak......",
      ".......kHHHHaaaak.......",
      "........kkaaaakk........",
      "..........kkkk..........",
      "........................",
      "........................",
    ],
  },
  // 革袋の口から鱗状の金片がこぼれ、溶け合って金だまりになっている
  m_hoard_flake_pouch: {
    pal: { "a": "#fff2b8" },
    art: [
      "........................",
      "........................",
      "......kkkkkkk...........",
      ".....kYYYYYYOk..........",
      "....kOyyyyyyoOk.........",
      ".....kOOOOOOOk..........",
      "......kLLLlDk...........",
      ".....kLLLlllDk..........",
      ".....kDDDDDDDNk.........",
      "....kLLllllllNk.........",
      "...kLLllllllllNk........",
      "...kLLlldlllllNkk.......",
      "..kLLlLlllldlYaYyk......",
      "..kLlllllllllYyyokk.....",
      "..kLlLldlllldddYaYyk....",
      "..kDllllllldYaYyyyokk...",
      "...kLlllllldYyyokYaYyk..",
      "...kDllldlddddYaYyyyok..",
      "....kDlllddYaYyyyokYYk..",
      ".....kDDdddYyYYYYYYaOyk.",
      "......kkDDDkkOOOOOOOOk..",
      "........kkk..kkykkkkk...",
      "...............k........",
      "........................",
    ],
  },
  // 左から満ちかけている月を宿した珠と、喪の黒帯を結んだ黒鉄の高坏
  m_mourning_moon_orb: {
    pal: { "a": "#f2f0fa", "H": "#cdc8e0", "K": "#9b96b8", "M": "#4a4668", "Q": "#2a2840", "T": "#17162a" },
    art: [
      "........................",
      "........................",
      "........kkkkkkkk........",
      ".......kaaaaaaTTk.......",
      "......kaaaaaaQQTTk......",
      ".....kaaaaaaaQQTTTk.....",
      "....kaaaaaaaQQQTTTTk....",
      "....kaaaKKaaQQQTTTTk....",
      "....kaaaaaaaQQTTTTTk....",
      "....kaaaaaaKQQTTTTTk....",
      "....kaaaaaaaQTTTTTTk....",
      "....kaaKaaaaTTTTTTTk....",
      "....kaaaKaaaTTTTTTTk....",
      "....kHHaaHKHTTTTTTTk....",
      ".....kHHHHHHKTTTTTk.....",
      "......kKKKKKKTTTTk......",
      ".......kkvvvvvkTk.......",
      "........kfffFfffk.......",
      ".........kkCkCkk........",
      ".........kfvkkfk........",
      "........kCkkkkkCk.......",
      ".........kkkkk.k........",
      "........................",
      "........................",
    ],
  },
  // 成長の輪が刻まれた太く反った角の先と、白い髄の断面がのぞく砕けた根元
  m_elder_horn_shard: {
    pal: { "a": "#24180a", "H": "#5a3e18", "K": "#8c6a2c", "M": "#c09a50", "Q": "#e8d08a", "T": "#f4ead0", "U": "#3a2810" },
    art: [
      "........................",
      "..................kkk...",
      "...............kkkMaak..",
      ".............kkMMMakk...",
      "...........kkMMKaak.....",
      "..........kMUKKakk......",
      "........kkQMUMak........",
      ".......kQMUMKUk.........",
      "......kUQMUUak..........",
      ".....kQMUMMKUk..........",
      ".....kUQKUUak...........",
      "....kMMUMKKak...........",
      "...kUQKKUUUk............",
      "...kMUUMKKak............",
      "..kMKKKUUUUk............",
      "..kMKKKKKKak............",
      "..kKKKKKHKak............",
      ".kKKTTTMKKak............",
      "..kMQKKMKak.............",
      "..kKMMMKKk..............",
      "..kHaKKaak..............",
      "...kkkakk...............",
      "......k.................",
      "........................",
    ],
  },
  // 金の冠が溶けて垂れ落ち、尖塔が曲がったまま頭蓋に溶け付いている
  m_crown_fused_skull: {
    pal: { "a": "#fff0b0", "H": "#1a1412" },
    art: [
      "........................",
      "........................",
      "........................",
      "...........k............",
      "....k.....kak......k....",
      "...kak..kkkOkkkk..kOk...",
      "...kOOkkOxxYOxBBkkyOk...",
      "....kYOxYYYyOxYOByoOk...",
      "...kOyyYyyyyyyooyooOk...",
      "....kOOOcOOOrOOOcOOk....",
      "....kxxxxxxxxBBBIIzk....",
      "...kxxYxYxxxxYBYIIYzk...",
      "...kxxyHoHHBByHoHIyzk...",
      "...kBxoHHHHBByoHHzyzk...",
      "....kBBHHHHBByHoHzyk....",
      "....kBBBBBBBIoIzzzyk....",
      ".....kIBxxxxHxxzzzok....",
      "......kIxxBHHBBzzkk.....",
      ".......kxzzzzzzzk.......",
      ".......kxBzBzBzBk.......",
      ".......kzzzzzzzzk.......",
      "........kkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  // U 字の足枷 (下に切れた鎖の輪) の両耳を貫く、頭に輪のある赤錆の留め針
  m_rusted_shackle_pin: {
    pal: { "a": "#2a1610", "H": "#5a2c18", "K": "#8a4a2a", "M": "#b8703c", "Q": "#d89a5a", "T": "#3a2c28", "U": "#5e4a40" },
    art: [
      "........................",
      "........................",
      "...kkkkk........kkkk....",
      "..kQaaKakkkkkkkkKKKak...",
      ".kaaKaQMMQMMMMQKKKKKKk..",
      "..kaQaaaaaaHaaaaHaaaaKk.",
      "...kaKKakkkkkkkkkKUakKk.",
      "....kKKak.......kKUakk..",
      "....kKKak.......kKUak...",
      "....kKKak......kKUTak...",
      "....kKKak......kKTTak...",
      "....kaKak......kUTak....",
      ".....kKUakk..kkUTKk.....",
      ".....kaUKKakkUUTTak.....",
      "......kaaUUKUTTaak......",
      ".......kkaaaaaakk.......",
      ".........kkKaKk.........",
      ".........kKaaak.........",
      ".........kakkak.........",
      ".........kakkak.........",
      ".........kaKUak.........",
      "..........kaak..........",
      "...........kk...........",
      "........................",
    ],
  },
  // 指の骨を削った不揃いな骰子二つ (大きい方の上の目は赤い一つ)
  m_prisoners_dice: {
    pal: { "a": "#1e1814", "H": "#e0d6bc" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      ".......kk...............",
      ".....kkBBkk.............",
      "...kkBBBBBBkk...........",
      "..kHBBBqqBBBBk..........",
      ".kBBBBBrrBBBBk..........",
      ".kBBBBBBBBBzzk..........",
      ".kBBaIIBBIzzak..........",
      ".kBIIIIIIIzzzk.kkk......",
      ".kBzIIIIIzzazkkHBBkk....",
      ".kIIIIIIzazzzHHBaBBBk...",
      ".kIIIIaIzzzBHBaBaBBBBk..",
      "..kkIIIIzzzBBIBBBBazzk..",
      "....kIIIzzzBIIIBBIzzzk..",
      ".....kkIzkkIIaIIIzzzak..",
      ".......kk.kIIIIIzzzzzk..",
      "...........kkIaIzzazk...",
      ".............kIIzzkk....",
      "..............kkkk......",
      "........................",
      "........................",
    ],
  },
  // 鍵束の鉄の輪 (小鍵が一本残る) に吊られた真鍮の印形
  m_warden_signet: {
    pal: { "a": "#2e2010", "H": "#6a4a1a", "K": "#a9781f", "M": "#d6a848", "Q": "#f0d488" },
    art: [
      "........................",
      "........k...............",
      ".....kkkekkk..k.........",
      "....kwweeewekkak........",
      "...kwwekkkeveQaak.......",
      "...kwek...keaakQak......",
      "...kek.....keaQak.......",
      "..keek.....kvQQMk.......",
      "...kek.....kQQMKak......",
      "...kwek...kveMMak.......",
      "...kevekkkvgeMKak.......",
      "....keeeveeekMKak.......",
      "...kweekekkkkMKak.......",
      "...kekekk..kMMMak.......",
      "...keeek...kMQKKak......",
      "...kevk...kMMKKKKak.....",
      "...kevk..kMKQKKHHHak....",
      "....kvk..kaQMMMMMaak....",
      "....kvk.kMMMMMMMMMMak...",
      "....kvgkkaHHHHHHHHHHk...",
      "....kvk..kkaaaaaaakk....",
      "....kggk...kkkkkkk......",
      ".....kk.................",
      "........................",
    ],
  },
  // 節ごとに細い脚の並ぶ大百足の抜け殻 (背が裂けて中空、頭に触角)
  m_centipede_husk: {
    pal: { "a": "#1e2410", "H": "#3e4a1e", "K": "#6a7e36", "M": "#9cae66", "Q": "#cbd59a", "T": "#8a7440", "U": "#6a5530" },
    art: [
      "........................",
      "...........TT.....kkT...",
      ".............Ukk.kQHk.T.",
      ".............kQHkkQakT..",
      "........TTUkkkQMHkHHk...",
      "..........kQHkHMHkkk....",
      "..........kHaHkHHk......",
      "........UkQHHHHkk.......",
      "......TTkHMaHkkUT.......",
      ".........kHHHHkTT.......",
      ".......UkQQQHkUT........",
      "......TTkHaHHkUT........",
      "........kQQHk.T.........",
      "......TkHHaMHk.T........",
      "......T.kQHHk.T.........",
      "..T.T.TkHMaQHk.T........",
      "...TUTUkQHHHkUT.........",
      "...kkTkQHMaHk.T.........",
      "..kQHkQHMHHHkU..........",
      "..kQHkQHHaHk.T..........",
      "..kQHkHHkHHk.T..........",
      "..kHHkkHkkkU............",
      "...kk..k..T.............",
      "........................",
    ],
  },
  // 太いコルクの寸胴瓶に詰まった青緑に光る苔 (瓶の脇に光の尾)
  m_phosphor_moss_jar: {
    pal: { "a": "#0f2a20", "H": "#1f5a42", "K": "#3fae78", "M": "#86e6b0", "Q": "#dcfff0", "T": "#2a3640", "U": "#4e6270", "V": "#9ab8c4" },
    art: [
      "........................",
      "........................",
      ".......kkkkkkkkk........",
      "......kNNNNNNNNSk.......",
      "......kNNnnnnnnSk.......",
      "......kNnnnnnssSk..K....",
      "......kDDDDDDDDDDk......",
      ".......kVVVVVVVTLk..M...",
      "......kVVVVVUUUTkLk.....",
      ".....kVVVVVUUUMUTk.K....",
      ".....kVVVVUUUMMMUTk.....",
      ".....kVQMMMMMMMKKTk.....",
      ".....kMQMMMQMMKQKTk.....",
      ".....kMQQMMMMMKKKTk.....",
      ".....kMMMMUUKKKKHTk.....",
      ".....kMMMMMKKQKHHTk.....",
      ".....kVMMQKKKKHHHTk.....",
      ".....kVKKKKKKHHHaTk.....",
      ".....kVKKKKHHHHaaTk.....",
      ".....kTHHHHHHaaaaTk.....",
      "......kkHHHaaaakkk......",
      "........kkkkkkk.........",
      "........................",
      "........................",
    ],
  },
  // 返しの付いた幅広の錆びた矢じり (刃縁に研ぎ目が光る) と袋穂、折れた矢柄
  m_siege_arrowhead: {
    pal: { "a": "#2a1610", "H": "#5a2c18", "K": "#8a4a2a", "M": "#b8703c", "Q": "#d8d4c8" },
    art: [
      "........................",
      "...................kk...",
      "...............kkkkQQk..",
      "............kkkQQQQHak..",
      "...........kQQQMMMHak...",
      "..........kMMKKMMHKak...",
      ".........kMMKKKMHKHak...",
      "........kMMKKMMHKHak....",
      "........kaaaMaHKHHak....",
      ".........kkMKKaHHHak....",
      ".........kMKKKaHHHak....",
      "........kMKaKaKHHak.....",
      ".......kMSKKakKHak......",
      ".......kNnSakkaak.......",
      "......kNnSak..kk........",
      ".....kNnSkk.............",
      "....kNnSk...............",
      "...kSnSk................",
      "....kSk.................",
      "...kNk..................",
      "....kNk.................",
      ".....k..................",
      "........................",
      "........................",
    ],
  },
  // 金の透かし枠に桃色の宝玉を据え、真珠の雫を下げた襟の留め金
  m_chatelaine_brooch: {
    pal: { "a": "#3a1020", "H": "#7a2a4a", "K": "#b04a78", "M": "#d36b9a", "Q": "#f6c0d6", "T": "#e8e2ea", "U": "#a8a0b4" },
    art: [
      "........................",
      "...........kk...........",
      "..........kYOk..........",
      ".........kOyyOk.........",
      ".......kkYYYYYOkk.......",
      "......kYYYOOOOyYOk......",
      ".....kYYOOQQQQOOYOk.....",
      "...kkkYOQQQQQMMKOOkkk...",
      "..kYOYYOQQQQQMKKOyOYOk..",
      "..kYyYOQQQQQMMKHaOOyOk..",
      "..kYyYOMQQQMMKKHaOOyOk..",
      "..kOOOyOMMMMKKHaOoOOOk..",
      "...kkkYOKKKKHHaaOOkkk...",
      ".....kOYOOHHaaOOoOk.....",
      "......kOOyOOOOoOOk......",
      ".......kkOOOOOOkk.......",
      ".........kOyyOk.........",
      "..........kOOk..........",
      "..........kTUk..........",
      ".........kTxTUk.........",
      ".........kUTTUk.........",
      "..........kUUk..........",
      "...........kk...........",
      "........................",
    ],
  },
  // 名を刻んだ線の残る鉛の小札と、切れた革紐 (縁に刃傷の欠け)
  m_mercenary_tag: {
    pal: { "a": "#22242c", "H": "#454852", "K": "#6c707c", "M": "#959aa4", "Q": "#bcc0c6" },
    art: [
      "........................",
      ".....kk.................",
      "....kLLk.........kk.....",
      ".....kLLk.......klLk....",
      ".....kLlk......kllk.....",
      "......kllk....kllk......",
      ".......kllk..kllk.......",
      ".......kldkkkllk........",
      ".......kkddMllMak.......",
      "......kMMMdDDKKak.......",
      ".....kMMMMkkkKKak.......",
      ".....kaMMMMKKKKak.......",
      "......kMMMKKaaaKak......",
      "......kMMaaaKKKKak......",
      "......kMKKQKaaaaak......",
      "......kMKaaaKKQHak......",
      "......kaKKQKaaHHak......",
      ".......kMKaaKHHHHak.....",
      ".......kMKKKKHHHHak.....",
      ".......kMKKKHaaaaak.....",
      ".......kaaaaakkkkk......",
      "........kkkkk...........",
      "........................",
      "........................",
    ],
  },
  // 横倒しになったくさび形の要石 (目地のしっくいの残り、鑿の跡とひび、苔)
  m_battlements_keystone: {
    pal: { "a": "#1e1e24", "H": "#3e3e46", "K": "#64646c", "M": "#8e8c90", "Q": "#b8b4ae", "T": "#d8d2c6", "U": "#a89c84" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      ".....kkkk...k...........",
      "....kTTTTkkkhk..........",
      "...kTTTTUUQGGk..........",
      "..kTTTTQQQUQQQkk........",
      ".kMTTQQQQQQQQQUQkkk.....",
      ".kMMMTTTTQQQQQQQQGQkk...",
      ".kMMMMMMMTTTTQQQQQGQQk..",
      ".kMMMMKMMMMMMTTTTQQQHk..",
      ".kMMMMMHMMKMMMMMMTTHHk..",
      ".kMMMMMMMMMHMMKMaKKHk...",
      ".kMMUMMMMMMMMMMaKKKk....",
      ".kMMMMMKMMMKMMKKkkk.....",
      ".kMMMUMMHMMMHkkk........",
      ".kMMMMUMMkkkk...........",
      "..kHMMkkk...............",
      "...kHk..................",
      "....k...................",
      "........................",
      "........................",
    ],
  },
  // 砕けた石の指の節 (白い割れ口と地衣のしみ) から鉤に曲がって伸びる石の爪
  m_gargoyle_chip: {
    pal: { "a": "#1c1c22", "H": "#3a3a44", "K": "#5e5f6a", "M": "#8a8b94", "Q": "#b8b6b2", "T": "#d8d2c4", "U": "#2c3a28", "V": "#5a7048" },
    art: [
      "........................",
      "........................",
      "........................",
      "........kkkkkk..........",
      ".....kkkMMMMMakkk.......",
      "...kkaMMVVMMMKMMak......",
      "..kTMaMMMUVMMKKKKak.....",
      ".kTTTMMMMMMMKKKKKKak....",
      ".kTMTaMMMMMKKKKKKKak....",
      ".kTTTaMMMMKKKKKKKKHak...",
      ".kMTQaaaMKaaaaaaKHHak...",
      ".kTTQaaaaakkkkkkMHHak...",
      "..kkkkkkkk.....kaHHak...",
      "................kMHak...",
      "................kMHak...",
      "................kMHak...",
      "...............kKHak....",
      "...............kKHak....",
      "...............kKak.....",
      "..............kKak......",
      ".............kaak.......",
      "..............kk........",
      "........................",
      "........................",
    ],
  },
  // 後家のかぶり布 — 顔のない闇を包む黒い被り布、顎の下にほどかれなかった結び目
  m_widows_veil: {
    pal: { "a": "#9a98ac" },
    art: [
      "........................",
      "..........kkkk..........",
      "........kkACCfkk........",
      ".......kAAAACCffk.......",
      "......kAAAAACCCffk......",
      ".....kAAAAaAaCaffFk.....",
      ".....kAAAAAkkAAffFk.....",
      "....kAAAAkkkkkkAfFFk....",
      "....kCAAakkkkkkAaFFk....",
      "....kCAAAkkkkkkAfFFk....",
      "....kCACAkkkkkkAfFFk....",
      "....kCACakkkkkkAaFFk....",
      "....kCACAkkkkkkAfFFk....",
      "...kCCCCfAkkkkAffFFFk...",
      "...kCCCCFkkAkkffFfFFk...",
      "...kCCCCkAakaAkfFCFFk...",
      "...kCCCFkCAAACkffCFFk...",
      "...kCCCFfkkAkkfffFCFk...",
      "...kfCfFffkCAkfFFFCFk...",
      "..kffCFFFkCkkCkFFFFFFk..",
      "..kFFFFFFkCkFkCkFFFFFk..",
      "...kkkkkkAk.k.kAkkkkk...",
      ".........k.....k........",
      "........................",
    ],
  },
  // 呪われた戦勝貨 — 房飾りの兜の将の横顔を打ち出した金貨、顔を裂く紫のひびと怨みの靄
  m_cursed_war_coin: {
    pal: { "a": "#a07ac8", "H": "#5e4680", "$": "#5e4680" },
    art: [
      "........................",
      ".................$......",
      "................$.$.$...",
      "........kkkkkkk$...$....",
      ".......kYYYYYYOkk.......",
      ".....kkYYoooooYOOk......",
      "....kYYoooOOOoyOyyk.....",
      "....kYoooOYYYOoOJyOk....",
      "...kYoooOYYyyyOJooyOk...",
      "...kYooOYyyyyyyaooHOk...",
      "..kYoooOOOOOyyJOoOoyOk..",
      "..kYooOYoyyyyyJoOOoyOk..",
      "..kYooOYyyyyyyOJOOoyOk..",
      "..kYoooOYyyyyyOJOOoyOk..",
      "..kYooooOYyyyOaOOOoyOk..",
      "...kyHoooOYyyOJOOoyOk...",
      "...kyoooOYYyyJOOOHyOk...",
      "....kyHOYyyyyyJOoyOk....",
      "....kyyooOOOOOJoHyOk....",
      ".....kkyyoooooyyOOk.....",
      ".......kyyyyyyyOkk......",
      "........kkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  // 錬金術師の残りかす瓶 — 栓をした丸底フラスコ、底に虹色のおりが層をなす
  m_alchemist_residue: {
    pal: {  },
    art: [
      "........................",
      "...........kkk..........",
      "..........kNNNk.........",
      ".........kNNnnsk........",
      ".........kNnnssk........",
      "........kvvvgggk........",
      ".........kvgggk.........",
      ".........kvgeek.........",
      ".........kgweek.........",
      "........kkgweekk........",
      ".......kvgggeeeek.......",
      "......kvvgggeejeek......",
      ".....kvvgxeeeeepeek.....",
      ".....kvgxeeeeeeejek.....",
      "....kvggweeeeeeeeeek....",
      "....kgggYYReeeeYYeek....",
      ".....kgYYhYYYYYYhek.....",
      ".....kghhhhhhhhhhek.....",
      ".....kggbbbbbbbbeek.....",
      "......kgeppppppeek......",
      ".......keeeeeeeek.......",
      "........kkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  // こだま貝 — 殻を閉じた巻貝、口の奥が青く光り声の波紋が漏れる
  m_chasm_echo_shell: {
    pal: { "H": "#3e6f86" },
    art: [
      "........................",
      "........................",
      "...................k....",
      "..................kIk...",
      "................kkzIk...",
      "...............kzxIzk...",
      "............kkkxxzxIk...",
      ".........kkkxxxzxxIk....",
      ".......kkxxxzxxxzIzk....",
      "......kxxxxxxzxxIzzk....",
      ".....kxxxxxxxBzBxzzk....",
      "....kxxxxxBBBxBzIxk.....",
      "....kxxmmBBBBBxIzzk.....",
      "...kxxmkkmBBBmIxzk......",
      "...kxmkkkkmBBIIzk.......",
      ".HckmkkkkkmmBIzzk.......",
      "....kkuckkmIIIzzk.......",
      ".Hc.kkkbkmIImzzk........",
      "....kkukummzzzk.........",
      "...ckkkkmzzzkk..........",
      ".....k..kkkk............",
      "....H...................",
      "........................",
      "........................",
    ],
  },
  // 虚蛾の鱗粉袋 — 眼状紋の大蛾を縫い付けた灰の袋、綻びから漆黒の鱗粉がこぼれる
  m_void_moth_dust: {
    pal: { "a": "#9496aa", "$": "#1a1424", "%": "#8a6aaa" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "........kkkkkkk.........",
      ".......kaafafCfk........",
      ".......kafaaACCk.k......",
      "........kaafAfk.kLk.....",
      "........kaaaCCkklk......",
      ".......kaDDDDDDlk.......",
      "......kkaaaAAACkk.......",
      ".....kjjkkaAAkkjjk......",
      ".....kjiijkAkjiijk......",
      "....kkjixjjkjjxijkk.....",
      "...kakJjjjjDjjjjJkfk....",
      "...kaakJjjkDkjjJkCfk....",
      "...kAaakjjkDkjjkCffk....",
      "....kAAkJkAkAkJkffk.....",
      "....kCCAkCCCCCkfffk.....",
      ".....kCCCCCCCCfffk$..%..",
      "......kkCCCffffkk..$%...",
      "........kkkkkkk...%$.$..",
      "....................$...",
      "........................",
    ],
  },
  // 墜ちた者の結び縄 — 命綱の輪と固く締まった結び目、片端は千切れてほつれる
  m_fallen_rope_knot: {
    pal: {  },
    art: [
      "........................",
      "..........kkkk..........",
      "........kkLLNLkk........",
      ".......kLLnnnNnNk.......",
      ".......kNnskkNNnk.......",
      "......kLNsk..knnnk......",
      "......kLsk....kLsk......",
      "......kLkkk..kkksk......",
      ".......kNLLkkLLNk.......",
      ".......kLLnkLLnsk.......",
      "........kkkkkkkk........",
      ".......kLLNLLLnnk.......",
      ".......knkknskksk.......",
      "........kLnkkLNk........",
      ".......kNLskkLLNk.......",
      ".......kLnskkLnNnk......",
      "......kLNsk..kNNsk......",
      "......kLnsk...kNnskk....",
      ".....kLLsk....kNsNkLk...",
      ".....kNNsk.....knkNkk...",
      ".....kNssk......knkkNk..",
      "......ksk......knk..k...",
      ".......k........k.......",
      "........................",
    ],
  },
  // 蒼き提灯の硝子 — 鉄枠の角が残る青く濁った硝子片、芯の燐光が冷たくくゆる
  m_pale_lantern_glass: {
    pal: { "a": "#b4dcec", "H": "#4f86a8", "@": "#3b6c8a" },
    art: [
      "........................",
      "..........kk............",
      ".....kkkkkwgkk..........",
      "...kkwwwwwxekHkkkkk.....",
      "..kwwxvggeekccHbbuuk....",
      "..kwwvekkkkaccHbbuuk....",
      "...kwgkaaaaacHHbuuuk....",
      "...kvgkaaaaccHbbuuuk....",
      "...kvekuaaaccHubuuk.....",
      "...keekuaaaccHbuuuk.....",
      "....kkaauaaxaHbbuuuk....",
      "....kaaauacacHbuuuuuk...",
      "...kccaaauacHcbuuuuuk.@.",
      ".@.kHccaauacHHbuuuuuk...",
      "....kkccaucHHbuuukkk....",
      "..@...kkccbHbbuuuk...@..",
      ".......kccHHkkuuuk......",
      "........kcHk..kuuk......",
      "........kHHk...kuk......",
      "........kHk.....k.......",
      "........kHk.............",
      ".........k...@..........",
      "..........@...@.........",
      "........................",
    ],
  },
  // 奈落の塩 — 骸晶の段が刻まれた青白い立方の塩の結晶
  m_abyss_salt: {
    pal: { "a": "#dde4ee", "H": "#a8b2c6", "K": "#737c94", "M": "#4e5468", "x": "#f6f8fb" },
    art: [
      "........................",
      "........................",
      "...........kkkkkkkk.....",
      "..........kxxxxxxxHk....",
      ".........kxaaaaaaHHk....",
      "........kxaaaaaaHHMk....",
      ".......kaaaaaaaaHMMk....",
      ".......kaHHHHHHKMMMk....",
      ".......kaHaaaaHKMMMk....",
      "......kkkkkkkaHKMMMk....",
      ".....kxxxxxxHkHKMMMk....",
      "....kxaaaaaHHkHkkkkkk...",
      "...kxaaaaaHHMkkxxxxxHk..",
      "..kaaaaaaaHMMkxaaaaHHk..",
      "..kaHHHHHKMMkaaaaaaHMk..",
      "..kaHaaaHKMMkaHHHHKMMk..",
      "..kaHaHaHKMMkaHaaHKMMk..",
      "..kaHaaaHKMMkaHaaHKMMk..",
      "..kaHHHHHKMMkaHHHHKMMk..",
      "..kaKKKKKKMkkaKKKKKMak..",
      ".kakkkkkkkkaKkkkkkkkk...",
      "..k........kk...........",
      "........................",
      "........................",
    ],
  },
  // 水死人の竪琴弦 — 藻の絡む朽ちた竪琴、切れた弦の中にただ一本だけ張った弦
  m_drowned_lyre_string: {
    pal: { "^": "#6aa6c4" },
    art: [
      "........................",
      "....kkk..........kkk....",
      "...kNNnk........kNNnk...",
      "...kNNnk........kNnsk...",
      "....kknkkkkkkkkkknkk....",
      "......knnnnnnssssk......",
      ".....kNkkkkkkkkkknk.....",
      ".....knskkgkwkgkntGk....",
      ".....knk.kgkwkkgkGhk....",
      "....kNnk..kewkgkkhGk....",
      "....kNGk...kxkkekntk....",
      ".....khk...kxk.kkGtk....",
      ".....ktnk..kwk.kNtk.....",
      ".....kNnk..kwk.kNsk.....",
      ".....knnskkkwkkNnsk.....",
      "......knnkekwkkNsk.^....",
      ".....kNknsgNwkNnksk.....",
      ".....kNksskooknskok^....",
      "......kNkkNnnnkkSk......",
      "......knnnSnnSsSSk......",
      ".......ksSsSSSSSk.^.....",
      "........kkkSSkkk........",
      "...........kk...........",
      "........................",
    ],
  },
  // 水妖の鱗片 — 上辺に放射の溝、核のまわりに虹の成長輪を持つ一枚鱗、雫を滴らせる
  m_nixie_scale: {
    pal: { "a": "#4a8a9e", "H": "#6aa6a2", "K": "#9a8ab8", "M": "#b898bc", "j": "#30485c", "^": "#6aa6c4", "m": "#dcc4d4" },
    art: [
      "........................",
      "........................",
      "......kk.kk..kk.kk......",
      "....kkmjkijkkcjkKmkk....",
      "...kmmiijccjcjcijjmMk...",
      "...kmmiiijjjcjcjKKMMk...",
      "...kmmiiiccjjjjKKKMMk...",
      "...kmmiicHHHHHHHKpMJk...",
      "...kmmpixHHHHHHKKjJJk...",
      "...kmmpxKHHHHHHKKjJJk...",
      "....kmxiKpHHHHpKpjJk....",
      "....kmxiKKpHHpKKpJJk....",
      "....kmmpKKKKKKKpjJJk....",
      ".....kmmpKKKKKpjJJk.....",
      ".....kmmmpKKKKjMJJk.....",
      "......kmmmpppjMJJk......",
      "......kmmmMMMMJJJk......",
      ".......kMMMJJJJJk.......",
      "........kMJJJJJk........",
      ".........kkkkkk.........",
      "........................",
      "............^...........",
      ".............^..........",
      "........................",
    ],
  },
  // 潮に縛られた羅針 — 緑青に覆われフジツボの付いた羅針盤、針は深みへ傾く
  m_tidebound_compass: {
    pal: { "a": "#4e7a62", "H": "#7aa58a" },
    art: [
      "........................",
      "........................",
      "...........kkk..........",
      "..........kHaHk.........",
      ".........kkkkkk.........",
      ".......kkykaHGkkk.......",
      "......kyyykkkkHHak......",
      ".....kyykkBBBBkkaak.....",
      "....kyykLLLLsBBBkaGk....",
      "....kykLLLLBBBBBBkGk....",
      "...kyykLLwBBBBBBBkGGk...",
      "...kykBLLBwBBBBBBBkGk...",
      "...kykBBBBBwBBBBBBkGk...",
      "...kBkBsBBBBOBBBBskGk...",
      "...kHkBBBBBBBrBBBBkGk...",
      "...kaHkBBBBBBBRBBkGGk...",
      "....kBkBBBBBBBBrBkGk....",
      "....kaIkBBBBBBBBqGGk....",
      ".....kBGkkBBsBkkGGtk....",
      "......kzGGkkkkGGGhk.....",
      ".......kBGGGGGGktk......",
      "........kkkkkkk.k.......",
      "........................",
      "........................",
    ],
  },
  // 海女の肺石 — 二葉の肺のかたちに結んだ真珠色の石
  m_pearl_diver_lung: {
    pal: { "0": "#2c3846", "1": "#4c6070", "2": "#7d96a4", "3": "#b6ccd2", "4": "#e6f0ee", "m": "#b8a0b0" },
    art: [
      "........................",
      "...........kk...........",
      "..........k33k..........",
      "..........k32k..........",
      "..........k3k...........",
      "..........k32k..........",
      "..........k31k..........",
      "......kk.k3321k.kk......",
      ".....k44k321111k32k.....",
      "....k444k21kk11k321k....",
      "....k4444kkk4k43321k....",
      "...k444433k444433210k...",
      "...k444433k444332210k...",
      "...k444332k333332210k...",
      "...k333322k333322100k...",
      "...k333221k333221100k...",
      "...k222211k222211000k...",
      "...k222110k122110000k...",
      "....k1110m0k11100m0k....",
      "....k000000kk000000k....",
      ".....kk000k..k000kk.....",
      ".......kkk....kkk.......",
      "........................",
      "........................",
    ],
  },
  // 河伯の涙 — 雫のかたちの硝子瓶に澄みきった水、金の口金
  m_river_god_tear: {
    pal: { "a": "#b4d6e6" },
    art: [
      "........................",
      "...........kkk..........",
      "..........kDkDk.........",
      "...........kkk..........",
      "..........kYyok.........",
      "..........kyoOk.........",
      "...........kkk..........",
      "..........kxxk..........",
      ".........kxxxak.........",
      ".........kxxxak.........",
      "........kxxxxack........",
      ".......kxxxxxacbk.......",
      "......kxxaxxxaacbk......",
      "......kxxxxxaaacbk......",
      ".....kxxxxxaxxabuuk.....",
      ".....kxxxxxxxacbuuk.....",
      "......kxxxaxaacbuk......",
      "......kaaaaaaccuuk......",
      "......kcaaccccuuuk......",
      ".......kcbbbuuuuk.......",
      "........kkuuuukk........",
      "..........kkkk..........",
      "........................",
      "........................",
    ],
  },
  // 香炉の残灰 — 口を開いた麻袋にひとすくいの灰、くすぶりの残り火から細い煙
  m_censer_ash: {
    pal: { "~": "#6c6a72" },
    art: [
      "........................",
      ".............~..........",
      "..........~.~...........",
      "...........~..~.........",
      "...........~............",
      "...........kk...........",
      "........kkkxxkkk........",
      ".......kBxxxxwwLk.......",
      "......kBxxwwvRvgdk......",
      "......kBwvegggggdk......",
      ".......kldddddddk.......",
      ".......kkkkkkkkkDk......",
      "......kBBBBBBLLLLlk.....",
      ".....kBBBlBLLLlLLlk.....",
      "....kBBBBlBLLLlLDklk....",
      "....kBBBBlLLlLLlLllk....",
      "....kBBBlLLLlLLlLldk....",
      "....kLLLlLLLlLLllddk....",
      "....kLLLlLLLlLlllddk....",
      ".....kLLllllllddldk.....",
      "......kkllldldddkk......",
      "........kkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  // 聖歌隊の骨笛 — 指孔の並ぶ細い骨の横笛、色褪せた紫のリボン
  m_choir_bone_flute: {
    pal: { "'": "#8c8aa0" },
    art: [
      "........................",
      "......................'.",
      ".................kkkk'..",
      "................kxxxIk..",
      "................kxxkzk..",
      "...............kxxBzzk..",
      "..............kxxBzzzk..",
      ".............kxxBzzkk'..",
      "............kxxBzzk.....",
      "...........kxxkzzk..'...",
      "..........kxxBzzpjk.....",
      ".........kxxkzzpiJk.....",
      "........kxxIzzpipk......",
      ".......kxxkzkkjpk.......",
      "......kxxzzzk.kpjk......",
      ".....kxxkzkk...kpk......",
      "...kkxxzzzk....kjk......",
      "..kxxxIzkk......k.......",
      ".kxxxIzk................",
      ".kxBIzzk................",
      "..kzzzk.................",
      "...kkk..................",
      "........................",
      "........................",
    ],
  },
  // 聖遺の釘 — 平たい鍛造の頭をもつ赤錆びた長釘、先に古い血がこびりつく
  m_reliquary_nail: {
    pal: { "1": "#5a2a1a", "2": "#86422a", "3": "#a8633e" },
    art: [
      "........................",
      ".......kk...............",
      "......kRRk..............",
      ".....kRR1qk.............",
      "....kRR1qk..............",
      "...kR31qk...............",
      "..kRR1qk2k..............",
      ".kRR1qk222k.............",
      ".kR1qk22222k............",
      "..kqk.k2q322k...........",
      "...k...k22222k..........",
      "........k2q222k.........",
      ".........k22322k........",
      "..........k22q31k.......",
      "...........k2221k.......",
      "............k1112k......",
      ".............kk2q2k.....",
      "...............k222k....",
      "................k21qk...",
      ".................kqqk...",
      "..................krr...",
      "....................q...",
      "........................",
      "........................",
    ],
  },
  // 喪のいろ硝子 — 鉛の桟で区切られた紫・藍・紅・琥珀の色硝子の、ぎざぎざに割れた欠片 (割れ口は鋭く、左上に光筋)
  m_mourning_glass: {
    pal: { "0": "#4e3866", "2": "#24365a", "3": "#b6cfdc", "4": "#9c4240", "6": "#3e2a12", "8": "#52121a", "9": "#8a6a2a" },
    art: [
      "........................",
      ".........kkk............",
      "..kk....k3cbk...........",
      ".kp0kkkk0kccbkkkkkkkk...",
      ".kppppii0kcccbbbbb22uk..",
      ".kpppipp0kccbbbbbc2uk...",
      ".kppiippjkcbbbbbc2uk....",
      ".kpippp0jkb2222uuuk.....",
      ".kii00jjjk2kkkkkkk......",
      "..kkkkkkkkkyyyyyok......",
      "...kr44rr8kyyyy99ok.....",
      "....k4rrr8kyyy999ok.....",
      "...k4rrrrqkyy9oooo6k....",
      "...krrrr8qk9ookkkkk6k...",
      "...krr8q4kkkkkok6666k...",
      "..kr88kkkjjjjJk.kkk66k..",
      "..k8kk..kJjjjJk....kk...",
      "...k.....kjjjJk.........",
      ".........kJjJk..........",
      "..........kjJk..........",
      "..........kJJk..........",
      "...........kk...........",
      "........................",
      "........................",
    ],
  },
  // 葬送の仮面 — 目を伏せた白磁の面、こめかみから垂れる黒い結い紐と額のひび
  m_funeral_mask: {
    pal: { "a": "#e4e4ea", "H": "#b6b6c4", "K": "#868698", "M": "#4e4e5c", "x": "#f8f8fa", "m": "#b89aa4", "f": "#3a3848" },
    art: [
      "........................",
      "...........kk...........",
      ".........kkxakkk........",
      ".......kkxxxxxaMk.......",
      "......kxxxxxxxaMHk......",
      "......kxxxxxxxMaak......",
      ".....kxxxxxxxxMaaHk.....",
      ".....kxxxxxxxxaMaHk.....",
      "....kxxxxHHxxHHaaHKk....",
      "....kxxxHxxxxaaHaHKk....",
      "...kkxxMxxMxaMaaMHKkk...",
      "...FkxxxMMxaHaMMaHKkF...",
      "...fkxxxxxxaHaaaaHKkf...",
      "...FkaxxmxaaKaaamKMkF...",
      "....FaxxxaaxaaaaHKMF....",
      "....fkaxxaaaaaaaKMkf....",
      "...kFkaaaaKMMKaHKMkFk...",
      "...k..kaaaaHHaHKMk..k...",
      "......kHaaaaHHKMMk......",
      ".......kkHHKKKMkk.......",
      ".........kkKMkk.........",
      "...........kk...........",
      "........................",
      "........................",
    ],
  },
  // 煤けた振り香炉 — 三本鎖で吊る煤だらけの香炉、透かしに残り火、くゆる煙
  m_blackened_thurible: {
    pal: { "~": "#5a5862" },
    art: [
      "........................",
      "...........kk...........",
      "..........kyok..........",
      "..........kkkwk.........",
      ".........kgkgkgk........",
      ".........kwkwkwk........",
      "........kgkkgkkgk.......",
      "........kwkkwkkwk....~..",
      "..~....kgkkkykkkgk..~...",
      "...~....kyyooggkwk...~..",
      "..~....kyyyooggekgk.~...",
      "...~..koooRggeRfFkk.....",
      "......kggeffRfFFFkgk....",
      "......keRfFFFFFFRkwk....",
      ".....kkkkkkkkkkkkkk.....",
      ".....kgooooggggeffk.....",
      ".....kggooogggeffFk.....",
      "......keggggeefFFk......",
      ".......kffffFFFFk.......",
      "........kkfeegkk........",
      "..........kkkk..........",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 竜に挑んだ喉当て — 重ね板の鋼の喉当て、牙の穴が穿たれ端が歪み裂ける
  m_knight_gorget: {
    pal: {  },
    art: [
      "........................",
      "........................",
      "........................",
      "..kkkk............kkkk..",
      ".kxewvk..........kwwegk.",
      ".kxexwk..........kxxevk.",
      ".kxexwk..........kxxevk.",
      ".kxxxwvk........kxxwggk.",
      ".kwxevvk........kwweeek.",
      ".kwxxwwvkk....kkwwwxeek.",
      ".kxxeewwwwkkkkxxxxweeek.",
      "..kxxexwwxxxxxxxxwekwk..",
      "..kwweewwwwwwwwwxkeekvk.",
      "..kvwweevwwwwvvvkkeekk..",
      "...kwwxeewwwwxkeexeekk..",
      "...kwwweweeeekkkvgeek...",
      "....kvvvwwvkkvkggeek....",
      ".....kgggggkggeeeek.....",
      "......kgggggeeeeek......",
      ".......kkggggeekk.......",
      ".........kkkkkk.........",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 石化した心の臓 — 下の尖った左右非対称の心臓。大動脈の弓と太い血管の切り口まで灰色の石になり、ひびの奥にかすかな赤
  m_petrified_heart: {
    pal: { "H": "#2a2527", "K": "#4a4345", "M": "#6e6664", "P": "#958c86", "Q": "#bdb3a8", "r": "#5e1c1e", "R": "#a8383a" },
    art: [
      "........................",
      "...........kk..k..k.....",
      "..........kPHkkHkkHk....",
      "...........kMHHHkPMk....",
      "...........kHPPPPHKk....",
      ".....kk....kPMMMMPHk....",
      "....kPPkk.kPMMMMMMPk....",
      "...kMkPHHkkHHHHHHMKk....",
      "...kHHHPPPPMMMMKHHKHk...",
      "...kHPPQQPPrMMMKKHHHk...",
      "....kPQQQQPrMMMMKKHHk...",
      "...kPPQQQQPPrMMMKKHk....",
      "...kPPPQQPPPRMMKKKHk....",
      "....kPPPPPPrRMMKKKHk....",
      "....kMMPPMrMrMMrrKHk....",
      ".....kKKMrMMMrrKKHk.....",
      "......kkKKMMMRKKKHk.....",
      "........kkKMKKrKHk......",
      "..........kHKKrHHk......",
      "...........kHKrHk.......",
      "............kHHHk.......",
      ".............kHk........",
      "..............k.........",
      "........................",
    ],
  },
  // 墓守の灯油壺 — 注ぎ口に尽きぬ小さな火が灯り、口縁から琥珀の油が垂れる素焼きの壺
  m_grave_lantern_oil: {
    pal: { "H": "#211612", "K": "#43291c", "M": "#6e4529", "P": "#9a6a3c", "Q": "#c09058", "a": "#ffe7a0", "Z": "#e8a040" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "....k...................",
      "...kRk...kkkkkk.........",
      "...kZk..kQQQQPMk........",
      "..kRaZkkPQQHHoKHk.......",
      "..kZaZk.kMKKHHyk........",
      "...kZk..kMPPMKYokkkk....",
      "..kPPMkkkMPPMKykkQPPk...",
      "..kKMPMQQQMMKHPyKKHMMk..",
      "...kHMQQQQHHHHPYoKkkPKk.",
      "....kHQQQQQPPPMMyKkkPKk.",
      "....kPPKKKKHHHHHYHHkPKk.",
      "....kPPPPHPPHMMHyHHkPHk.",
      "....kMPPPPMMMMKKoHHQKk..",
      ".....kMMMMMMKKKHHHMKk...",
      ".....kKKKKKKKHHHHHkk....",
      "......kkHHHHHHHHkk......",
      "........kkHHHHkk........",
      "..........kkkk..........",
      "........................",
      "........................",
    ],
  },
  // 石化した手向け花 — 花も葉も石と化した花環。苔が薄く浮き、石の飾り紐が垂れる
  m_ossified_wreath: {
    pal: { "H": "#262527", "K": "#454340", "M": "#6c6860", "P": "#9a9484", "Q": "#cdc6b2" },
    art: [
      "........................",
      ".......kkkkkkkkkk.......",
      "......kPPMMQPMPMKk......",
      ".....kkMMKQQPMMKHkk.....",
      "....kMMMMHQPHKHMMKKk....",
      "...kQQQPKKMMKKKKQQPMk...",
      "..kPQQHMHHHHHHKKQHPKMk..",
      "..kPPPMKHkkkkkkKPMKHKk..",
      "..kMMKHHk......kHHHMHk..",
      "..kMKHKHk......ktMKHKk..",
      "..kQQQMk........kQQQMk..",
      "..kQQHMk........kQHPMk..",
      "..kPPMKHk......kMPPKKk..",
      "..kKKHHKk......kMKKHHk..",
      "..kPMGKQPkk..kkQQMMtHk..",
      "..kMHKQQPKKkkMQQQPKKHk..",
      "..kHkPQHMtMQPMQQHMHkHk..",
      "...kkKMMKHGPMKtMKKHkk...",
      ".....kkKKKKKHHKKHkk.....",
      ".......kHHHKHHHHk.......",
      "......kQMHkkkkMMKk......",
      "......kPKk....kMKk......",
      ".......kk......kk.......",
      "........................",
    ],
  },
  // 蘇り縛りの鎖 — 錆びた太い鎖の先に閉じた枷と蝶番。錆の陰に呪いの紫がくすぶる
  m_revenant_chain: {
    pal: { "H": "#1c1014", "K": "#3c2220", "M": "#663822", "P": "#8c522e", "Q": "#b07646" },
    art: [
      "........................",
      "..kkkkk.................",
      ".kQPPPMk................",
      ".kPKHMPMk...............",
      ".kPKkkMMKk..............",
      ".kMMKkkPKk..............",
      "..kMPPQPKkk.....i.......",
      "..kKMPjPMPPkk...........",
      "...kkHHMQPPPMk.......p..",
      ".....kkPPJHMPMkkkkk.....",
      "......kMPHKkQQQPPPMk....",
      ".......kPMkQQPMMPPPMk...",
      "...p...kKMQQjMHKKMPMKk..",
      "........kQQMMKkkkKMPMk..",
      "........kQPKHHk..kMPMHk.",
      "........kPPKkk...kMPMHk.",
      "........kPPKk....kPjMHk.",
      "........kPPMKk...kQPMHk.",
      "........kMPjMMkkkQPkMk..",
      ".........kMpPPPQQPkMMHk.",
      ".......j..kKMMPPMMKMHHk.",
      "...........kHjjKKHHkHk..",
      "............kkkkkkk.k...",
      "........................",
    ],
  },
  // 霊廟の封蝋 — 真っ二つに割られた黒い封蝋。盛り上がった縁と押し紋、千切れた紐の端
  m_tomb_seal_wax: {
    pal: { "H": "#120e16", "K": "#221b29", "M": "#362c40", "P": "#54475f", "Q": "#7c6e8c" },
    art: [
      "........................",
      "........................",
      "........k...............",
      "......kkPk.kkkkk........",
      ".....kPPPkkQPPPMkk......",
      "....kPPQQQkPQQPMMMk.....",
      "...kPPQQQHkkQQQQPMMk....",
      "...kPQQHHHkkQHHPPPMKk...",
      "..kPPQQHHHHkHHKKPPPKk...",
      "..kPPQHHHHHkkQKKPMMKKk..",
      "..kPPQHHMHHkkQKKKPMKKk..",
      "..kPPQHHKMMMkKKMKPMHHk..",
      "..kMMQQHKHKHkkQKKPMHHk..",
      "...kMPPHKKMKMkKKPMMHHk..",
      "..kMMMPPPPPPPkkQPMMHk...",
      ".kMMKKMPMMMMMMkMMMHHk...",
      "..kKKkMKKKMMHHkkQHHrk...",
      "...kk.kkKKKHHHkkQHrrrk..",
      "........kkkkkk..kkkrrk..",
      "..................kqrqk.",
      "...................krrk.",
      "....................krk.",
      ".....................k..",
      "........................",
    ],
  },
  // 竜眼の硝子体 — 少したるんだ琥珀色の澄んだ球。底に縦に裂けた竜の瞳の影が揺らぐ
  m_wyrm_eye_jelly: {
    pal: { "H": "#2c1a0c", "K": "#5a3814", "M": "#8c5e1e", "P": "#c08a30", "Q": "#e8c060", "a": "#fff2c8" },
    art: [
      "........................",
      "........................",
      "........................",
      "..........kkkk..........",
      ".......kkkMMMMkkk.......",
      "......kMMKKKKKKKKk......",
      ".....kMKKQKKooKMMKk.....",
      "....kMKaaKKKooMMMMKk....",
      "...kMMKaQKKKOOMMMMKKk...",
      "...kMKQKKKMMOOMMMMPKk...",
      "...kMKKKKMMoOOoMPPPKk...",
      "...kMKKMMMMoOOoPPPPKk...",
      "...kMKMMMMMoOOoPPPPKk...",
      "...kMMMMMMMoOOoPPQQKk...",
      "...kMMMMMMMoOOoPQQQKk...",
      "...kKKMMMPPPOOQQQQKKk...",
      "....kKMMPPPPOOQQaQKk....",
      "...kkKKPPPPPooQQQKHkk...",
      "..kKKKKKKPQQooQKKHHHHk..",
      "...kKKKKKKKKKKHHHHHHk...",
      "....kkkkkKKKHHHkkkkk....",
      ".........kkkkkk.........",
      "........................",
      "........................",
    ],
  },
  // 竜の腱 — 弦にするため輪に束ねた太い腱。筋目が走り、革紐で一か所くくってある
  m_dragon_sinew: {
    pal: { "H": "#3a1a16", "K": "#6a3226", "M": "#94573c", "P": "#ba8460", "Q": "#dcb088" },
    art: [
      "........................",
      "........................",
      "........................",
      "..........kkkkkkkkk.....",
      "........kkQQQQPPPPPk....",
      ".......kQQPMPPPPPPMPk...",
      ".....kkQPPMMHHHHHKMPMk..",
      "....kQQPPMHHHkkkkKKPKHk.",
      "....kPPMHHHkk....kMPMHk.",
      "...kQlDHHkk......kPMMHk.",
      "..kldDHkk........kQPKHk.",
      ".kdDDHkkk........kPMHk..",
      ".kDMMHldDk.....kkQPHHk..",
      ".kPQMdDDkkk..kkQMMHHk...",
      ".kPldDkkkdDkkQQMMHHk....",
      ".kMPMQMldDkQQPPMHHHk....",
      "..kMQPdDDQQMPMHHHkk.....",
      "...kPDDPKPMKHHHHk.......",
      "..kPPHHQMHHHHHkk........",
      "..kPMkkMMkkkkk..........",
      "..kQKk.kPKk.............",
      "..kKHk..kk..............",
      "...kk...................",
      "........................",
    ],
  },
  // 溶け残りの竜鱗 — 竜の炎を浴び、右下の縁だけが溶けて赤熱のまま垂れた、稜の立つ一枚鱗
  m_molten_scale: {
    pal: { "H": "#260a0e", "K": "#e06a2a", "M": "#f8a850", "a": "#ffe0a0" },
    art: [
      "........................",
      "...........kk...........",
      "........kkkrrkkk........",
      ".......krrRRRRRHk.......",
      "......kqqrrRRRRrHk......",
      ".....kqqYrrRRrRrqHk.....",
      ".....kqRrrrRRrrrqqk.....",
      "....kqqrrrRRRrrrqqHk....",
      ".....kqrrrRRRrrrqqHk....",
      ".....kqrrrRRrrrrqqHk....",
      ".....kqrrqRRqrrqqqHk....",
      ".....kqrrrRRrqrqqRKKk...",
      ".....kqrrRRrrqqqRKkKk...",
      "......krrRRrrqRKKkkMk...",
      "......kqrRRrrRKkkk.k....",
      "......kqrRrrRKk.kKk.....",
      ".......krrrRKk..kKk.....",
      ".......krrRKk...kKk.....",
      ".......krRKk..k.kMk.....",
      "........kkk..kKk.k......",
      ".............kMk........",
      "..............k.........",
      "........................",
      "........................",
    ],
  },
  // 竜の胃石 — 胃の腑で磨き上げられた卵形の石。呑まれた紅玉・翠玉・金が埋まって光る
  m_drake_gizzard_stone: {
    pal: { "H": "#2a3440", "K": "#4e6070", "M": "#7890a0", "P": "#a4bccb", "Q": "#d4e2ea" },
    art: [
      "........................",
      "........................",
      "........................",
      "..........kkkkk.........",
      "........kkQQQPPkk.......",
      ".......kQQQQQQPPMk......",
      "......kQxQQQQQPPMKk.....",
      ".....kQQQQQQQQkPMMKk....",
      "....kQQQQQQQQkRqMMKk....",
      "....kQQQQQQQQPqqMKKk....",
      "....kQQQQQQkPPPMMKHHk...",
      "...kPQQQQQkcuPMMKKHHk...",
      "...kPQQQQPPuuMMMKKHHk...",
      "...kPPPPPPPPMMMKKHHHk...",
      "...kMPPPPkMMMMKKkHHk....",
      "....kMPPkhtMMKKkYoHk....",
      "....kMMMMttKKKHHooHk....",
      "....kKKMKKKKKHHHHHk.....",
      ".....kKKKKKHHHHHHk......",
      "......kHHHHHHHHHk.......",
      ".......kkHHHHHkk........",
      ".........kkkkk..........",
      "........................",
      "........................",
    ],
  },
  // 古竜のひげ — 根元に肉の残る一本の長い銀のひげが大きく S 字にうねり、先で巻く
  m_wyrm_whisker: {
    pal: { "H": "#2c2a36", "K": "#56546a", "M": "#9492a6", "P": "#cdc8cc", "Q": "#fff6dc" },
    art: [
      "........................",
      "........................",
      "...............kkkk.....",
      "..............kQKPMk....",
      ".............kkKkkPk....",
      "...........kkQMkkkMk....",
      "..........kQMkkMPPk.....",
      ".........kPMk..kkk......",
      ".........kPk............",
      ".........kMk............",
      ".........kMMk...........",
      ".........kKHKk..........",
      "..........kKMk..........",
      "...........kHKk.........",
      "...........kHKk.........",
      "..........kkPKk.........",
      "........kkQPMk..........",
      "......kkQQMKk...........",
      "...kkkQQPMHk............",
      "..kmrqPKKHk.............",
      ".krrqHHHkk..............",
      "..kHHkkk................",
      "...kk...................",
      "........................",
    ],
  },
  // 竜火のおき火 — 炭のように黒く固まった塊のひびが赤く燃え、上に小さな火がゆらぐ
  m_dragonfire_cinder: {
    pal: { "H": "#141012", "K": "#2a2022", "M": "#463836", "P": "#d85a28", "Q": "#ffa040", "a": "#ffe6a0" },
    art: [
      "........................",
      "........................",
      "........................",
      "........................",
      "............k...........",
      "...........kPk..........",
      "...........kQPk.........",
      ".........kkPPQk.........",
      ".......kkkPMQMPk........",
      ".....kkMMMMMMMKKk.......",
      "....kMMMMMMMMMKHkkk.....",
      "...kMMMMMMMMPKKHMMKk....",
      "...kMMMMMMMKPKHHMMKHk...",
      "..kMMMMMKKKPQHHPPKKHk...",
      "..kMMMMMMHPQaHPMKKKHk...",
      "...kMMMKPPMMQQMKKKHHk...",
      "...kKKKPKKKMMPPKKHHHk...",
      "....kHHHHHKKPKKPHHHHk...",
      ".....kkHHHHHHHHHHHHk....",
      ".......kkkkkkkHHkkk.....",
      "..............kk........",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 蛇王の冠片 — 鎌首をもたげた蛇の飾りが立つ、緑青を吹いた冠の割れた欠片。翠玉入り
  m_serpent_crown_shard: {
    pal: { "H": "#24443a", "K": "#4c8070", "a": "#ecdc9c" },
    art: [
      "........................",
      "..........kkk...........",
      ".........kYyok..........",
      ".........kaYoOk.........",
      "........kYryork...k.....",
      "........kYyyyook.kYk....",
      ".......kYYyyyookkyyOk...",
      "......kYKYyOOooOkkOk....",
      ".......kYYOrrOok.kok....",
      "........kYyOOoHk.kok....",
      "....kk..kYyyyok.kYook...",
      "...kYok..kYyok..kYoKk...",
      "...kYok..kyyok..kYookk..",
      "..kYYookkkyyok.kYHoooyk.",
      ".kykkHYYYkHyokkYYYyyyok.",
      ".kokyyyyyYyyoYYyyyooHok.",
      ".kokooyyyyyoOKyyyyhGook.",
      ".kOoooohGooOOohGooGtoOk.",
      "..kOHKOGtoooooGtKOOOOk..",
      "...kkkkkkHKOHOOkkkkkk...",
      ".........kkkkkk.........",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 古竜の心臓鱗 — 六角の厚い大鱗。中心に脈打つ熱が灯り、赤い脈が縁へ走る
  m_elder_heartscale: {
    pal: { "H": "#1c080c", "K": "#d8502a", "M": "#ffb070", "a": "#fff0c8", "Z": "#521418" },
    art: [
      "........................",
      "........................",
      "..........kkkk..........",
      "........kkRRrrkk........",
      ".......kRRRrrrrZk.......",
      ".....kkRRRrrZZZZZkk.....",
      "....kRRRRrqqKqZZqqqk....",
      "...kRRRRrqqqKqqqqqHHk...",
      "...kRRZqqqqqKqqqqHZHk...",
      "...kRrrKKqqKKqqqKKHHk...",
      "...krrrqqKKMMKqKZHHHk...",
      "...krrZqqKMaaMKZZHHHk...",
      "...krZZqqKMaaMKZZHHHk...",
      "...kZZZqqqKMMKKZZHHHk...",
      "...kZZqqKKqKKZZKKHHHk...",
      "...kZqZKqqZZKZZZHKZHk...",
      "....kqqHHZZZKZZHHHHk....",
      ".....kHHHHHZKHHHHHk.....",
      "......kkHHHHKHHHkk......",
      "........kHHHZHHk........",
      ".........kkHHkk.........",
      "...........kk...........",
      "........................",
      "........................",
    ],
  },
  // 世界樹の朽木片 — 樹皮の残る太い木っ端。裂けた木目に淡い緑の光が脈打つ
  m_world_root_splinter: {
    pal: { "H": "#1e1610", "K": "#3a2a1c", "M": "#5e4630", "P": "#8a6c4a", "Q": "#b0946a", "a": "#c4eab0", "Z": "#78a86a" },
    art: [
      "........................",
      ".................kk.k...",
      "................kQPkPk..",
      "................kQPPkk..",
      "..............kkQQPMkKk.",
      ".............kQQQPMMHk..",
      "............kQPPPPMKKk..",
      ".....Z....kkQPPPMMKKk...",
      ".........kQQPPPMMKHk....",
      "........kQQPPZZZZKKk.h..",
      "........kQPPZMZHHKk.....",
      ".......kQPPZMKKKHk......",
      "...h..kPPPZMKKKKk.......",
      ".....kQPPZMMKHHKk...Z...",
      "....kkQPMZMaKKHk........",
      "...kQQPPMMKHKkk.........",
      "....kPPMZZKKk...........",
      "...kPPMZHHKk............",
      "....kPZKKkk.............",
      "....kMHKKk..............",
      ".....kHHk...............",
      "....kKkk................",
      ".....k..................",
      "........................",
    ],
  },
  // 墜星の鉄塊 — 打ち固めた暗い鉄の塊。上面に星鉄特有の網目模様が浮き、角に星の光が宿る
  m_star_iron_ingot: {
    pal: { "H": "#15161e", "K": "#272a38", "M": "#3e4256", "P": "#5e6680", "Q": "#8a96b0", "a": "#e0ecff", "Z": "#b8c8e8" },
    art: [
      "........................",
      "........................",
      ".................c......",
      ".................Z......",
      "...............cZaZc....",
      ".............kk..Z......",
      "..........kkkQPkk.......",
      "........kkQQQQPPQkkk....",
      ".....kkkQQQQPPQQPPPQk...",
      "....kPQQQQPPQQPPPQPQQk..",
      "...kMQQPPPQQPPPQPQQKKk..",
      "...kKMMPQQPPPQPQQKKKKk..",
      "...kMHMMKPPQPQQKKKKKHk..",
      "...kMMMKMMMQQKKKKKHHHk..",
      "...kMMHMMMMKKKKKHHHHk...",
      "..kMMKMMMMKKKKHHHHkk....",
      "...kkMMMHKMKHHHHkk......",
      ".....kkMKMMHHHHk........",
      ".......kkMMHHkk.........",
      ".........kkkk...........",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  // 亡国王の璽 — 王冠のつまみを戴く角形の金の印章。竜の炎に焼かれ、煤と溶け垂れが残る
  m_sovereign_signet: {
    pal: { "H": "#151011", "K": "#2e2420" },
    art: [
      "........................",
      "........................",
      "........................",
      "...........kk...........",
      ".......k..kYyk..k.......",
      "......kYY.kYyk.kok......",
      "......kYYkyyRykook......",
      ".......kYYyyryook.......",
      ".......kYYyyyyoKk.......",
      ".......koorooorok.......",
      ".......kyyyoooOOk.......",
      "........kkyyoOkk........",
      "......kkkyyyoHykkk......",
      "...kkkyyyyyyoOyyyykkk...",
      "..kyyyyyyyyyoOyyyyyyyk..",
      "..koYYyyyyooOOHyHyOYYk..",
      "..koooYYYYyyyyyKKKYKOk..",
      "..koooooooYYOYYOOKKOKk..",
      "..koooHoooooOOOOHOHHOk..",
      "...kooooooooOOOKOOOkk...",
      "....kkyoooooOKOOkkk.....",
      ".....kokkkooOkkk........",
      "......k...kkk...........",
      "........................",
    ],
  },
  // 不死鳥の綿羽 — 白い羽軸に、根元は淡い金・先は燃える橙のふわりとした綿羽。先から火の粉
  m_phoenix_down: {
    pal: { "H": "#5a2618", "K": "#9a4424", "M": "#d0763a", "P": "#f0ae5c", "Q": "#ffe2a4", "a": "#fff6dc" },
    art: [
      "........................",
      "........................",
      ".............P.....Q....",
      ".................kk.P...",
      "................kMKk....",
      "............k.kkQMKk....",
      "...........kKkKMQMk..M..",
      "..........kMMMMPQMkk....",
      ".........kMMMMPQPMKMk...",
      ".........kMMMMPQPMMKk...",
      "........kMMMMPQQMMMMk...",
      ".........kkMPPQPPMMk....",
      "..........kPPaPPMMMk....",
      ".........kPPaaPMPMk.....",
      ".........kPQaPMPMk......",
      "........kMQaPMPMk.......",
      "........kPaPkMMk........",
      "........kaPk.kk.........",
      ".......kakk.............",
      "......kak...............",
      "......kak...............",
      ".......k................",
      "........................",
      "........................",
    ],
  },
  // 深淵真珠の核 — 外層が剥がれかけた黒真珠。顔を映さず、縁にだけ虹の光がにじむ
  m_abyssal_pearl_core: {
    pal: { "H": "#121018", "K": "#1e1b28", "M": "#2e2a3c", "P": "#4a4462", "Q": "#5f8c94", "a": "#d6dcea", "Z": "#8a8098" },
    art: [
      "........................",
      "........................",
      "........................",
      ".......kkkkkkkk.........",
      "......kiiiiiiiPk........",
      ".....kiiPPPPPPPPk.......",
      "....kiPPiKKKKKMMPk......",
      "...kiiPaKHHHHKKMPPk.....",
      "...kiPiKHHHHHHKKMPk.....",
      "...kPPKHHHHHHHHKMPk.kk..",
      "...kPPKHHHHHHHHKMPkkZxk.",
      "...kPPKHHHHHHHHKMQkkZxk.",
      "...kPPKHHHHHHHHKMQkkZxk.",
      "...kPPKKHHHHHHKKMQkkxBk.",
      "...kPPMKKHHHHKKMQQkZxBk.",
      "....kPMMKKKKKKMMQkkZxk..",
      ".....kPPMMMMMMQQkkZxBk..",
      "......kPPPQQQQQkkZxxk...",
      ".......kkkkkkkkkZxxBk...",
      "..........kkkkZZxxBk....",
      ".........kZZZxxxBkk.....",
      ".........kxxBBBkk.......",
      "..........kkkkk.........",
      "........................",
    ],
  },
  // 神殺しの牙 — 根元を金の輪で巻いた、ひときわ白く長い大牙。刃先まで欠けひとつ無い
  m_godslayer_fang: {
    pal: { "H": "#fbf7ec", "a": "#6e604a" },
    art: [
      "........................",
      "...............kk.......",
      "..............kHHkk.....",
      ".............kHHHxBk....",
      "............kHHHxxBk....",
      "...........kHHxBxIIak...",
      "..........kHHHxBBIak....",
      ".........kHHHxxBOook....",
      ".........kHHHOOyyok.....",
      "........kHOOYYyyyk......",
      "........kYYYYYykk.......",
      ".......kYYYYHak.........",
      ".......kYOOIak..........",
      "......kOHxBHk...........",
      "......kHxBak............",
      "......kHxak.............",
      ".....kHHBak.............",
      ".....kHxIk..............",
      ".....kHxk...............",
      ".....kHBk...............",
      ".....kHak...............",
      "......kk................",
      "........................",
      "........................",
    ],
  },
  // 最初の火の残り火 — 白熱の芯をもつ小さな炎が宙に浮き、四方へ光の矢を放って闇を退ける
  m_first_flame_ember: {
    pal: { "H": "#8a2c18", "K": "#d0602a", "M": "#f4a040", "P": "#ffd880", "Q": "#fffbe8" },
    art: [
      "........................",
      "........................",
      "............P...........",
      "........................",
      "....M.......k.......M...",
      ".....P.....kKk.....P....",
      "..........kKKKk.........",
      "..........kKKKk.........",
      ".........kKKKKKk........",
      ".........kMMMMMk........",
      "........kKMPPPMKk.......",
      "..PM...kKMPQQPMKk...MP..",
      ".......kKMPQQPMKk.......",
      "......kKMMPQQPMKKk......",
      "......kKKMPQQPMKk.......",
      ".......kKMPPPPMKk.......",
      "........kMMPPMKk........",
      ".........kMMMMk.........",
      "..........kkkk..........",
      ".....M.............M....",
      "....M.......M.......M...",
      "............P...........",
      "........................",
      "........................",
    ],
  },
};
