// 手描きの装備の絵: 組 arm3 (LR の防具)
//   久遠 (a5): 朽ちぬ霊鉄 = 月白の鋼に金の縁、青緑に灯る霊の環の紋 (永遠の輪)。覇の品は黄金に白い日輪。
//   永劫 (a20): 夜の紫鋼に銀の星々と金の縁、星をめぐる環の紋。
import { pal } from "./pal.js";
export const ART_ARM3 = {
  lr_a5_body_hv: { // 久遠の鎧: 月白の霊鉄の胸甲と重ねた肩当て・金の高い襟と縁・胸に青緑に灯る霊の環・金の帯と重ねの草摺
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..eek...OOOOOOOk...eek..",
      ".exxwek.OyWYyYok.eevwwk.",
      "exxwwwveeOyyooOeegvvvwwk",
      "ewwYwvvgexwwvvweeggvyvvk",
      "OYYYyyyoexxwvwweOoooyyyk",
      "kgvvYvgeexwwvvweeegyggkk",
      ".kyyyyoexwwwvvvweOoookk.",
      "..kggeexwwYYyyvvweeekk..",
      "...exxwwwY1232yvvvwwk...",
      "...exwwwwY2343yvvvvwk...",
      "...kwwwvwwyyoovvgvvkk...",
      "....ewwvvww34vvggvvk....",
      "....evwvvvw23vgggvgk....",
      "....OyyyYYYYyyyyoook....",
      "....Ooyyyy1232ooooOk....",
      "....ewxxxwweevvwwwvk....",
      "...egvvvvvveeggggggek...",
      "...ewxxxwwweevvvwwwvk...",
      "..egvvvvvvveegggggggek..",
      "..ewxxxwwwweevvvvwwwvk..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_hv: { // 久遠の鉄兜: 月白の霊鉄の大兜・頭頂から面頬へ通る金の鶏冠・額の金の帯に霊の環・覗き穴に灯る青緑の眼光
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..........OOOk..........",
      "........eeYWYyek........",
      "......eexxYWYywwek......",
      ".....exxxwYYyyvwwwk.....",
      "....exxwwwYYyyvvvwwk....",
      "....exwwwvYYyygvvvwk....",
      "...exwwwvvYYyyggvvvwk...",
      "...ewwwvvvyYyogggvvvk...",
      "...OYYYYYyy12ooyyyyyk...",
      "..eevkk12kkkkkk32kkgek..",
      "..Oexwwvvvvyoggggvvwek..",
      ".O2ewwvkvkvYygkgkgvve3k.",
      ".k3ewvvvvvvYyggggggvekk.",
      "..kewvvkvkvyogkgkggvkk..",
      "...ewvvvvvvYyggggggvk...",
      "...OyyyyyyyYyoooooook...",
      "..exwwwwvvvvggggvvvvwk..",
      ".exwwwvvvvggeeggggvvvwk.",
      ".kvvvvggggeeeeeeeegggkk.",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_hand_hv: { // 久遠の籠手: 板を連ねた月白の霊鉄の指・拳に青緑の霊玉を据えた金の帯・霊の環を打ち出した金縁の袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..........eek...........",
      "......eek.ewk.eek.......",
      "......ewvkxwvkxwk.......",
      "......eggkgggkgggkek....",
      "......ewvkxwvkxwvkxk....",
      "......ewvkxwvkxwvkwk....",
      "......eggkgggkgggkgk....",
      "..ek..ewvkxwvkxwvkwk....",
      ".ewwk.OyYYYY12YYYYyk....",
      ".kwvveoyyyyy23yyyyok....",
      "..evvgxxwwwwwwwwvvvk....",
      "..kwvgxwwwwwvvvvvvgk....",
      "...kkkxwwwwvvvvvgggk....",
      "......kwwwvvvvvvgkkk....",
      ".......ewvvvvvgggk......",
      ".......egggggggeek......",
      ".....OOYYYYYYYYYYyOk....",
      "....exwwwwyYYywvvvvgk...",
      "....ewwwwy2112yvvvggk...",
      "....ewwwwy2332yvvvggk...",
      "....ewvvvvyyyyvvgggek...",
      "....kkkkkkkkkkkkkkkkk...",
      "........................",
    ],
  },
  lr_a5_feet_hv: { // 久遠の具足: 月白の霊鉄の脛当てと重ねの鉄靴を一組・霊玉を据えた金縁の膝当て・脛を走る青緑の霊の筋
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "...........OOOOOOOk.....",
      "....OOOOOOOokv23vgk.....",
      "....Oxxw12wvkyyyyok.....",
      "....Oxw2332vkvvggek.....",
      "....kyYYYYyokvv3gek.....",
      ".....exwwvgkwvv4gek.....",
      ".....exw2vgkwvv3gek.....",
      ".....exw3vgkwvv4gek.....",
      ".....exw2vgkwvvggek.....",
      ".....exw3vgkwvvggek.....",
      ".....exw2vgkwvvggek.....",
      ".....exw3vgkwvvggek.....",
      ".....exwwvgkyyyyyok.....",
      "....OYYYYyyokvvggek.....",
      "...exxwwwvvgkvvggek.....",
      "..exxwwwwvvgkgggggk.....",
      ".eggggggggggkvvgggk.....",
      ".exxwwwwwvvgkyyyykk.....",
      ".kYYYYYYYYyykkkkkk......",
      "..kkkkkkkkkkk...........",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_shield_k1: { // 久遠の大盾: 胸壁の形に刻んだ上縁の月白の霊鉄の大盾・金の縁と背骨・盾心に青緑に灯る大きな霊の環
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".OOk.OOk.OOOOOk.OOk.OOk.",
      ".OYyOyyyOyYYyyoOoooOoyk.",
      ".OXxxwwwwwwwvvvvvvvwwxk.",
      ".Oxwwwwwwwwwvvvvvvvvvwk.",
      ".OxwwwwwyyyYyooovvvvvwk.",
      ".OxwwwwyY322334yovvvvwk.",
      ".OwwwwyY32112234yovvvvk.",
      ".OwwwwY3211122234yvvvvk.",
      ".OwwwwY3211122234yvvvvk.",
      ".kwwwwyY32112234yovvvkk.",
      "..OwwwwyY322334yovvvvk..",
      "..OwwwwwyyyYyooovvvvvk..",
      "..kvwwwwwwyYyovvvvvvkk..",
      "...OvwwwwwyYyovvvvvgk...",
      "...kvvwwwwyYyovvvvgkk...",
      "....kvvwwwyYyovvvgkk....",
      ".....kvvwwyYyovvgkk.....",
      "......kvvwyYyovgkk......",
      ".......kvvyYyogkk.......",
      "........kvyYyokk........",
      ".........kYYykk.........",
      "..........kkkk..........",
      "........................",
    ],
  },
  lr_a5_shield_r1: { // 久遠の円盾: 打ち出しの環が幾重にも波打つ月白の霊鉄の円盾・金の鋲の縁・青緑の霊玉を据えた盾心
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".........OOOOOk.........",
      "......OOOxxxwwwOOk......",
      ".....OYxxwwwwwwwwyk.....",
      "....OYxwwwwwwwwwwvyk....",
      "...OYxwwwxxxxxwwwwvWk...",
      "..OYxwwxxxxxxwwwwwwvyk..",
      "..Oxwwxxxwwwwwwwwwvvgk..",
      "..OxwwxxwOyYYowwwvvvgk..",
      ".OxwwxxwOyY12Yowvvvvvgk.",
      ".OxwwxxwyY1XX2yovvvvvgk.",
      ".OxwwxxwYY1X123ovvvvvgk.",
      ".OwwwxxwyY2233yovvvvvek.",
      ".Owwwxwwoy2334yovvvvgek.",
      ".kwwwwwwwoyyyoovvvvggkk.",
      "..Owwwwwwwvvvvvvvvggek..",
      "..Owwwwwwvvvvvvvvvggek..",
      "..kyvwwwvvvvvvvvvggekk..",
      "...kyvwvvvvvvvvgggekk...",
      "....kyvvvvvvvvgggekk....",
      ".....kyggvvvvggeekk.....",
      "......kkkgggeekkkk......",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a5_body_lt: { // 久遠の革鎧: 青緑の縞が走る月白の霊獣の革を重ねた胴・白い毛皮の襟と肩・胸の霊の環の留め金・金の鋲の帯と革の垂れ
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "......7777ZZZZ788k......",
      "...77766675ZZ6877777k...",
      ".776HHK667e56e877MKK77k.",
      "76HHK3KKeHK67MKeMM4MKK7k",
      "ZHK3KKMMeHKKMMKeZZMM4MKk",
      "ZK3KKMMZeHK34MKeZZZMM4Mk",
      "kyWyyyyoeHK34MKeOooooYkk",
      ".kZMMZZeHKK34MMKeZZZZkk.",
      "..eHHKKK3KoYyOM4MMMKKk..",
      "..eHK3KKKKY12yMMMM4MKk..",
      "..eHK3KKKKy23oMMMM4MKk..",
      "..eHKK3KKKKoOMMMM4MMKk..",
      "..eKKKK3KKKMZMMM4MMMMk..",
      "..OyWyyyyyyyoooooooYok..",
      "..kyykkykk123kkokkOokk..",
      "...eHk.Zk.ZKMk.Zk.ZKk...",
      "...eKk.Zk.ZMZk.Zk.ZMk...",
      "...e3k.4k.4KMk.4k.44k...",
      "...eKk.Zk.ZMZk.Zk.ZMk...",
      "...kkk.kk.kkkk.kk.kkk...",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_lt: { // 久遠の革兜: 霊獣の耳を立てた白い毛皮の飾り・青緑の縞の霊獣の革の頭巾兜・額の毛皮の帯に霊の環・金の鼻当てと首垂れ
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "..7k................7k..",
      "..75k..............86k..",
      "..756k.eZZZZZZZZk.876k..",
      "..k667eHHKKKMMMKKe87kk..",
      "...k6eHHK3KKMM4MKKekk...",
      "....eHHK3KKKMMM4MKKk....",
      "...eHHK3KKKKMMMM4MKKk...",
      "...eHK3KKKKKMMMMM4MKk...",
      "..eHKKKKKKoYyOMMMMMMKk..",
      "..e5566666Y12y7777766k..",
      "..e5666667y23o8777776k..",
      "..eHKZkkkkoYyOkkkkZMKk..",
      "..eHKZkkkkoYyOkkkkZMKk..",
      "..eHK3ZkkkkyokkkkZ4MKk..",
      "..eHKKZkkkkkkkkkkZMMKk..",
      "..eK3KKZZZZZZZZZZMM4Mk..",
      "..eHK3KKKKKKMMMMMM4MKk..",
      "..eKKKK3KKKKMMMM4MMMMk..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_hand_lt: { // 久遠の革手甲: 青緑の縞の霊獣の革の手甲を一組・指の付け根に並ぶ金の鋲・白い毛皮の袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "..............ZZZk......",
      "............ZZKMKk......",
      "............ZMKMKMZk....",
      "............ZMKMKMKk....",
      "............ZMKMKMKk....",
      "......ZZZk..ZZZZZZZk....",
      "....ZZHKHk..OYoYoYoYk...",
      "....ZKHKHKZZKKM4MMMZZk..",
      "....ZKHKHKHKKM4MMM4MZk..",
      "....ZKHKHKHKkM4MM4MZZk..",
      "....ZMZMZMZMkMM4M4MZkk..",
      ".Zk.OWyWyWyWoKMM4MMZk...",
      ".ZKZHHK3KKKMMkMMMMZZk...",
      ".kKKkK3KKK3KMk677778k...",
      "..kKkK3KK3KMMk7777788k..",
      "...kkKK3K3KMMk777888kk..",
      ".....ZKK3KKMkkkkkkkkk...",
      ".....ZKKKKMMk...........",
      "....75566667k...........",
      "...7566666677k..........",
      "...k66666777kk..........",
      "....kkkkkkkkk...........",
      "........................",
    ],
  },
  lr_a5_feet_lt: { // 久遠の革靴: 白い毛皮の履き口と青緑の縞の霊獣の革の長靴を一組・金の留め具の革帯・爪先を守る金の覆い
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "..............7777888k..",
      ".............k67777788k.",
      "..............k778888kk.",
      "...............ZKM4MZk..",
      ".....7777777k..ZM4MMZk..",
      "....k56666677k.OoYooOk..",
      ".....k667778kk.ZMM4MZk..",
      "......ZHK3KMk..ZM4MMZk..",
      "......ZK3KKMk..ZMMM4Zk..",
      "......OyWyyok..OoYooOk..",
      "......ZKK3KMk..ZM4MMZk..",
      "......ZK3KKMk..ZMM4MZk..",
      "......ZKKK3Mk.ZKMM4MZk..",
      "......OyWyyokZKMMMM4Zk..",
      "......ZK3KKMkM4MMMMMZk..",
      "......ZKK3KMkMMM4MMMZk..",
      ".....ZHKK3KMkMMMMMMMZk..",
      "...ZZHKKKK3MkZZZZZZZkk..",
      "..ZHK3KKKKKMkkkkkkkkk...",
      ".OYHKKK3KKKMk...........",
      ".OYyKKKKKKKMk...........",
      ".kyoZZZZZZZkk...........",
      "..kkkkkkkkkk............",
      "........................",
    ],
  },
  lr_a5_shield_r2: { // 久遠の小盾: 青緑の縞を三筋描いた霊獣の革を張った小盾・金の鋲を打った月白の霊鉄の縁・霊の環を象る金の盾心
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "........................",
      "...........ek...........",
      "........eeeWxeek........",
      "......eexxHHHHwwek......",
      ".....exxH3HHHHHKwvk.....",
      "....exx33HHH33KKKvvk....",
      "....ex3HHHH3HKKKKKvk....",
      "...eW3HHHHHHKKKKKKWvk...",
      "...exHHHHHyYyKKKKKKvk...",
      "...eHHHHHyY12oKKKKKKk...",
      "..exHHHHHY123oKKKKKKgk..",
      "..kxHHHHKoy3oOKKKKKKkk..",
      "...eHHHKKKooOKKKKKKKk...",
      "...ewHKKKKKKKKKKKKKek...",
      "...kWKKKKKKKKKKKKK3kk...",
      "....ewKKKKKKKKKK33ek....",
      "....kvvKKKKKK333Mekk....",
      ".....kvvKKKKKKKMekk.....",
      "......kkvvKKKKekkk......",
      "........kkkWkkkk........",
      "...........kk...........",
      "........................",
      "........................",
    ],
  },
  lr_a5_body_int: { // 久遠の法衣: 深い瑠璃の法衣と広い袖・金の高い襟と前の縁取り・前合わせに青緑に灯る魔力の流れ・袖と裾に金の縁
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0", "H": "#6f8fd6", "K": "#3f5aa6", "M": "#26356e", "Z": "#141c40" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      "......ZZOyM23ZoOZk......",
      "....ZZHKOyZMZZoOMKZk....",
      "..ZZHKKKMyM12ZoZMMMKZk..",
      ".ZHKKKKKMyZMZZoZMMMMMKk.",
      "ZHK3KKKKMyM23ZoZMMMM4MKk",
      "ZK3KKKMZHyZMZZoKZZMMM4Mk",
      "ZKKKKMZHHyM12ZoKKZZMMMMk",
      "ZKKKMZHHKyZMZZoMKKZZMMMk",
      "ZKKMMZHKKyM23ZoMMKZZZMMk",
      "ZKMMMZHKKyZMZZoMMKZZZZMk",
      "ZKMMZHHKKyM12ZoMMKKZZZMk",
      "ZKMMZHKKKyZMZZoMMMKZZZMk",
      "ZMMMZHK3KyM23ZoM4MKZZZZk",
      "OWyyoHK3KyZMZZoM4MKOooYk",
      "kkkkOHKK3yM12Zo4MMKkkkkk",
      "....eHKK3yZMZZo4MMKk....",
      "....eHKKKyM23ZoMMMKk....",
      "...eHKK3KyZMZZoM4MMKk...",
      "...eHK3KKyM12ZoMM4MKk...",
      "...kkkkkkkkkkkkkkkkkk...",
      "........................",
      "........................",
    ],
  },
  lr_a5_body_pie: { // 久遠の聖衣: 金縁の短い肩掛けを重ねた白い聖衣・胸から裾へ垂れる金のストラに霊の環を二つ・空色の裏地・金の袖口と裾
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      "......7766yYyo777k......",
      "....776666yYyo77777k....",
      "..77666666yYyo7777777k..",
      ".7566666c6yYyo7b777776k.",
      "756666c66cyYyob77b77776k",
      "OWyyyyyyyoyYyoOoooooooYk",
      "7666776677Y12y887788777k",
      "76677ebb67Y23y87uue8877k",
      "7667eb5667yYyo8776ue877k",
      "7667e56667yYyo87776e877k",
      "7677e56667yYyo87776e887k",
      "7677e56667yYyo87776e887k",
      "7677e56667yYyo87776e887k",
      "OWyoe56667Y12y87776eOoYk",
      "kkkke56667Y23y87776kkkkk",
      "....e56667yYyo87776k....",
      "...e566667yYyo877776k...",
      "...e566677yYyo887776k...",
      "..e5666677yYyo8877776k..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_int: { // 久遠の知冠: 金の環の正面に立つ台座に瑠璃と青緑の大きな知恵の玉・左右へ翼のように反る金の透かし・環に並ぶ小さな瑠璃
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "9": "#a8c8ff", "X": "#fffbe6", "W": "#fff0b0", "H": "#6f8fd6", "K": "#3f5aa6", "M": "#26356e", "Z": "#141c40" }),
    art: [
      "........................",
      "........................",
      "...........Ok...........",
      "..........OWYk..........",
      ".........OY19Hk.........",
      ".........O199Kk.........",
      "..Ok.....OH9HKk.....Ok..",
      "..kWk....OHHKMk....Okk..",
      "...kYk...kyKMkk...Okk...",
      "....kYk...Oyok...Okk....",
      ".....kYk..OYyk..Okk.....",
      "..Ok..OYOOYWYyOOyk..Ok..",
      "..OWOOYYYYYYYYyyyyOOyk..",
      ".OYYWYYyyyyyyyyyyyyoyyk.",
      ".OYK9yYYK9yYyoK9yoyK9ok.",
      ".kyMHyoyMHyoyoMHyooMHkk.",
      "..kkyyyyyyyyyyyyyyykkk..",
      "....kkkkkkkkkkkkkkkk....",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_pie: { // 久遠の聖冠: 白と金の宝冠の上に浮かぶ青緑に灯る霊の環 (光輪)・冠の正面の金の日輪と霊玉・白い七宝の帯
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      ".......3222221111.......",
      ".....43..........13.....",
      "....43............34....",
      ".....43..........34.....",
      ".......4433333344.......",
      "...........Ok...........",
      "......k....Ok....k......",
      ".....OWk..OWWk..Oyk.....",
      "..k..OYk.OYXXYk.Oyk..k..",
      "..Ok.OWYOYX12XYOyyoOOk..",
      "..OWOYYYYYX23XYyyyoyyk..",
      "..OYYYYYYyYXXYyyyyyyok..",
      "..O555666yyYYyy556667kk.",
      "..O5c6c65Y1Y12Y56c6c7k..",
      "..O566665yYYyyy566677k..",
      "..kyyyyyyyyyyyyyyyyyokk.",
      "...kkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_body_hv2: { // 久遠の覇鎧: 三枚重ねの大きな肩当ての黄金の全身鎧・胸に白く輝く日輪と霊玉・金の帯から垂れる覇者の紅の前垂れ
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      "..OOOOk.OyWYyYok.OOOOk..",
      ".OYWWYYOOoyYyoOOOyyYYyk.",
      "OYWYYyyyoOyyooOOoooyyYyk",
      "OYYyyyyooOyYyoOOOooooyyk",
      "OOOOOOOOOYWYyYyOOOOOOOOk",
      "OYWYyyyoOYYYyyyOOoooyYyk",
      "kOOOOOOOYYWXxYyyOOOOOOkk",
      ".kYYyyoOYWXXxxYyOOooykk.",
      "..kOOOOYyYXXxxyoyOOOkk..",
      "...OyYYYyyWXxYooyyyok...",
      "...OyYWYYyyYyooyyYyok...",
      "...OyYYYyyyyooooyyyok...",
      "...OOoooooooOOOOOOOOk...",
      "...OWYYYYY1232yyyyyYk...",
      "...koyyyyyyyoooooookk...",
      "....OyyRRqrRrqqrrook....",
      "....OyRRRrRRrrqrrrok....",
      "....OyRRrrRRrrqqrrok....",
      "....OyRRrRRRrrrqrrok....",
      "....koYWYYYYyyyyYykk....",
      ".....kkkkkkkkkkkkkk.....",
      "........................",
    ],
  },
  lr_a5_head_hv2: { // 久遠の覇兜: 紅の羽根飾りを立てた黄金の大兜・左右に広がる金の翼・額の帯に白い日輪と霊玉・T字の覗き穴
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "...........qk...........",
      "..........qRrk..........",
      ".........qRRrrk.........",
      "........OYrqqqyk........",
      "......OOYWYYyyYyOk......",
      "k....OYWWYYYyyyYYyk....k",
      "Ok..OYWYYYyyooyyyYyk..Ok",
      "OYk.OWYYyyyyooooyyYk.Oyk",
      "kYyOYYyyyyyyooooooyyOokk",
      ".kyoYyyyyyyyoooooooyOkk.",
      "..kOWYYYYWYXxyYyyyyYkk..",
      "...OyyyyyyX12xooooook...",
      "...Okkkkkkkkkkkkkkkkk...",
      "...OYWyyyyykkoooooYyk...",
      "...OYyyyyyykkooooooyk...",
      "...OYykyykykkokookoyk...",
      "...OyyyyyyyYyoooooook...",
      "...OoYYYYYYYyyyyyyyOk...",
      "..OyWyyyyyyyoooooooYok..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_hand_hv2: { // 久遠の覇籠手: 固く握った黄金の拳の籠手・指の節を覆う金の板・手の甲に白い日輪・紅の裏地をのぞかせる広がった袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........................",
      ".....OOOOOOOOOOOOOOOk...",
      ".....OWYyYWYyYWYyYWYyk..",
      ".....OYyoyYyoyYyoyYyok..",
      ".....OooOOooOOooOOooOk..",
      ".....OYYYYYYYYYYYYyyok..",
      "...OOYWYYYYYyYyYYyyyok..",
      "..OYWYYoYYYyWyYYyyyyok..",
      "..OWYYOoYYyWXWyYyyyyok..",
      "..OYYyOoYyWXX1WyyyyOok..",
      "..kYyyOoYYyWX2yYyyyook..",
      "...kyyOoYYYyWyYYyyyook..",
      "....kkkkyyyyyyyyyyookk..",
      "........OyyyyyyyyyoOk...",
      ".......OYYYYYYYYYYYYOk..",
      "......OYWYYYYYYYYYyyyok.",
      ".....OYrRRRRRRRRRrrqqyk.",
      ".....OyRRrRRrRRrRRrqqok.",
      "....OYWYYYYYYYYYYyyyyykk",
      "....kkkkkkkkkkkkkkkkkkk.",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_feet_hv2: { // 久遠の覇脚甲: 黄金の脛当てと尖った鉄靴を一組・白い日輪を据えた膝当て・脛に打った金の鋲と紅の飾り紐
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".............OOOOOOk....",
      "............OyYxxoook...",
      "............OYx23xoOk...",
      ".....OOOOOOOOoyxxooOk...",
      "....OYWXXyyykkOOOOOkk...",
      "....OWX12Xyok.OYyoOk....",
      "....kyYXXyyOk.OyooOk....",
      ".....koooookk.qrqqqk....",
      "......OWYyok..OYyoOk....",
      "......OYyyok..OyooOk....",
      "......qRrqqk..OYyoOk....",
      "......OWYyok..OyooOk....",
      "......OYyyok.OyyyooOk...",
      "......OWYyok.OOOOOOOk...",
      "......OYyyokOyYyyooOk...",
      ".....OYYYyyokyyyoooOk...",
      ".....OOooooOkooooooOk...",
      "....OYWYYyyokOOOOOOkk...",
      "..OOWYYYyyyokkkkkkkk....",
      ".OYYyyyyyyyok...........",
      ".kOOOOOOOOOkk...........",
      "..kkkkkkkkkk............",
      "........................",
    ],
  },
  lr_a5_shield_k2: { // 久遠の覇盾: 紅の地に白い日輪から金の光条が八方へ走る黄金縁の大盾・上縁の三つの金の尖り・日輪の芯の霊玉
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".Ok....Ok..Ok..Ok....Ok.",
      ".OWOOOOYWOOWYOOYyOOOOYk.",
      ".OWYYYYYYYYYyyyyyyyyyYk.",
      ".OyRRRRRRRRYyrrrrrrrrok.",
      ".OyRyRRRRRRYyrrrrrrorok.",
      ".OyRRyRRRRRYyrrrrrorrok.",
      ".OyRRRyRRRYWYyrrrorrrok.",
      ".OyRRRRyRYWXxYyrorrrrok.",
      ".OyRRRRRYXXXxxxyrrrrrok.",
      ".OyYYYYYWXX12xxYyyyyyok.",
      ".OyRRRRRYXX23xxyrrrrrok.",
      ".kyRRRRRRYWXxYyrrrrrrkk.",
      "..OyRRRRyRYWYyrorrrrok..",
      "..kyRRRyRRRYyrrrorrrkk..",
      "...OyRyRRRRYyrrrrorok...",
      "...kyyRRRRRYyrrrrrokk...",
      "....kyRRRRRYyrrrrrkk....",
      ".....kyRRRRYyrrrrkk.....",
      "......kyRRRYyrrrkk......",
      ".......kyRRYyrrkk.......",
      "........kyYWYykk........",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a5_hand_int: { // 久遠の知手袋: 細身の瑠璃の手袋を一組・甲に金糸で縫い取った魔法陣が青緑に灯る・金の帯の袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0", "H": "#6f8fd6", "K": "#3f5aa6", "M": "#26356e", "Z": "#141c40" }),
    art: [
      "..............Zk........",
      "............ZZKMZk......",
      "............ZMKMKMZk....",
      "............ZMKMKMKk....",
      "............ZMKMKMKk....",
      "............ZMKMKMKk....",
      ".......Zk...ZZMZMZMZk...",
      ".....ZZHKZk.ZKMMMMMZZk..",
      ".....ZKHKHKZKMOyyoOMZk..",
      ".....ZKHKHKHKOy3M4oOZk..",
      ".....ZKHKHKHKy3MZM4oZk..",
      ".....ZKHKHKHKOy4M4oOZk..",
      ".....ZMKMKMKMkOoooOMkk..",
      "..Zk.ZHKKKKKMMkMMMMZk...",
      "..ZKZHKoYYyoKMkyyyooOk..",
      "..kKKkoY2K3yoMkMM3MZZk..",
      "...kkkY2KMK3yMkkkkkkkk..",
      ".....ZoY3K3yoMk.........",
      ".....kKoyyyoKkk.........",
      "......ZKKKKKMk..........",
      ".....OYWYYYyyok.........",
      ".....ZK2KK2KMMk.........",
      ".....kkkkkkkkkk.........",
      "........................",
    ],
  },
  lr_a5_hand_pie: { // 久遠の聖手袋: 祝福に掲げた白い手袋の掌に金の聖印と青緑の霊玉・金の帯の袖口と下がる霊の環の飾り
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      ".........77k............",
      ".........76777k.........",
      "......77856756k.........",
      "......76756756k.........",
      "......76756756777k......",
      "......76756756756k......",
      "......77867867867k......",
      "......76756756756k......",
      "..7k..76666666666k......",
      "..76k.76666Yy6666k......",
      "..k66756666Yy6666k......",
      "...k6656YYY12yyy6k......",
      "....k656yyy23ooo6k......",
      ".....k56666Yo6666k......",
      "......k6666yo666kk......",
      ".......766666667k.......",
      "......OYWYYYYYyyyk......",
      ".....75666666266678k....",
      "....7566666666666777k...",
      "....kkkkkkkyykkkkkkkk...",
      "...........OYk..........",
      "...........kkk..........",
      "........................",
    ],
  },
  lr_a5_feet_c1: { // 久遠の靴: 白い帯を斜めに編み上げた空色の布の軽い長靴を一組・足首から風にたなびく白い帯・金の縁の靴底
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      ".7k..................7k.",
      "7kk................7kkk.",
      "kk...........9999776k...",
      ".k7k.........9uuu5u9k...",
      "..kk7k.......77bb679k...",
      "....kk.......967bb69k...",
      ".....k.......9b67bb7k...",
      ".............77bb679k...",
      "....999999k..967bb69k...",
      "....9bbbbbuk.9b67bb7k...",
      "....76cc56uk.9buuuu9k...",
      "....956cc5uk9bbuuuu9k...",
      "....9c56cc6kbbbuuuu9k...",
      "....76cc56ukbbbuuuuu9k..",
      "....956cc5ukbbuuuuuu99k.",
      "....9c56cc6kyyyyyyoookk.",
      "....9cbbbbukkkkkkkkkkk..",
      "...9ccbbbbuk............",
      "..9cccbbbbuk............",
      ".9ccccbbbbbuk...........",
      ".9cccbbbbbbuuk..........",
      ".kWYYYYYYyyykk..........",
      "..kkkkkkkkkkk...........",
      "........................",
    ],
  },
  lr_a5_feet_c2: { // 久遠の聖靴: 金糸で十字を縫い取った白い柔らかな長靴を一組・空色の履き口・足首に下がる霊の環の数珠
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      ".............999999k....",
      ".............9uuuuu9k...",
      ".............7777778k...",
      ".............777y778k...",
      ".............77yYy78k...",
      "....999999k..777y778k...",
      "....9bbbbbuk.777o778k...",
      "....7666667k.7777778k...",
      "....766Y667k.OoYyooOk...",
      "....76YWY67k.7777778k...",
      "....766Y667k.7777778k...",
      "....766y667k76777778k...",
      "....7666667k67777778k...",
      "....OyWYyyok777777788k..",
      "....766666yk777777788k..",
      "....7666667oyyyyyyookk..",
      "...75666667kykkkkkkkk...",
      "..756666667oYk..........",
      ".7566666667Y2k..........",
      ".7666666667okk..........",
      ".kyYYYYYYyykk...........",
      "..kkkkkkkkkk............",
      "........................",
    ],
  },
  lr_a5_shield_o: { // 久遠の宝珠: 青緑に脈打つ白い霊の宝珠・斜めにめぐる金の霊の環・宝珠を抱く金の三本爪の台座
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........................",
      ".........44444k.........",
      ".......441122224k.......",
      "......41112222222k......",
      ".....4111211112223k.....",
      ".....4112111122233kOOO..",
      "....411211112222333k.Oy.",
      "....412111XXXX22233k.yo.",
      "...O422111XXXX22233kyyo.",
      "..OO422112XXX2222yyyyo..",
      ".OO.422122XX22YYYyooo...",
      ".WW.k2222YYYYYYoookk....",
      ".yyWWWWWYYyyooo334k.....",
      "..yyyyyyyy2223334kk.....",
      "......k333333334kk......",
      ".......OY333334Yk.......",
      ".......kWY3334ykk.......",
      "........OWYYYYyk........",
      "........kYWYYykk........",
      ".........Oyyyok.........",
      ".......OOYYYyyyOk.......",
      ".......kkkkkkkkkk.......",
      "........................",
    ],
  },
  lr_a5_shield_t: { // 久遠の聖典: 金の四隅と縁で飾った白い革の聖典・表紙の霊の環の金の飾り板に青緑の霊玉・小口に二つの金の留め金
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      "........................",
      "...OOOOOOOOOOOOOOOOk....",
      "..OYWY55555556666YYyk...",
      "..OWY5555555566666yyok..",
      "..OY556666666666667yok..",
      "..O556666yYYYy666667yk..",
      "..O56666yY222Yy66667yk..",
      "..O5666yY21XX2Yy6667Yk..",
      "..O5666Y21X112Yy6667WYk.",
      "..O5666Y2X1123yo6667YYk.",
      "..O5666Y21123yyo6667Ykk.",
      "..O5666yY2233yo66667yk..",
      "..O56666yY33yo666667yk..",
      "..O566666yyyoo666677yk..",
      "..O566666666666667777yk.",
      "..O56666666666666777WYk.",
      "..O5666666666666677yYok.",
      "..OY566666666666777yyok.",
      "..OWY666666666667777ykk.",
      "..kYWYYYYYYYYYYYYYYyok..",
      "...kyyyyyyyyyyyyyyyokk..",
      "....kkkkkkkkkkkkkkkkk...",
      "........................",
    ],
  },
};
