// 手描きの装備の絵: 組 arm3 (LR の防具)
//   久遠 (a5): 朽ちぬ霊鉄 = 月白の鋼に金の縁、青緑に灯る霊の環の紋 (永遠の輪)。覇の品は黄金に白い日輪。
//   永劫 (a20): 夜の紫鋼に銀の星々と金の縁、星をめぐる環の紋。
import { pal } from "./pal.js";
export const ART_ARM3 = {
  lr_a5_body_hv: { // 久遠の鎧: 月白の霊鉄の胸甲と重ねた肩当て・金の高い襟と縁・胸に青緑に灯る霊の環・金の帯と重ねの草摺
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..eek...OOOOOOOk...eek..",
      ".exxwek.OyWYyYok.eevwwk.",
      ".exwwwveeOyyooOeegvvvwk.",
      ".ewYwvvgexwwvvweeggvyvk.",
      ".OYYyyyoexxwvwweOoooyyk.",
      ".evvYvgeexwwvvweeegyggk.",
      ".kyyyyoexwwwvvvweOoookk.",
      "..kggeexwwYYyyvvweeekk..",
      "...exxwwwY1232yvvvwwk...",
      "...exwwwwY2343yvvvvwk...",
      "...kwwwvwwyyoovvgvvkk...",
      "....ewwvvww34vvggvvk....",
      "....evwvvvw23vgggvgk....",
      "....OyyyYYYYyyyyoook....",
      "....Ooyyyy1232ooooOk....",
      "....ewxxxwweevvwwwvk....",
      "...egvvvvvveeggggggek...",
      "...ewxxxwwweevvvwwwvk...",
      "..egvvvvvvveegggggggek..",
      "..ewxxxwwwweevvvvwwwvk..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_hv: { // 久遠の鉄兜: 月白の霊鉄の大兜・頭頂から面頬へ通る金の鶏冠・額の金の帯に霊の環・覗き穴に灯る青緑の眼光
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..........OOOk..........",
      "........eeYWYyek........",
      "......eexxYWYywwek......",
      ".....exxxwYYyyvwwwk.....",
      "....exxwwwYYyyvvvwwk....",
      "....exwwwvYYyygvvvwk....",
      "...exwwwvvYYyyggvvvwk...",
      "...ewwwvvvyYyogggvvvk...",
      "...OYYYYYyy12ooyyyyyk...",
      "..eevkk12kkkkkk32kkgek..",
      "..Oexwwvvvvyoggggvvwek..",
      ".O2ewwvkvkvYygkgkgvve3k.",
      ".k3ewvvvvvvYyggggggvekk.",
      "..kewvvkvkvyogkgkggvkk..",
      "...ewvvvvvvYyggggggvk...",
      "...OyyyyyyyYyoooooook...",
      "..exwwwwvvvvggggvvvvwk..",
      ".exwwwvvvvggeeggggvvvwk.",
      ".kvvvvggggeeeeeeeegggkk.",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_hand_hv: { // 久遠の籠手: 板を連ねた月白の霊鉄の指と親指・拳に青緑の霊玉を据えた金の帯・霊の環を打ち出した金縁の袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..........eek...........",
      "......eek.ewk.eek.......",
      "......ewvkxwvkxwk.......",
      "......eggkgggkgggkek....",
      "......ewvkxwvkxwvkxk....",
      "......ewvkxwvkxwvkwk....",
      "......eggkgggkgggkgk....",
      "..ek..ewvkxwvkxwvkwk....",
      ".ewweeoyYYYY12YYYYyk....",
      ".kYyyooyyyyy23yyyyok....",
      "..ewvgxxwwwwwwwwvvvk....",
      "..kwvgxwwwwwvvvvvvgk....",
      "...kkkxwwwwvvvvvgggk....",
      "......ewwwvvvvvvggkk....",
      "......exwwvvvvvgggk.....",
      "......eggggggggggek.....",
      ".....OYYYYYYYYYYYyyk....",
      "....exwwwwyYYywvvvvgk...",
      "....ewwwwy2112yvvvggk...",
      "....ewwwwy2332yvvvggk...",
      "....ewvvvvyyyyvvgggek...",
      "....kkkkkkkkkkkkkkkkk...",
      "........................",
    ],
  },
  lr_a5_feet_hv: { // 久遠の具足: 月白の霊鉄の脛当てと重ねの鉄靴を一組・扇の形に張り出した金縁の膝当てに霊玉・脛を走る青緑の霊の筋
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "...........OOOOOOOOk....",
      "..........Oywwv23vgok...",
      "...OOOOOOOyowv3443gekk..",
      "..OYxxw12wvykvggggeok...",
      "..Oxxw2332vgykooooOkk...",
      "..kYwwvvvvgykwvvggek....",
      "...koyyyyyoOkwv3vgek....",
      "....exwwvvgkwwv4vgek....",
      "....exw2wvgkwwv3vgek....",
      "....exw3wvgkwwv4vgek....",
      "....exw2wvgkwwv3vgek....",
      "....exw3wvgkwwvvvgek....",
      "....exw2wvgkyyyyyooOk...",
      "....exwwwvgkwvvvvggek...",
      "...OYYYYYyyokvvvvggek...",
      "...exwwwwvvgkvvvvggek...",
      "..exxwwwwvvgkeeeeeeek...",
      ".exxwwwwwvvgkvvvvvgek...",
      ".eggggggggggkyyyyyookk..",
      ".exxwwwwwwvgkkkkkkkkk...",
      ".kYYYYYYYYyykk..........",
      "..kkkkkkkkkkk...........",
      "........................",
    ],
  },
  lr_a5_shield_k1: { // 久遠の大盾: 胸壁の形に刻んだ上縁と石積みの目地を打ち出した月白の霊鉄の大盾・金の縁・盾心に青緑に灯る大きな霊の環
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".eek.eek.eeeeek.eek.eek.",
      ".OYYOYYYOYYYyyyOyyyOyyk.",
      ".OXxxxxxxxxxwwwwwwwwwxk.",
      ".Oxwwwwwwwwwvvvvvvvvvwk.",
      ".Oxvvvvvvvvvgggggggggwk.",
      ".OxwwwvwwwyYyovvvgvvvwk.",
      ".OxwwwvwwyY34yovvgvvvwk.",
      ".OxvvvvvyY3234yogggggwk.",
      ".OxwvwwwY321234yvvvgvwk.",
      ".OxwvwwwY321234yvvvgvwk.",
      ".OxvvvvvyY3234yogggggwk.",
      ".OxwwwvwwyY34yovvgvvvwk.",
      ".kxwwwvwwwyyoovvvgvvvkk.",
      "..Oxvvvvvvvvggggggggwk..",
      "..kxwvwwwwwwvvvvvvgvkk..",
      "...Oxwvwwwwwvvvvvgvwk...",
      "...kxvvvvvvvgggggggkk...",
      "....kxwwwvwwvvgvvvkk....",
      ".....kxwwvwwvvgvvkk.....",
      "......kxvvvvggggkk......",
      ".......kkwwwvvkkk.......",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a5_shield_r1: { // 久遠の円盾: 打ち出しの環が盛り上がる月白の霊鉄の円盾・金の鋲の縁・青緑の霊玉を据えた金の盾心
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".........OOOOOk.........",
      "......OOOWYggYYOOk......",
      ".....OWWggxxxxggYYk.....",
      "....OWgxxxxxxxxxwgyk....",
      "...OWgxxxxggggxwwwgyk...",
      "..OWgxxxggwwwwggwwwvyk..",
      "..OWxxxgwwwwwvvvgwwwyk..",
      "..Ogxxgwwwwwvvvvvwwwvk..",
      ".OWgxxgwwwyYYovvvwwwvok.",
      ".OYxxgwwwyY12Yovvvwwwok.",
      ".OgxxgwwwY1X23ovvvwwwvk.",
      ".OgxxgwwvY1223ovvvwwwvk.",
      ".OYxxgwvvoy33yOvvvwwvok.",
      ".kYgxxgvvvooOOvvvwwvvkk.",
      "..Ogxwgvvvvvvvvvvwvvvk..",
      "..OYwwwgvvvvvvvvwvvvOk..",
      "..kYgwwwwwvvvvwwvvvvkk..",
      "...kygwwwwwwwwwvvvvkk...",
      "....kyvwwwwwwwvvvvkk....",
      ".....kyyvvwwwvvvOkk.....",
      "......kkkoovvokkkk......",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a5_body_lt: { // 久遠の革鎧: 青緑の縁取りを走らせた霊獣の革を重ねた胴・肩を覆う白い毛皮の肩掛け・胸の霊の環の留め金・金の帯と革の垂れ
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "......7777ZZZZ887k......",
      "...7776667ZZZZ877777k...",
      ".775666667888887777767k.",
      ".76666677eH34Ke8877777k.",
      ".76667778eH34Ke8888777k.",
      ".77778888eH34Ke8888888k.",
      ".k8888ZZeHK34MKeZZ888kk.",
      "..kMKKKZeHK34MKeZMMMkk..",
      "...eHHK3HHKYyMKK4MKKk...",
      "...eHHK3HHY12yKK4MKKk...",
      "...eHKK3HKy23oMK4MMKk...",
      "...eHKK3KKKoOMMM4MMKk...",
      "...eKKK3KKKKMMMM4MMMk...",
      "...OyWyyyyyyooooooYok...",
      "...Oykkykk123kkokkook...",
      "...eHk.Zk.ZKMk.Zk.ZKk...",
      "...eHk.Zk.ZKMk.Zk.ZKk...",
      "...eKk.Zk.ZMZk.Zk.ZMk...",
      "...e3k.4k.423k.4k.44k...",
      "...kkk.kk.kkkk.kk.kkk...",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_lt: { // 久遠の革兜: 霊獣の耳を立てた白い毛皮の飾り・青緑の縁取りの霊獣の革の頭巾兜・額の毛皮の帯に霊の環・金の鼻当てと首垂れ
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "..7k................7k..",
      "..75k..............86k..",
      "..756k.eZZZZZZZZk.876k..",
      "..k667eHHKKKMMMKKe87kk..",
      "...k6eHHHKKKMMMKKKekk...",
      "....eHHHKKKKMMMMKKKk....",
      "...eHHHKKKKKMMMMMKKKk...",
      "...eHHKKKKKKMMMMMMKKk...",
      "..eHHKKKKKoYyOMMMMMKKk..",
      "..e5566666Y12y7777766k..",
      "..e5666667y23o8777776k..",
      "..eH3ZkkkkoYyOkkkkZ4Kk..",
      "..eH3ZkkkkoYyOkkkkZ4Kk..",
      "..eH3ZkkkkkyokkkkkZ4Kk..",
      "..eH3ZkkkkkkkkkkkkZ4Kk..",
      "..eK3KZZZZZZZZZZZZM4Mk..",
      "..eHK333333KM444444MKk..",
      "..eKKKKKKKKKMMMMMMMMMk..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_hand_lt: { // 久遠の革手甲: 甲に青緑の爪痕の縫い取りをした霊獣の革の手甲を一組・指の付け根に並ぶ金の鋲・白い毛皮の袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "..............ZZZk......",
      "............ZZKMKk......",
      "............ZMKMKMZk....",
      "............ZMKMKMKk....",
      "............ZMKMKMKk....",
      "......ZZZk..ZZZZZZZk....",
      "....ZZHKHk..OYoYoYoYk...",
      "....ZKHKHKZZK4MMMM4ZZk..",
      "....ZKHKHKHKKM4MM4MMZk..",
      "....ZKHKHKHKkMM44MMZZk..",
      "....ZMZMZMZMkMMMMMMZkk..",
      ".Zk.OWyWyWyWoKMMMMMZk...",
      ".ZKZH3KKKK3MMkMMMMZZk...",
      ".kKKkK3KK3KKMk677778k...",
      "..kKkKK33KKMMk7777788k..",
      "...kkKKKKKKMMk777888kk..",
      ".....ZKKKKKMkkkkkkkkk...",
      ".....ZKKKKMMk...........",
      "....75566667k...........",
      "...7566666677k..........",
      "...k66666777kk..........",
      "....kkkkkkkkk...........",
      "........................",
    ],
  },
  lr_a5_feet_lt: { // 久遠の革靴: 白い毛皮の履き口と青緑の縫い目の霊獣の革の長靴を一組・金の留め具の革帯・爪先を守る金の覆い
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "..............7777888k..",
      ".............k67777788k.",
      "..............k778888kk.",
      ".....7777777k..ZK4MMZk..",
      "....k56666677k.ZK4MMZk..",
      ".....k667778kk.OoYooOk..",
      "......ZH3KKMk..ZK4MMZk..",
      "......ZH3KKMk..ZK4MMZk..",
      "......OyWyyok..ZK4MMZk..",
      "......ZH3KKMk..OoYooOk..",
      "......ZH3KKMk..ZK4MMZk..",
      "......ZH3KKMk..ZK4MMZk..",
      "......OyWyyok.ZKK4MMZk..",
      "......ZH3KKMkZKMM4MMZk..",
      "......ZH3KKMkMMM4MMMZk..",
      ".....ZHH3KKMkM44MMMMZk..",
      "...ZZHKK3KKMkMMMMMMMZk..",
      "..ZHKKK3KKKMkZZZZZZZkk..",
      ".OYHK33KKKKMkkkkkkkkk...",
      ".OYyKKKKKKKMk...........",
      ".kyoZZZZZZZkk...........",
      "..kkkkkkkkkk............",
      "........................",
    ],
  },
  lr_a5_shield_r2: { // 久遠の小盾: 縁から青緑の縞が獣の毛並みのように走る霊獣の革を張った小盾・金の鋲の月白の霊鉄の縁・霊の環の金の盾心
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f6f1e4", "6": "#d2c9b2", "7": "#968c76", "8": "#574e40", "X": "#fffbe6", "W": "#fff0b0", "H": "#c4b192", "K": "#94805f", "M": "#625140", "Z": "#352a20" }),
    art: [
      "........................",
      "........................",
      "...........ek...........",
      "........eeeWxeek........",
      "......eexxHH4Hwwek......",
      ".....ex43HHH3HH34vk.....",
      "....exxH3HHHHHK3Kvvk....",
      "....exHHH3HHHK3KKKvk....",
      "...eWHHHHHHHKKKKKKWvk...",
      "...exHHHHHyYYoKKKKKvk...",
      "...eHHHHHyY12YoKKKKKk...",
      "..exH433HY1X23oKKKKKgk..",
      "..kxHHHHKY1223oKK334kk..",
      "...eHHHKKoy33yOKKKKKk...",
      "...ewHKKKKooOOKKKKKek...",
      "...kWKKKKKKKKKKKKKWkk...",
      "....ewKKK3KKKK3KKMek....",
      "....kvvK3KKKKKK3Mekk....",
      ".....kv43KKK3KK34kk.....",
      "......kkvvKK4Kekkk......",
      "........kkkWkkkk........",
      "...........kk...........",
      "........................",
      "........................",
    ],
  },
  lr_a5_body_int: { // 久遠の法衣: 深い瑠璃の法衣と広い袖・金の高い襟と前の縁取り・前合わせに青緑に灯る魔力の流れ・袖と裾に金の縁
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0", "H": "#6f8fd6", "K": "#3f5aa6", "M": "#26356e", "Z": "#141c40" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      "......ZZOyM23ZoOZk......",
      "....ZZHKOyM23ZoOMKZk....",
      "..ZZHKKKMyM23ZoZMMMKZk..",
      ".ZHKKKKKMyM23ZoZMMMMMKk.",
      ".ZK3KKKKMyM23ZoZMMMM4Mk.",
      ".Z3KKKMZHyM23ZoKZZMMM4k.",
      ".ZKKKMZHHyM23ZoKKZZMMMk.",
      ".ZKKMZHHKyM23ZoMKKZZMMk.",
      ".ZKMMZHKKyM23ZoMMKZZZMk.",
      ".ZMMMZHKKyM23ZoMMKZZZZk.",
      ".ZMMZHHKKyM23ZoMMKKZZZk.",
      ".ZMMZHKKKyM23ZoMMMKZZZk.",
      ".ZMMZHK3KyM23ZoM4MKZZZk.",
      ".OyyoHK3KyM23ZoM4MKOook.",
      ".kkkOHKK3yM23Zo4MMKkkkk.",
      "....eHKK3yM23Zo4MMKk....",
      "....eHKKKyM23ZoMMMKk....",
      "...eHKK3KyM23ZoM4MMKk...",
      "...eHK3KKyM23ZoMM4MKk...",
      "...kkkkkkkkkkkkkkkkkk...",
      "........................",
      "........................",
    ],
  },
  lr_a5_body_pie: { // 久遠の聖衣: 金縁の短い肩掛けを重ねた白い聖衣・胸から裾へ垂れる金のストラに霊の環を二つ・空色の裏地・金の袖口と裾
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "9": "#151d2c", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      "......7766yYyo777k......",
      "....776666yYyo77777k....",
      "..77666666yYyo7777777k..",
      ".7566666c6yYyo7b777776k.",
      ".76666c66cyYyob77b7777k.",
      ".OyyyyyyyoyYyoOoooooook.",
      ".766776677Y12y88778877k.",
      ".7677ebb67Y23y87uue887k.",
      ".767eb5667yYyo8776ue87k.",
      ".767e56667yYyo87776e87k.",
      ".777e56667yYyo87776e88k.",
      ".777e56667yYyo87776e88k.",
      ".777e56667yYyo87776e88k.",
      ".Oyoe56667Y12y87776eOok.",
      ".kkke56667Y23y87776kkkk.",
      "....e56667yYyo87776k....",
      "...e566667yYyo877776k...",
      "...e566677yYyo887776k...",
      "..e5666677yYyo8877776k..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_int: { // 久遠の知冠: 金の環の正面に立つ台座に瑠璃と青緑の大きな知恵の玉・左右へ翼のように扇に開く金の透かし・環に並ぶ小さな瑠璃
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "9": "#a8c8ff", "X": "#fffbe6", "W": "#fff0b0", "H": "#6f8fd6", "K": "#3f5aa6", "M": "#26356e", "Z": "#141c40" }),
    art: [
      "........................",
      "........................",
      "...........Ok...........",
      "..........OWYk..........",
      ".Y.......OY19Hk.......y.",
      ".WY..Y...O199Kk...y..yo.",
      ".YWY.WY..OH9HKk..yo.yyo.",
      ".oYWYYWY.OHHKMk.yoyyyoO.",
      "..oYWYYWykyKMkkoyoyyoO..",
      "...ooYYyy.Oyok.yyooOO...",
      ".....OOoo.OYyk.ooOO.....",
      "..Ok.....OYWYyk.....Ok..",
      "..OWOOOOOYYYYYyOOOOOyk..",
      ".OYYWYYyyyyyyyyyyyyoyyk.",
      ".OYK9yYYK9yYyoK9yoyK9ok.",
      ".kyMHyoyMHyoyoMHyooMHkk.",
      "..kkyyyyyyyyyyyyyyykkk..",
      "....kkkkkkkkkkkkkkkk....",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_head_pie: { // 久遠の聖冠: 白と金の宝冠の上に浮かぶ青緑に灯る霊の環 (光輪)・冠の正面の金の日輪と霊玉・白い七宝の帯
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "9": "#151d2c", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      ".......3222221111.......",
      ".....43..........13.....",
      "....43............34....",
      ".....43..........34.....",
      ".......4433333344.......",
      "...........Ok...........",
      "......k....Ok....k......",
      ".....OWk..OWWk..Oyk.....",
      "..k..OYk.OYXXYk.Oyk..k..",
      "..Ok.OWYOYX12XYOyyoOOk..",
      "..OWOYYYYYX23XYyyyoyyk..",
      "..OYYYYYYyYXXYyyyyyyok..",
      "..O555666yyYYyy556667kk.",
      "..O5c6c65Y1Y12Y56c6c7k..",
      "..O566665yYYyyy566677k..",
      "..kyyyyyyyyyyyyyyyyyokk.",
      "...kkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a5_body_hv2: { // 久遠の覇鎧: 三枚重ねの大きな肩当ての黄金の全身鎧・胸に光条を放つ白い日輪と霊玉・金の帯から垂れる覇者の紅の前垂れ
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      "..OOOOk.OyWYyYok.OOOOk..",
      ".OYWWYYOOoyYyoOOOyyYYyk.",
      ".OWYYyyyoOyyooOOoooyyYk.",
      ".OYyyyyooOyYyoOOOooooyk.",
      ".OOOOOOOOYWYyYyOOOOOOOk.",
      ".OWYyyyoOYyYyoyOOoooyYk.",
      ".OOOOOOOYyWXxYoyOOOOOOk.",
      ".kYYyyoOYWXXxxYyOOooykk.",
      "..kOOOOYyWXXxxYoyOOOkk..",
      "...OyYYYYyWXxYoyyyyok...",
      "...OyYWYYyYyoyoyyYyok...",
      "...OyYYYyyyyooooyyyok...",
      "...OOoooooooOOOOOOOOk...",
      "...OWYYYYY1232yyyyyYk...",
      "...kokkyyyyyooookkokk...",
      "....kk.ORRRRrrrrk.kk....",
      ".......ORrRRrrqrk.......",
      ".......ORrRRrrqrk.......",
      ".......ORrRYyrqrk.......",
      ".......kYWYYyyYkk.......",
      "........kkkkkkkk........",
      "........................",
    ],
  },
  lr_a5_head_hv2: { // 久遠の覇兜: 紅の羽根の前立てを立てた黄金の大兜・左右に広がる金の翼・額の帯に白い日輪と霊玉・T字の覗き穴
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "..........qqqk..........",
      "..........qRrk..........",
      ".........qRRrrk.........",
      ".........qRRrrk.........",
      ".Y......OYYYyyyk......y.",
      ".YW...OOYWYYyyYyOk...yo.",
      ".WYY.OYWWYYYyyyYYyk.yyo.",
      ".YWYyYWYYYyyooyyyYyyyoo.",
      "..YWYyYYyyyyooooyyyyoo..",
      "...YYyoyyyyyooooooyoo...",
      "...OooOyyyyXxooooOokk...",
      "...OWYYYYWX12xYyyyyYk...",
      "...OyyyyyyX23xooooook...",
      "...Okkkkkkkkkkkkkkkkk...",
      "...OYWyyyyykkoooooYyk...",
      "...OYyyyyyykkooooooyk...",
      "...OYykyykykkokookoyk...",
      "...OyyyyyyyYyoooooook...",
      "...OoYYYYYYYyyyyyyyOk...",
      "..OyWyyyyyyyoooooooYok..",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
    ],
  },
  lr_a5_hand_hv2: { // 久遠の覇籠手: 固く握った黄金の拳の籠手・指の節を覆う金の板と横に締めた親指・袖口に白い日輪と霊玉・紅の裏地
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........................",
      ".....OOOOOOOOOOOOOOOk...",
      ".....OWYyYWYyYWYyYWYyk..",
      ".....OYyoYYyoYYyoYYyok..",
      ".....OyOOoyOOoyOOoyOOk..",
      ".....OWYyYWYyYWYyYWYyk..",
      "...OOYYYYYYYyoYYyoYyok..",
      "..OYWWYYYYYYYyoYyoyyok..",
      "..OWYYyyyyyyyyoyyoyyok..",
      "..kkyoooooooooOooOookk..",
      "....kYYYYYYYYYYYYyyok...",
      ".....kkyyyyyyyyyyykkk...",
      ".......OYYYYYYYYyok.....",
      ".....OOWYYYYyYYyyyk.....",
      "....OYWYYYyWXWyYyyyk....",
      "....OWYYYyWX12WyYyyk....",
      "...OYYYYYYyW2WyYyyyyk...",
      "...OYYYYYYYyWyYYyyyyk...",
      "..OYWYYYYYYYYYYYyyyyyk..",
      "..ORRRRRRRRRRRRRRrrrqkk.",
      "..kkkkkkkkkkkkkkkkkkkk..",
      "........................",
      "........................",
    ],
  },
  lr_a5_feet_hv2: { // 久遠の覇脚甲: 黄金の脛当てと先の尖った鉄靴を一組・白い日輪を据えた扇形の膝当て・脛に巻いた覇者の紅の飾り紐
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "...........OOOOOOOOk....",
      "..........OyYxxxooook...",
      "...OOOOOOOyoxx23xooOkk..",
      "..OYWXXXyyyykxxxooOok...",
      "..OWXX12XyyOykOOOOOkk...",
      "..kYyXXXyyOykYyyooOk....",
      "...koooooooOkyyoooOk....",
      "....OWYYyyokrrrrqqqk....",
      "....OYYyyyokyYyyooOk....",
      "....qRRRrqqkyyyoooOk....",
      "....OWYYyyokyYyyooOk....",
      "....OYYyyyokyyyoooOk....",
      "....OWYYyyokyyyyyooOk...",
      "....OYYyyyokOOOOOOOOk...",
      "...OYYYYYyyokyyyyooOk...",
      "...OOooooooOkyyyyooOk...",
      "...OWYYYYyyokyyyooooOk..",
      "..OYWYYYYyyokooooooOOk..",
      ".OYYYYYYyyyyokOOOOOOkk..",
      ".OYyyyyyyyyookkkkkkkk...",
      ".kOOOOOOOOOOkk..........",
      "..kkkkkkkkkkk...........",
      "........................",
    ],
  },
  lr_a5_shield_k2: { // 久遠の覇盾: 紅の地に白い日輪から金の光条が八方へ走る黄金縁の大盾・上縁の三つの金の尖り・日輪の芯の霊玉
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".Ok....Ok..Ok..Ok....Ok.",
      ".OWOOOOYWOOWYOOYyOOOOYk.",
      ".OWYYYYYYYYYyyyyyyyyyYk.",
      ".OyRRRRRRRRYyrrrrrrrrok.",
      ".OyRyRRRRRRYyrrrrrrorok.",
      ".OyRRyRRRRRYyrrrrrorrok.",
      ".OyRRRyRRRYWYyrrrorrrok.",
      ".OyRRRRyRYWXxYyrorrrrok.",
      ".OyRRRRRYXXXxxxyrrrrrok.",
      ".OyYYYYYWXX12xxYyyyyyok.",
      ".OyRRRRRYXX23xxyrrrrrok.",
      ".kyRRRRRRYWXxYyrrrrrrkk.",
      "..OyRRRRyRYWYyrorrrrok..",
      "..kyRRRyRRRYyrrrorrrkk..",
      "...OyRyRRRRYyrrrrorok...",
      "...kyyRRRRRYyrrrrrokk...",
      "....kyRRRRRYyrrrrrkk....",
      ".....kyRRRRYyrrrrkk.....",
      "......kyRRRYyrrrkk......",
      ".......kyRRYyrrkk.......",
      "........kyYWYykk........",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a5_hand_int: { // 久遠の知手袋: 細身の瑠璃の手袋を一組・甲に金糸で縫い取った魔法陣が青緑に灯る・金の帯の袖口
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0", "H": "#6f8fd6", "K": "#3f5aa6", "M": "#26356e", "Z": "#141c40" }),
    art: [
      "........................",
      "..............Zk........",
      "............ZZKMZk......",
      "............ZMKMKMZk....",
      "............ZMKMKMKk....",
      "............ZMKMKMKk....",
      ".......Zk...ZMKMKMKk....",
      ".....ZZHKZk.ZZMZMZMZk...",
      ".....ZKHKHKZKKMMMMMZZk..",
      ".....ZKHKHKHKMOyyoOMZk..",
      ".....ZKHKHKHKOy3M4oOZk..",
      ".....ZKHKHKHKy3MZM4oZk..",
      ".....ZMKMKMKMky4M4oOZk..",
      "..Zk.ZHKKKKKMMkoooOMkk..",
      "..ZKZHKoYYyoKMkMMMMZk...",
      "..kKKkoY2K3yoMkyyyooOk..",
      "...kkkY2KMK3yMkMM3MZZk..",
      ".....ZoY3K3yoMkkkkkkkk..",
      ".....kKoyyyoKkk.........",
      "......ZKKKKKMk..........",
      ".....OYWYYYyyok.........",
      ".....ZK2KK2KMMk.........",
      ".....kkkkkkkkkk.........",
      "........................",
    ],
  },
  lr_a5_hand_pie: { // 久遠の聖手袋: 祝福に掲げた白い手袋の掌に金の聖印と青緑の霊玉・金の帯の袖口と下がる霊の環の飾り
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "9": "#151d2c", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      ".........77k............",
      ".........76777k.........",
      "......77856756k.........",
      "......76756756k.........",
      "......76756756777k......",
      "......76756756756k......",
      "......77867867867k......",
      "......76756756756k......",
      "..7k..76666666666k......",
      "..76k.76666Yy6666k......",
      "..k66756666Yy6666k......",
      "...k6656YYY12yyy6k......",
      "....k656yyy23ooo6k......",
      ".....k56666Yo6666k......",
      "......k6666yo666kk......",
      ".......766666667k.......",
      "......OYWYYYYYyyyk......",
      ".....75666666266678k....",
      "....7566666666666777k...",
      "....kkkkkkkyykkkkkkkk...",
      "...........OYk..........",
      "...........kkk..........",
      "........................",
    ],
  },
  lr_a5_feet_c1: { // 久遠の靴: 白い帯を斜めに編み上げた空色の布の軽い長靴を一組・足首で結んだ白い帯の蝶結びが風にたなびく・金の縁の靴底
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "9": "#151d2c", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      "............9999999k....",
      "............9uuuuuu9k...",
      "............77bb67b9k...",
      "..55....55..967bb679k...",
      ".5665..5665.9b67bb69k...",
      ".5666556667877bb67b9k...",
      "..566y2y6789b67bb679k...",
      "...86Y1y8bbukb67bb69k...",
      "..567oyo65cukuuuuuu9k...",
      ".567856c567ukuuuuuu9k...",
      ".6789c56c67ukuuuuuu9k...",
      "..8.76cc568ukuuuuuuu9k..",
      "....956cc56ukuuuuuuu99k.",
      "....9c56cc5ukuuuuuuu99k.",
      "....9bbbbbbukyyyyyoookk.",
      "...9cbbbbbbukkkkkkkkkk..",
      "..9ccbbbbbbuk...........",
      ".9cccbbbbbbbuk..........",
      ".9ccbbbbbbbbuuk.........",
      ".9ccbbbbbbbbuuk.........",
      ".kWYYYYYYYyyykk.........",
      "..kkkkkkkkkkkk..........",
      "........................",
    ],
  },
  lr_a5_feet_c2: { // 久遠の聖靴: 金糸で十字を縫い取った白い柔らかな長靴を一組・空色の履き口に金の縁・足首から下がる霊の環の数珠
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "9": "#151d2c", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      "............kOOOOOOOk...",
      ".............9bbbbuuk...",
      ".............9uuuuu9k...",
      ".............7777778k...",
      ".............777y778k...",
      "...kOOOOOOOk.77yYy78k...",
      "....9ccccbbk.777y778k...",
      "....9bbbbbuk.777o778k...",
      "....7666667k.OoYyooOk...",
      "....766Y667k.7777778k...",
      "....76YWY67k.7777778k...",
      "....766Y667k76777778k...",
      "....766y667k67777778k...",
      "....OyWYyyok777777788k..",
      "....766666yk777777788k..",
      "....766666okyyyyyyookk..",
      "...756666oYokkkkkkkkk...",
      "..7566666Y2y............",
      ".75666666o3ok...........",
      ".O6666666677k...........",
      ".kyYYYYYYyykk...........",
      "..kkkkkkkkkk............",
      "........................",
    ],
  },
  lr_a5_shield_o: { // 久遠の宝珠: 青緑に脈打つ白い霊の宝珠・斜めにめぐる金の霊の環・宝珠を抱く金の三本爪の台座
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........................",
      ".........44444k.........",
      ".......441122224k.......",
      "......41112222222k......",
      ".....4111211112223k.....",
      ".....4112111122233kOOO..",
      "....411211112222333k.Oy.",
      "....412111XXXX22233k.yo.",
      "...O422111XXXX22233kyyo.",
      "..OO422112XXX2222yyyyo..",
      ".OO.422122XX22YYYyooo...",
      ".WW.k2222YYYYYYoookk....",
      ".yyWWWWWYYyyooo334k.....",
      "..yyyyyyyy2223334kk.....",
      "......k333333334kk......",
      ".......OY333334Yk.......",
      ".......kWY3334ykk.......",
      "........OWYYYYyk........",
      "........kYWYYykk........",
      ".........Oyyyok.........",
      ".......OOYYYyyyOk.......",
      ".......kkkkkkkkkk.......",
      "........................",
    ],
  },
  lr_a5_shield_t: { // 久遠の聖典: 金の四隅と縁で飾った白い革の聖典・表紙の霊の環の金の飾り板に青緑の霊玉・小口に二つの金の留め金
    palette: pal({ "1": "#d6fff2", "2": "#7ee0c8", "3": "#3a9c90", "4": "#1d4a4c", "5": "#f8f4ea", "6": "#d8d0bc", "7": "#a0967e", "8": "#5e5444", "9": "#151d2c", "X": "#fffbe6", "W": "#fff0b0", "c": "#9cc4dc", "b": "#5a84a6", "u": "#2a3e58" }),
    art: [
      "........................",
      "........................",
      "...OOOOOOOOOOOOOOOOk....",
      "..OYWY55555556666YYyk...",
      "..OWY5555555566666yyok..",
      "..OY556666666666667yok..",
      "..O556666yYYYy666667yk..",
      "..O56666yY222Yy66667yk..",
      "..O5666yY21XX2Yy6667Yk..",
      "..O5666Y21X112Yy6667WYk.",
      "..O5666Y2X1123yo6667YYk.",
      "..O5666Y21123yyo6667Ykk.",
      "..O5666yY2233yo66667yk..",
      "..O56666yY33yo666667yk..",
      "..O566666yyyoo666677yk..",
      "..O566666666666667777yk.",
      "..O56666666666666777WYk.",
      "..O5666666666666677yYok.",
      "..OY566666666666777yyok.",
      "..OWY666666666667777ykk.",
      "..kYWYYYYYYYYYYYYYYyok..",
      "...kyyyyyyyyyyyyyyyokk..",
      "....kkkkkkkkkkkkkkkkk...",
      "........................",
    ],
  },
  lr_a20_shield_k1: { // 永劫の大盾: 面取りの縁と金の内縁の大きな黒曜の紫鋼の大盾・四隅へ伸びる金の線細工・盾心に紅玉を抱く金の環
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0", "x": "#a898c0", "w": "#6e6088", "v": "#463a5a", "g": "#2a2238", "e": "#120e1c" }),
    art: [
      "........................",
      "..eeeeeeeeeeeeeeeeeek...",
      ".exwwwwwwwwwwwwwwwwwvek.",
      ".ewYYYYYYYYYYYYYYYyyvgk.",
      ".ewYYyQTTTTTTTTTTTUyvyk.",
      ".ewYQYyTTTTTTTTTTTUyyok.",
      ".ewYQTyYTTTTTTTUTUUyogk.",
      ".ewYQTTYyTWWYYTTUUyovgk.",
      ".ewYQTTTyWW2RYyTUUoyvgk.",
      ".ewYQTTTWW21RryyUUUyvgk.",
      ".ewYQTTTW2RRrrqyUUUyvgk.",
      ".kwYQTTTYRRrrqqoUUUyvkk.",
      "..ewYQTTYYrrqqooUUyvgk..",
      "..kwYQTTTyyqqooUUUyvkk..",
      "...ewYQTTTyyooUUUyvgk...",
      "...kwYQTTyTTTTUoUyvkk...",
      "....kwYQyoTTUUUyovkk....",
      ".....kwyoTTyUUUyyok.....",
      "......OoYQToUUyvkkk.....",
      "......kkwYQyUyvkk.k.....",
      "........kwYyyvkk........",
      ".........kwvvkk.........",
      "..........kkkk..........",
      "........................",
    ],
  },
  lr_a20_shield_k2: { // 永劫の覇盾: 中央の山形の上縁の厚い金縁の黒曜の紫鋼の大盾・左右に広げた覇者の金の翼・翼の芯の紅玉の環から放つ聖光の白金の光
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........OOOOOOOk........",
      ".OOOOOOOyYWXxYyoOOOOOOk.",
      ".OWYYYYYYYYYXyyyyyyyyYk.",
      ".OyQQTTTTTTTXUUUUUUTTok.",
      ".OyQTTTTTTXTXWUWUUUUTok.",
      ".OyQTTTTTTTXXXWUUUUUTok.",
      ".OyQYyTTXXoYYYoWUUoyTok.",
      ".OyQWYYyToYrRRyUoyyYTok.",
      ".OyQTWYYYYyR2RryyyYUTok.",
      ".OyQyTWYYYyRRrqyyYUoTok.",
      ".OyQTyTWYyorrqoyYUoUTok.",
      ".OyQTTyTWYoooOOYUoUUTok.",
      ".kyQTTTyTWYXWyYUoUUUTkk.",
      "..OyQTTTTTXTWUWUUUUTok..",
      "..kyQTTTTTTTWUUUUUUTkk..",
      "...kyQTTTTTTYUUUUUTkk...",
      "....kyQTTTTTUUUUUTkk....",
      ".....kyQTTTTUUUUTkk.....",
      "......kyQTTTUUUTkk......",
      ".......kyQTTUUTkk.......",
      "........kyYYyykk........",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a20_shield_r1: { // 永劫の円盾: 盾面いっぱいに金の線細工の羅針を打ち出した黒曜の紫鋼の円盾・金の鋲を打った金の縁・盾心に紅玉を抱く金の環
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".........OOeOOk.........",
      "......OOOWQQQQYOOk......",
      ".....OWQQQQQQQQTTYk.....",
      "....eWQQQQQQQQQQTTyk....",
      "...OWQQQQQQYYQQQTTTyk...",
      "..OWQQQQQQQYYQQTTTTTyk..",
      "..OQQQQQQQQYYQQTTTTTTk..",
      "..OQQQQQYQQYYQQYTTTTTk..",
      ".OWQQQQQQoYYYoYTTTTTUok.",
      ".OQQQQQQQYrRRyoTTTTTTUk.",
      ".eQQQYYYYyR2RroyyyyTUUk.",
      ".OQQQYYYYyRRrqOyyyyTUUk.",
      ".OQQQQQQQorrqoOTTTTUUUk.",
      ".kYQQQQQQYoooOyTTTUUUkk.",
      "..OTQQTTYTTyyTTyTUUUUk..",
      "..OTTTTTTTTyyTTTUUUUUk..",
      "..kYTTTTTTTyyTTUUUUUkk..",
      "...kyTTTTTTyyTUUUUUkk...",
      "....kyTTTTTTTUUUUUkk....",
      ".....kyTTUTUUUUUUkk.....",
      "......kkkoUUUUkkkk......",
      ".........kkkkkk.........",
      "........................",
    ],
  },
  lr_a20_shield_r2: { // 永劫の小盾: 金の糸で星形に縫い合わせた霊獣の紅黒の革を張った小盾・金の鋲の金縁・盾心に紅玉を抱く金の環
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0", "H": "#a4504c", "K": "#76302f", "M": "#4e1c22", "Z": "#2c0e14" }),
    art: [
      "........................",
      "........................",
      "........................",
      "........OOOOeOOk........",
      "......OOWWKKyKYYOk......",
      ".....OWWHKKKyKKKYYk.....",
      "....OWWHKKKKyKKKKyyk....",
      "....OXHKKKKKyKKMKKyk....",
      "...OWHKKyKKKKKKKyKKyk...",
      "...OWKKKKyKKKMKyKMMok...",
      "...OKKKKKKKyYyMKKMZMk...",
      "...OKKKKKKyR2roMMMMZk...",
      "...eyyyyKKYRrqoMyyyykk..",
      "...OKKKKKMyrqqOMMZMMk...",
      "...OYKKKKKMooOZMMMZOk...",
      "...kYKKMKyKMMMMyMMZkk...",
      "....OYKKyKKMZMMMyZOk....",
      "....kXyKKMMMyZMMZOkk....",
      ".....kyyKMZMyMZZOkk.....",
      "......kkyoMZyMOkkk......",
      "........kkkkkkkk........",
      "............k...........",
      "........................",
      "........................",
    ],
  },
  lr_a20_shield_o: { // 永劫の宝珠: 紅の熾火を芯に灯す黒曜の紫の宝珠・渦を巻く紫の星雲と金の火の粉・宝珠を抱く金の環の台座に紅玉
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "........................",
      "........VVVVVVVk........",
      ".......VTTTTTTTTk.......",
      "......VTTTTTTYTTTk......",
      ".....VTTTTTQQQTTTTk.....",
      "....VQTTT1QQQQTTTTUk....",
      "....VTTTTQQqqTUTTTUk....",
      "....VTTTTQqRRqUWUUUk....",
      "....VTTUUqR22rqVUUUk....",
      "....VTTTUqR22rqUVUUk....",
      "....VTTYUUqrrqTUVWUk....",
      "....VTTTTUUqqTTUVVUk....",
      "...OyTTTTRTTTTUVVVkk....",
      "...kYyTTTTTTTU1Vyyk.....",
      "....kYyUTTTRUUVyykk.....",
      ".....kYyyUUUUyyykk......",
      "......kkYYyyyykkk.......",
      "........kRR2Rkk.........",
      ".........OYYyk..........",
      "........OYWYyyk.........",
      ".......kkkkkkkkk........",
      "........................",
      "........................",
    ],
  },
  lr_a20_shield_t: { // 永劫の聖典: 金縁の黒曜の紫の表紙を広げた聖典・紅玉の環を記した光る頁・頁から扇に立ちのぼる光の筋と紅玉の環
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "5": "#fbf6e8", "6": "#e2d8bc", "7": "#a89c7e", "8": "#5e5444", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      ".......Y...yYy..Y.......",
      "........Y.yR2roYY.......",
      "...Y....WWYRrqoW....Y...",
      "....YY...WyrqqOW..YY....",
      ".....WWW.WXooOX..WW.....",
      ".......WX.X.XXX.X.......",
      "........XX.XWXXX........",
      "..........X...X.........",
      "....777777k..77777k.....",
      "..7766666678866666677k..",
      ".756666666777666666666k.",
      ".7666yYo6677766yYo6666k.",
      ".766yRro667776yRro6666k.",
      ".766oqqo667776oqqo6666k.",
      ".766666666777666666666k.",
      ".766666666777666666666k.",
      ".VY666666677766666665yk.",
      ".VTY5566667776666665Yyk.",
      ".kTTYYY556777766655yykk.",
      "..kTTTTYYYy77yyyyyykkk..",
      "...kkkkkkkkkkkkkkkkk....",
      "........................",
      "........................",
    ],
  },
  lr_a20_head_lt: { // 永劫の革兜: 霊獣の紅黒の革の軽兜・左右に反り立つ金の線細工の翼・額の金の帯に紅玉を抱く環・金の鋲の縁
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#463a5a", "U": "#2a2238", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0", "H": "#a4504c", "K": "#76302f", "M": "#4e1c22", "Z": "#2c0e14" }),
    art: [
      "........................",
      ".Y....................y.",
      ".YW..................yo.",
      ".YWY................yYo.",
      ".YWWY..eZZZZZZZZk..yYyo.",
      "..YWYyZHHHHKMKKKKZYyyo..",
      "..YWyYyHHHKKMMKKKyoyo...",
      "...YWyyoKKKKMMMMyyyoO...",
      "...eooooKKKKMMMMoooOk...",
      "...eHHKKKKoYYYoMMMKKk...",
      "...eHHKKKoYrRRyMMMKKk...",
      "...eHKKKKYyR2RrMMMMKk...",
      "...OYYYYYYyRRrqyyyyyk...",
      "...eKKMoyyorrqooOZMMk...",
      "...eKMZZooooOOOOZZZMk...",
      "...eKMZkkkkkkkkkkZZMk...",
      "...OKMZkkkkkkkkkkZZMk...",
      "...eKMZkkkkkkkkkkZZMk...",
      "...kKKMk........ZZMkk...",
      "....kkkk........kkkk....",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
  lr_a20_head_pie: { // 永劫の聖冠: 五本の尖塔の先に紅玉を戴く高い黄金の宝冠・象牙の白の天鵞絨・正面に紅玉を抱く金の環と紅玉を嵌めた帯
    palette: pal({ "1": "#fff4c8", "2": "#ff8a5a", "P": "#a898c0", "Q": "#6e6088", "T": "#c9c0a6", "U": "#8f8670", "V": "#120e1c", "X": "#fffbe6", "W": "#fff0b0" }),
    art: [
      "........................",
      "...........R............",
      "..........R2r...........",
      "...........qk...........",
      "......R....Ok....R......",
      ".....R2r..OWYk..R2r.....",
      "..R...q...OWYk...q...R..",
      ".R2r..Ok..OWYk..Ok..R2r.",
      "..q..OWk..OWYk..OYk..q..",
      "..Ok.OWyk.OWYk.VoYk.Ok..",
      "..OWOYWyTVYWYyVUoYyOYk..",
      "..OWyYWyYToYYYoyoYyoYk..",
      "..OWYYYWYoYrRRyyYyyyYk..",
      "..OWYYYYYYyR2RryyyyyYk..",
      "..OYYYYYYYyRRrqyyyyyyk..",
      "..OyRrYYRyorrqoryyqrok..",
      "..OyrqyYrqoooOOqyoqqok..",
      "..kyyyyyyyyyooooooookk..",
      "...kkkkkkkkkkkkkkkkkk...",
      "........................",
      "........................",
      "........................",
      "........................",
      "........................",
    ],
  },
};
