// 回復時計の境界と、安定度記録の収支・連続プレイ推計を確認する。
import assert from 'node:assert/strict';
import { recoverStability, stabilityWaitMs, STABILITY_RECOVERY_MS as step } from '../../src/stability.js';
const base = 1000000;
const old = {};
assert.equal(recoverStability(old,base),0);
assert.deepEqual(old,{stability:100,stabilityAt:base});
const d = {uid:1,name:'検証',stability:90,stabilityAt:base};
assert.equal(recoverStability(d,base+step-1),0);
assert.equal(recoverStability(d,base+step),1);
assert.equal(recoverStability(d,base+step*2+12000),1);
assert.equal(d.stabilityAt,base+step*2);
assert.equal(recoverStability(d,base+step*20),8);
assert.equal(d.stability,100);
assert.equal(d.stabilityAt,base+step*20);
recoverStability(d,base+step*100);
d.stability-=10;
assert.equal(recoverStability(d,base+step*100+1),0,'満タン中の時間は使わない');
assert.equal(recoverStability(d,base),0,'時計の巻き戻し');
assert.equal(d.stabilityAt,base);
d.stability=8;
assert.equal(stabilityWaitMs(d,base+60000),300000);
assert.equal(recoverStability(d,base+step*1000),92,'長いオフライン回復は上限まで');
const store=new Map();
globalThis.localStorage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};
const T=await import('../../src/telemetry.js');
const data=()=>JSON.parse(T.tlExportText().split('\n').at(-1));
const party=Array.from({length:3},(_,i)=>({uid:i+1,name:`検証${i+1}`,alive:true,stability:90}));
T.tlSetOn(true);
T.tlStabilityTick(party,7200000);
for(let i=0;i<10;i++)T.tlStability('entry',party.map(doll=>({doll,amount:10})),{dungeon:'w01'});
T.tlStability('natural',[{doll:party[0],amount:5}],{state:'town'});
T.tlStability('red',[{doll:party[0],amount:10}],{redSpent:10});
T.tlRedGain(60,'quest');
assert.equal(data().stability.spent,300);
assert.equal(data().stability.events[0].dolls[0].before,100);
assert.equal(data().stability.natural,5);
assert.equal(data().stability.red,10);
assert.equal(data().stability.redEarned,60);
assert(T.tlStabilitySummary().some(s=>s.includes('🔴90.0/実プレイ1時間')));
const before=JSON.stringify(data().stability);
T.tlSetOn(false);T.tlStabilityTick(party,5000);T.tlStability('entry',[{doll:party[0],amount:10}]);T.tlRedGain(5,'off');
assert.equal(JSON.stringify(data().stability),before);
T.tlClear();assert.equal(data().stability,null);
console.log('旧セーブ・端数・上限・オフライン・時計巻き戻し・回復待ち・記録ON/OFF・消費収支・連続プレイ推計を確認');
