// モンスター共通スキーマ + 種族定義 + 共有ドット絵ライブラリ
//
// ===== 設計ルール (ダンジョン単位コンテンツの生命線) =====
// 1. ID は「d<番号>_名前」(固有種) / 「cm_名前」(共通種) で名前空間化する。
//    既存IDの変更・並べ替えは禁止 (セーブ/図鑑の参照が壊れる)。追記のみ。
// 2. すべてのモンスターは defMonster() を通して定義する。
//    将来フィールドを足す時はここのデフォルトに足せば全体に行き渡る。
// 3. 1ダンlike1モジュール (d01.js, d02.js, ...)。盤面設定と出現モンスターを同居させ、
//    index.js のレジストリに登録する。

// ===== 種族分類 (16タイプ) — 図鑑のタブ =====
export const MON_RACES = [
  { key: "amorph", label: "不定形" },
  { key: "beast", label: "獣" },
  { key: "wing", label: "飛獣" },
  { key: "avian", label: "鳥人" },
  { key: "insect", label: "虫" },
  { key: "plant", label: "植物" },
  { key: "aquatic", label: "水棲" },
  { key: "reptile", label: "爬虫" },
  { key: "dragon", label: "竜" },
  { key: "humanoid", label: "亜人" },
  { key: "giant", label: "巨人" },
  { key: "undead", label: "不死" },
  { key: "specter", label: "幽鬼" },
  { key: "demon", label: "悪魔" },
  { key: "construct", label: "構造体" },
  { key: "armored", label: "機鎧" },
  { key: "elemental", label: "精霊" },
];
export const RACE_LABEL = (() => {
  const m = {};
  for (const r of MON_RACES) m[r.key] = r.label;
  return m;
})();

// ===== 属性 (エレメント) =====
// 6属性 + 無属性。循環: 火→風→土→水→火。光↔闇は相互に有利。
export const ELEMENTS = {
  none:  { label: "無", color: "#9aa0ac" },
  fire:  { label: "火", color: "#ff6b3a" },
  water: { label: "水", color: "#4aa3ff" },
  wind:  { label: "風", color: "#5fd08a" },
  earth: { label: "土", color: "#c89a4a" },
  light: { label: "光", color: "#ffe27a" },
  dark:  { label: "闇", color: "#9b6bd0" },
};
// A が有利を取る相手 B のリスト
const ELEM_BEATS = {
  fire: ["wind"], wind: ["earth"], earth: ["water"], water: ["fire"],
  light: ["dark"], dark: ["light"],
};
export function elemBeats(a, b) { return !!(ELEM_BEATS[a] && ELEM_BEATS[a].includes(b)); }
// 攻撃属性 atk が 防御属性 def に与えるダメージ倍率
// 有利: 1.5倍 / 不利(相手が有利): 0.5倍 / それ以外: 1.0倍。無属性が絡めば常に1.0
export function elemMult(atk, def) {
  if (!atk || atk === "none" || !def || def === "none") return 1;
  if (elemBeats(atk, def)) return 1.5;   // 光↔闇は双方ここで 1.5 になる
  if (elemBeats(def, atk)) return 0.5;
  return 1;
}

// ===== 属性攻撃 / 属性防御 (装備で得るレベル付きステータス) =====
// 属性攻撃 Lv1=◯: 有利属性へのダメージ+50% / 不利属性へ-50%。Lv2=◎: ±100%。
//   aE/aLv  : 攻撃側の属性と属性攻撃レベル (呪文・モンスター固有属性は Lv1 扱い)
//   tgtElem : 対象の固有属性 (モンスター)。攻撃側の有利不利はこれと比較する
//   tgtDef  : 対象の属性防御 {el, lv} (装備由来)。攻撃属性に有利な時のみ被ダメージを軽減
// 属性防御は「軽減のみ」: 有利属性で受けると減るが、不利属性で受けても増えない
//   (装備した属性防具が裏目に出てダメージが増えることはない)。
//   軽減量は Lv1=◯ 25% / Lv2=◎ 50% (Lv2 が上限)。
// 光↔闇は相互有利の例外: 攻撃側は常に「有利」、防御側は常に「軽減」扱いになる。
export function elemDmgMult(aE, aLv, tgtElem, tgtDef) {
  if (!aE || aE === "none") return 1;
  let m = 1;
  if (aLv > 0 && tgtElem && tgtElem !== "none") {
    const k = 0.5 * Math.min(2, aLv);
    if (elemBeats(aE, tgtElem)) m *= 1 + k;
    else if (elemBeats(tgtElem, aE)) m *= Math.max(0, 1 - k);
  }
  if (tgtDef && tgtDef.lv > 0 && tgtDef.el && tgtDef.el !== "none") {
    const k = 0.25 * Math.min(2, tgtDef.lv); // Lv1→25% / Lv2→50% 軽減
    if (elemBeats(tgtDef.el, aE)) m *= Math.max(0, 1 - k); // 防御側が有利 → 軽減 (不利でも増加はしない)
  }
  return m;
}

// ===== 色ユーティリティ (パレットの部分差し替え用) =====
function hex(n) { return Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, "0"); }
function parseHex(h) { return [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)]; }
function blend(a, b, t) {
  if (!a) return a; const A = parseHex(a), B = parseHex(b);
  return "#" + hex(A[0] + (B[0] - A[0]) * t) + hex(A[1] + (B[1] - A[1]) * t) + hex(A[2] + (B[2] - A[2]) * t);
}
// ベースパレットを tint 方向へ amount 混ぜる (新種の固有色を作る時に使う)
export function tint(pal, tintColor, amount) {
  const out = {};
  for (const k in pal) out[k] = pal[k] ? blend(pal[k], tintColor, amount) : pal[k];
  return out;
}

// ===== 共有ドット絵ライブラリ =====
// 形ごとの原型。各モンスターは artKey で形を選び、palette で固有の色を持つ。
// 解像度は混在可 (旧 12x12 / 新 32px 級)。drawSpriteFit (sprites.js) が
// 見かけサイズを 12 グリッド換算へ正規化するので、大きいアートほどドットが細かくなる。
// 高解像度アートの規約: 'o'=輪郭 / 光源は左上 / 各素材 3トーン (本体・影・ハイライト)。
export const ARTS = {
  // ── 第1層「墓地」の固有プロトタイプ ──
  gravewisp: { // 墓火: 漂う鬼火。白熱した芯と青緑の炎、細い尾を引く
    palette: { o: "#06201e", t: "#0d3a36", F: "#1f8c7e", L: "#46d6be", W: "#e6fff6" },
    art: [
      "........oo........",
      ".......oWWo.......",
      ".......oWLo.......",
      "......oLWWLo......",
      "......oLWWLo......",
      ".....oLLWWLLo.....",
      ".....oLLLLLLo.....",
      "....oFLLLLLLFo....",
      "....oFFLLLLFFo....",
      "....oFFFLLFFFo....",
      ".....oFFFFFFo.....",
      ".....oFFFFFFo.....",
      "......oFFFFo......",
      "......otFFto......",
      ".......otto.......",
      "........to........",
    ],
  },
  grasphand: { // 這い寄る腐手: 土から突き出し掴みかかる腐肉の手
    palette: { o: "#0e0a08", H: "#b8a07e", h: "#7c674a", D: "#241a12", d: "#3a2a1c" },
    art: [
      ".....oo...oo.....",
      "....oHo...oHo....",
      "....oHo...oHo..oo",
      ".oo.oHo...oHo.oHo",
      "oHo.oHo...oHooooHo",
      "oHho.oHo.oHHHHHHHo",
      "oHHho.oHooHHHHHHo.",
      ".oHHhooHHHHHHHHo..",
      "..oHHHHHHHHHHHo...",
      "...oHHHHHHHHHo....",
      "....ohHHHHHho.....",
      "....ohhHHHhho.....",
      "...oDdhhhhhdDo....",
      "..oDDDDddDDDDDo...",
      "..oDDDDDDDDDDDo...",
      "...ooooooooooo....",
    ],
  },
  mournshade: { // 嘆きの喪影: 頭を垂れ、青白い顔から涙を流す喪服の霊
    palette: { o: "#0a0810", S: "#2a2640", s: "#171430", F: "#b8c0e0", T: "#7fd0ff" },
    art: [
      "......oooo......",
      "....ooSSSSoo....",
      "...oSSSSSSSSo...",
      "..oSSSSSSSSSSo..",
      "..oSSoFFFFoSSo..",
      "..oSSoFFFFoSSo..",
      "..oSSoFTTFoSSo..",
      "..oSSSoTToSSSo..",
      "..oSSSSFFSSSSo..",
      ".oSSSSSSSSSSSSo.",
      ".oSSSSSSSSSSSSo.",
      ".oSssSSSSSSssSo.",
      ".osssSSSSSSssso.",
      "..osssssssssso..",
      "...ossssssssso..",
      "....ooooooooo...",
    ],
  },
  slime: {
    palette: { o: "#102c16", D: "#185424", G: "#389a42", L: "#6ecc64", B: "#aaeb91", W: "#ebffdc", E: "#081408" },
    art: [
      ".............................o..",
      "............................oLo.",
      "..........oooooooooooo.......o..",
      "........ooBBBBBLLLLLLGoo........",
      ".......oBBBBBWBLLLLLLGGGo.......",
      "......oBBBBBBBBLLLLLLGGGGo......",
      ".....oBBWWWWBBBLLLLLLGGGGGo.....",
      "....oBBWWWWWBBBLLLLLLGGGGGGo....",
      "....oBBBWWWBBBBLLLLLLGGGGGGo....",
      "...oBBBBBBBBBBLLLLLLLLBGGGGGo...",
      "...oBBBBBBBBBBLLLLLLGGLGGGGGo...",
      "...oBBBBBBBBBLLLLLLLGGGGGGGGo...",
      "..oLLBBBBBBELLLLLLLEGGGGGGDGGo..",
      "..oLLLLLLLLEELLLLLLEEGGGGGDGGo..",
      "..oLLLLLLLLLELLLLLGGEGGGGDDGGo..",
      "..oLLLLLLBLLLLLLLGGGGGGGGDDGGo..",
      "..oLLLLLLLLLLLLEEGGGGGGGDDDGGo..",
      "..oLLLLLLLLLLLLGGGGGGGGGDDDGGo..",
      "..oLLLLLLLLLLLGGGGGGGGGDDDDGGo..",
      "..oGGGLLLLLGGGGGGGGGGGGDDDDGGo..",
      ".oGGGGGGGGGGGGGGGGGGGGDDDDDDGGo.",
      "oGGGGGGGGGGGGGGGGGGGGGGGDDDDDGGo",
      "oGGGGGGGGGGGGGGGGGGGDDDDDDDDDGGo",
      ".oooooooooooooooooooooooooooooo.",
    ],
  },
  bat: {
    palette: { o: "#180e24", d: "#2a1a40", D: "#3a2458", P: "#6b3fa0", L: "#9a6fd0", H: "#ceb2eb", F: "#7a6096", f: "#56406e", E: "#781018", R: "#ff4040", W: "#ece6f4" },
    art: [
      ".oo.........oo....oo.........oo.",
      "oLLoo.......oFo..ofo.......ooPPo",
      ".oPLLo......oFFooffo......oPPDo.",
      ".oPPPLoo...oHHFFFfffo...ooPDDDo.",
      ".oDPPPLLoo.oHHFFFfffo.ooPPDDDdo.",
      ".oDPPPPPLLoHHRFFFWfffoPPDDDDDdo.",
      "..oPPPPPPPLFFERFFREffPDDDDDDDo..",
      "..oPPPPPPPPFFFFFFffffDDDDDDDDo..",
      "..oPPPPPPPPFFFFooffffDDDDDDDDo..",
      "..oDPPPPPPLLffWffWffPPDDDDDDdo..",
      "..oDPPPDPLLLffWffWffPPPDdDDDdo..",
      "...oPPDDPLPLFFFFFfffPDPDddDDo...",
      "...oDPDoLPLoFFFFFfffoPDPodDdo...",
      "...oDPooDPLoFFFFFfffoPDdooDdo...",
      "....oDooDPooFFFFFfffooDdoodo....",
      "....oLo.oLo.offffffo.oPo.oPo....",
      ".....o..oLo.offffffo.oPo..o.....",
      ".........o...ofoofo...o.........",
      ".............ofoofo.............",
      "............ofo..ofo............",
      ".............o....o.............",
    ],
  },
  beast: {
    palette: { o: "#1e140c", B: "#7a5230", b: "#52361e", H: "#ba8a58", d: "#3a2616", R: "#ff463c", W: "#f0ece2", k: "#140a06" },
    art: [
      "..........o...................",
      ".........obo.o................",
      "........oooHobo.o............o",
      ".......obbHbHHHoboooooo.....ob",
      "...ooooHHHHHHHHBBHBbBBbo...oBo",
      "..oHHHoHHHHHHHHBBBBBHBbbo.oBbo",
      ".ooBRRBBBBBBBBBBBBBBBBbbboBbo.",
      "okBBBBBBBBBBBBBBBBBBBBbbbBbo..",
      "oBBBBBBBBBBBBBBBBBBBBBbbbbo...",
      "okWkWkWkBBBBBBBBBBBBBBbbbbbo..",
      "oddddddBBBBBBBBBBBBBBBbbbbo...",
      ".oooooBBBBBBBBBBBBBBBBdddbo...",
      ".....oBBBdddddddddBBBddddo....",
      ".....oBBBdddddddddBBBddddo....",
      ".....oBBBoddddddddBBBddddo....",
      ".....oBBBoodddoodoBBBodddo....",
      ".....oBBBoodddo.ooBBBoooo.....",
      "....oWbbbWoooo..oWbbbWo.......",
      ".....ooooo.......ooooo........",
    ],
  },
  kobold: {
    palette: { o: "#28180c", B: "#8a5a2b", b: "#5e3a18", H: "#c98c4a", S: "#d9b07a", s: "#ac8254", P: "#d88282", E: "#ffd84a", M: "#b8b8c8", m: "#7e7e8e", W: "#f0f0ea", G: "#a87820", R: "#a03028", r: "#6e1e1a" },
    art: [
      "....o............o....",
      "...obo..........obo...",
      "...obBo........oBbo...",
      "...obPBooooooooBPbo...",
      "..o.oPHoHBBBBBbbPo....",
      ".oMo.oHoHBBBBBbbo.....",
      ".oWmooHHHBBBBBbbbo....",
      ".oMo.oHoHBBBBBbobo....",
      ".oMmooBoEoBBBoEobo....",
      ".oMmooBBBBBBBBbbbo....",
      "oGGGooBBSSoosssbbo....",
      ".oSSooBSSSoossssbo....",
      ".oSBHooBoWoooWobo.....",
      "..ooBHoBBBBBBBbbo.....",
      "....oBBoBBBBBbboo.....",
      ".....oooBBBBBbbobo..o.",
      ".......oBSSSSbboobooHo",
      "......oBBSSSsbbbobooBo",
      "......oBBSSSsbbbossBo.",
      "......oBBSSSsbbboWBo..",
      "......oBBSSSSbbbobo...",
      "......oBRRRRrrrbbo....",
      "......oBRRRRrrrbo.....",
      ".......oRRRRrrro......",
      ".......oBBroobbo......",
      ".......oBBo.obbo......",
      ".......oBBo.obbo......",
      "......oBBo...obbo.....",
      ".....ooBBo...obboo....",
      "....oWBBBBo.obbbbWo...",
      ".....ooooo...ooooo....",
    ],
  },
  skeleton: {
    palette: { o: "#28281e", B: "#d9d4bf", s: "#969078", W: "#fffffa", k: "#10100c", R: "#ff4040", M: "#aaaab8", m: "#6e6e7e", G: "#786032" },
    art: [
      "........oooooo.......",
      ".......oWWBssso......",
      "..oo..oWWWBsssso.....",
      ".oMmooWWWWBssssso....",
      ".oWmooBBBBBssssso....",
      ".oMmooBkRkBskRkso....",
      ".oMoooBkkkBskkkso....",
      ".oMmo.oBBBkkssso.....",
      ".oMmo..oBBBssso......",
      ".oMmo..oWsWssso......",
      ".oMmo..osssssso......",
      "oGGGGo..oossoo.......",
      ".oBBo.oooBBssooo.....",
      ".oBo.oBBBoBsossso....",
      ".oBooBoooBBssoooso...",
      "..oBBoBBBoBsosssoso..",
      "..oBosoooBBssooosso..",
      "...o.oBBBoBsosssooso.",
      "....osoooBBssooososo.",
      ".....oBBBoBsosssooso.",
      "....osooooBsoooososo.",
      ".....o.oBBBBBBo.oosso",
      "......osBBkkBBso..oWo",
      ".......oBBoosso....o.",
      ".......oBBoosso......",
      ".......oBBoosso......",
      ".......oWBooWso......",
      ".......oBBoosso......",
      ".......oBBoosso......",
      "......ooBBoossoo.....",
      ".....oBBBBoosssso....",
      "......oooo..oooo.....",
    ],
  },
  orc: {
    palette: { o: "#10200e", G: "#4f7a3a", d: "#305024", L: "#79a857", k: "#14100a", R: "#ff463c", W: "#f0f0e6", M: "#969ca8", m: "#646a76", X: "#dce2ea", A: "#6e4a26", a: "#4a3018" },
    art: [
      "...........okkkkko.......",
      "..........oLLkkkddo......",
      "oooooo...oLLLGGGdddo.....",
      "WWMMmmo..oLLLGGGdddo.....",
      "WMMMmmo..oLooGGGoodo.....",
      "MMMMmmo..oGRRGGGRRdo.....",
      "MMMMmmo..oGWGddGdWdo.....",
      "MMMMmmo..oGWGGGGdWdo.....",
      "ooAaomooooGooooooodo.....",
      ".oAaoooMMMMMGGGGdddoo....",
      "..oAaooMXXMMGGGGGGdddo...",
      "..oAaooMMMMMGGGGGGdddoo..",
      "...oAaLGGMMMGGGGGGdddddo.",
      "...oAaLGGLLAaGGGGGdddddo.",
      "...oAaGGGLLGAaGGGGdddddo.",
      "....oAaGGGGGGAaGGGdddddo.",
      "....oAaGGGGGGGGGGGdddddo.",
      "....oGAaGGGGGGGGGadddddo.",
      "....oGAaoGGGGGGGGAaddddo.",
      ".....ooooGGGGGGGGGAaodddo",
      "........oGGGGGGGGGddodddo",
      ".........oAAAAAAaaaoodddo",
      ".........oAAAAAAaaaooWoWo",
      ".........oAAAAAAaaao.o.o.",
      ".........oLGGGaddddo.....",
      ".........oLGGGoddddo.....",
      ".........oLGGGoddddo.....",
      ".........oLGGGoddddo.....",
      ".........oLGGGoddddo.....",
      "........oAAAAAoaaaaao....",
      "........oAAAAAoaaaaao....",
      ".........ooooo.ooooo.....",
    ],
  },
  golem: {
    palette: { o: "#181b1f", S: "#6a727a", G: "#464d55", L: "#9aa3ab", d: "#30353c", k: "#14161a", C: "#7fd0e6", c: "#d2f5ff" },
    art: [
      "...........ooooo..........",
      "..........oSSSSSo.........",
      ".........oSSSSSSSo........",
      ".........oScCScCSo........",
      ".........oSCCSCCSo........",
      ".........oSSSSSSSo........",
      "......ooooSSSSSSSoooo.....",
      "..ooooLLLSSSSdSSSGGGGooo..",
      ".oLLLLLLLSSSSdSSkGGGGGGGo.",
      ".oLLLLLLLSSSSdSSkGGGGGGGo.",
      ".oLLLLoLLSSSSdSSSkGGoGGGo.",
      ".oLLLLoLLSSSCcCSSkGGoGGGo.",
      ".oLLLLoLLSSSSdSSSGGGoGGGo.",
      ".oSSSSodddddddddddddoGGGo.",
      ".oddddoSSSSSSdSSSGGGoddddo",
      "oSSSSSoSSkSSSdSSSGGGoGGGGo",
      "oSSSSSoSSSkSSdSSSGGGoGGGGo",
      "oSSSSSoSSSkSSdSSSGGGoGGGGo",
      "oSSSSSoSSSSkSdSSSGGGoGGGGo",
      "oSSSSSoSSSSSSdSSSGGGoGGGGo",
      "oSSSSSoodddddddddddooGGGGo",
      ".ooooo.odddddddddddo.oooo.",
      ".......oSSSSSoSSSGGo......",
      ".......oSSSSSoSSSGGo......",
      ".......oSSSSSoSSSGGo......",
      ".......odddddodddddo......",
      ".......oGGGGGoGGGGGo......",
      ".......oGGGGGoGGGGGo......",
      ".......oGGGGGoGGGGGo......",
      "......oGGGGGGoGGGGGGo.....",
      ".......oooooo.oooooo......",
    ],
  },
  wraith: {
    palette: { o: "#0a101c", D: "#182640", P: "#2b466e", B: "#4e78a5", k: "#04060c", C: "#5fc8ff", c: "#b4f0ff", S: "#c8cdd7", s: "#8c92a0" },
    art: [
      ".........oooooooo.........",
      ".......ooBBBBBPPPoo.......",
      "......oBBBBBBBPPPPPo......",
      "......oBBBBBBBBPPPPo......",
      ".....oBBBDkkkkkkDPPPo.....",
      ".....oBBBkkkkkkkkPPPo.....",
      ".....oBBBkkCckCckPPPo.....",
      ".....oBBBkkkkkkkkPPPo.....",
      ".....oBBBkkkkkkkkPPPo.....",
      "......oBBkkkkkkkkPPo......",
      "......oBBBBBBBPPPPPo......",
      "......oBBBBBBBPPPPPo......",
      "....ooBBBBBBBPPPPPPDo.....",
      "...oSSSBBBBBPPPPPPDDo.....",
      "...oSSSPPPPPPPPPPPDDDo....",
      "..oSoSPSPPPPPPPPPDDssso...",
      ".osoPsPPsPPPPPPPDDDssso...",
      "..ooPPPPPPPPPPPPDDsDsDso..",
      "..oDDPPPPPPPPPDDDDDDDDDoo.",
      "..oDDDDPPPPPDDDDDDDDDDDoDo",
      ".oDDDDDDDDDDDDDDDDDDDDDDo.",
      "oDDDDDDDDDDDDDDDDDDDDDDDo.",
      ".oDDDDDDDDDDDDDDDDDDDDDDo.",
      ".oDDoDDDoDDDoDDDoDDDoDDDo.",
      ".oDooDDooDDooDDooDDooDDo..",
      "..o.oDo.oDo.oDo.oDo.oDo...",
      ".....o...o...o...o...o....",
    ],
  },
  imp: {
    palette: { o: "#2a0a0a", R: "#9c2a2a", d: "#6c1a1a", L: "#d65a3a", D: "#4a1418", P: "#78282c", E: "#340c10", W: "#f0eade", w: "#b4aa9b", Y: "#f2c14e", k: "#1a0606" },
    art: [
      "........o......o.........",
      ".oo....oWo....oWo....oo..",
      "oDDo..oWo.oooo.owo..oEEo.",
      ".oPDooDwooRRRRoowEooEDo..",
      "..ooDDDDLoRRRRodEEEEoo...",
      "...oDDDDLoYRRYodEEEEo....",
      ".ooDDDDDRRRRRRddEEEEEoo..",
      "oDDDDDDDRkRRRRkdEEEEEEEo.",
      "oDDDDDDDRkkkkkkdEEEEEEEo.",
      "oDDDDDDDRRWRRWddEEEEEEEo.",
      "oDDDoDDDooRRRRooEEEoEEEo.",
      "oDDo.oDDoLRRRRdoEEo.oEEo.",
      "oDo...oDoRRRRRdoEo...oEo.",
      "oDo...oRRLRLLRdddo...oEo.",
      ".o..ooRooLRLLRdoodoo..o..",
      "...okRo.oLRLLRdo.odkooko.",
      "....oo..oLRRRRdo..oo.oRko",
      "........oRRooddoo..ooRko.",
      "........oRRooddddooRRoo..",
      ".......ooRRooddoodRoo....",
      "......okRRo..oddkoo......",
      ".......ooo....ooo........",
    ],
  },
  lizard: {
    palette: { o: "#0e2814", G: "#3a8a3a", d: "#226028", L: "#7fd06a", Y: "#e8c24a", y: "#b48e30", F: "#d4504e", f: "#963234", W: "#f0f0e6", k: "#0a160c", M: "#aab0bc", A: "#6e4a26", a: "#4a3018" },
    art: [
      ".........oFfo...........",
      "........oFFFfo..........",
      ".......oFFFFffo.........",
      "......oLLWGGGddo........",
      ".......oYMGGYodo........",
      "......oLMGGGGydoo.......",
      ".....oGGAGGGGddddo......",
      ".....okGAGGGGdddko......",
      ".....okAWkkkkkWkko......",
      "......oAoGGGGoooo.......",
      ".....oAooGGGGooo........",
      ".....oAGLGGGGdddo.......",
      "....oAoGGyyyydddo.......",
      "...ooAGLGYYYYddddo......",
      "..oGLooGGyyyydddodo.....",
      "..oGAooGGYYYYdddoddo....",
      "..oAo.oGGyyyydddoddo....",
      "..oAo.oGGYYYYdddooo.....",
      ".oAo..oGGyyyydddo.......",
      ".oAo..oGGYYYYddGo......o",
      "oAo....oAAAAAAadGoo..ood",
      ".o.....oAAAAAaAodGGooGGo",
      ".......oGGGodddooddGGoo.",
      ".......oGGGodddo.oodo...",
      ".......oGGGodddo...o....",
      "......oGGGo.odddo.......",
      "......oGGGo.odddo.......",
      ".....ooGGGooodddoo......",
      "....oWGGGGGWdddddWo.....",
      ".....ooooooooooooo......",
    ],
  },
  ghost: {
    palette: { o: "#162630", D: "#3a6070", G: "#6ea0b2", B: "#9fd6e6", W: "#e1f8ff", k: "#0a1218" },
    art: [
      ".........oooooo.........",
      ".......ooBBBBBBoo.......",
      "......oWWWWBBBBBGo......",
      ".....oWWWWWWBBBBGGo.....",
      "....oWWWWWWWWBBBBGGo....",
      "...oWWWWWWWWWBBBBGGGo...",
      "...oWWWWWWWWWBBBBGGGo...",
      "...oWWWWWWWWWBBBBGGGo...",
      "...oWWWWokWWWBokBGGGo...",
      "..oBWWWWkkWWWBkkBGGGGo..",
      "...oWWWWkkWWWBkkBGGGo...",
      "...oBWWWWWWWBBBBGGGGo...",
      "...oBBWWWWWBBBBBGGGGDo..",
      "...oBBBBBBBokoBGGGGGDo.o",
      "....oBBBBBBkkkBGGGGDDooD",
      ".....oBBBBBkkkGGGGGDDo.o",
      "......oBBBBBBGGGGGDDDDo.",
      "..o...oBBBBGGGGGGDDDDDo.",
      ".oGo...ooGGGGGGGGDDDDDo.",
      "oDo.....oGGGGGGGDDDDDDo.",
      ".o.......oGGGGDDDDDDDDDo",
      ".......o.oGGGDDDDDDDDDDo",
      "......oGo.ooGooooGoooGo.",
      "......oGo..oDo..oGo.oDo.",
      ".......oDo..o....oGo.o..",
      "........o........oDo....",
      "..................o.....",
    ],
  },
  knightmare: {
    palette: { o: "#101018", M: "#7a8096", m: "#505569", W: "#bec4d7", d: "#323546", k: "#06060c", R: "#ff463c", r: "#962832", F: "#c83238", f: "#822028", L: "#cdd8e0", l: "#919caa", G: "#96783c" },
    art: [
      ".........oFFooFFfo..",
      ".........ooFFFooofo.",
      "........oWMMMmo..o..",
      ".......oWWMMMmmo....",
      ".......oWWMMMmmo....",
      ".......okkRkkRko....",
      ".......okkkkkkko....",
      ".......oMMMMMmmo....",
      "....oooRMMMMMmmrooo.",
      "...oWWMMMMMmMmMmmmmo",
      "...oMMMMMWMmMmMmmmmo",
      "...oMMMMMMMmMmMmmmmo",
      ".ooGGGoMMMMmMmMmmmmo",
      "oGGGGGGoMMMmMmMommo.",
      ".ooWlMModddddddommo.",
      "..oWlMMoMMMmMmmommo.",
      "..oLlMMoMMMmMmMommo.",
      "..oLlmmodddkdddommo.",
      "..oLlmmodddkdddodddo",
      "..oLlooodddddddodddo",
      "..oLlo.ommmmmmmoooo.",
      "..oLlo.ommmmmmmo....",
      "..oLlo.oWMMommmo....",
      "..oLlo.oWMMommmo....",
      "..oLlo.odddodddo....",
      "..oLlo.oWMMommmo....",
      "..oLlo.oWMMommmo....",
      "..oLlooMMMMommmmo...",
      "..olo.oMMMMommmmo...",
      "...o...oororoooo....",
      ".........o.o........",
    ],
  },
  dragon: {
    palette: { o: "#320c0c", R: "#9c2a2a", Q: "#6e181a", L: "#d65a3a", P: "#782428", E: "#56181e", D: "#3c1012", d: "#2c0c0e", Y: "#f2c14e", y: "#be8c32", W: "#f5eede", w: "#b9ac96", k: "#1e0606", F: "#ff7828" },
    art: [
      ".o........o......o..........o..",
      "oPo......oWo....oWo........oEo.",
      "oPDo....oWoooooooowo......odEo.",
      "oPDPoo..owLLLRRRRQwo....ooEdEo.",
      "oPDPPDo..oLoYRRYoQo....odEEdEo.",
      "oPDPPDDo.oLLLRRRRQooo.oddEEdEo.",
      "oPDPPDPPoRRRRRRRRQQQkoEYdEEdEo.",
      "oPDPPDPPPRRRRRRRRQQQQQFEdEEdEo.",
      "oPPDPDPPPkkWkkkWkkkWkkEEFEdEEo.",
      "oPPDPPDPPPoRRRRRRRQoEEEdEEdEEo.",
      "oPPDPPDPPPoRRRRRRRQoEEEdEEdEEo.",
      "oPPDPPDPPPwRRwRRwRQwEEEdEEdEEo.",
      "oPPDPPDPPLLRRRRRRRQQQEEdEEdEEo.",
      "oPPDPoDPPLLRYYYYYYQQQEEdoEdEEo.",
      "oPPPooDPPLLRyyyyyyQQQEEdooEEEo.",
      "oPoo..oooLLRYYYYYYQQQooo..ooEo.",
      ".o......oRRRyyyyyyQQQo......o..",
      "........oRRRYYYYYYQQQo.........",
      "........oRRRyyyyyyQQQo.......o.",
      "........oRRRYYYYYYQQQo......oWo",
      "........oRRRyyyyyyQQRoo.....owo",
      "........oRRRYYYYYYQQQRRoo.ooRow",
      "........oLRRRooooQQQQQQRRoRRo.o",
      "........oLRRRo..oQQQQooQQRoo...",
      "........oLRRRo..oQQQQo.ooQo....",
      "........oLRRRo..oQQQQo...o.....",
      "........oLRRRo..oQQQQo.........",
      ".......oRRRRRo..oQQQQQo........",
      "......oWRRWRRWooWQQWQQWo.......",
      ".......ooooooo..ooooooo........",
    ],
  },
  harpy: {
    palette: { o: "#322412", F: "#caa06a", f: "#967042", e: "#684c2a", H: "#ebcd96", A: "#784623", a: "#543018", S: "#e8be8e", s: "#be9264", E: "#e8c24a", k: "#3c1e14", Y: "#d9a93f", y: "#a07828", W: "#f0ece2" },
    art: [
      "............oooooo............",
      ".o.........oAAAAAAo.........o.",
      "oFoo......oAAAAAAaao......oofo",
      "oFFFoo....oAAAAAAaao....oofffo",
      "oFFFFFoo..oASSSSssao..oofffffo",
      "oFFFFFFFoooASESSEsaooofffffffo",
      "oFFFFFFFFFoASoSSosaofffffffffo",
      "oFFFFFFFFFFASSkkssaffffffffffo",
      "oFoFFFFfFfFaSSSSssafefeffffofo",
      "oFFFFfFfFffoFFFFffoeefefeffffo",
      "ofFfoffofofoFHHHffoeoeoeeoefeo",
      "offffooofoooFHHHffoooeoooeeeeo",
      ".ofofo..o..oFHHHffo..o..oeoeo.",
      "..o.o......oFHHHffo......o.o..",
      "...........oFFHFffo...........",
      "...........oFFFFffo...........",
      "...........oFFFFffo...........",
      "...........oFYFoyo............",
      "..........oFoYFoyfo...........",
      "..........ofoYfoyeo...........",
      "...........ooYooyo............",
      "...........oWYWWyWo...........",
      "...........oWooWoo............",
      "............o..o..............",
    ],
  },
  spider: {
    palette: { o: "#160c16", P: "#4a2d4a", L: "#7a5074", D: "#301c30", k: "#1e1220", R: "#d43c38", r: "#8c282c", W: "#f0ece2", w: "#b9ac96" },
    art: [
      "............o..o............",
      "........o..oDookoo.o........",
      ".......oDooLLLLLLDoko.......",
      "........oLLLLLLLLLLDo.......",
      ".......oLLLLLLLLLLLLDo......",
      "......oLLLLLLLLLLLLLLDo.....",
      "......oLLLLLLRRRLLLLLDo.....",
      "......oLLLLLLLRLLLLLLDo.....",
      ".....oPLLLLLLRRRLLLLLPDo....",
      ".....ooPPLLLPPPPLLLPPDo.....",
      "....okoPPPPPPPPPPPPPPDko....",
      "....okDPPPPPPPPPPPPPPkko....",
      "...okooDPPPPPDkPPPPPkooko...",
      "...okoooDDDDDDkkkkkkoooko...",
      "..okkDDooDLLPPPPLLkookkkko..",
      "..okoooDDoDPRPPRPkokkoooko..",
      ".okkokDDoDDrPrrPrkkokkkokko.",
      ".okookooDDDPPPPPPkkkookooko.",
      ".okoko.oooDDPPPPkkooo.okoko.",
      "okookookDDooWooWookkkookooko",
      ".ooko.okoo.owoowo.ooko.okoo.",
      "..okooko....o..o....okooko..",
      "...o.oko............oko.o...",
      "....oko..............oko....",
    ],
  },
  mandrake: {
    palette: { o: "#1a140a", B: "#caa06a", b: "#966e42", H: "#e8c48c", K: "#604024", k: "#281a0e", G: "#3a8a3a", g: "#226028", L: "#8fd06a" },
    art: [
      "...oLLo...oGo..oLLo...",
      "....ogo..oLGo..ogo....",
      "..oo.ogoo.oGooogo.oo..",
      ".oLLo.oggooGoggo.oLLo.",
      ".oggooooogoGgoooooggo.",
      "..ooggggooggooggggoo..",
      "....ooooggggggoooo....",
      "....oHHHHBBBBBbbbo....",
      "....oHHHHBBBBBbbbo....",
      "....oHHHHBBBBBbbbo....",
      "....oHHHbbBbbBbbbo....",
      "....oHHkHkBBkBkbbo....",
      "....oHHHkBBBBkbbbo....",
      "....oBBBBBBBBBbbbo....",
      "...oBoBbbBbbBbbbobo...",
      "..oBooBBbkkkkbbboobo..",
      ".oBo.oBBkkkkkkbbo.obo.",
      "obbo..oBkkkkkkbo...obo",
      ".oo...obkkKKkkbo....o.",
      "......oBBBBBBBbo......",
      ".......oBBBBBBo.......",
      ".......oBbbBbbo.......",
      "........oBBBBBo.......",
      "........oBBBBo........",
      "........oBBBBo........",
      ".......oBoboobo.......",
      "......oBo.oboobo......",
      "......oBo..o.obo......",
      ".....oBo......obo.....",
      "....obo........obo....",
    ],
  },
  sahagin: {
    palette: { o: "#082634", C: "#1f6a7a", D: "#144a58", L: "#4fb0c0", P: "#9be8e0", p: "#6eb4af", F: "#5fc8d7", f: "#328ca0", Y: "#f2c14e", y: "#b98c32", W: "#ebf5f5", k: "#061820", M: "#aab0bc", A: "#6e4a26" },
    art: [
      "........ooFoo.......",
      ".o.o...oFfooFo......",
      "oWoWo..oFFFfFfo.....",
      "oMWMo.oLLLCCCDDo....",
      "oMMMo.oLLLCCCDDo....",
      ".oAo.oWYLLCCCDYYo...",
      ".oAo.oYDCCCCCDYyo...",
      ".oAo.oCDCCkkCDDDo...",
      ".oAo..oCCkkkkDDo....",
      ".oAo..ofLCCCCDfo....",
      ".oAo...oLCCCCDo.....",
      ".oAo...oLCCCCDo.....",
      ".oAo..oLCCCCCDDo....",
      ".oAoooCCLPPPPDDDo...",
      ".oACCCoLLPPPpDDoDo..",
      ".oACCooCCPPPPDDFoDo.",
      ".oAoo.oCCPPPpDDooDDo",
      ".oAo..oCCPPPPDDoDoDo",
      ".oAo..oCCPPPpDDoo.o.",
      ".oAo..oCCPPPPDDo....",
      ".oAo..oCCCCCCDDo....",
      "..o....oDDDDDDo.....",
      ".......oDDDDDDo.....",
      ".......oCCCoDDDo....",
      ".......oCCCoDDDo....",
      ".......oCCCoDDDo....",
      "......ooCCCoDDDoo...",
      ".....oCCCCCoDDDDDo..",
      "....oFFCCCCoDDDDFfo.",
      ".....oooooo.oooooo..",
    ],
  },
  ogre: {
    palette: { o: "#20160e", S: "#b08a5a", s: "#80603a", H: "#d8b27c", k: "#1c120a", R: "#ff463c", W: "#f0ece2", w: "#b9ac96", A: "#684624", a: "#462e16", B: "#8c6438" },
    art: [
      ".............oWo..........",
      ".............oWwo.........",
      "...........ooSSSSoo.......",
      "..........okkSSSSkko......",
      "..........oHRSSSSRso......",
      "..........oSSSSSSsso......",
      "..........oSSHHHHsso......",
      "..........oSWsHHsWso......",
      "..........okkkkkkkko......",
      ".........ooooSSSSoooo.....",
      "........oAAAAAAAAAAAAo....",
      ".....oooAAAAAAAAAAAAAaooo.",
      "....oHSSHaAaAaAaAaAaAsssso",
      "....oHSSHHSSSSSSSSSSssssso",
      "....oSSSHHSSSSSSSSSSssssso",
      "....oSSSHHSSSSSSSSSSssssso",
      "....oSSSHHSSSSSSSSSSssssso",
      "....oSSSHHSSSSSSSSSSssssso",
      "....oSSSHHSSSSSSSSSSssssso",
      "...oSSSSSSSSSSSSSSSSssssso",
      "...oSSSSSsssssssssssssssso",
      "...oASSSSSSSSSkkSSSSssssso",
      "...oAooSSSSSSSSSSSSSssssso",
      "..oAo.oSSSssssssssssssWoWo",
      ".ooAo..oSSSSSSSSSSSSsso.o.",
      "oWAoo...oSSSSSSSSSSSso....",
      "aAAAAo...oAAAAAAAAAAo.....",
      "ABAWAo...oAAAAAAAAAao.....",
      "AABAAo...oAAaAAAaAAAo.....",
      "AAAAAo...oSSSSoosssso.....",
      "AAAAao...oSSSSoosssso.....",
      "ooooo...osssssoossssso....",
    ],
  },
  // 緑肌の小鬼。大きな耳・鉤鼻・牙の並んだ口で、犬頭のコボルドと描き分ける
  goblin: {
    palette: { o: "#16280e", d: "#2e5a1e", G: "#4f8a2f", L: "#82bf63", E: "#f2d23a", k: "#0a0a0a", W: "#f0ece2", B: "#6e4a26" },
    art: [
      "....oo......oo..",
      "...oGGo....oGGo.",
      "...oGGoo..ooGGo.",
      "...oGGGGGGGGGGo.",
      "..oGGGGGGGGGGGGo",
      "..oGGEkGGGGkEGGo",
      "..oGGGGGddGGGGGo",
      "..oLGGGddddGGGLo",
      "..oGGGoddddoGGGo",
      "..oGkWkWkWkWkGGo",
      "...oGGGGGGGGGGo.",
      "....ooGGGGGGoo..",
      "...oBBoGGGGoBBo.",
      "..oBGGGGGGGGGGBo",
      "..oGGGGGGGGGGGGo",
      "..oGGGBBBBBBGGGo",
      "...oGGoGGGGoGGo.",
      "...oWWo.oo.oWWo.",
    ],
  },
  // 横向きの大鼠。とがった鼻面に前歯、まるい体、右へ伸びる尾の先がピンク
  rat: {
    palette: { o: "#1e140c", H: "#9a7a52", B: "#6e5230", b: "#4a3620", P: "#e6a6a6", k: "#0a0a0a", W: "#f0ece2" },
    art: [
      "......oPo...............",
      "......oPPo..............",
      "...oooPPHooo............",
      "..oPHHHHHHHHHoo.........",
      ".oPkHHHHHHHHHHHo........",
      ".oPHHHHHHHHHHHHHoo......",
      ".oWHHHHHHHHHHHHHHHo.....",
      ".oWHHHHHHHHHHHHHHHHo....",
      "..oHHHHHHHHHHHHHHHHBo...",
      "..oBHHHHHHHHHHHHHHBBBBBoo",
      "..oBbHHHHHHHHHHHBBoooooPPo",
      "..oBbbbHHHHHHHbBBo.....oo",
      "...oBboooHHHooobBo.......",
      "...oHo..oHo..oHHo........",
      "..oWWo..oWo..oWWo........",
    ],
  },
  // 硬い甲羅の甲虫。上の大顎と六本の脚、毒の緑斑で蜘蛛と描き分ける
  beetle: {
    palette: { o: "#0e0a06", k: "#0a0a0a", S: "#a8884a", c: "#7a5a2e", C: "#4e3416", G: "#6fae3a", L: "#2e1e10" },
    art: [
      "...ok......ko...",
      "...okk....kko...",
      "....okk..kko....",
      "..oooSSSSSSooo..",
      ".oSSSccccccSSSo.",
      "oSScccccccccSSSo",
      "oSccGcccccGccSSo",
      "oSccccccccccccSo",
      "oSCcccccccccCSSo",
      "oSCCcccccccCCSSo",
      "oSSCCCccccCCCSSo",
      ".oSSCCCCCCCCSSo.",
      "..oSSCCCCCCSSo..",
      "L..oSSSSSSSSo..L",
      "oLo.oLo..oLo.oLo",
      ".o...o....o...o.",
    ],
  },
  // 骸の蝙蝠。中央に頭蓋、左右に骨だけの翼。膜のある黒翼蝙蝠と描き分ける
  bonebat: {
    palette: { o: "#15151c", B: "#b8b09a", s: "#7c745f", W: "#efe9d8", k: "#0a0a0a" },
    art: [
      "o....B......B....o",
      "oo..BsB....BsB..oo",
      "oBo.BsBB..BBsB.oBo",
      "oBBoBssBWWBssBoBBo",
      "oBBBssskWWksssBBBo",
      "oBBBsssWWWWsssBBBo",
      ".oBBssWkWWkWssBBo.",
      "..oBssWWWWWWssBo..",
      "..oBssWoWWoWssBo..",
      "...oBssWWWWssBo...",
      "...oBsskWWksssBo..",
      "....oBssWWssBo....",
      ".....oBsWWsBo.....",
      "......oBssBo......",
      ".......oBBo.......",
      "........oo........",
    ],
  },
  // 二足の狼人間。直立した体躯・牙の並ぶ顎・鉤爪で、四足の beast と描き分ける
  werewolf: {
    palette: { o: "#0b0a0f", D: "#26222e", F: "#3d3848", L: "#5b5468", R: "#ff4a4a", W: "#e8e4da", k: "#050409" },
    art: [
      "...oo.....oo...",
      "..oDFo...oFDo..",
      "..oDFFo.oFFDo..",
      "..oDFFoooFFDo..",
      "..oDFLFFFLFDo..",
      "..oFFLFFFLFFo..",
      "..oFRkFFFkRFo..",
      "..oFFFLWLFFFo..",
      "..ooFWkkkWFoo..",
      "....oFFFFFo....",
      "...oDFLLLFFDo..",
      "..oDFFLLLFFFDo.",
      ".oDFLFFFFFLFDo.",
      "WkoFLFFFFFLFokW",
      ".WkoFFFFFFFokW.",
      "...oFFDDFFo....",
      "...oDDo.oDDo...",
      "..oWko...okWo..",
    ],
  },
  // 呪詛を刻まれた四足の狼の骸。露出した肋骨と緑の呪い火で、生きた狼と描き分ける
  hexwolf: {
    palette: { o: "#080610", D: "#241a36", P: "#43345f", L: "#62508c", B: "#c4bcce", G: "#74b052", R: "#ff4a4a", k: "#040308" },
    art: [
      "................oPo.",
      "oPo............oPPLo",
      "oPPoooooooooooPPLLo.",
      ".oRkPPPPPPPPPPPLLLo.",
      "oBkBPPPPPGPPPPLLLPo.",
      ".ooPPPPLLGGLPPLLLPo.",
      "..oPPLLBBLLLLPLLLPo.",
      "..oPLLBoBoBLLPGLLPo.",
      "..oPLLBBBBBLLLLLLPo.",
      "..oPPLPPPLLPPLLPPo..",
      "..oPo.oPo.oPo.oPo..",
      "..oDo.oDo.oDo.oDo..",
      ".oko..oko.oko..oko.",
    ],
  },
  // 横向きの大さそり。左の大鋏と右へ反り返る毒尾(赤い針)で、蜘蛛と描き分ける
  scorpion: {
    palette: { o: "#0e0a06", B: "#b8923a", d: "#7e6020", L: "#dab45c", R: "#d44438", W: "#f0e6c0", k: "#080603" },
    art: [
      "...............ooo...",
      "..........ooo.oRRRo..",
      ".........odBdooRRRo..",
      "..oLBo...odBdoodddo..",
      ".oLBBdo..odBdo.ooo...",
      "oLBBLdo..odBdo.......",
      "oLBdo..ooodBdo.......",
      ".oBdooLLBBBBBdoo.....",
      "oLBBoBLLBBLLBBdo.....",
      "oLBdooBLBBLLBBLdo....",
      ".oo.koBLLBBLLBBdo....",
      "....k.oko.oko.oko....",
      ".....k.k...k...k.....",
    ],
  },
  // 漆黒の頭巾と白髪のダークエルフ射手。右手に弓を構える。犬頭のコボルドと描き分ける
  darkelf: {
    palette: { o: "#0c0a14", D: "#241c38", P: "#3c3056", S: "#6a5a78", s: "#473a55", H: "#d4cce4", W: "#f2eef8", B: "#7a5226", b: "#4e3416", R: "#ff5a5a", k: "#060410" },
    art: [
      "....oooo........",
      "...oDDDDo.......",
      "..oDHHHHDo......",
      "..oDHWWHHo...oBo",
      "..oDHSSHHo..oBbo",
      "..oHSRSRSo..oBo.",
      "..oHSssSSo.oBbo.",
      "..ooHsssoo.oBo..",
      "...oDPPDo..oBbo.",
      "..oDPPPPDo.oBo..",
      ".oDPSSSSPDooBbo.",
      ".oDPSWWSPDooBo..",
      ".oDPSSSSPDo.Bbo.",
      ".oPPSSSSPPo.oBo.",
      "..oPSSSSPo..oBbo",
      "..oPSooSPo..oBo.",
      "..oPSo.oSPo.oBo.",
      "..oDo..oDo.oBbo.",
      "..oDo..oDo.oBo..",
      "..oso..oso......",
      ".oWko..okWo.....",
    ],
  },
  // 人型に結んだ水の精霊。泡立つ白い水頭と流れる体・広がる裾で、スライムと描き分ける
  waterelemental: {
    palette: { o: "#0a2436", D: "#16486e", C: "#2e7ab0", L: "#56a0d8", W: "#bfe8ff", k: "#06141f" },
    art: [
      ".......o.......",
      "......oWo......",
      ".....oWLo......",
      "....oWLCo......",
      "...oWLCCo..oWo.",
      "..oWLCCDo.oWLo.",
      "..oWLCCDoooLCo.",
      ".oWLCkCDLLLCCo.",
      ".oWLCkCCLCCCDo.",
      ".oWLCCCCCCCDDo.",
      ".oWLLCCCCCDDo..",
      "..oLCCCCCDDo...",
      "..oLCCCWCDDo...",
      "..oLCCWWWCDo...",
      ".oLCCCWWWCCDo..",
      ".oLCCCCCCCCDo..",
      ".oWLCCCCCCDDo..",
      "oWLLCCCCCCCDDo.",
      "oWLCCCCCCCCCDDo",
      ".oooooooooooo..",
    ],
  },
  // 泥と苔の塊から成る不定形のゴーレム。歪んだ団塊と滴る泥で、石のゴーレムと描き分ける
  marshgolem: {
    palette: { o: "#0e0a04", D: "#2e2210", M: "#4e3c1c", L: "#6e5630", G: "#5a6a32", W: "#8a7448", k: "#080502" },
    art: [
      ".....oooo.........",
      "....oMMMMo........",
      "...oMLLLMMo.......",
      "...oMLWLMMo..ooo..",
      "...oMLLLGMooMMMMo.",
      "..ooMMMMMMoMLLLMo.",
      ".oMLLLLMMMMMLLMMo.",
      "oMLLGLLLMMLLMMMMMo",
      "oMLLLLLLMMLLLGMMMo",
      "oMLLLLMMMMMMLLMMMo",
      "oMMLLMMMMMMMMLMMo.",
      ".oMMMMMMMMMMMMMo..",
      ".oMLLMMooMMMMLMo..",
      ".oMLMo..oMLMMMo...",
      ".oMMo...oMMMMo....",
      ".oDMo...oMMDo.....",
      ".oDo.....oDo......",
      "oMMo.....oMMo.....",
    ],
  },
  // 正面向きの洞窟ネズミ。丸い大耳・赤い目・前歯、右へ伸びる尾。横向きの溝鼠と描き分ける
  caverat: {
    palette: { o: "#1a1410", G: "#6f6a62", g: "#47433d", H: "#9a958c", P: "#e0a0a8", E: "#ff5a4a", k: "#0a0a0a", W: "#f0ece2" },
    art: [
      "..o........o....",
      ".oGo......oGo...",
      ".oGGoo..ooGGo...",
      ".oGGGGooGGGGo...",
      "..oGGGGGGGGo....",
      ".oGHHGGGGHHGo...",
      ".oGEkGGGGkEGo...",
      ".oGGGGGGGGGGo...",
      ".oGGGkPPkGGGo...",
      "..oGWWPPWWGo....",
      "..oGGGGGGGGo....",
      ".oGgGGGGGGgGo...",
      ".oGgooooooogGo..",
      "oGgo......ogGGoooooo",
      ".o........o..oooPPo",
    ],
  },
  // 朽ちた兵士。錆兜の眼に緑火、血染めの陣羽織。骨だけの骸骨と描き分ける
  soldier: {
    palette: { o: "#1a1a14", M: "#7a8a86", m: "#4e5a56", L: "#a8b4ae", d: "#2a3230", S: "#6a5a3a", k: "#0a0a0a", E: "#9fe04a", R: "#a03028" },
    art: [
      ".....oooooo.....",
      "....oMLLLLMo....",
      "....oMLLLLMo....",
      "....ommMMmmo....",
      "....okEEEEko....",
      "....ommMMmmo....",
      ".....oMMMMo.....",
      "...ooMMMMMMoo...",
      "..oMLMMMMMMLMo..",
      "..oMMdSSSSdMMo..",
      "..oMMdSRRSdMMo..",
      "..oMMdSSSSdMMo..",
      "...okMMMMMMko...",
      "...oSSmmmmSSo...",
      "...oSSo..oSSo...",
      "...omMo..oMmo...",
      "...omMo..oMmo...",
      "...okko..okko...",
    ],
  },
  // 腐乱死体。緑に爛れた肉・落ち窪んだ眼・剥き出しの肋骨。両腕を広げて迫る
  zombie: {
    palette: { o: "#14180e", G: "#6a8a4a", g: "#46602e", H: "#9ab86a", k: "#0a0a0a", R: "#a83838", W: "#e8e2d0", b: "#3a2a1a" },
    art: [
      ".....oooo......",
      "....oGGGGo.....",
      "...oGHHGGGo....",
      "...oGkGGkGo....",
      "...oGGGGGGo....",
      "...oGGRRGGo....",
      "....oGWWGo.....",
      "..ooGGGGGGoo...",
      ".oGGoGGGGoGGo..",
      "oGGGoWWWWoGGGo.",
      "oHGo.oWWo.oGHo.",
      ".oo..oWWo..oo..",
      ".....oGGo......",
      "....oGGGGo.....",
      "....obGGbo.....",
      "....obbobbo....",
      "....oggoggo....",
      "....oGo.oGo....",
      "...okko.okko...",
    ],
  },
  // ハイエナ頭の獣人ゴール。丸耳・傾いた口吻・牙・背の鬣・斑点。オークと描き分ける
  gnoll: {
    palette: { o: "#1c140a", B: "#9a7a4a", b: "#665030", H: "#c2a064", M: "#d8c89a", S: "#3a4a2a", k: "#0a0a0a", W: "#f0ece2", D: "#2a1e10" },
    art: [
      "....oo.....oo....",
      "...oBBo...oBBo...",
      "...oBHBoooBHBo...",
      "..oBHHBBBBBHHBo..",
      "..oBHkBBBBBkHBo..",
      "..oBBBBBBBBBBBo..",
      "..oBBkWWWWkBBBo..",
      "...oMBWWWWWWBMo..",
      "...oMMBBBBBBMMo..",
      "..oMMHBBBBBHMMo..",
      ".oBMHHBBBBHHMBBo.",
      ".oBBHDBBBBDHBBBo.",
      ".oBHBBBBBBBBBHBo.",
      "..oBBBSSSSBBBBo..",
      "..oBBoSSSSoBBBo..",
      "..oBHo.SS.oBHo...",
      "..obbo.SS.obbo...",
      "..okko....okko...",
    ],
  },
  // 影犬。低く伏せ右を向く痩躯、逆立つ背毛の棘、赤い眼。四足の大狼と描き分ける
  hound: {
    palette: { o: "#0a0a12", G: "#2e2e3e", g: "#1a1a26", H: "#4a4a60", E: "#ff4a4a", k: "#050508", W: "#c0c0d0" },
    art: [
      "....................o..",
      "..o...o...o...o....oGo.",
      ".oGo.oGo.oGo.oGo..oGGo.",
      ".oGGooGGooGGooGGooGGGGo",
      "oGGGGGGGGGGGGGGGGGGGHo.",
      "oGgGGGGGGGGGGGGGGGGHEo.",
      "oGgGGGGGGGGGGGGGGHHHko.",
      ".ogGGGGGGGGGGGGGWWkGo..",
      ".oggGGGGGGGGGGGGGGGo...",
      "g.oGoGGoGGoGGoGGGo.....",
      "g.oGo.oGo.oGo.oGo......",
      "go.Go.oGo.oGo.oGo......",
      ".o.oko.oko.oko.oko.....",
    ],
  },
  // ゴブリンの呪い手。尖り頭巾の紫法衣、緑肌の覗く顔、髑髏付き骨杖。小鬼の術者
  gobshaman: {
    palette: { o: "#16280e", H: "#6a3f8a", h: "#3f2456", G: "#4f8a2f", g: "#2e5a1e", E: "#c07be0", k: "#0a0a0a", W: "#e8dcc0", S: "#8a5a2b", B: "#d8d0b0" },
    art: [
      "......ohho........",
      ".....ohHHho.......",
      "....ohHHHHho......",
      "...ohHHHHHHho.....",
      "...oHHGGGGHHo.....",
      "..oHHGGGGGGHHo....",
      "..oHGEkGGkEGHo....",
      "..oHGGGGGGGGHo....",
      "..oHGgkWWkgGHo....",
      "..oHhGGGGGGhHo....",
      ".ohHHHHHHHHHHho..B",
      ".ohHHHHHHHHHHhoSBB",
      ".ohHhHHHHHHHhhoSBo",
      ".ohHHHHHHHHHHhoSoo",
      ".ohHHhHHHHhHHhoSo.",
      "..ohHHHHHHHHho.So.",
      "..ohHHHHHHHHho.So.",
      "..ohhHHHHHHhho.So.",
      "...ohho..ohho.So..",
      "...ohho..ohho.oo..",
      "...oo......oo.....",
    ],
  },
  // ゴブリンの族長。角付き兜・重ね鎧・牙の緑肌の大柄な長。小鬼(goblin)と描き分ける
  gobchief: {
    palette: { o: "#16280e", G: "#4f8a2f", g: "#2e5a1e", L: "#82bf63", k: "#0a0a0a", E: "#f2d23a", M: "#8a8a96", m: "#54545e", R: "#c0402e", W: "#f0ece2", B: "#6e4a26" },
    art: [
      "...E........E....",
      "..oEo......oEo...",
      "..oEMo....oMEo...",
      "..oMMMooooMMMo...",
      ".oMMMMMMMMMMMMo..",
      ".oMMGGGGGGGGMMo..",
      ".oMGGEkGGkEGGMo..",
      ".oMGGGGGGGGGGMo..",
      ".oMGGkWWWWkGGMo..",
      ".oMMMGGGGGGMMMo..",
      "oMMMMMMMMMMMMMMo.",
      "oMMmRRRRRRRRmMMo.",
      "oMMMGGGGGGGGMMMo.",
      ".oMGGGGGGGGGGMo..",
      ".oBBBGGGGGGBBBo..",
      ".oBoGGGGGGGGoBo..",
      ".oGGo.oGGo.oGGo..",
      ".oGLo.oGGo.oGLo..",
      ".oBBo......oBBo..",
      ".okko......okko..",
    ],
  },
  // 鼠寄せの笛吹き。とんがり帽の外套、骨笛を口に当てる手、足元に鼠を侍らす
  piper: {
    palette: { o: "#1a140a", C: "#7a5a2a", c: "#4e3818", S: "#caa86a", k: "#0a0a0a", W: "#e8dcc0", G: "#6f6a62", g: "#47433d", P: "#e0a0a8" },
    art: [
      "........oo........",
      ".......oCCo.......",
      "......oCCCCo......",
      ".....oCCCCCCo.....",
      "....oCCCCCCCCo....",
      "...oCCCCCCCCCCo...",
      "....oSSSSSSSSo....",
      "....oSkSSSkSo.....",
      "....oSSSSSSSo.....",
      "...oCCWWWWWWWWo...",
      "...oCSCWWWWCSCo...",
      "...oCCCCCCCCCCo...",
      "..oCCCCCCCCCCCCo..",
      "..oCcCCCCCCCCcCo..",
      "..oCCCCCCCCCCCCo..",
      "..oCCCCCCCCCCCCo..",
      "..oCcCCCCCCcCCCo..",
      "...oCCCCCCCCCCo...",
      "...ooCCCCCCCCoo...",
      ".....oo....oo.....",
      "..oGgo...........P",
      ".oGGgggooo......PP",
      "oGgGGggggoooooooo.",
    ],
  },
  // ガーゴイル。広げた石翼・湾曲した角・牙、しゃがんだ石像の魔。ゴーレムと描き分ける
  gargoyle: {
    palette: { o: "#15171c", G: "#5a626a", g: "#3a4046", L: "#828a92", k: "#0a0a0a", W: "#c0c8d0", E: "#9fe04a" },
    art: [
      "..o........o..",
      ".oGo.oooo.oGo.",
      "oGGo.oGLLGo.oGGo",
      "oGGGoGLLLLGoGGGo",
      ".oGGGGEkkEGGGGo.",
      "oGo.oGLLLLGo.oGo",
      "oGGo.oGLLGo.oGGo",
      "oGGGoGkWWkGoGGGo",
      ".oGGoGLLLLGoGGo.",
      "..ooGGLLLLGGoo..",
      "...oGGLLLLGGo...",
      "...oGgGLLGgGo...",
      "...oGGoLLoGGo...",
      "..oGGo.oo.oGGo..",
      "..oWo......oWo..",
      "..oo........oo..",
    ],
  },
  // ゴルゴン。蛇の髪・石化の眼・蛇身の下半身。鳥人(harpy)と描き分ける
  gorgon: {
    palette: { o: "#0e1810", G: "#3a6a3a", g: "#244a24", S: "#c8b48a", s: "#8a7654", E: "#f2d24a", k: "#0a0a0a", W: "#e8e2d0", H: "#5f9a5a" },
    art: [
      "..G..oGo..oGo..G..",
      ".GGo.oGo..oGo.oGG.",
      "oGGGooGGooGGooGGGo",
      ".oGGSSSSSSSSSSGGo.",
      "..oSSSSSSSSSSSSo..",
      "..oSSEkSSSSkESSo..",
      "..oSSSSSSSSSSSSo..",
      "..oSSSSsSSsSSSSo..",
      "..oSSSSkWWkSSSSo..",
      "...oSSSSSSSSSSo...",
      "....oSSSSSSSSo....",
      "...oHSSSSSSSSHo...",
      "..oGHSSSSSSSSHGo..",
      "..oGGHSSSSSSHGGo..",
      "...oGGGHSSHGGGo...",
      "....oGGGGGGGGo....",
      "...oGGGgggggGGo...",
      "..oGGGo....oGGGo..",
      "...oGGGGooGGGGo...",
      ".....oGGGGGGo.....",
    ],
  },
  // 深海魚人。退化した眼・誘引する発光突起・牙の大顎・鰭。サハギンと描き分ける
  deepsahagin: {
    palette: { o: "#04121c", C: "#16505e", D: "#0c3038", L: "#3a8a96", E: "#bfff6a", k: "#06141a", W: "#e8f0ee", F: "#5fb0b0" },
    art: [
      ".....oEo.......",
      "....oCEo.......",
      "....oCo........",
      "...oCCo........",
      "..oCCCCCCo.....",
      ".oCDDLLLLDDo...",
      ".oCDLLLLLLDCo..",
      ".oCLEkLLkELCo..",
      ".oCLLLLLLLLCo..",
      ".oCkWWWWWWkCo..",
      ".oCWWWWWWWWWo..",
      ".oCCLLLLLLDCo..",
      "..oCLLLLLLCo...",
      ".oFCLLLLLLCFo..",
      "FoCCLLLLLLCCoF.",
      ".oCLLLLLLLLCo..",
      ".oCCLLLLLLCCo..",
      "..oCLLLLLLCo...",
      "..oCCo..oCCo...",
      ".oFFo....oFFo..",
    ],
  },
  // バンシー。長い髪を振り乱し絶叫する泣き女の霊。さまよう亡霊(ghost)と描き分ける
  banshee: {
    palette: { o: "#101824", D: "#26405a", G: "#4a7a8a", B: "#7ab0c0", W: "#e6f6ff", k: "#0a1018", R: "#c86a8a" },
    art: [
      "...BB......BB...",
      "..BGGBooooBGGB..",
      ".BGGGGBBBBGGGGB.",
      "BGGGWWWWWWWWGGGB",
      "BGGWWWWWWWWWWGGB",
      "BGGWWkkWWkkWWGGB",
      "BGGWWkkWWkkWWGGB",
      "BGGWWWWWWWWWWGGB",
      "BGGWWWoookWWWGGB",
      ".BGWWWkRRkWWWGB.",
      ".BGWWWkRRkWWWGB.",
      ".BGGWWWooWWWGGB.",
      "B.BGGWWWWWWGGB.B",
      "BB.BGGGWWGGGB.BB",
      ".BB.BGGGGGGB.BB.",
      "..BB.GGGGGG.BB..",
      "...B.oGGGGo.B...",
      ".....oGooGo.....",
      "....oGo..oGo....",
      "...oGo....oGo...",
    ],
  },
  // 邪神の僧。深く頭巾を被り痩せた腕を伸ばす亡僧。さまよう亡霊(ghost)と描き分ける
  cultist: {
    palette: { o: "#100a16", H: "#3a2a4a", h: "#22182e", G: "#5a4a6a", E: "#b07be0", k: "#0a0a0a", S: "#8a7a6a", W: "#cabfb0" },
    art: [
      "......ohho......",
      ".....ohHHho.....",
      "....ohHHHHho....",
      "...ohHHHHHHho...",
      "...oHhkkkkhHo...",
      "...oHhkEEkhHo...",
      "...oHhkkkkhHo...",
      "...oHHhhhhHHo...",
      "..oHHHHHHHHHHo..",
      ".oHHHHHHHHHHHHo.",
      "oSHHHHHHHHHHHHSo",
      "SHoHHHHHHHHHHoHS",
      "ooHHHHHHHHHHHHoo",
      ".oHHHHHHHHHHHHo.",
      ".oHHhHHHHHHhHHo.",
      ".oHHHHHHHHHHHHo.",
      ".oHHHHHHHHHHHHo.",
      "..oHHhHHHHhHHo..",
      "...oHHHHHHHHo...",
      "....oooooooo....",
    ],
  },
  // 黒甲の武者。前立てのある黒兜・面頬・大鎧、抜き身の太刀。西洋機鎧(knightmare)と描き分ける
  samurai: {
    palette: { o: "#0e0e14", M: "#3a3a48", m: "#22222c", L: "#5a5a6a", k: "#0a0a0a", R: "#a83838", E: "#f2d24a", W: "#c8ccd4", d: "#16161e", G: "#8a6a2a" },
    art: [
      "....G....G.....",
      "...oGo..oGo....",
      "...oGMooMGo....",
      "..oMMMMMMMMo...",
      ".oMMMMMMMMMMo..",
      ".oMMdddddddMo..",
      ".oMMRkMMkRMMo..",
      ".oMMMkWWkMMMo..",
      "..oMMMMMMMMo...",
      ".oMMMMMMMMMMo.W",
      "oMLMMMMMMMMLMoW",
      "oMMMdddddddMMoW",
      "oMMMMMMMMMMMMoW",
      ".oMMdddddddMMWo",
      ".oMMMMMMMMMMWo.",
      ".oLLMMMMMMLLo..",
      ".oLLo.MM.oLLo..",
      ".oMMo.MM.oMMo..",
      ".oddo.MM.oddo..",
      ".oWWo....oWWo..",
    ],
  },
  // デュラハン。首のない鎧、左腕に抱えた赤眼の生首。普通の機鎧(knightmare)と描き分ける
  dullahan: {
    palette: { o: "#0e0e16", M: "#2e2e3c", m: "#1c1c26", L: "#4e4e60", k: "#0a0a0a", R: "#a83838", E: "#ff5a4a", W: "#c8ccd4", H: "#7c6450" },
    art: [
      "....ooooooo....",
      "...oMmkkkmMo...",
      "..ooMMMMMMMoo..",
      ".oMLMMMMMMMLMo.",
      ".oMMMMMMMMMMMo.",
      ".oMMMRRRRRMMMo.",
      ".oMMMMMMMMMMMoW",
      "oMLMMMMMMMMLMoW",
      "oMMMMMMMMMMMMoW",
      "oMMMmMMMMmMMMoW",
      ".oMMMMMMMMMMMW.",
      "oHHo.MMMMMM.oMo",
      "oHEHo.MMMM.oMMo",
      "oHHHo.MMMM.oMMo",
      ".ooo.oMMMMo.oo.",
      "....oMMooMMo...",
      "....oMo..oMo...",
      "....oMo..oMo...",
      "...oddo..oddo..",
      "...okko..okko..",
    ],
  },
  // 鉄の騎士。無骨な鉄塊の自動人形、面のない兜に赤い眼光。装飾的な機鎧と描き分ける
  ironknight: {
    palette: { o: "#14140f", I: "#5a5a52", i: "#3a3a34", L: "#80807a", k: "#0a0a0a", R: "#a83838", W: "#b0b0a8" },
    art: [
      ".....ooooo.....",
      "....oIIIIIo....",
      "....oILLLIo....",
      "....oiRRRio....",
      "....oIIIIIo....",
      "...ooIIIIIoo...",
      "..oILIIIIILIo..",
      ".oIILIIIIIILIIo",
      ".oIIIiIIIIiIIIo",
      ".oIILIIIIIILIIo",
      ".oIIIIIIIIIIIIo",
      ".oIIRRRRRRRRIIo",
      ".oIIiIIIIIIiIIo",
      ".oLIIIIIIIIIILo",
      "oWLIIIIIIIIIILWo",
      ".oIIIIIIIIIIIIo",
      "..oIIIoIIoIIIo.",
      "..oIIo..oIIo...",
      "..oIIo..oIIo...",
      "..oiIo..oIio...",
      "..okko..okko...",
    ],
  },
  // 炎の大蛇。手足のない焔の蛇身、鎌首をもたげ牙を剥く。脚のあるトカゲ(lizard)と描き分ける
  fireserpent: {
    palette: { o: "#2a0a06", R: "#c03a1a", r: "#7e2410", L: "#ff7a3a", Y: "#f2c14e", W: "#ffe6c0", k: "#1a0604" },
    art: [
      ".....ooooo.....",
      "....oRRRRRo....",
      "...oRLLLRRRo...",
      "...oRYkRkYRo...",
      "...oRRRRRRRo...",
      "...oRLWWWLRo...",
      "..oWkRRRRkWo...",
      "..oYoRRRRoYo...",
      "...oRLLLRRo....",
      "....oRRRRo.....",
      "....oRLLRo.....",
      "...oRRLLRRo....",
      "..oRRLLRRRRo...",
      ".oRRLLRRRRRRo..",
      "oRRLLRRRRRrrRo.",
      "oRrLLRRRRrrrRo.",
      ".oRrrRRRrrrRo..",
      "..oRrrrrrrRRo..",
      "...oRRrrrRRo...",
      "....oRRRRRo....",
      ".....ooooo.....",
    ],
  },
  // 嵐の巨人。青灰の肌の巨躯、髭、両拳に走る稲妻。普通の巨人(ogre)と描き分ける
  stormgiant: {
    palette: { o: "#12141a", S: "#4a5a6a", s: "#2e3a46", H: "#6e8296", k: "#0a0a0a", E: "#f2f24a", W: "#d8e0e8", B: "#3a2a1a" },
    art: [
      ".......ooooo.......",
      "......oSSSSSo......",
      ".....oSHHHHHSo.....",
      ".....oSEkSSkEo.....",
      ".....oSSSSSSSo.....",
      ".....oSWWWWWSo.....",
      "......oSSSSSo......",
      "....ooSSSSSSSoo....",
      "..oSSSSSSSSSSSSSo..",
      ".oSSHSSSSSSSSHSSo..",
      ".oSSSSSSSSSSSSSSo..",
      ".oSSSsSSSSSSsSSSo..",
      "E.oSSSSSSSSSSSSo.E.",
      "EEoSSSSSSSSSSSSoEE.",
      "E.oSSHSSSSSSHSSo.E.",
      "..oSSSSSSSSSSSSo...",
      "..oBBBSSSSSSBBBo...",
      "..oBBoSSSSSSoBBo...",
      "..oSSo.SSSS.oSSo...",
      "..oSSo......oSSo...",
      "..oHSo......oSHo...",
      "..oBBo......oBBo...",
      "..okko......okko...",
    ],
  },
  // ワイバーン。二足・尾の毒針・広げた翼の飛竜。四足の竜(dragon)と描き分ける
  wyvern: {
    palette: { o: "#0e2810", G: "#3a7a4a", g: "#225030", L: "#6ab06a", Y: "#e8c24a", W: "#cfe8cf", k: "#0a160a", R: "#c83838", D: "#163a1e" },
    art: [
      "...........oooo......",
      "..o.......oGLLGo.....",
      ".oGo.....oGGYkGo.....",
      "oGGGo...oGGGGGGo.....",
      ".oGGGoooGGGGGGGo.....",
      "..oGGGGGGGGLLGGo.....",
      ".oWGGGGGGGGGGGGo.....",
      "oWWGGGGGGGGGGGGGo....",
      "oWWWGGGGGGGGGGGGGo...",
      ".oWWGGGGGGGGGGGGGGo..",
      "..oWGGGGGGGGGGGGGGGo.",
      "...oGGGGGGGGGGGGDDo..",
      "....oGGGGGGGGGDDo....",
      ".....oGGGoGGGoDDDo...",
      "....oGLo.oGLo.oDDo...",
      "....oGo...oGo..oDDo..",
      "...okko...okko..oDRo.",
      "...............oDRo..",
      "................oRo..",
    ],
  },
  // ヴァンパイア。蒼白の貴族、赤い眼と牙、立て襟の外套を広げる。亡霊(wraith)と描き分ける
  vampire: {
    palette: { o: "#0e0810", S: "#c8b8c0", s: "#9a8a96", K: "#1a0e1e", P: "#5a1a2e", p: "#360e1c", R: "#ff3a4a", k: "#0a0a0a", W: "#f0e8ee", Y: "#e8c24a" },
    art: [
      "......ooooo......",
      ".....oKKKKKo.....",
      "....oKKKKKKKo....",
      "....oSSSSSSSo....",
      "....oSRkSSkRo....",
      "....oSSSSSSSo....",
      "....oSSkWWkSo....",
      ".oo..oSSSSSo..oo.",
      "oPPo.oSWWWSo.oPPo",
      "oPpPooSSSSSooPpPo",
      "oPpPPYSSSSSYPPpPo",
      "oPpPPSSSSSSSPPpPo",
      "oPpPPSSSSSSSPPpPo",
      "oPppPPSSSSSPPppPo",
      ".oPppPSSSSSPppPo.",
      ".oPppoSSSSSoppPo.",
      "..oPpoSSoSSopPo..",
      "..oppo.oo.oppo...",
      "...oo.oSSo.oo....",
      ".....oSo.oSo.....",
      ".....okko.okko...",
    ],
  },
  // 死神。深い頭巾の虚ろな顔に緑光、長衣、片側に大鎌。亡霊(wraith)と描き分ける
  reaper: {
    palette: { o: "#0a0a0e", H: "#2a2a34", h: "#16161c", K: "#0a0a0a", E: "#7affc0", S: "#8a8a96", W: "#c8ccd4" },
    art: [
      ".....ohhhh.......",
      "....ohHHHHho....W",
      "...ohHHHHHHho..WW",
      "...oHhKKKKhHo.WWW",
      "...oHhKEEKhHo.oWo",
      "...oHhKKKKhHo.oSo",
      "...oHHhhhhHHo.oSo",
      "..oHHHHHHHHHHooSo",
      ".oHHHHHHHHHHHHSoo",
      ".oHHHHHHHHHHHSo..",
      ".oHHhHHHHHHhHHo..",
      ".oHHHHHHHHHHHHo..",
      ".oHHHHHHHHHHHHo..",
      ".oHHhHHHHHHhHHo..",
      "..oHHHHHHHHHHo...",
      "..oHHHHHHHHHHo...",
      "..ohHHHHHHHHho...",
      "...ohhHHHHhho....",
      "...ohHo..oHho....",
      "...oWo....oWo....",
      "...oo......oo....",
    ],
  },
  // 水晶のゴーレム。角張った半透明の結晶躯、内に光核。鋼鉄のゴーレム(golem)と描き分ける
  crystalgolem: {
    palette: { o: "#0e1a24", C: "#5a9ad0", c: "#3a6a9a", L: "#9ad0f0", W: "#dff4ff", k: "#0a1018", B: "#7ab0e0" },
    art: [
      ".....ooooo.....",
      "....oCLLLCo....",
      "...oCLWWWLCo...",
      "...oCLWcWLCo...",
      "...oCLLLLLCo...",
      "....oCCCCCo....",
      "..ooCLLLLLCoo..",
      ".oCLLCLLLCLLCo.",
      ".oCLCWWWWWCLCo.",
      ".oCLLWWcWWLLCo.",
      ".oCLLLWWWLLLCo.",
      ".oCLLLLLLLLLCo.",
      ".oCLCLLLLLCLCo.",
      ".oCCLLLLLLLCCo.",
      "..oCLLLLLLLCo..",
      "..oCLCoLoCLCo..",
      "..oCLo.o.oLCo..",
      "..oCLo...oLCo..",
      "..oCLo...oLCo..",
      ".oCLLo...oLLCo.",
      ".oWWo.....oWWo.",
      ".oo.........oo.",
    ],
  },
  // 死霊術師。頭巾の痩せた術師、髑髏付きの杖と法衣の呪印。漂う亡霊(ghost)と描き分ける
  necromancer: {
    palette: { o: "#0c0e0a", H: "#2e3a2a", h: "#1a221a", G: "#5a7a4a", k: "#0a0a0a", E: "#9fe04a", S: "#8a5a2b", W: "#e8e2d0", P: "#6a3f8a" },
    art: [
      ".....ohhhho....W.",
      "....ohHHHHho..WWW",
      "...ohHHHHHHho.WkW",
      "...oHGGGGGGHo.oWo",
      "...oHGEkkEGHo.oSo",
      "...oHGGGGGGHo.oSo",
      "...oHGkWWkGHo.oSo",
      "...oHHhhhhHHo.oSo",
      "..oHHHHHHHHHHooSo",
      ".oHHHHHHHHHHHHoSo",
      ".oHHPHHHHHHPHHSoo",
      ".oHHHHHHHHHHHHo..",
      ".oHHHHHHHHHHHHo..",
      ".oHHPHHHHHHPHHo..",
      ".oHHHHHHHHHHHHo..",
      "..oHHHHHHHHHHo...",
      "..oHHHHHHHHHHo...",
      "..ohHHHHHHHHho...",
      "...ohhHHHHhho....",
      "...ohho..ohho....",
      "...oo......oo....",
    ],
  },
  // 堕天使。光輪と大きな羽根の翼を広げた人型、聖衣。鳥人(harpy)と描き分ける
  angel: {
    palette: { o: "#1a1814", F: "#e8e2d0", f: "#b8b0a0", S: "#e8c8a8", H: "#f0e8d0", h: "#cabfa8", E: "#f2d24a", k: "#0a0a0a", R: "#a83838", W: "#fffaf0" },
    art: [
      ".........EEE.........",
      "........EoooE........",
      "....F....ooo....F....",
      "...FFF..oSSSo..FFF...",
      "..FFFFF.oSkSo.FFFFF..",
      ".FFFFFFFoSSSoFFFFFFF.",
      "FFFFFFFFoWWWoFFFFFFFF",
      "FFFFFFFFFWWWFFFFFFFFF",
      ".FFFFFFFoHHHoFFFFFFF.",
      "..FFFFFoHHHHHoFFFFF..",
      "...FFFoHHHHHHHoFFF...",
      "....FoHHHHHHHHHoF....",
      ".....oHHHHHHHHHo.....",
      ".....oHHHRRRHHHo.....",
      ".....oHHHHHHHHHo.....",
      "....oHHHHHHHHHHHo....",
      "....oHHHHhohHHHHo....",
      "....oHHo.h.h.oHHo....",
      "....oHo..h.h..oHo....",
      ".....o...h.h...o.....",
    ],
  },
};

// ===== ランク基準ステータス =====
// モンスターランク (1-10) から基準ステータスを算出する。全100迷宮のバランスの
// 単一の調整点。個体差は mul (hp/atk などの倍率) で付ける。
// ・hp はプレイヤーの攻撃力カーブ (魂×5部位+武器) に対し通常2-3撃で倒せる量
// ・atk はプレイヤーの VIT 半減則 (combat.js) を踏まえた貫通量
export function monStats(rank, boss = false) {
  const r = Math.max(1, Math.min(10, rank));
  const s = {
    hp: Math.round(30 * Math.pow(r, 1.8)),
    atk: Math.round(12 + 3.2 * r * r),
    def: Math.round(2 * Math.pow(r, 1.5)),
    spd: 4 + Math.round(r * 0.9),
    soul: Math.round(10 * Math.pow(1.65, r - 1)),
    gold: Math.round(8 * Math.pow(1.7, r - 1)),
  };
  if (boss) {
    s.hp = Math.round(s.hp * 3.2);
    s.atk = Math.round(s.atk * 1.3);
    s.def = Math.round(s.def * 1.2);
    s.spd += 2;
    s.soul *= 8;
    s.gold *= 10;
  }
  return s;
}

// ===== モンスター定義ヘルパー =====
// すべてのモンスターはここを通る。スキーマ:
// { id, key, name, race, rank, desc, maxhp, hp, atk, def, spd, soul, gold,
//   art, palette, boss?, dropNormal?, dropRare?, soulClass? }
// soul は撃破時に回収できる Soul 量 (経験値の役割を兼ねる)。
// 注: def/spd は定義用の名前のまま。出現時に六大ステへ写像される
//     (combat.js makeEnemy: atk→ATK, def→VIT, spd→AGI)。
// dropNormal/dropRare は省略可 (省略時は game.js がランクから決定的に割り当てる)。
// soulClass を持つ人型は撃破時にまれに魂を落とす。
export function defMonster(def) {
  if (!def.id) throw new Error("monster id required");
  if (!ARTS[def.artKey || ""] && !def.art) throw new Error("unknown artKey: " + def.artKey + " (" + def.id + ")");
  const base = ARTS[def.artKey] || {};
  const m = {
    id: def.id, key: def.id,
    name: def.name || "???",
    race: def.race || "beast",
    element: def.element || "none",
    rank: def.rank || 1,
    desc: def.desc || "",
    maxhp: def.hp || 10, hp: def.hp || 10,
    atk: def.atk || 1, def: def.def || 0, spd: def.spd || 5,
    soul: def.soul || 5, gold: def.gold || 3,
    art: def.art || base.art,
    palette: def.palette || base.palette,
    boss: !!def.boss,
  };
  if (def.dropNormal) m.dropNormal = def.dropNormal;
  if (def.dropRare) m.dropRare = def.dropRare;
  if (def.soulClass) m.soulClass = def.soulClass;
  if (def.elite) m.elite = true; // 強敵 (強敵階専用。通常プール・ミミックの対象外)
  // 役割持ち: role (healer/guard/summoner) + escort (取り巻きのid)。
  // summoner は summonKey の仲間を戦闘中に呼び寄せる。ability は明示指定で上書き可
  // (省略時は game.js が種族から決定的に付与する)
  if (def.role) m.role = def.role;
  if (def.escort) m.escort = def.escort;
  if (def.summonKey) m.summonKey = def.summonKey;
  if (def.ability !== undefined) m.ability = def.ability;
  // 個体ごとの戦闘特性 (図鑑にも掲載される):
  //   physResist : 物理被ダメを割合カット (0〜0.9)。「物理がほとんど効かない」表現
  //   magWeak    : 攻撃呪文の被ダメ倍率 (>1)。「魔法に弱い」表現
  //   regen      : 毎ラウンド最大HPの割合だけ自己回復 (0〜1)
  //   swift      : 出現時に AGI を底上げ (先手を取りやすい)
  //   evasive    : 物理攻撃を確率で大きく回避する
  //   pack       : 群れで現れる (出現数の下限を引き上げる)
  if (def.physResist) m.physResist = def.physResist;
  if (def.magWeak) m.magWeak = def.magWeak;
  if (def.regen) m.regen = def.regen;
  if (def.swift) m.swift = true;
  if (def.evasive) m.evasive = true;
  if (def.pack) m.pack = true;
  // 追加の戦闘特性 (combat.js が解釈):
  //   magResist   : 攻撃呪文の被ダメを割合カット (0〜0.9)。「魔法がほとんど効かない」
  //   enrage      : HPが3割を切ると一度だけ ATK/AGI が跳ね上がる
  //   endure      : 致死の一撃を一度だけ HP1 で耐える
  //   lifesteal   : 与えた物理ダメージの割合だけ自己回復 (0〜1)
  //   multistrike : 1手番で続けざまに攻撃する回数 (2〜4)
  //   barrier     : 被ダメを半減できる残り回数 (数回制)
  //   (ability に "warcry"=鼓舞 / "weaken"=弱体 も指定可)
  if (def.magResist) m.magResist = def.magResist;
  if (def.enrage) m.enrage = true;
  if (def.endure) m.endure = true;
  if (def.lifesteal) m.lifesteal = def.lifesteal;
  if (def.multistrike) m.multistrike = def.multistrike;
  if (def.barrier) m.barrier = def.barrier;
  if (def.traits) m.traits = def.traits; // 表示専用の追加特徴キー
  return m;
}

// ===== モンスターの特徴・スキル (図鑑表示 + 戦闘挙動の単一の語彙) =====
// 各キーは「ラベル」と「説明」を持つ。固有ドロップに代わって図鑑に列挙される。
export const TRAITS = {
  swift:      { label: "俊敏",   desc: "素早く先手を取りやすい" },
  evasive:    { label: "回避",   desc: "物理攻撃をよくかわす" },
  physResist: { label: "物理耐性", desc: "物理攻撃がほとんど効かない" },
  magWeak:    { label: "魔法弱点", desc: "魔法で大ダメージを受ける" },
  regen:      { label: "再生",   desc: "毎ターン少しずつ傷を癒す" },
  pack:       { label: "群棲",   desc: "群れをなして現れる" },
  summon:     { label: "招来",   desc: "戦闘中に仲間を呼び寄せる" },
  heal:       { label: "治癒",   desc: "傷ついた仲間を癒す" },
  guard:      { label: "庇護",   desc: "仲間への攻撃を庇う" },
  breath:     { label: "ブレス", desc: "全体を巻き込む息を吐く" },
  poison:     { label: "毒",     desc: "攻撃で毒を与えてくる" },
  paralyze:   { label: "麻痺",   desc: "攻撃で麻痺させてくる" },
  stone:      { label: "石化",   desc: "凝視で石に変えてくる" },
  drain:      { label: "吸命",   desc: "宿した魂のレベルを喰らう" },
  soulSteal:  { label: "魂奪",   desc: "Soul を吸い取ってくる" },
  goldSteal:  { label: "強奪",   desc: "金品を奪い取ってくる" },
  critical:   { label: "痛撃",   desc: "急所を狙う一撃を放つ" },
  magResist:  { label: "魔法耐性", desc: "魔法がほとんど効かない" },
  enrage:     { label: "激昂",   desc: "手負いになると荒れ狂う" },
  endure:     { label: "不屈",   desc: "致命の一撃を一度だけ耐える" },
  lifesteal:  { label: "吸血",   desc: "与えた傷の分だけ己を癒す" },
  multistrike:{ label: "連撃",   desc: "一手で続けざまに打つ" },
  barrier:    { label: "障壁",   desc: "数度だけ被害を半減する" },
  warcry:     { label: "鼓舞",   desc: "雄叫びで味方を奮い立たせる" },
  weaken:     { label: "弱体",   desc: "力を削ぐ呪いをかける" },
};

// モンスター定義から特徴キーの並びを導く (重複なし、表示順は定義順)。
// 既存の ability / role と新フィールドを単一の語彙へ正規化する。
export function monsterTraitKeys(m) {
  if (!m) return [];
  const keys = [];
  const add = (k) => { if (k && TRAITS[k] && !keys.includes(k)) keys.push(k); };
  if (m.swift) add("swift");
  if (m.evasive) add("evasive");
  if (m.physResist) add("physResist");
  if (m.magWeak) add("magWeak");
  if (m.regen) add("regen");
  if (m.pack) add("pack");
  if (m.magResist) add("magResist");
  if (m.enrage) add("enrage");
  if (m.endure) add("endure");
  if (m.lifesteal) add("lifesteal");
  if (m.multistrike) add("multistrike");
  if (m.barrier) add("barrier");
  if (m.role === "summoner") add("summon");
  if (m.role === "healer") add("heal");
  if (m.role === "guard") add("guard");
  add(m.ability); // poison/paralyze/stone/drain/soulSteal/goldSteal/critical/breath/warcry/weaken
  for (const t of m.traits || []) add(t);
  return keys;
}

// 表示用に {key,label,desc} の配列へ展開する
export function monsterTraits(m) {
  return monsterTraitKeys(m).map((k) => ({ key: k, ...TRAITS[k] }));
}

// 定義の配列を { id: monster } に変換 (重複IDは即エラー)
export function defMonsters(defs) {
  const out = {};
  for (const d of defs) {
    const m = defMonster(d);
    if (out[m.id]) throw new Error("duplicate monster id: " + m.id);
    out[m.id] = m;
  }
  return out;
}
